### PR TITLE
fix: Booking Question Dialog: Dropdown covered by DialogFooter (CALCOM-10987)

### LINKED ISSUE #10987: Booking Question Dialog: Dropdown covered by DialogFooter
I can't scroll in the dropdown

https://github.com/calcom/cal.com/assets/8019099/3c64f4f3-2c2b-4804-bab9-b04d15551a89

### PR DESCRIPTION
**Pull request by gitstart-calcom**
## DEMO

https://github.com/calcom/cal.com/assets/121884634/603ea9c8-6a62-4ffb-8b0c-a2f30b334f21

### CODE REVIEW

**Comment by gitstart-calcom** [comment]
Hi @PeerRich @ciaranha We can remove this entire className too, in this case the dialog will be rendered like this:

https://github.com/calcom/cal.com/assets/121884634/8266f2db-db5f-47fc-a555-b0bb0e86dbdf

**Comment by PeerRich** [comment]
> Hi @PeerRich @ciaranha We can remove this entire className too, in this case the dialog will be rendered like this:
> 
>  Gravacao.de.Tela.2023-08-28.as.11.29.07.mov

i like this more

**Comment by gitstart-calcom** [comment]
@PeerRich We removed the classNames, please take a look 😄

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Pull request merged**
