### PR TITLE
chore: Replace prisma actions Credential Repository / SelectedCalendar Repository methods

### PR DESCRIPTION
**Pull request by hbjORbj**
## What does this PR do?

- A refactor to not use prisma in `api/integrations/googlecalendar/callback`
- Create a dedicated `google.ts` file in `packages/lib` and move google related methods there
- This will come handy for #17251

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A - I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by keithwillcode** [comment]
@hbjORbj sone unit tests are failing

**Review by joeauyeung — CHANGES_REQUESTED** [review]
This is on the right track @hbjORbj. 

I noticed there are "Google" specific methods in the repositories. I think these repositories should be agnostic of any app they're interacting with, or else we would end up with a ton of methods for each specific app.

If you want to create any reusable functions for GCal I think it should live in the gcal folder. There we can call on the repository methods.

**Comment by hbjORbj** [comment]
@joeauyeung Thanks for the review. Good point, I made `GoogleRepository`.

**Review by joeauyeung — APPROVED** [review]
I'll approve for now as the functionality works. 

I'm a uneasy with the idea of having google specific functions living mixing with files that handle core logic. I think once we start working on https://github.com/calcom/cal.com/pull/17251 there might be a better place to keep these files.

**Comment by hbjORbj** [comment]
Thanks Joe. Joe and I agreed that we rename `GoogleRepository` to `GoogleService` and move it to `/services` folder to not mix concepts! (Will be included in #17251)

**Pull request merged**
