### PR TITLE
fix: Duplicate labels for Destination Calendar

### LINKED ISSUE #11988: [CAL-2625] Duplicate labels for Destination Calendar
image
<sub>[CAL-2625](https://linear.app/calcom/issue/CAL-2625/duplicate-labels-for-destination-calendar)</sub>

### PR DESCRIPTION
**Pull request by siddharth-movaliya**
## What does this PR do?

Fixed duplicate labels for Destination Calendar on `Advanced` tab for event settings.

Fixes #11988 

Screenshot 2023-10-19 at 12 07 28 PM

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1. Go to event settings
2. Go to Advanced tab
3. Select a calendar if not already selected
4. It will now show only one label for Destination Calendar

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by PeerRich — DISMISSED** [review]
i think @hariombalhara was referring to these duplicate labels:

CleanShot 2023-10-20 at 15 36 03@2x

**Comment by Siddharth-2382** [comment]
Oh... Will do the changes in a moment :⁠,⁠-⁠)

**Comment by Siddharth-2382** [comment]
Kept the `Add to Calendar` and added it's description using `add_to_calendar_description`. Removed `Add events to`.

**Comment by PeerRich** [comment]
@Siddharth-2382 can you show another screenshot?

**Comment by Siddharth-2382** [comment]
Sure.

**Comment by Siddharth-2382** [comment]
> @Siddharth-2382 can you show another screenshot?

Here it is.

Screenshot 2023-10-29 at 1 29 09 AM

**Review by Udit-takkar — APPROVED** [review]
LGTM.  I have pushed some more changes according to the figma designs

**Pull request merged**
