### PR TITLE
fix: remove px and change min width in suffix

### LINKED ISSUE #5580: [CAL-394] Input with prefix padding is too large
Example from the sign up page but this issues exists everywhere.

Should be 

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=346%3A30200&t=Jyinup7nmMfztw66-1)

> From [SyncLinear.com](https://synclinear.com) | [CAL-394](https://linear.app/calcom/issue/CAL-394/input-with-prefix-padding-is-too-large)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: https://github.com/calcom/cal.com/issues/5580, https://github.com/calcom/cal.com/issues/5458

fixed suffix addon width

Screenshot 2022-11-18 at 6 25 57 PM

Sign up page
Screenshot 2022-11-18 at 6 29 01 PM

### CODE REVIEW

**Comment by Udit-takkar** [comment]
@zomars can you also remove px-3 from https://github.com/calcom/website/blob/main/pages/signup.tsx#L256  ?

**Comment by Udit-takkar** [comment]
Screenshot 2022-11-18 at 6 54 25 PM

@JeroenReumkens did you remove these files ? apps/website uses them

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
>  can you also remove px-3 from https://github.com/calcom/website/blob/main/pages/signup.tsx#L256 ?
@Udit-takkar 
done: https://github.com/calcom/website/pull/395

**Comment by Udit-takkar** [comment]
thanks @PeerRich  ❤️🙏

**Pull request merged**
