### PR TITLE
fix: Dialog is open after adding a new overwrite

### LINKED ISSUE #11198: [CAL-2413] date overwrites: keep dialog open after adding a new overwrite
https://github.com/calcom/cal.com/assets/8019099/c3947fd4-757e-424a-9a0b-cd8f47387488

<sub>[CAL-2413](https://linear.app/calcom/issue/CAL-2413/date-overwrites-keep-dialog-open-after-adding-a-new-overwrite)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #11198 
Screenshot 2023-09-09 060609

Loom Video: https://www.loom.com/share/375d9bc884e1475cb0c4270954e7e870?sid=cc8936b6-c412-4c46-9ae7-793780398e67
## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by anikdhabal** [comment]
Ok understood where to update.

**Comment by anikdhabal** [comment]
cc: @PeerRich

**Review by PeerRich — APPROVED** [review]
very nice! thank you. I wonder if we should also throw a toast whenever adding

**Comment by anikdhabal** [comment]
> very nice! thank you. I wonder if we should also throw a toast whenever adding

That's a nice idea though. Let's add that in another PR.

**Comment by PeerRich** [comment]
> > very nice! thank you. I wonder if we should also throw a toast whenever adding
> 
> That's a nice idea though. Let's add that in another PR.

you're right: https://github.com/calcom/cal.com/issues/11762

**Pull request merged**
