### PR TITLE
Add Typescript Linting

### PR DESCRIPTION
**Pull request by marcoscannabrava**
## Proposed Changes
- Add ESLint rules to keep code clean and enforce typing
- Updated Modal.tsx and Settings.tsx to visualize the changes proposed
- If this suggestion goes through I recommend spreading the codebase update over 3-4 PRs with time for testing in between the merges

*Suggestion: 2 space indentation since some of the markup is getting pretty nested

Open to feedbacks

### CODE REVIEW

**Comment by baileypumfleet** [comment]
Hey Marcos, thank you very much for your PR. I will have to take a little longer reviewing this PR, because there are some type errors among the project, and I don't want the whole project to break if I merge this in, which enables strict mode 😁

**Comment by marcoscannabrava** [comment]
True, we can remove strict mode. Should we adopt these linting rules to
enforce typing and a 2-space indentation though? 2-space is nitpicking and
a personal preference though. I'd just enforce something to get consistency
across the codebase.

*Marcos Provenzano Cannabrava*
*+1 (415) 992 5332 / **+55 (21) 99535 0555*
github <https://github.com/marcoscannabrava/> | linkedin
<https://www.linkedin.com/in/marcos-cannabrava/> | portfolio
<https://cannabrava.co/>

**Comment by emrysal** [comment]
Suggesting to change 2-space indentation to 4-space indentation for consistency with the current codebase (Most files are currently 4-spaced)

**Comment by sharno** [comment]
I'd suggest this PR be split into different ones, one just to enable the strict flag of the TS compiler, it requires some work in of itself.
The other would be actually adding Prettier for formatting instead of warning about it only with a linter.
Then the last thing being the linter to fix any other issues (although I feel linters with TS are just more work than there needs to be with diminishing returns)

**Comment by marcoscannabrava** [comment]
Agreed. Closing

**Pull request closed without merging**
