### PR TITLE
fix: invite modal

### LINKED ISSUE #9709: Copy Invite Link Button goes out of Invite Team Member Popup for screen size smaller than 640
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Copy Invite Link Button goes out of Invite Team Member Popup for screen size smaller than 640px

### Steps to Reproduce

1. Open Chrome Browser
2. Click on Settings
3. Under Teams, Select your team and click members
4. Click +Add button, a Popup will open
5. Check Copy Invite Link Button can be seen inside Popup
6. Bug - Now reduce the screen size to less than 640px, Copy Invite Link Button goes out of popup

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version - Chrome: v114.0.x
- Node.js version
- Anything else that you think could be an issue.

Invite_Team_Member-CSSBUG

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #9709

after :

Screen Shot 2023-06-22 at 15 54 19

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by singhnsatya** [comment]
I think to maintain the consistency of UI design copy invite link button should stay on the bottom left of the popup same like other screen sizes.

Attaching original popup design and how it should look on smaller screen size.

I think only this below change is enough to fix, let me know if what i am thinking is correct.

<div className= "relative right-40"> // before
<div className= "relative right-2 sm:right-40"> // after

og_CIL
solved_CIL

**Comment by PeerRich** [comment]
hey @G3root can we fix this too:

CleanShot 2023-06-22 at 13 16 05@2x

i dont mind having a bigger min-width

**Comment by G3root** [comment]
@PeerRich made those changes 

Screen Shot 2023-06-23 at 10 49 04

**Review by PeerRich — APPROVED** [review]
works!

**Pull request merged**
