### PR TITLE
chore: add ImageUploader in storybook (CALCOM-10760)

### PR DESCRIPTION
**Pull request by gitstart-calcom**
## DEMO

https://github.com/calcom/cal.com/assets/121884634/4cac4524-15c2-4c0d-9a95-fb33f2e403cb

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
This should open dark mode modal

Screenshot 2023-08-23 at 12 51 05 PM

like this 

Screenshot 2023-08-23 at 12 51 45 PM

**Comment by gitstart-calcom** [comment]
Hi @Udit-takkar, the requested changes have been made. Please take a look

**Comment by Udit-takkar** [comment]
@gitstart-calcom ui build (storybook) is failing

**Comment by gitstart-calcom** [comment]
> @gitstart-calcom ui build (storybook) is failing

Hi @Udit-takkar, it's failing on the `main` branch too due to the following code
Screenshot 2023-08-24 at 3 00 20 PM

**Review by Udit-takkar — APPROVED** [review]
LGTM 

we are looking into fixing the build error

**Pull request merged**
