### PR TITLE
Show dialog only for InPerson and Link locations

### LINKED ISSUE #1716: remove "edit location" dialog for non-in-person
this dialog image

should only be shown when selecting "in-person or link"
image

### PR DESCRIPTION
**Pull request by miguelnietoa**
## What does this PR do?

Fixes #1716

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Enter to edit an event type
- [ ] Set a location i.e JitsiMeet and notice the modal is not shown

**Demo:**
https://app.birdeatsbug.com/sessions/Pnue5mPSURmD2tItO_dBi

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
hey @miguelnietoa can you allow us to update the branch on behalf of you? https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md

**Comment by miguelnietoa** [comment]
Hi @PeerRich, that option is not available since this branch is under a repository forked by an organization. 
If you want, provide the usernames of each maintainer to give you all individual access because we don't find a way to give permissions to all the Calendso team.

**Comment by PeerRich** [comment]
> Hi @PeerRich, that option is not available since this branch is under a repository forked by an organization. 
> 
> If you want, provide the usernames of each maintainer to give you all individual access because we don't find a way to give permissions to all the Calendso team.

yeah lemme create a contributor team and invite you

**Comment by PeerRich** [comment]
@miguelnietoa added you to https://github.com/orgs/calcom/teams/contributors/members let me know if I should add more people of your organisttion

**Comment by miguelnietoa** [comment]
> 

Thanks for inviting me, I already accepted, so what's next? 🤔

**Comment by PeerRich** [comment]
> > 
> 
> 
> 
> Thanks for inviting me, I already accepted, so what's next? 🤔

awesome welcome to the community contributor team

@sean-brydon can review

**Comment by miguelnietoa** [comment]
Thanks a lot!!! @PeerRich ✔️

**Review by PeerRich — APPROVED** [review]
tested and works

**Comment by PeerRich** [comment]
image
can you update again? alternatively you can close the PR and reopen it so it's being opened as a team member

**Review by sean-brydon — COMMENTED** [review]
Tested and works - Nice approach i like it :)

**Comment by miguelnietoa** [comment]
> image
> 
> can you update again? alternatively you can close the PR and reopen it so it's being opened as a team member

Updated. I will keep it in mind for next PRs 👍🏻

**Comment by PeerRich** [comment]
reviewed, tested and merged! thank you @miguelnietoa

**Pull request merged**
