### PR TITLE
fix: made the name field required in ROUTING FORMS

### LINKED ISSUE #9871: Routing form accepts blank as its name
### Issue Summary

To have a name is something mandatory for the routing form, however, it accepts blank as a name.
 
### Steps to Reproduce

1. Install the routing form app
2. Click to add a new routing form
3. Type a single space
4. Click on the Continue button
5. Observe

### Actual Results

- It's accepting blank as a name

### Expected Results

- It should validate that there is no valid value

### Technical details

- Tested on Chrome (114.0.5735.134)

### Evidence

image

image

image

### PR DESCRIPTION
**Pull request by AnitKrJha**
## What does this PR do?

Makes the name field in the routing form compulsory

image

/claim #9871 
Fixes #9871 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

`there was no need to add additional logic , as the forms name are private to the logged in user and has no role in creating the URLs for the same`

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
simplest solution so far. works for me!

**Comment by PeerRich** [comment]
i think this is required: https://github.com/calcom/cal.com/pull/9880

**Comment by PeerRich** [comment]
are you sure "required" is enough? someone pointed out the field already had requried

**Comment by AnitKrJha** [comment]
> are you sure "required" is enough? someone pointed out the field already had requried

It is enough ! The form name provides no purpose in link creation ! It is there just for the creator of the form to identify them. 
I don't see a reason to pack in additional JavaScript! 

Also if we want to have atleast one character in the form field ! Let's just add pattern(regex) to the input field ! 

No custom logic!

**Comment by PeerRich** [comment]
awesome this worked.

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
@hariombalhara the routing form check is failing, i think because the check doesnt need a title

**Comment by PeerRich** [comment]
@AnitKrJha would you be down to fix the test?

**Comment by PeerRich** [comment]
https://github.com/calcom/cal.com/actions/runs/5445419924/jobs/9904917679

**Comment by AnitKrJha** [comment]
@PeerRich you can just close this issue , When going through the tests , I realized i added the required attr to the form desc .
Title field was already required ! 


My bad !
That required was a blind spot for both of us 😂

**Comment by AnitKrJha** [comment]
I don't think this issue needs to be further addressed!

**Pull request closed without merging**
