### PR TITLE
perf: improve typescript perf by pre-generating the router types

### LINKED ISSUE #15175: [CAL-3796] Slow Typescript in vs code
Found a bug? Please fill out the sections below. 👍

Just use the repo

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

type errors should be visible in vs code

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3796](https://linear.app/calcom/issue/CAL-3796/slow-typescript-in-vs-code)</sub>

### PR DESCRIPTION
**Pull request by dlvhdr**
### UPDATE

We ended up adding a turborepo task to run the build script on the trpc package.
This allows devs to run `yarn build` at the root of the project and have the types work fast. The web's build task now has a dependency on the trpc's package build script.

For a future task we should probably add support for typescript's project references to help typescript with the load even further.

### Notes

The typescript language server gets very slow / crashes often when working on the web.
I've tried to debug its perf by following these docs:
- https://github.com/microsoft/TypeScript/wiki/Performance#using-type-annotations
- https://github.com/microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code
- https://github.com/trpc/trpc/discussions/2448

Following microsoft's docs revealed the slowness to be somewhere around the trpc router in combination with the generated prisma types.

The command I ran was: 

```sh
cd apps/web
NODE_OPTIONS=--max_old_space_size=8096 yarn tsc -p . --generateTrace . --incremental false
```

image

It was hard to pinpoint exactly where the issue is but one of the major perf hits seems to be around the `useHasPaidPlan` hook which uses the `trpc.viewer.teams.hasTeamPlan` query which uses the `prisma.membership` object. I haven't worked with prisma or trpc before but the stack probably does a lot of heavy lifting with typescript to provide type-safety and autocompletion. It could be too much for tsserver to do on the fly.

I didn't explore all the possible solutions but the last link in the trpc repo had a solution that seems to improve the perf significantly, at least when working on the web (working on the trpc package is still slow).

- Fixes #15175
- Fixes CAL-3796

#### Notes
- It requires to generate the router types for every change to any route.
  - This is done with turborepo.

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A - I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Run `yarn build` from `packages/trpc/package.json` to generate the `types/router.d.ts` file.
- Open up a file in the web (e.g. `modules/event-types/views/event-types-listing-view.tsx`)
- Notice server boots up fast and types are inferred correctly, e.g. https://github.com/dlvhdr/cal.com/blob/main/apps/web/modules/event-types/views/event-types-listing-view.tsx?plain=1#L232

### CODE REVIEW

**Comment by zomars** [comment]
Awesome write and interesting approach so far! I got one quick Q. Will providing pre-generated typings prevent the IDE from trying to infer them on the fly? Or should we add certain things to an ignore list?

**Comment by zomars** [comment]
Tagging @KATT as since he may have some interesting insights as well 🙏

**Comment by dlvhdr** [comment]
I did a bit more digging, and now I understand why a saw a project at a previous company use something called project references.

Here's my write up:

---
tags: typescript
---

- [Project references](https://www.typescriptlang.org/docs/handbook/project-references.html)

## Notes

- without project references you reveal the internal implementation to consumers unnecessarily
- without it you can't parallelize builds
- With it there's less typechecking

## Usage

```json
{
    "compilerOptions": {
        composite: true, // need this if references by another project
        declaration: true, // ^ same
        declarationMap: true // allows to "Go To Definition" between projects (generates source maps)
    },
    "references": [
        { "path": "../src" }
    ]
}

```

In the package.json:
```json
"scripts": {
  "transpile": "tsc -p ." // maybe use https://tsup.egoist.dev with tsup --dts?
}
```

- This greatly improves the speed of typechecking and compiling, reduce mem usage in the editor and improves isolation
- You'd usually want to use Configuration file inheritance to centralize your common compiler options
- Another good practice is to have a “solution” tsconfig.json file that simply has references to all of your leaf-node projects and sets files to an empty array
	- Allows to simply run `tsc -b src` in the root folder

## Tradeoffs

- Need to either have to check in certain build outputs or build a project after cloning it
- Projects can't have errors as `noEmitOnError` is implicitly on

## Build Mode

- smart incremental builds for TypeScript projects
- Running tsc --build (tsc -b for short) will find references projects and build them if they're outdated

## Tooling

- <https://github.com/microsoft/lage>
- <https://turbo.build/repo/docs>
- <https://tsup.egoist.dev/#generate-typescript-declaration-maps--d-ts-map>

**Comment by dlvhdr** [comment]
Also, I guess a good bench mark would be to run `tsc --noEmit` to typecheck the project as well as `tsc --noCheck` to build the project and time them with something like `hyperfine`

**Comment by keithwillcode** [comment]
@emrysal @zomars are these yarn.lock deletions valid?

**Review by zomars — DISMISSED** [review]
Fixed yarn lock file. Testes locally and all checks are passing. Will test some more before merging. Thank you for your contribution 🙏 @dlvhdr

**Review by zomars — APPROVED** [review]

**Comment by zomars** [comment]
Seems like we have some issues to resolve before merging: 
image

**Pull request merged**
