### PR TITLE
renamed Enterprise Edition to Commercial Edition to be more inclusive for startups

### PR DESCRIPTION
**Pull request by PeerRich**
we've recently changed our pricing to be more startup-friendly which also means the name "Enterprise" license doesn't make much sense for non-enterprise customers.

since the license is usage-based, it makes sense to call it "commercial" license instead.

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
Looks OK to me, but CE normally stands for Community Edition so I wonder if the CE abbr will age very well.

**Comment by PeerRich** [comment]
> Looks OK to me, but CE normally stands for Community Edition so I wonder if the CE abbr will age very well.

thats a very good point. @baileypumfleet

**Comment by baileypumfleet** [comment]
Actually, do we have to worry about scaring startups away, as pricing is publicly shown at cal.com/pricing? Startups will only be scared away if they don't think it's worth requesting pricing and engaging with the sales team, but we don't have that problem. Plus, enterprise sounds cool, and /ee is commonly used.

**Comment by PeerRich** [comment]
> Actually, do we have to worry about scaring startups away, as pricing is publicly shown at cal.com/pricing? Startups will only be scared away if they don't think it's worth requesting pricing and engaging with the sales team, but we don't have that problem. Plus, enterprise sounds cool, and /ee is commonly used.

we don't know if we have that problem. I think i'd rename it to /commercial/ to be extra clear and not /ce/

**Pull request closed without merging**
