### PR TITLE
feat: team availability - vertical selector and align times

### LINKED ISSUE #17499: [CAL-4680] team availability: vertical selector and align times
we have this:

https://github.com/user-attachments/assets/9eb84491-23f4-437e-b4f4-fb89bce8011b

but it would be nice to do something like https://www.worldtimebuddy.com/ where they have a vertical bar and also align all times symmetrically

https://github.com/user-attachments/assets/3ed6bdc0-4305-473f-8776-0d8a6148a51c

<sub>[CAL-4680](https://linear.app/calcom/issue/CAL-4680/team-availability-vertical-selector-and-align-times)</sub>

### PR DESCRIPTION
**Pull request by itsalam**
## What does this PR do?
- In the teams availability view:
  - Alligns Timezones that are offset by minutes (i.e GMT +0:30)
  - Adds minutes to said timezones
  - Adds a verticle selector/guide to better view alligned timezones.  
- Fixes #17499 
- Fixes CAL-4680 

 Loom Video: https://www.loom.com/share/adc6fe94b0114ab2b5e2b5509118369c?sid=5b2dab2e-e4d0-4d0a-b723-3f32427a38f6

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works. (Doesn't seem to be any test suites to test the rest of the relevant code, which makes testing this quite difficult.) 

## How should this be tested?

Manually: 
1. Add timezones various teams in seed.ts
2. Run development mode via "yarn dx"
3. In the /availability?type=team, view the changes
   - Run the mouse along the calender days to move the verticle selector, it is hidden until the mouse stops hoving over the calender days.
   - Ensure the schedules that are offset by minutes are properly labelled and aligned. 
   
  /claim #17499

### CODE REVIEW

**Comment by rajesh-jonnalagadda** [comment]
@itsalam it looks great. please check the functionality of   https://www.worldtimebuddy.com/

verticle selector/guide can be expandable. based on that time range changes.(not sure these changes are needed. please conform before you even start working)

replication steps.
1. click on time.
2. drag the selector.
3. check the time range post drag

https://www.loom.com/share/89739642c8a4480aada5739f935903e2

**Review by sean-brydon — APPROVED** [review]
LGTM - tested works flawlessly. I'm happy to merge this without the additional features mentioned in the above comment.

**Comment by itsalam** [comment]
@rajesh-jonnalagadda, Id be happy to add that as a later feature, but I couldn't find any functionality that the calcom app uses that with, since clicking on any part of the row just opens a modal.

**Comment by sean-brydon** [comment]
Ship it!

**Pull request merged**
