### PR TITLE
Performance increase for the DatePicker component

### PR DESCRIPTION
**Pull request by armr-dev**
## What does this PR do?

Greatly increases the performance when changing the month on the `Datepicker` component. Running the profiler, I saw that it took around 4 seconds on my PC to change the month. Analyzing the component, @toybeaver44 and I found out that the issue was with too much recalculation on each re-render. 

The issue was fixed by moving these recalculations to an `useEffect`. Doing that, I was able to reduce the time it took to change month from 4 seconds to around 170ms (running locally).

### Before
(This was ran directly from production)
https://user-images.githubusercontent.com/19255973/147831110-dd9734da-0679-41d9-b86a-7493cd1f94bb.mov

### After
(This was ran locally)
https://user-images.githubusercontent.com/19255973/147831138-6c9a65dc-81f6-4972-96f5-8f2d63dc6e05.mov

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

If there already is an automated test for this, it should work. Else, I can create one later.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rjherrera** [comment]
@armr-dev I'm experiencing the same issue when switching months! I hope it gets merged, great work!

**Comment by PeerRich** [comment]
thank you for this PR. @emrysal is currently touching a lot of these files and works on a complete makeover of the system, but i am sure he can take a look at this and potentially merge this in before the refactor goes live

**Review by emrysal — APPROVED** [review]

**Review by PeerRich — APPROVED** [review]
thank you for this PR. it's a temporary fix that will help a lot of people until we refactored the system

**Comment by rjherrera** [comment]
for some reason, after deploying the app with this fix merged, I'm still experiencing the issue 🤔 . Maybe I'm doing something wrong but I double checked the deploy and it is running this new code. Did any of you guys manage to try it out after the merge? Thanks! 😬

**Comment by armr-dev** [comment]
> for some reason, after deploying the app with this fix merged, I'm still experiencing the issue 🤔 . Maybe I'm doing something wrong but I double checked the deploy and it is running this new code. Did any of you guys manage to try it out after the merge? Thanks! 😬

Yeah, just tested here and for some reason it is slow again. Will take a look at what might be. 1 sec.

**Comment by armr-dev** [comment]
> for some reason, after deploying the app with this fix merged, I'm still experiencing the issue 🤔 . Maybe I'm doing something wrong but I double checked the deploy and it is running this new code. Did any of you guys manage to try it out after the merge? Thanks! 😬

Ok so I tested this and it still is slow. It's interesting that on our fork, with the same changes, it is working very fast, tho.

What I was able to trace was the issue now is with the `isDisabled` function. It's ran once for every day of the month, and the function is very CPU consuming, as it uses some heavy operations from DayJS multiple times.

As @emrysal is working on refactoring all of this code, I think it's best if we wait @rjherrera, as I don't see an easy solution to this issue without digging deep into the logic behind the calculations.

**Comment by rjherrera** [comment]
I also did a bit of digging with the profiling tool in chrome and I found out that there are a lot of calls to the `startOf`, `isBefore` and `endOf` functions. I guess those come from DayJs as you say! 

I agree, I don't see it either as I have not dug enough in the actual code. It is usable in the current state and as we are at the beginning of the month, at least for most of our use cases, it is not that critical hahaha.

thanks for everything!

**Comment by zomars** [comment]
@rjherrera @armr-dev seems like Vercel is having trouble deploying today: https://www.vercel-status.com/incidents/j8cn7nwycvr6

**Comment by armr-dev** [comment]
Hey @rjherrera! As you are interested in this issue, I was working on improving even more the performance (as this is crucial to our application). Talking with @emrysal, he told me removing the `useMemo` from the `DatePicker` component significantly improves the performance.

I was able to remove it and indeed it has improved the performance even more. 

I will open a PR removing the `useMemo` soon 😎

**Comment by armr-dev** [comment]
Sorry @rjherrera! I did some more testing and found some issues with this solution. We do gotta wait for the refactoring @emrysal is doing 😅

**Comment by rjherrera** [comment]
no worries @armr-dev ! thanks for the hard work! We'll have to wait, but this team works very fast so thats alright. I'm looking forward to see that refactor!

**Pull request merged**
