### PR TITLE
RFC: Truncate user about text on team public page

### LINKED ISSUE #2814: truncate user about text on team public page
If a user has a long About section when they are displayed on the about page it will visually break the layout.

Image

Solutions proposed (but not yet signed off) in [Figma](https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6993%3A127726)

At the very least we should truncate the about text.

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #2814 (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Loom video: https://www.loom.com/share/ba658d5b870a4cee8b7b375d175255f7

### CODE REVIEW

**Review by emrysal — CHANGES_REQUESTED** [review]
Thanks for this; requesting a small amend to make it more consistent with the design provided.

image

I have investigated a little and I think the design is most easily replicable using https://github.com/tailwindlabs/tailwindcss-line-clamp - Using this TailwindCSS plugin, you can use `line-clamp-4` to achieve the desired result:

image

@see https://tailwindcss.com/blog/multi-line-truncation-with-tailwindcss-line-clamp

**Review by PeerRich — APPROVED** [review]

**Review by PeerRich — COMMENTED** [review]
I agree we should use line-clamp

**Review by pumfleet — APPROVED** [review]

**Comment by gitstart** [comment]
@PeerRich @emrysal sorry for the delay!  Request addressed

https://www.loom.com/share/2f4f1f3f8eb244c1a4830925defd996d

**Review by emrysal — APPROVED** [review]

**Comment by joeauyeung** [comment]
Since this PR has been approved by 3 people I'm going to approve Vercel - swagger

**Comment by emrysal** [comment]
@joeauyeung It's being prevented from merging due to Kodiak not having sufficient permissions to auto-update 😞

**Pull request merged**
