### PR TITLE
feat: Allow / disallow SEO indexing on booking pages

### LINKED ISSUE #10465: Allow search engine blocking (noindex) for user/booking page and events
### Is your proposal related to a problem?
I have a focus on privacy and do not want my cal.com link, user/profile/booking page and events to be publicly accessible through search engines.

Currently, for example if you search for "site:cal.com" on Google, you will find all users's booking pages, because the cal.com source code contains the meta-tags "index,follow" in the header sections. Obviously, similar search results are to be expected when searching for the user's name that he provided on his cal.com account.

### Describe the solution you'd like
In the general settings for the cal.com account, it should be possible to generally disable the SEO indexing, for example by adding a checkbox "Disallow search engines from accessing your booking pages". When this checkbox is active, the meta-tags in the header sections should change from "index,follow" to "noindex, nofollow".

Networks like LinkedIn offer similar options in their profile settings.

### Describe alternatives you've considered
The only option is to create a secret event type as this has already been implemented here: https://github.com/calcom/cal.com/issues/6815

However, this does not protect the general booking page (cal.com/USERNAME) from being crawled by search engines.

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?

Fixes #10465 (issue)
/claim #10465

https://github.com/calcom/cal.com/assets/54475686/5bef9099-a639-4484-818c-5d8df391bbfa

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Go to general settings of your account
- Toggle Allow SEO Indexing (should be the last option in the form) and update the profile
- Go to the your booking page for any event type, check the meta tags
- Meta tags should reflect your choice of SEO indexing

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by pandeymangg** [comment]
> Hi @pandeymangg, thank you! Can you confirm the relevant meta tags in the header will be reflected for ANY public pages related to the user, especially for the user landingpage (cal.com/USERNAME) as well? In your video, only a booking page is shown.
> 
> Also, I think it is a bit confusing that in the backend settings, the headline says "Allow SEO indexing" and in the copy below it says "Disallow search engines..."... Probably the copy should be altered to "Allow search engines to access your public content" to avoid confusion.

ahh, I mistook it for only the booking page, I'll add it to other public pages as well and change the wording of the text as well

**Comment by pandeymangg** [comment]
@mbscala thanks for pointing this out, I've done the changes accordingly

**Comment by pandeymangg** [comment]
any updates on this?

**Review by zomars — CHANGES_REQUESTED** [review]
Thank you for your contribution.

Can you untrack the yarn lock file? `git checkout origin/main yarn.lock`

Also can you check the type errors?

Once addressed feel free to request a re-review. 🙏🏽

**Review by zomars — APPROVED** [review]
Reverted unrelated formatting changes for this PR. Will address in a follow-up.

Code and checks are looking good.

Thank you for your contribution 🙏

**Pull request merged**
