### PR TITLE
Fix prisma commands in README file

### LINKED ISSUE #1839: Prisma commands don't work
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Prisma commands don't work due to the project reorganization.

#### Running the Prisma commands found in the README.md file.
- ❌ `npx prisma studio`
image

- ❌ `npx prisma migrate deploy`
image

- ❌ `npx prisma migrate dev`
image

#### Running with `--schema=apps/web/prisma/schema.prisma`
- ✅ `npx prisma studio --schema=apps/web/prisma/schema.prisma`
image

- ❌ `npx prisma migrate deploy --schema=apps/web/prisma/schema.prisma`
image

- ❌ `npx prisma migrate dev --schema=apps/web/prisma/schema.prisma`
image

**Note that even when running the command specifying the schema file it does not load the `.env` file inside the `apps/web` folder.**

### Technical details
- Node.js version: `14.17.6`

### PR DESCRIPTION
**Pull request by miguelnietoa**
## What does this PR do?

Fixes #1839

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How should this be tested?

- ✅ `yarn prisma studio`
image

- ✅ `yarn workspace @calcom/web prisma migrate deploy`
image

- ✅ `yarn workspace @calcom/web prisma migrate dev`
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pumfleet — APPROVED** [review]
Great spot, I hadn't noticed this!

**Comment by miguelnietoa** [comment]
> 

Hey, @baileypumfleet , nice! 🎉 
I can see there is an automatic deployment for the documentation, so can I update these commands on the documentation `apps/docs/`?

**Comment by PeerRich** [comment]
> > 
> 
> Hey, @baileypumfleet , nice! 🎉 I can see there is an automatic deployment for the documentation, so can I update these commands on the documentation `apps/docs/`?

yes you can!

**Comment by miguelnietoa** [comment]
Documentation updates are done in #1875 @PeerRich

**Pull request merged**
