### PR TITLE
Fix: settings moved to userdropdown

### LINKED ISSUE #8395: [CAL-1532] Add Settings Button to Bottom Left
Can we also add the settings button to the bottom left portion where the users profile picture "Shiraz Dole cal.com/shiraz"? I end up clicking to here all the time looking for settings and I see users do this on demo calls all the time. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1532](https://linear.app/calcom/issue/CAL-1532/add-settings-button-to-bottom-left)</sub>

### PR DESCRIPTION
**Pull request by joe-shajan**
## What does this PR do?

Fixes #8395

Screenshot 2023-04-20 194859

Screenshot 2023-04-20 194915

https://user-images.githubusercontent.com/69904519/233395775-6856661c-68b0-426e-91cf-381b9a886b12.mp4

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by PeerRich — CHANGES_REQUESTED** [review]
i think @shirazdole asked to have it **also** in the dropdown, not moved there entirely

waiting for @Jaibles for ultimate decision

**Comment by joe-shajan** [comment]
> i think @shirazdole asked to have it **also** in the dropdown, not moved there entirely
> 
> waiting for @Jaibles for ultimate decision

Ok got it

**Comment by Jaibles** [comment]
@shirazdole that's a great suggestion. I think ultimately, we're going to have so many nav items that we will have to move it to the dropdown. Most other apps have it here so we're following a very common external UX pattern. However, since we have space for it now, let's put it in both places. This will provide time to show people that it's in settings, and when we do have to move it might help people to find it.

cc @PeerRich @joe-shajan

**Comment by joe-shajan** [comment]
> @shirazdole that's a great suggestion. I think ultimately, we're going to have so many nav items that we will have to move it to the dropdown. Nearly every other app you use will have it in a user/account dropdown, so we're following a very common external UX pattern.
> 
> However, since we have space for it now, let's put it in both places. This will provide time to show people that it's in settings, and when we do have to move it might help people to find it.
> 
> cc @PeerRich @joe-shajan

Ok, I have added settings back to the side menu. 
Is the location of the settings in the dropdown menu above the sign-out button currently appropriate?

https://user-images.githubusercontent.com/69904519/233825929-627bf32e-3f1d-4f5f-8119-b5392c444e7c.mp4

**Comment by Jaibles** [comment]
Re that last question...

@PeerRich @shirazdole  thoughts on re-ordering things so that we have things you use more frequently closer to the bottom?
CleanShot 2023-04-23 at 09 59 32@2x

**Comment by PeerRich** [comment]
IMO i am used to have logout at the bottom in pretty much every SaaS I use. 

I wouldnt change much here. the only question is, if settings comes into the dropdown (exclusively or additionally)

**Comment by Jaibles** [comment]
> IMO i am used to have logout at the bottom in pretty much every SaaS I use. 
> 
> 
> 
> I wouldnt change much here. the only question is, if settings comes into the dropdown (exclusively or additionally)

Yes, but usually the bottom of drop-down that opens from the top, ie the furthest away action, which is what I'm proposing here. It's the action we want you taking least.

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
thank you @joe-shajan

**Pull request merged**
