### PR TITLE
fix: Only able to create one webhook per event type

### LINKED ISSUE #14919: [CAL-3653] Only able to create one webhook per event type
After creating the first webhook for an event type the button to create more webhooks is missing. It is possible to create more webhooks on one event type using the API

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3653](https://linear.app/calcom/issue/CAL-3653/only-able-to-create-one-webhook-per-event-type)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

Fixes #14919 

Screenshot 2024-05-07 at 8 12 27 PM

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by CarinaWolli — APPROVED** [review]
Thank you for this quick fix 🙏

**Review by keithwillcode — DISMISSED** [review]
Looks like this change has broken webhook e2e tests

**Comment by Amit91848** [comment]
> Looks like this change has broken webhook e2e tests

Tests are failing but I don't think it was because of my changes, webhooks e2e is passing now but getting timeout fails in other e2e @keithwillcode 

The previous fail of webhook.e2e.ts was happening because unauthorized was thrown at settings/developers/webhooks which seems to have gone away now. 

Screenshot 2024-05-08 at 6 51 00 PM

**Comment by CarinaWolli** [comment]
> doesn't look related, look like a flaky test

This maybe fixes the flaky test: https://github.com/calcom/cal.com/pull/14949

**Pull request merged**
