### PR TITLE
fix: add calendar button layout shift

### LINKED ISSUE #7853: [CAL-1299] /installed-apps - Add new calendar: weird behaviour after clicking button
Currently

[cd6b54af-8b4e-4c9b-9aa5-049b7df7af40](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0829469c-212c-4b84-b374-bc3a36b312ad/cd6b54af-8b4e-4c9b-9aa5-049b7df7af40)

Should be

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1299](https://linear.app/calcom/issue/CAL-1299/installed-apps-add-new-calendar-weird-behaviour-after-clicking-button)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #7853 

after:
 
Screenshot 2023-03-24 18:02:19

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by CarinaWolli — COMMENTED** [review]
We should left align everything so that the calendar logo and the plus icon are in-line.

**Comment by G3root** [comment]
> We should left align everything so that the calendar logo and the plus icon are in-line.

@CarinaWolli pushed some changes

Screenshot 2023-03-25 05:53:29

**Comment by CarinaWolli** [comment]
Still not quite in line, icons and the beginning of the text should be in line like that: 

Screenshot 2023-03-27 at 08 03 02

**Review by emrysal — DISMISSED** [review]
In agreement with @CarinaWolli that the alignment needs to be as in the design before this can be merged 🙏

**Comment by G3root** [comment]
@CarinaWolli new changes
Screenshot 2023-03-30 01:07:36

**Review by CarinaWolli — APPROVED** [review]
Looks good now 👍

**Pull request merged**
