### PR TITLE
Fix: Inconsistencies Between Installed & Settings Pages

### LINKED ISSUE #12367: [CAL-2713] Selected Calendars - Inconsistencies Between Installed & Settings Pages
These inconsistencies are affecting what users believe which calendars are being selected to check for availabilities. The settings page had it's own logic and components compared to `<CalendarListContainer />` that was being used in the installed apps page and onboarding.

Refactor to have the same components & logic between these pages.
[https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=7684-26931&mode=design](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&node-id=7684-26931&mode=design)

[https://threads.com/thread/34546541751/34546675985?s=qP7XpM1vHJBE9RNuBdp4Hn](https://threads.com/thread/34546541751/34546675985?s=qP7XpM1vHJBE9RNuBdp4Hn)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2713](https://linear.app/calcom/issue/CAL-2713/selected-calendars-inconsistencies-between-installed-and-settings)</sub>

### PR DESCRIPTION
**Pull request by MehulZR**
## What does this PR do?

Fixes #12367 (issue) (Attempt)

An unrefined attempt to figure out, if the desired solution is this method ?

To reuse the *CalendarListComponent* within two pages which have different logic, I lifted the logic from leaf nodes to parents node a bit.

The setting page requires the logic to be of a form.
While the installed_apps page requires the logic to be more direct.

@joeauyeung Is your desired solution somewhere in the ballpark to this? If so I can proceed further and make it more robust as It contains bugs and types issues. or you can explain a bit how you want it to be solved.

Screenshot 2023-11-25 at 14-17-49 Calendars Cal
Screenshot 2023-11-25 at 14-20-11 Installed Apps Cal

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@MehulZR Thanks for your contribution but joe was already working on this https://github.com/calcom/cal.com/pull/12388 and that PR has been merged

**Comment by MehulZR** [comment]
> @MehulZR Thanks for your contribution but joe was already working on this https://github.com/calcom/cal.com/pull/12388 and that PR has been merged

Oh Okay. The PR wasn't linked so I thought no was working on it.

**Comment by Udit-takkar** [comment]
> Oh Okay. The PR wasn't linked so I thought no was working on it.

Sorry for any inconvenience

**Comment by MehulZR** [comment]
> > Oh Okay. The PR wasn't linked so I thought no was working on it.
> 
> Sorry for any inconvenience
> 
> 

No worries 👍

**Pull request closed without merging**
