### PR TITLE
Feature/refresh tokens and error handling

### PR DESCRIPTION
**Pull request by Malte-D**
Implemented/Fixed:
- save refreshed tokens of both calendar integrations
- Office365 expiry check was off by *1000
- catch and log errors
- show errors in the booking frontend
- improved google calendar integration performance further

Notes:
- the api call for booking a meeting is now awaited in the frontend, but it is (at least locally) quite slow. Maybe that is only because the email sending fails for me locally, but if not, sending emails should be fire and forget, if the success is not relevant
- Exceptions while sending emails are only logged, but don't cause the api call to fail. 
   - Only exception to this is the legacy mail, which is sent if there are no integrations configured

### CODE REVIEW

**Comment by Malte-D** [comment]
@Nico-J Can you please review this, as I changed a lot of your code.

**Review by Nico-J — APPROVED** [review]
Beautiful! :clap:

**Comment by Nico-J** [comment]
There are just some conflicts to be resolved left. But the code I saw looked great! :)

**Comment by baileypumfleet** [comment]
Awesome, I'm happy with the code too. If you can get these conflicts resolved, @Malte-D, I'll get this merged in right away!

**Review by pumfleet — APPROVED** [review]

**Comment by Malte-D** [comment]
@baileypumfleet All conflicts are resolved

**Pull request merged**
