### PR TITLE
fix: The Url input field overflows when updating profile

### LINKED ISSUE #13786: [CAL-3197] The Url input field overflows when updating profile
### Issue Summary

The URL input field overflows when the URL is very long, breaking the UI.

### Steps to Reproduce

1. Go to My setting
2. Clicked on Profile
3. Update the input field of URL

### Actual Results

1. The URL field overflows horizontally breaking the UI
2. Check in the popup and the also in the events edit section

### Expected Results

1. The URL field should accommodate long URL strings.

### Evidence

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3197](https://linear.app/calcom/issue/CAL-3197/the-url-input-field-overflows-when-updating-profile)</sub>

### PR DESCRIPTION
**Pull request by subhanahujha007**
Fix issue:#13786

### CODE REVIEW

**Review by emrysal — CHANGES_REQUESTED** [review]
Please uncommit unrelated changes 🙏 & extra space added on L160 in the UsernameTextField

**Review by Udit-takkar — COMMENTED** [review]
use git checkout origin/main -- yarn.lock  command to undo yarn.lock changes and push it to this branch

**Review by subhanahujha007 — COMMENTED** [review]
hey there i can cleared the whitespace and removed unnecessary commit

**Review by keithwillcode — CHANGES_REQUESTED** [review]
@subhanahujha007 you added back the yarn.lock changes after we had fixed it

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
long usernames gets still cut off and breaks the design
Screenshot 2024-02-23 at 10 50 50 AM

**Pull request closed without merging**
