### PR TITLE
Bugfix: fetch only CalDAV calendars via tsdav

### PR DESCRIPTION
**Pull request by adriaandotcom**
## What does this PR do?

When using a CalDAV only everything works fine. When using CalDAV and Google Calendar the availability is not working anymore. After some debugging, I found the reason for that.

It should check for only calendars with the integration being `caldav_calendar`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

I don't know. It's fixed now at least.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pumfleet — APPROVED** [review]
Wow, thanks for this fix! Hugely appreciated 🙏🏼

**Comment by baileypumfleet** [comment]
Hey @adriaanvanrossum, could you fix the linting issues that are introduced? You may need to use Prettier to do this. I can't seem to do this myself

**Comment by adriaanvanrossum** [comment]
I gave contributors access to change my PR. I can fix the linter issues as I'm away for the weekend. Feel free to create your own PR.

**Comment by baileypumfleet** [comment]
This has now been superseded by #1727, as I couldn't apply the linting fixes properly in this PR.

**Pull request closed without merging**
