### PR TITLE
fix: Org Team Invite link doesn't create relationship with the org on following the link

### LINKED ISSUE #12770: [CAL-2803] Org Team Invite link doesn't create relationship with the org on following the link
1. Create an org
2. Create a team Marketing in it.
3. Copy Invite link for Marketing team
4. Follow the invite link to create an account with it.
5. Notice that the user is available as Marketing team member, but doesn't show up as organization member.

Originally reported on slack(Private link) [https://calcominc.slack.com/archives/C05V243E153/p1702407169502219](https://calcominc.slack.com/archives/C05V243E153/p1702407169502219)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2803](https://linear.app/calcom/issue/CAL-2803/org-team-invite-link-doesnt-create-relationship-with-the-org-on)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

Fixes #12770

### CODE REVIEW

**Review by Abdel-Monaam-Aouini — APPROVED** [review]

**Comment by CarinaWolli** [comment]
@SomayChauhan could you please take a look at the merge conflicts? 🙏

**Comment by SomayChauhan** [comment]
i think @hariombalhara handled it in #12774

**Comment by CarinaWolli** [comment]
Ah ok, let's close this PR + the issue if it is already fixed. Tagging @hariombalhara to confirm this

**Comment by hariombalhara** [comment]
Yeah it should be fixed along with that. Closing this one now.

**Pull request closed without merging**
