### PR TITLE
Fixing TS errors in storybook

### PR DESCRIPTION
**Pull request by sean-brydon**
Fix TS error in main for storybook

### CODE REVIEW

**Comment by sean-brydon** [comment]
https://www.chromatic.com/build?appId=62bb0d967cb8b3b4e3e3f43a&number=779 We can see its no longer failing here

**Review by alishaz-polymath — COMMENTED** [review]
https://github.com/calcom/cal.com/pull/4002/files#r958197887

Maybe we should take care of it here?

**Review by alishaz-polymath — CHANGES_REQUESTED** [review]
Blocking to allow #4002 merge and not "double fix" the issue accidentally.

**Comment by sean-brydon** [comment]
> [#4002 (files)](https://github.com/calcom/cal.com/pull/4002/files#r958197887)
> 
> Maybe we should take care of it here?

**Pull request closed without merging**
