### PR TITLE
fix: Spacing issues on "settings" Button navbar skeleton (fix-settings-skeleton)

### PR DESCRIPTION
**Pull request by gitstart-calcom**
Here is the GitStart Ticket for this pull request: [fix-settings-skeleton](https://developers.gitstart.com/client/calcom/ticket/fix-settings-skeleton)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/calcom/ticket/fix-settings-skeleton).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/calcom/ticket/fix-settings-skeleton) to manually finish the task that is related to this PR.

Happy hacking! 🎉

## Demo

image

Fix Profile page shifting

https://www.loom.com/share/7d0564dc2012426aace794928136e5bc

### CODE REVIEW

**Comment by PeerRich** [comment]
this is still missing: 
CleanShot 2023-06-20 at 14 39 04@2x


check out the initial PR

the avatar is too small and the padding is wrong


there is also still some Layout Shift https://web.dev/cls/

**Comment by PeerRich** [comment]
hey @gitstart-calcom there is still some layout shifting going on 
https://github.com/calcom/cal.com/assets/8019099/9ced68f3-a6c3-47fa-a33a-c068c46536ff

**Comment by gitstart-calcom** [comment]
Hi @PeerRich we made the changes here

**Comment by Udit-takkar** [comment]
@gitstart-calcom can you fix the type error and conflicts ?

**Comment by gitstart-calcom** [comment]
Hi @Udit-takkar, PR has been updated and resolved conflicts. Please take a look

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
