### PR TITLE
fix heroku build

### PR DESCRIPTION
**Pull request by nosovk**
## What does this PR do?

In continue of https://github.com/calcom/cal.com/discussions/3616#discussioncomment-3294836

Fixes # (issue)

based on https://github.com/calcom/cal.com/pull/3506

### CODE REVIEW

**Comment by sagararyal** [comment]
Thanks a lot @nosovk! Deploys fine and works well.

Would you be able to add few more env in the app.json?
``` 
NEXT_PUBLIC_LICENSE_CONSENT, CRON_API_KEY
```
and perhaps the SMTP env variables as well.


Also using generator as below you can have heroku auto generate the secrets during deployment.

```
		"NEXTAUTH_SECRET": {
			"description": "Cookie encryption key",
			"generator": "secret"
		},
```

and could add required to `"required" : true`  for required env's.

**Comment by nosovk** [comment]
@sagararyal good idea, updated PR

**Comment by agustif** [comment]
Thanks for this @nosovk, a lot of customers will be happy to be able to deploy again!

**Review by zomars — APPROVED** [review]
LGTM. Thank you for your contribution 🙏

**Pull request merged**
