### PR TITLE
fix: use z-9999 on tooltip

### LINKED ISSUE #6467: [CAL-780] Tooltip is behind Dialog
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Tooltip is shown behind dialog.
In this case, the upgrade button has a tooltip. You can see a little bit of the tooltip on the right side of the dialog:

Screenshot 2023-01-13 at 13 12 10

<sub>[CAL-780](https://linear.app/calcom/issue/CAL-780/tooltip-is-behind-dialog)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes https://github.com/calcom/cal.com/issues/6467

Alternate approach:- https://github.com/calcom/cal.com/pull/6491

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
you tested this, right? if yes we can merge this

**Comment by Udit-takkar** [comment]
Screenshot 2023-01-22 at 6 26 24 PM

yes

**Comment by mocherfaoui** [comment]
this is better than my complicated approach 😅 
note that react-hot-toast also uses z-index: 9999. But I don't think it's going to create a problem with tooltips
@Udit-takkar can you include this small fix https://github.com/calcom/cal.com/pull/6491#discussion_r1083441987 in your PR too if it's possible?

**Comment by Udit-takkar** [comment]
@mocherfaoui i am unable to find max-lg in tailwind docs. do you mean max-w-lg ?

**Comment by Udit-takkar** [comment]
closing in favour of https://github.com/calcom/cal.com/pull/6491

**Pull request closed without merging**
