### PR TITLE
fix: [CAL-1490] Google Cal/Outlook not actively syncing/self hosted

### LINKED ISSUE #8259: [CAL-1490] Google Cal/Outlook not actively syncing/self hosted
[https://www.loom.com/share/2698d47055c64f2c8199cd65d991f620](https://www.loom.com/share/2698d47055c64f2c8199cd65d991f620)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1490](https://linear.app/calcom/issue/CAL-1490/google-cal-not-actively-syncingself-hosted)</sub>

### PR DESCRIPTION
**Pull request by roae**
## What does this PR do?

Prevents error setting the x-csp header in _document getInitialProps when revalidating the Calendar cache.

Fixes: #8259 #7526 #8248

https://www.loom.com/share/97d0ee4075ef4e8ab68e3f489bb5f72e

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by funsurfer2008 — COMMENTED** [review]
Working for me, but one " is wrong in text. web compilation failed with ” instead of "

**Comment by melakhvision** [comment]
Hi,
I'm having same issue with docker self hosted.
Any fix ?

**Comment by roae** [comment]
> Working for me, but one " is wrong in text. web compilation failed with ” instead of "

Hey @funsurfer2008, what do you mean? Sorry, I don't understand, maybe I don't get the context

**Comment by funsurfer2008** [comment]
> > Working for me, but one " is wrong in text. web compilation failed with ” instead of "
> 
> Hey @funsurfer2008, what do you mean? Sorry, I don't understand, maybe I don't get the context

I mean that the second quote is different from the first one. So with the code you have posted the yarn command failed. If i change it to the Same as the first Quote it works. You can see the diference: ” "

**Comment by roae** [comment]
> Hi, I'm having same issue with docker self hosted. Any fix ?

@melakhvision Are you having the char issue?

**Review by funsurfer2008 — APPROVED** [review]

**Review by hariombalhara — APPROVED** [review]
Change is completely safe. But I would like to know when exactly it happens, so I have added a log.

**Comment by sypion** [comment]
The issue still persists. No external calendar account is connected and just occurs when reaching the event page.  Additionally, an embed of an event does not appear when linking to a website. Also using a local installation.

**Comment by funsurfer2008** [comment]
> The issue still persists. No external calendar account is connected and just occurs when reaching the event page. Additionally, an embed of an event does not appear when linking to a website. Also using a local installation.

if you run the yarn and use the latest file with the code above it works nomraly. The Problem is about syncing, not connecting.maybe another bug?

**Comment by stenius** [comment]
> Hi, I'm having same issue with docker self hosted. Any fix ?

I used the container tagged `v2.8.1` and it worked.

Last I checked, the `latest` tag was only pointing to `v2.8.0`

**Comment by sypion** [comment]
> > The issue still persists. No external calendar account is connected and just occurs when reaching the event page. Additionally, an embed of an event does not appear when linking to a website. Also using a local installation.
> 
> if you run the yarn and use the latest file with the code above it works nomraly. The Problem is about syncing, not connecting.maybe another bug?

Using the latest file or release doesn't really make a difference. However, I can actually go book events now. This wasn't something I could do before. Here's the error for reference:

```
@calcom/web:start: Error setting header x-csp=not-opted-in for /sypion/15min Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
@calcom/web:start:     at new NodeError (node:internal/errors:372:5)
@calcom/web:start:     at ServerResponse.setHeader (node:_http_outgoing:576:11)
@calcom/web:start:     at ServerResponse._res.setHeader (/Users/computer/cal/node_modules/next/dist/server/base-server.js:180:24)
@calcom/web:start:     at setHeader (/Users/computer/cal/apps/web/.next/server/pages/_document.js:120:18)
@calcom/web:start:     at Function.getInitialProps (/Users/computer/cal/apps/web/.next/server/pages/_document.js:130:13)
@calcom/web:start:     at Object.<anonymous> (/Users/computer/cal/node_modules/next/dist/shared/lib/utils.js:84:33)
@calcom/web:start:     at Generator.next (<anonymous>)
@calcom/web:start:     at asyncGeneratorStep (/Users/computer/cal/node_modules/@swc/helpers/lib/_async_to_generator.js:13:28)
@calcom/web:start:     at _next (/Users/computer/cal/node_modules/@swc/helpers/lib/_async_to_generator.js:31:17)
@calcom/web:start:     at /Users/computer/cal/node_modules/@swc/helpers/lib/_async_to_generator.js:36:13
@calcom/web:start:     at new Promise (<anonymous>)
@calcom/web:start:     at Object.<anonymous> (/Users/computer/cal/node_modules/@swc/helpers/lib/_async_to_generator.js:28:16)
@calcom/web:start:     at Object.loadGetInitialProps (/Users/computer/cal/node_modules/next/dist/shared/lib/utils.js:62:33)
@calcom/web:start:     at loadDocumentInitialProps (/Users/computer/cal/node_modules/next/dist/server/render.js:682:48)
@calcom/web:start:     at renderDocument (/Users/computer/cal/node_modules/next/dist/server/render.js:732:45)
@calcom/web:start:     at /Users/computer/cal/node_modules/next/dist/server/render.js:769:114 {
@calcom/web:start:   code: 'ERR_HTTP_HEADERS_SENT'
@calcom/web:start: }
```

**Comment by hariombalhara** [comment]
I can replicate the error 'Error setting header x-csp=not-opted-in for /sypion/15min Error' locally. It seems to happen for /[user]/[slug] route which is an ISR page. Doesn't happen for other pages in booking flow, which are SSRd.

I try to create an independent scenario in a simple Next.js app but couldn't re-create the issue. 

Will spend some more time understanding why this is happening.

**Comment by hariombalhara** [comment]
But I don't have any understanding of how it can affect Google Cal/Outlook sync. It might be completely unrelated as well.

**Comment by sypion** [comment]
> But I don't have any understanding of how it can affect Google Cal/Outlook sync. It might be completely unrelated as well.

I would say it's unrelated. I do not (nor ever) had Google or Outlook sync enabled since the start of this issue a couple of months ago.

**Pull request merged**
