### PR TITLE
Gitignored prisma/zod

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

This removes prisma/zod from version control as this is a generated file.

### CODE REVIEW

**Comment by zomars** [comment]
There's only one caveat. I made the mistake to add a file that is not auto-generated in there: `packages/prisma/zod/eventtypecustominput.ts` Where should we put this file? @emrysal

**Comment by emrysal** [comment]
@zomars I'd say lib/types

**Comment by zomars** [comment]
> @zomars I'd say lib/types

But it's not a type per se. Is a validation schema. 🤔

**Review by pumfleet — APPROVED** [review]
Once @zomars' comment is resolved, this looks all good to merge

**Comment by zomars** [comment]
BTW. Type-check and E2E won't pass on this PR since they're being run against main, which expects the old location.

**Review by zomars — APPROVED** [review]

**Comment by emrysal** [comment]
#therewasanattempt.

**Pull request closed without merging**
