### PR TITLE
fix: typo in german translation

### PR DESCRIPTION
**Pull request by rweisleder**

### CODE REVIEW

**Review by anikdhabal — DISMISSED** [review]
🚀

**Review by keithwillcode — APPROVED** [review]

**Review by keithwillcode — DISMISSED** [review]
@rweisleder this is pointing to ‘master’. We take PRs into main. I’ve just update it. Can you please fix conflicts?

**Comment by PeerRich** [comment]
can you record a loom of all of the other UI changes?

**Comment by anikdhabal** [comment]
> can you record a loom of all of the other UI changes?

These changes were pushed due to switches in the base branch.

**Review by anikdhabal — APPROVED** [review]
LGTM

**Pull request merged**
