### PR TITLE
FEAT: add loading spinner on action buttons

### PR DESCRIPTION
**Pull request by iamtabrezkhan**
This PR addresses [this](https://github.com/calendso/calendso/issues/90) issue.

- [x] Creates two atomic components inside UIComponents folder [Loading, UIButton]
- [x] Creates atomic svg components inside SvgComponents folder
- [x] Add loader/spinner inside UIButton

spinner

### CODE REVIEW

**Comment by iamtabrezkhan** [comment]
@baileypumfleet ^

**Comment by emrysal** [comment]
This works great; but personally I'm not a fan of the additional added root structure. UIComponents and SVGComponents is a bit bulky - it's also more about what format they are not what they are for. What is your opinion of regrouping this into the <root>/components folder (I'm thinking ./components/LoadingButton...)?

**Comment by iamtabrezkhan** [comment]
@emrysal that would work as well. IMO, I created those to put all the atomic components in them (like InputField, SelectDropdown etc).

**Comment by iamtabrezkhan** [comment]
@emrysal a quick question, what about SvgComponents?

**Comment by baileypumfleet** [comment]
I agree with @emrysal. Definitely want to try for a more organised version of this. But thank you for your contribution!

**Comment by iamtabrezkhan** [comment]
Right, that's why I moved UIComponents into components folders but not sure about SvgComponents.

**Comment by iamtabrezkhan** [comment]
@baileypumfleet, I have moved svg components into the components folder as well for now.

**Comment by emrysal** [comment]
@baileypumfleet I think this is good to go now; there are some structural changes that can be improved upon at a later time, I think the code introduces here is a step in the right direction.

**Review by emrysal — APPROVED** [review]

**Comment by baileypumfleet** [comment]
Closing this as we have implemented this in another commit

**Pull request closed without merging**
