### PR TITLE
fix: #15989 disable country prefill in phone input

### LINKED ISSUE #15989: [CAL-4081] Don't prefill country code in phone number input
Right now the country is automatically selected in the phone number input field. However, this is not always accurate and sometimes the wrong country code is selected. We want to remove the automatic prefill and users should enter the full phone number with country code themselves.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4081](https://linear.app/calcom/issue/CAL-4081/dont-prefill-country-code-in-phone-number-input)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #15989 
- Fixes CAL-4081

https://www.loom.com/share/f89d755b4ac44bf0be592070ba3835e6?sid=b724c9ec-f139-49f8-8b1e-742bded64673

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by anikdhabal — DISMISSED** [review]
LGTM!

**Review by Amit91848 — DISMISSED** [review]
LGTM!!

**Review by keithwillcode — DISMISSED** [review]
@CarinaWolli @sean-brydon is this what we're looking for here? If so, let's just remove it completely versus commenting it

**Review by anikdhabal — DISMISSED** [review]
Removed comments, LGTM!

**Comment by anikdhabal** [comment]
@vijayraghav-io e2e test is failing, pls fix that.

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io e2e test is failing, pls fix that. Need to handle this two->` Can add Organzer Phone Number location and book with it` and `can add Attendee Phone Number location and book with it`

Yes looking into this

**Review by anikdhabal — APPROVED** [review]

**Comment by vijayraghav-io** [comment]
@anikdhabal 
As pre-filling country is removed, updated test cases accordingly. 
All e2e tests are passing now.

**Comment by anikdhabal** [comment]
> @anikdhabal As pre-filling country is removed, updated test cases accordingly. All e2e tests are passing now.

Thanks for your work, checked that.

**Pull request merged**
