### PR TITLE
Make switch thumb color white when disabled.

### PR DESCRIPTION
**Pull request by barisunsalhn**
## What does this PR do?

This will change turned off switch's (thumb) color from black to white.

Fixes # ([issue](https://github.com/calcom/cal.com/issues/8161))

https://www.loom.com/share/cec1d3a85b004f6883e41daf8bd771e8
**Environment**: Staging(main branch) / Production
Main branch.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Test A
Open event-types. Turn of show on profile for some meeting
Make sure toggle button does not contain black color in anywhere. 

## Checklist

- I haven't checked if new and existing unit tests pass locally with my changes
https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md does not contain any info about unit tests.

### CODE REVIEW

**Comment by PeerRich** [comment]
hey there @sean-brydon is refactoring the entire component right now to support brand colors

**Comment by sean-brydon** [comment]
Hey @lapaz17 i believe this issue should already be fixed in this PR https://github.com/calcom/cal.com/pull/8213

**Comment by sean-brydon** [comment]
Thanks for the contribution @lapaz17 - we're going to merge https://github.com/calcom/cal.com/pull/8213 in favour of this as it adds brand colour to the switches also. 

Sorry for wasting your time on this one!

**Comment by lapaz17** [comment]
> Thanks for the contribution @lapaz17 - we're going to merge #8213 in favour of this as it adds brand colour to the switches also.
> 
> Sorry for wasting your time on this one!

No problem:)

**Pull request closed without merging**
