### PR TITLE
[embed-react] Implement `<CalProvider />` and `useCalApi()`

### LINKED ISSUE #5441: Ideas for better react embed
### Is your proposal related to a problem?

Unclear and unorthodox current react integration (this is opiniated).
Especially [this one](https://codesandbox.io/s/action-event-listeners-demo-react-cmj1c8?from-embed) (likely the most useful) from the docs. 

### Describe the solution you'd like

The best I can think of is a combination of `Provider` pattern with hooks, inspired by the excellent [`react-google-recaptcha-v3`](https://github.com/t49tran/react-google-recaptcha-v3)

- A `<CalProvider>` (with options for the script) would be responsible of injecting the embeddable script
  ```ts
  const App = () => (
    <CalProvider>
      <SomeComponent />
    </CalProvider>
  )
  ```
  (with potential options — as props — for the script. Eg. embed url)
- A `useCalApi` hook would gracefully retrieve the API. Ideally, internally it would retrieve it from the context consumer of `CalProvider`
  ```ts
  const MyComponent: FunctionalComponent = () => {
    const calApi = useCalApi()

    // `calApi` is a GlobalCal | null
    // depending of the loading state

    // use calApi(...)
  }
  ```
- A `useCalAction` hook, responsible of handling actions
```ts
  const MyComponent: FunctionalComponent = () => {
    const handleBookingSuccess = useCallback(() => {
      console.log('booked !')
    })

    useCalAction('bookingSuccessful', handleBookingSuccess)

    // ...
  }
```
- `<Cal />` component would not change, except it would internally **not** auto-inject the script, and rely on `useCalApi` 

This whole setup would actually allow to rely on `window.` on a single point, which would be the context `Provider`. A reference to the Api would be kept here, and distributed for various usages, component and hooks.

### Describe alternatives you've considered

I wrote my own versions of `useCalApi` and `useCalAction`; which are basically workarounds for now (rely on `getCalApi`).

```ts
import { getCalApi } from '@calcom/embed-react'
import { GlobalCal } from '@calcom/embed-core'
import { useEffect, useState } from 'react'

export const useCalApi = () => {
  const [calApi, setCalApi] = useState<GlobalCal | null>(null)

  useEffect(() => {
    ;(async function () {
      const calApi = await getCalApi()
      setCalApi(() => calApi ?? null)
    })()
  }, [setCalApi])

  return calApi
}
```

```ts
import { useEffect } from 'react'
import { useCalApi } from './use-cal-api'

const actionTypes = [
  'eventTypeSelected',
  'bookingSuccessful',
  'linkReady',
  'linkFailed',
] as const

type CalActionType = typeof actionTypes[number]

type CalActionDataEventTypeSelected = {
  eventType: Record<string, unknown>
}

type CalActionDataBookingSuccessful = {
  confirmed: boolean
  eventType: Record<string, unknown>
  date: string
  duration: number
  organizer: Record<string, unknown>
}

type CalActionDataLinkReady = Record<string, never>

type CalActionDataLinkFailed = {
  code: number
  msg: string
  data: Record<string, unknown>
}

type CalActionDetailsEventTypeSelected = {
  data: CalActionDataEventTypeSelected
  type: 'eventTypeSelected'
  namespace: string
}

type CalActionDetailsBookingSuccessful = {
  data: CalActionDataBookingSuccessful
  type: 'bookingSuccessful'
  namespace: string
}

type CalActionDetailsLinkReady = {
  data: CalActionDataLinkReady
  type: 'linkReady'
  namespace: string
}

type CalActionDetailsLinkFailed = {
  data: CalActionDataLinkFailed
  type: 'linkFailed'
  namespace: string
}

// type CalActionDetails =
//   | CalActionDetailsEventTypeSelected
//   | CalActionDetailsBookingSuccessful
//   | CalActionDetailsLinkReady
//   | CalActionDetailsLinkFailed

type _CalActionDetails = {
  eventTypeSelected: CalActionDetailsEventTypeSelected
  bookingSuccessful: CalActionDetailsBookingSuccessful
  linkReady: CalActionDetailsLinkReady
  linkFailed: CalActionDetailsLinkFailed
}

type CalActionCallback<
  T extends CalActionType,
  D extends _CalActionDetails[T] = _CalActionDetails[T],
> = (e: { details: D }) => void

export const useCalAction = <
  T extends CalActionType,
  C extends CalActionCallback<T> = CalActionCallback<T>,
>(
  action: T,
  callback: C,
) => {
  const calApi = useCalApi()

  useEffect(() => {
    if (calApi == null) {
      return
    }

    calApi('on', {
      action,
      callback,
    })

    return () => {
      calApi('off', {
        action,
        callback,
      })
    }
  }, [action, callback, calApi])
}

```

### Additional context

None

### PR DESCRIPTION
**Pull request by cyrilchapon**
## What does this PR do?

Enhanced API for *@calcom/embed-react* , leveraging react context.
(This is a first step before `useCalAction` implementation discussed in #5441)

Added :
- `<CalProvider />` which is a [context provider](https://reactjs.org/docs/context.html#contextprovider) injecting the embeddable script
- `useCalApi()` hook, which retrieves cal API gracefully from context
- (`<CalConsumer />` which is the [context consumer](https://reactjs.org/docs/context.html#contextconsumer))

Updated :
- `<Cal />` component, I made it dumb, it's now using cal API from context and it doesn't try to inject the embeddable anymore.

Kept :
- `getCalApi()` for backward compatibility (refactored)

Usage :
```tsx
import { CalProvider, useCalApi } from '@calcom/embed-react'

const myApp = () => (
  const [calDialogOpen] = useGlobalState()

  // Wrap `<Cal />` and `useCalApi` calls with the provider
  // It will inject the embeddable once, and provide `calApi` through context
  <CalProvider
    // Embed js URL is now on the Provider
    embedJsUrl="http://someurl.js"
  >
    <CalLink>Book a meeting</CalLink>
    {calDialogOpen ? <CalDialog /> : null}
  </CalProvider>
)

const CalDialog = (props) => {
  const [, setCalDialogOpen] = useGlobalState()

  return (
    <div>
      <Cal />{/* Same component as before (without embedJsUrl) */}
      <button onClick={() => setCalDialogOpen(false)}>close</button>
    </div>
  )
}

const CalLink = (props) => {
  // New hook
  // returns [CalGlobalState, true] | [null, false]
  const [calApi, calApiLoaded] = useCalApi()

  const [, setCalDialogOpen] = useGlobalState()

  // If Cal API loaded, button will open a cal dialog
  // otherwise fallback to cal link
  return ( calApiLoaded ? (
    <button onClick={() => setCalDialogOpen(true)}>{props.children}</button>
  ) : (
    <a href="https://cal.com/my-cal" target="_blank">{props.children}</a>
  ))
}
```

Fixes #5441 (partly)

**Environment**: ?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How should this be tested?

- [ ] Unit tests should be updated. I need help for this.
  After updating *packages/embeds/embed-react/test-cal.tsx*, I'm getting the following error :
  ```bash
  @calcom/embed-react:embed-tests-quick:   1) [chromium] › ../tests/basic.test.ts:6:1 › Inline Usage Snapshot 
  ===============================
  @calcom/embed-react:embed-tests-quick: 
  @calcom/embed-react:embed-tests-quick:     Error: Expected to provide an iframe, got null
  @calcom/embed-react:embed-tests-quick: 
  @calcom/embed-react:embed-tests-quick:        9 |   await page.goto("/");
  @calcom/embed-react:embed-tests-quick:       10 |   const embedIframe = await getEmbedIframe({ page, pathname: "/pro" });
  @calcom/embed-react:embed-tests-quick:     > 11 |   expect(embedIframe).toBeEmbedCalLink("", getActionFiredDetails, {
  @calcom/embed-react:embed-tests-quick:          |                       ^
  @calcom/embed-react:embed-tests-quick:       12 |     pathname: "/pro",
  @calcom/embed-react:embed-tests-quick:       13 |     searchParams: {
  @calcom/embed-react:embed-tests-quick:       14 |       theme: "dark",
  @calcom/embed-react:embed-tests-quick: 
  @calcom/embed-react:embed-tests-quick:         at /Users/cyril/Code/cyc/cal.com/packages/embeds/embed- react/playwright/tests/basic.test.ts:11:23
  ```

- [ ] probably `yarn build` and `yarn link` inside `@calcom/embed-react` to manually test it.
  I tried this in a personal project, and am getting strange error :
  ```bash
  ../cal.com/packages/embeds/embed-react/dist/Cal.es.js (67:38) @ _useLoadCalApi

     65 | EmbedSnippet.toString();
     66 | const _useLoadCalApi = (embedJsUrl) => {
   > 67 | const [calApi, setCalApi] = useState(null);
        |                             ^
     68 | useEffect(() => {
     69 |   (async function() {
     70 |     const _calApi = await getCalApi(embedJsUrl);
  ```

## Checklist

- The PR is not meant to be merged for now.
  - I need help on making unit-test pass and potentially upgrade them in the process.
  - It still needs a documentation upgrade

### CODE REVIEW

**Comment by hariombalhara** [comment]
Thank you so much for the PR 🙏
@cyrilchapon I will be on leave for next week. So, currently focussing only on wrapping my current work.
I will take a look at it next to next week.

For debugging playwright tests, you can use PWDEBUG=1 env variable supported by Playwright

**Comment by hariombalhara** [comment]
@cyrilchapon Fixed the test in a way similar to what you suggested but a bit cleaner.

FYI, We are also speccing out [**Cal Atoms**](https://cal.com/atoms) at the moment which is much more powerful embedding without iframe. So, I would take some time to review these changes considering that as well.

Also, can you confirm @cyrilchapon or make sure that when this is merged, existing users would be still able to use the embed with the non provider based approach.

**Comment by cyrilchapon** [comment]
Hey @hariombalhara ,

Thanks for that piece of review.

> @cyrilchapon Fixed the test in a way similar to what you suggested but a bit cleaner. The commit is here https://github.com/calcom/cal.com/commit/48e0fb2e3ca382b7ff0fd7fedae646bb10c3253c
Couldn't push to your branch as that is main of your repo.

Great. I shall try to run it in the next few days, but I'm also encountering some pains with "Pro" stuff when launching the tests. To be honest, configuring all the stuff and all the env vars is a bit of a pain due to the guess-game. But I'll digg into it.

> FYI, We are also speccing out [Cal Atoms](https://cal.com/atoms) at the moment which is much more powerful embedding without iframe. So, I would take some time to review these changes considering that as well.

Great. How can I help, if there is a react part in there ?

> Also, can you confirm @cyrilchapon or make sure that when this is merged, existing users would be still able to use the embed with the non provider based approach.

This is tricky — and IMHO could be reconsidered. What is the need for a backward compatibility here ?

To answer clearly,
- I did not touch the raw JS integration,
- but the react integration was designed to be a breaking change TBH.

I'd think of bumping the major. The react integration is pretty minimalist and wouldn't suffer from a major bump IMHO. (No real need to maintain old release, migration pretty straightforward and much cleaner.). What do you think ?

**Comment by hariombalhara** [comment]
Keeping it in draft till last comment is addressed(as that needs some work)

**Comment by hariombalhara** [comment]
Closing this PR. I will continue work on this as part of this ticket https://github.com/calcom/cal.com/issues/8331

**Pull request closed without merging**
