### PR TITLE
feat: add option to provide cancellation reason for email

### LINKED ISSUE #1451: Reason for cancellation
Add a text field for the reason for cancellation which shows up in the cancellation email.

### PR DESCRIPTION
**Pull request by nrademacher**
## What does this PR do?

Closes #1451 by adding an option to provide a reason when cancelling event, which is added to the cancellation email.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [x] Verified the new field is present by logging the email markup that would be sent to the cancelling attendee or organiser

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- ~~I have commented my code, particularly in hard-to-understand areas~~ 
  - Not warranted
- ~~I have made corresponding changes to the documentation~~ 
  - Not applicable
- [x] My changes generate no new warnings
- ~~I have added tests that prove my fix is effective or that my feature works~~
  - This would involve creating a functionality mocking setup; would skip if possible, considering the scope of the change
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by zomars — COMMENTED** [review]
Can we hide the field when the reason is empty, or add a "No reason provided" message?

image

**Comment by nrademacher** [comment]
> Can we hide the field when the reason is empty, or add a "No reason provided" message?
> 
> image

You're right, blank field looks odd. In case there's no reason given, it would in my opinion be best to omit the field in the email.

**Comment by zomars** [comment]
> You're right, blank field looks odd. In case there's no reason given, it would in my opinion be best to omit the field in the email.

 Agreed!

**Comment by alishaz-polymath** [comment]
I think this might a good PR to add Rejection reason as well. Thoughts @zomars, @emrysal ?

**Comment by zomars** [comment]
> I think this might a good PR to add Rejection reason as well. Thoughts @zomars, @emrysal ?

We could follow up in another PR 👍🏽

**Review by zomars — APPROVED** [review]
I'll merge once checks pass. Thank you for contributing! 🙏🏽

**Pull request merged**
