### PR TITLE
Fixes timeZone() by no longer needing timeZone()

### PR DESCRIPTION
**Pull request by emrysal**
timeZone() has issues on SSR, which was causing big issues. I've created a wrapper function around Dayjs which allows parsing a tz without autoconverting to local or utc (and losing utcOffset information in the process) - before it was impossible to get the same format out, of what you put in.

### CODE REVIEW

**Review by KATT — APPROVED** [review]
Jesus, this is ugly, but if it solves a bug, let's do it

**Comment by KATT** [comment]
Actually, a regression test proving it solves a bug would be great but might be hard with timezones?

**Comment by emrysal** [comment]
@KATT Au contraire - added a very basic testcase to just showcase what it does 👍

**Review by KATT — APPROVED** [review]
The jest tests are actually not run by CI (only e2e) but let's ignore that for now 😅

**Pull request merged**
