### PR TITLE
added fathom app

### LINKED ISSUE #4775: App Store: Analytics as category/interface
A new category would be nice:
- Analytics

which consist of
 
- [x] #4801
- [ ] plausible.io
- [ ] google analytics
- ..?

## implementation

We'd need an abstraction to add `<script> `code to the booking page with the UID from these analytics services when the app is added

### LINKED ISSUE #4801: usefathom.com

### PR DESCRIPTION
**Pull request by PeerRich**
**Requires https://github.com/calcom/cal.com/pull/4727 to be merged first**

[Demo Loom](https://www.loom.com/share/04e99819ef1342d8b048d0467b55a051)

- [ ] build an abstraction for any generic <script> tag to be loaded in the public booking pages for other analytics services  
- [x] needs script injection to public booking page
- [x] AppCard settings in event-types to add your tracking key

`<script src="https://cdn.usefathom.com/script.js" data-site="<fathom key here>" defer></script>`

CleanShot 2022-10-03 at 17 10 49@2x

Followup:
- A script Loader for all scripts
- Script configuration in config

### CODE REVIEW

**Review by pumfleet — DISMISSED** [review]
this doesn't seem to do anything?

**Comment by PeerRich** [comment]
> this doesn't seem to do anything?

forgot the WIP label

**Comment by hariombalhara** [comment]
cc @PeerRich  ^

**Comment by PeerRich** [comment]
@hariombalhara this is good to merge, no?

**Review by hariombalhara — APPROVED** [review]

**Comment by hariombalhara** [comment]
Requires https://github.com/calcom/cal.com/pull/4727 to be merged first and then it can be merged(after testing)

**Pull request merged**
