### PR TITLE
fix: the 500 error when inviting member to team via link

### LINKED ISSUE #10906: [CAL-2381] invited by link throws 500
inviting someone to a team via link is currently throwing a 500

<sub>[CAL-2381](https://linear.app/calcom/issue/CAL-2381/invited-by-link-throws-500)</sub>

### PR DESCRIPTION
**Pull request by abhijeetsingh-22**
## What does this PR do?

Inviting someone to the team via link was throwing a 500 error. The error was due to the use of `useSuspenseQuery` in the `teams` page. When the API throws `UNAUTHORIZED` error the suspense also throws an error. I changed it to `useQuery`, and this fixed the propagation of the error.

Fixes #10906 

Video after the fix. The incognito window demonstrates the link opening when the user is not logged in. 

[Video](https://github.com/calcom/cal.com/assets/55000107/70fadf2d-8d52-4bb9-9eec-bbacf8a4b1b7)

## Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

To test the solution, generate a team invite link and try to open it after logging out of the account or from the incognito window. Earlier it used to throw error. Now it should redirect to the login page and after loging-in the team invite will be shown.

## Mandatory Tasks

- [ x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by PeerRich** [comment]
fixes #10960

**Review by Udit-takkar — COMMENTED** [review]
@abhijeetsingh-22 thanks for looking into the issue but this is not the solution we are looking for.

if someone doesn't have an account and clicks on "don't have an account" which redirects to /signup then then callBackUrl (http://localhost:3000/teams?token=2ff3afa18db0dc113edae54254bd2052d4c65928eafd68d27363fb4dfe135b14) is lost.

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
@abhijeetsingh-22 thanks for looking into the issue but this is not the solution we are looking for.

if someone doesn't have an account and clicks on "don't have an account" which redirects to /signup then then callBackUrl (http://localhost:3000/teams?token=2ff3afa18db0dc113edae54254bd2052d4c65928eafd68d27363fb4dfe135b14) is lost.

**Comment by abhijeetsingh-22** [comment]
@Udit-takkar Made the required changes.
The search params were not being passes to the signup page from the login page.  Also wrong callback URL was being passed to the login function from the signup page. Due to this the invite token was being lost on clicking on `Don't have an account`

**Comment by SomayChauhan** [comment]
hi @abhijeetsingh-22 
GREAT SOLUTION BTW!!

i found a little bug here -
* when I click on Dont't have an account link i am redricted to the  signup page
* on signup page if I click on login-in instead button the BASE_URL is again appented to the callback url

[Screencast from 29-08-23 03:19:54 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/14696744-a65f-4a05-9554-070da37c3e0f)

**Comment by abhijeetsingh-22** [comment]
Fixed the issue of wrong callback link passed to the login page from signup

**Review by zomars — DISMISSED** [review]
Thank you for your contribution 🙏 LGTM

**Comment by zomars** [comment]
Thanks again for the contribution. But it seems that the main concerns we're already addressed in #11009 

Closing this for now. Feel free to discuss if you feel this should be merged anyways.

The suspense issue was not really the culprit.

​May you be well 🙏

**Pull request closed without merging**
