### PR TITLE
feat: Add Formbricks experience management support

### LINKED ISSUE #13147: [CAL-2890] Add Formbricks experience management support
Implemented in https://github.com/calcom/cal.com/pull/13362
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2890](https://linear.app/calcom/issue/CAL-2890/pr-review-add-formbricks-experience-management-support)</sub>

### PR DESCRIPTION
**Pull request by mattinannt**
## What does this PR do?

As discussed with Peer: This PR integrates the [Formbricks](https://formbricks.com) SDK (`@formbricks/js`) into the cal.com platforms and enables running targeted in-app surveys to help understand the needs of the cal.com users.

The SDK loads non-blocking on the client-side and is only enabled when the `NEXT_PUBLIC_FORMBRICKS` environment variable is set. The SDK is only loaded within the authenticated section of the app (after login) and sends user attributes and specific actions the user performs to Formbricks to enable targeted user surveys.

Screenshot 2023-08-09 at 11 24 32

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Create a new product on [app.formbricks.com](https://app.formbricks.com) (or the self-hosted version if this applies)
- Set the `NEXT_PUBLIC_FORMBRICKS` environment variable. It should have the format: `[apiHost]+[environmentId]`, e.g. `NEXT_PUBLIC_FORMBRICKS=https://app.formbricks.com+cll24iwen02vco30hy231njcb`
- Log into cal.com and see a new person getting registered in Formbricks
- Trigger a new action by updating event types or availability in cal.com
- Create a new in-product survey in Formbricks that is getting triggered by one of these new actions
- See the survey showing in cal.com when user performs one of the actions (survey gets only shown once by default)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by PeerRich** [comment]
as mentioned per DM, it would be better to abstract the formbricks code into the formbricks.ts lib to not convolute the core files

**Comment by mattinannt** [comment]
I made the required changes 😊
For testing and getting familiar with `formbricks-js`, `debug` mode is still enabled in the formbricks SDK. Before merging the `debug` flag needs to be removed  (that's why it's still a draft PR).

**Comment by PeerRich** [comment]
closing due to stale, can reopen later

**Review by joeauyeung — COMMENTED** [review]
While testing I ran into this error when trying to display the survey box for "event-type_updated"
CleanShot 2023-11-02 at 15 06 36@2x

**Comment by joeauyeung** [comment]
When filling out the survey box, the text is white on a grey background. I tried looking through the setting to change the colour but couldn't find it.

CleanShot 2023-11-02 at 15 12 34@2x

**Pull request closed without merging**
