### PR TITLE
feat: ApplePay as Payment Option for Paid Bookings

### LINKED ISSUE #15276: [CAL-3839] Add ApplePay as Payment Option for Paid Bookings
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3839](https://linear.app/calcom/issue/CAL-3839/add-applepay-as-payment-option-for-paid-bookings)</sub>

### PR DESCRIPTION
**Pull request by martinsione**
## What does this PR do?

This PR adds the ability to accept apple pay as payment option for paid bookings.

- Fixes https://github.com/calcom/cal.com/issues/15276
- Fixes [CAL-3839]

## Mandatory Tasks (DO NOT REMOVE)
Apple pay             |  Apple pay
:-------------------------:|:-------------------------:
Screenshot 2024-06-02 at 11 37 37 PM  |  Screenshot 2024-06-02 at 11 38 40 PM

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Apple Pay only runs on https so you'll need a way to run your app through https to test locally. You can use ngrok for this and what you need to do is go to your [payment method domains](https://dashboard.stripe.com/settings/payment_method_domains?enabled=true) and add a domain if you don't have one already, once you add your domain you'll need to put the file that stripe gives you under `.well-known` so you'll create a folder in `apps/web/public/.well-known` and paste the file that stripe gives you there, once you do that you should be good to go. If you are gonna test on desktop, keep in mind that apple pay only works on safari, this `PaymentRequestButtonElement` also works we the following providers (image below) so it's up to the company to decide which to accept but all of this are set up through the dashboard so you could add as many as you want.
Screenshot 2024-06-02 at 11 48 32 PM

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Hey @kemiller Is it check before displaying Apple Pay as a payment option in our app, if the user’s device supports Apple Pay and that they have a card added to their wallet?

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Left some comments. pls address them

**Comment by martinsione** [comment]
Will do, been busy with work but I can take a look soon

**Comment by Amit91848** [comment]
Closing because of inactivity, please let us know whenever you want to continue, will re open @martinsione

**Comment by iamhvsharma** [comment]
Assign Me issue #15300

**Comment by Bhavyajain21** [comment]
@keithwillcode is this issue closed?

**Pull request closed without merging**
