### PR TITLE
fix issue where checking availability throws an error

### PR DESCRIPTION
**Pull request by femyeda**
fix issue where checking availability throws an error

safely check availability with default as "available"

### CODE REVIEW

**Comment by emrysal** [comment]
I think that this PR is outdated at the moment, and I haven't encountered the error that this fixes anymore.

**Comment by femyeda** [comment]
Fixing this now. The code was previously commented out that's why the error didn't happen. 

Here's a demo of what this code is fixing. 
https://www.loom.com/share/f3e5a66d27654bd58178c8f79910ac8c

**Comment by femyeda** [comment]
Will update to use the same logic with detecting conflicts soon after.

**Comment by emrysal** [comment]
Ah OK I understand now; this duplicates a bit from the Slots() logic hense why I got the impression this was in the wrong location. All fine.

**Pull request merged**
