### PR TITLE
Improve create event-type flow

### PR DESCRIPTION
**Pull request by afzalsayed96**
## What does this PR do?

Improves create event type flow

https://user-images.githubusercontent.com/14029371/162587974-89cb4989-48d4-4d9f-88b8-af178895c487.mov

I noticed 3 issues in Create Event Flow:
1. When we hit submit, the form resets immediately regardless of the status of submission request.
2. When there's an error in form, values get reset.
3. Post event type creation, hitting back button reopens the Create Dialog. IMO, `back` should take back to event types list.

This PR addresses the above issues.

## Type of change

- [x] Improvement (non-breaking change which adds improvement)

## How should this be tested?

NA

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]
LGTM - code looks good and works as expected when testing! Nice job

**Review by alishaz-polymath — APPROVED** [review]
LGTM
Thank you for your contribution!! 🙏

**Review by zomars — APPROVED** [review]

**Review by zomars — CHANGES_REQUESTED** [review]
For some reason it seems like these changes are breaking the E2E tests for event types. Let's try to update those as well.

**Comment by afzalsayed96** [comment]
Ah yes. I wondered if the query params would ever change. Fixed!

**Review by zomars — APPROVED** [review]

**Pull request merged**
