### PR TITLE
V2: Routing Forms - Fix Route deletion 

### LINKED ISSUE #4462: /routing-forms - Unable to delete route
Do we need to somehow stop validation overriding the delete? Also seems to not delete when that field is filled.

https://user-images.githubusercontent.com/4536123/190108624-55ad4c80-f1b3-4243-b7dd-5b9ac41ed2c0.mp4

### PR DESCRIPTION
**Pull request by hariombalhara**
Fixes #4462

### CODE REVIEW

**Review by ciaranha — COMMENTED** [review]
that was quick ⚡️

**Review by emrysal — APPROVED** [review]
LGTM, gotta love buttons not being type="button"

**Comment by zomars** [comment]
> LGTM, gotta love buttons not being type="button"

We should default this prop as "button" IMO

**Comment by hariombalhara** [comment]
@zomars 100% agreed

**Pull request merged**
