### PR TITLE
Adds preact for production builds

### PR DESCRIPTION
**Pull request by zomars**
### Before 

image
image

### After

image
image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by KATT** [comment]
I am pretty sure we will want to start using react server components and other react 18 features soon, won't this stop that?

**Comment by zomars** [comment]
> I am pretty sure we will want to start using react server components and other react 18 features soon, won't this stop that?

It's easily reversible tho, @KATT

**Comment by KATT** [comment]
> > I am pretty sure we will want to start using react server components and other react 18 features soon, won't this stop that?
> 
> It's easily reversible tho, @KATT
> 
> Also Preact doesn't run on the server, just on client side. But we'll have to dig deeper to be sure.

I honestly feel that it might be bad timing for a PR of this sort, considering React 18 is due to be released soon with a bunch of goodies that we'll want to jump on.

The bundle improvements are nice, but what matters most is the time-to-interactive, and as long as we have proper _graceful degredation_ and use `<a href=""`-links, etc for UI-components the site will be interactive straight-away on render anyway.

**Comment by PeerRich** [comment]
> I honestly feel that it might be bad timing for a PR of this sort, considering React 18 is due to be released soon with a bunch of goodies that we'll want to jump on.

i agree with @KATT's perspective. closing for now until R18 comes out and we can then have a better idea of the state of Preact / performance 🙏

**Pull request closed without merging**
