### PR TITLE
Add text editor for custom email bodies (custom workflow template)

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Adds a text editor to create better custom email bodies. 

Screenshot 2022-10-25 at 11 23 54

Fixes: 
First step of making workflow templates more flexible (#4944)

 Loom Video: https://www.loom.com/share/a56df63342434a0a9727e8f770cc4c7b

**Environment**: Staging(main branch)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Create a new workflow with an email action 
- Test the custom email template as shown in the loom video

### CODE REVIEW

**Review by alannnc — COMMENTED** [review]
Looks good and it works! But I'm not sure about using a project that it's already on maintenance mode and soon to be archived.
Also we need to consider this:
image
Looks like it's no fully supported on ios or android.
They suggest to take a look on https://github.com/facebook/lexical

**Comment by CarinaWolli** [comment]
> But I'm not sure about using a project that it's already on maintenance mode and soon to be archived.
> They suggest to take a look on https://github.com/facebook/lexical

I am trying out lexical right now, I'll make this PR a draft for now

**Comment by techquestions** [comment]
Please consider checking [Slate](https://www.slatejs.org/) and [Quill](https://quilljs.com/). Both of these are production-ready editors/editor frameworks.

**Comment by CarinaWolli** [comment]
Used facebook/lexical instead of draft.js #5654

**Pull request closed without merging**
