### PR TITLE
fix: added loading state to button

### LINKED ISSUE #11113: There Should be a Loading icon when click on button events
### Is your proposal related to a problem?

When I am onboarding on the app. Every Time I click the Next or Continue button I am confused is that clicked or not. Because there is no loading effect or any loader showing after clicking on the button.

### Describe the solution you'd like

There should be a loader icon after clicking on the buttons.

### Describe alternatives you've considered

We can also disable the button after click them once.

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

### PR DESCRIPTION
**Pull request by ashishsurya**
# fix : add loading state button in logout page for a good UX

## What does this PR do?

This PR adds a loading state to the button which moves the user login page.

Fixes #11113

https://www.loom.com/share/4b5b44da1aac457aa588fe826e3dbed9?sid=30bca723-beb6-4017-a05e-a4d6477e2d03

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Please check the video and the code changes, that must be enough for testing.

- Are there environment variables that should be set? No
- What are the minimal test data to have? None
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR 

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes
> Ran the tests, there are some tests which are failed but not related the changes made by me

### CODE REVIEW

**Comment by Rohitk131** [comment]
Hello,

I'd like to contribute to this project for Hacktoberfest. Could you please assign this issue to me?

I'm eager to help and will follow any guidelines provided.

**Comment by pragyamishra56** [comment]
could you please assign me it would be my first contribution.

**Comment by Udit-takkar** [comment]
@Rohitk131 @pragyamishra56 this is a Pull request

**Review by Udit-takkar — COMMENTED** [review]
@ashishsurya  This is a page redirection so it's better to use <Link /> element here. we can just pass href to Button to render Link Component. can you think of another way to implement this without removing href from button ?

I thought of using  router.events.on("routeChangeStart", handleRouteChangeStart) instead but it looks like router.events has been removed in next js 13

**Comment by pragyamishra56** [comment]
> @Rohitk131 @pragyamishra56 This is a Pull request

@Rohitk131 congrats⭐

**Comment by ashishsurya** [comment]
> @ashishsurya This is a page redirection so it's better to use element here. we can just pass href to Button to render Link Component. can you think of another way to implement this without removing href from button ?
> 
> I thought of using router.events.on("routeChangeStart", handleRouteChangeStart) instead but it looks like router.events has been removed in next js 13

@Udit-takkar yeah, even though we have a href prop it is still rendered as a button right. I think it is ok to remove the href and show it is a button.

Since we are alreadu having a loading prop for button, we wil be using it

**Comment by Udit-takkar** [comment]
Screenshot 2023-10-06 at 5 14 46 PM

@ashishsurya no it renders <a> tag like it should. check code in Button component

**Comment by ashishsurya** [comment]
> Screenshot 2023-10-06 at 5 14 46 PM
> @ashishsurya no it renders tag like it should. check code in Button component

I am not talking about the tag, I am talking about the appearance.

**Comment by ashishsurya** [comment]
> > Screenshot 2023-10-06 at 5 14 46 PM
> > @ashishsurya no it renders tag like it should. check code in Button component
> 
> I am not talking about the tag, I am talking about the appearance.

I think my approach is looking good with a loader, when the button is clicked, but if you want only an anchor tag there then I can work on it.

**Review by Udit-takkar — DISMISSED** [review]
LGTM. Approving for now

**Comment by ashishsurya** [comment]
@Udit-takkar why am I getting those errors

**Comment by ashishsurya** [comment]
> Screenshot 2023-10-12 at 1 46 53 PM
> @ashishsurya the test is looking for tag with href ="auth/login" on the logout page which you replace with a button.
> 
> so either 1) try to implement using tag
> 
> 2. change the E2E test to look for button instead

OK, will look into this

**Comment by ashishsurya** [comment]
@Udit-takkar all the tests ran successfully, its ready to merge.

**Review by Udit-takkar — APPROVED** [review]

**Comment by ashishsurya** [comment]
@PeerRich enable auto merging,since all tests are running successfully

**Pull request merged**
