### PR TITLE
feat: ability to provide a reason for event rejection (from email) and some changes

### LINKED ISSUE #15079: [CAL-3754] Ability to provide a reason for event rejection
### Is your proposal related to a problem?

At Twenty, we have a "book a call" CTA on our homepage with a round-robin and the "Require confirmation" activated. When I get an email to confirm a meeting, I can only accept or reject the meeting without explanations.

### Describe the solution you'd like

The ability to provide a reason for the event rejection. I want to be redirected to a webpage to explain why I'm declining the event.

### Describe alternatives you've considered

I copy and paste the attendee's email and write them the reason directly (Often it is to reschedule)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3754](https://linear.app/calcom/issue/CAL-3754/ability-to-provide-a-reason-for-event-rejection)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

- Fixes #15079 

Loom:- https://www.loom.com/share/b64241a38a2a4cf7bc11a33dd1d24d89?sid=526359eb-cefe-4255-905f-267eb57d5e4c

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by Amit91848** [comment]
Can you fix the merge conflicts please @anikdhabal

**Review by ibex088 — DISMISSED** [review]
LGTM
Nice work as always man 💯

**Comment by CarinaWolli** [comment]
@anikdhabal can you fix the merge conflicts? 🙏

**Comment by anikdhabal** [comment]
@CarinaWolli fixed it

**Review by CarinaWolli — APPROVED** [review]
Approving on behalf of @SomayChauhan
Merge conflicts fix looked good and simple 👍

**Pull request merged**
