### PR TITLE
fix: ui of webhook segment

### LINKED ISSUE #5433: [PRO-25] UI bug: Segment component is oversized and missing padding
Currently

Should be

[Segments - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=15212%3A117411)

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #5433

Screenshot 2022-11-10 at 1 16 19 AM

### CODE REVIEW

**Review by JeroenReumkens — CHANGES_REQUESTED** [review]
@Udit-takkar  This component looks very similar to `ToggleGroup` in `packages/ui/v2/core/form/ToggleGroup.tsx`. Could you have a look and see if you can use that one? 

I also think that ToggleGroup perhaps shouldn't be in the form directory, but I will improve that when moving those form components over to the new form directory later!

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/201071068-d2684602-0dd1-4395-9484-05467335e310.mov

**Comment by Udit-takkar** [comment]
@JeroenReumkens  done

**Comment by JeroenReumkens** [comment]
@Udit-takkar  Amazing, looks great! 😄

**Review by JeroenReumkens — APPROVED** [review]

**Pull request merged**
