### PR TITLE
fixed ui bug

### LINKED ISSUE #8707: Search Bar Alignment in App Store
In App Store Search Bar not align on it's right position [https://app.cal.com/apps](url)
Steps to Reproduce

1. Go to cal.com
2. Click on Go App
3. Click on App Store
4. then click on search bar and you can find the issue,

Screenshot (210)

### PR DESCRIPTION
**Pull request by swarajbachu**
## What does this PR do?
Fixes: https://github.com/calcom/cal.com/issues/8707

I fixed the alignment of search bar in /app

Screenshot 2023-05-07 at 8 06 55 PM

Screenshot 2023-05-07 at 8 07 09 PM

Fixes # (issue)

- I added m-1 which gives it a little margin for all the sides and fix the alignment issue for all devices
Screenshot 2023-05-07 at 8 08 31 PM
Screenshot 2023-05-07 at 8 09 20 PM

@PeerRich @Udit-takkar

### CODE REVIEW

**Comment by swarajbachu** [comment]
@PeerRich @Udit-takkar

**Review by Udit-takkar — COMMENTED** [review]
@swarajbachu  I am not able to reproduce the bug on app.cal.com. Has it been fixed already ?

Screenshot 2023-05-08 at 2 17 08 PM

**Comment by swarajbachu** [comment]
> @swarajbachu I am not able to reproduce the bug on app.cal.com. Has it been fixed already ?
> 
> Screenshot 2023-05-08 at 2 17 08 PM

when you click on it, the focus mode is out of alientment, for all the devices!

**Comment by swarajbachu** [comment]
@Udit-takkar  pls check this, small change

**Review by Udit-takkar — APPROVED** [review]
Screenshot 2023-05-08 at 8 07 23 PM

LGTM
A bit hacky solution though

**Comment by swarajbachu** [comment]
> Screenshot 2023-05-08 at 8 07 23 PM
> 
> LGTM A bit hacky solution though

got it, why isnt it merged yet?

**Pull request merged**
