### PR TITLE
chore: Added missing dependency

### PR DESCRIPTION
**Pull request by sakshambp**
/claim #12446

### CODE REVIEW

**Comment by PeerRich** [comment]
i am not entirely sure if this is the right dependency in the right file. @krumware any details?

**Comment by sakshambp** [comment]
@krumware can you let me know whats the success criteria? How can i test my change basically how can i build docker just like you did in your issue example

I can test and update the PR accordingly if it passes success criteria (I think which is just that docker build should succeed)

**Comment by sakshambp** [comment]
@PeerRich  this issue was raised in the cal.com repo i also see [docker repo](https://github.com/calcom/docker/) exists , was it intended for the docker repo?

**Comment by krumware** [comment]
hi @sakshambp, you should also be need to commit the updated lockfile(s).

To test the docker build, you can follow the Advanced Users steps in the docker repo: https://github.com/calcom/docker#advanced-users-build-and-run-calcom
After Step 3, (the initial submodule steps), cd to the calcom submodule and check out your branch, then proceed with the build.

I'm on discord if you need help (colinkrumware)

**Comment by krumware** [comment]
@alishaz-polymath you mentioned in Discord that the fix was merged, and I do see that the build completed successfully (despite there being another dependency issue that's new).
Are you by chance able to reference the fix/commit/pr here?

**Comment by sakshambp** [comment]
Got it, I will work on same :) Let me try the steps to test as well

**Comment by sakshambp** [comment]
Updated PR also tested it with docker build
```
/Users/saksham.jain/Documents/ago/cal/calcom-docker/calcom [add-dependency]
% DOCKER_BUILDKIT=0 docker compose build calcom
WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRES_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DATABASE_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRES_DB" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRES_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DATABASE_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRES_DB" variable is not set. Defaulting to a blank string.
Sending build context to Docker daemon  1.099GB
Step 1/40 : FROM node:18 as builder
 ---> b10a162def5c
Step 2/40 : WORKDIR /calcom
 ---> Using cache
 ---> 759ef8b1358f
Step 3/40 : ARG NEXT_PUBLIC_LICENSE_CONSENT
 ---> Using cache
 ---> bef2a8c305f9
Step 4/40 : ARG CALCOM_TELEMETRY_DISABLED
 ---> Using cache
 ---> 08868b765c33
Step 5/40 : ARG DATABASE_URL
 ---> Using cache
 ---> 165f3cef1501
Step 6/40 : ARG NEXTAUTH_SECRET=secret
 ---> Using cache
 ---> cdf1cb3c7049
Step 7/40 : ARG CALENDSO_ENCRYPTION_KEY=secret
 ---> Using cache
 ---> 74bad210e710
Step 8/40 : ARG MAX_OLD_SPACE_SIZE=4096
 ---> Using cache
 ---> 7b0920829fbc
Step 9/40 : ENV NEXT_PUBLIC_WEBAPP_URL=http://NEXT_PUBLIC_WEBAPP_URL_PLACEHOLDER     NEXT_PUBLIC_LICENSE_CONSENT=$NEXT_PUBLIC_LICENSE_CONSENT     CALCOM_TELEMETRY_DISABLED=$CALCOM_TELEMETRY_DISABLED     DATABASE_URL=$DATABASE_URL     NEXTAUTH_SECRET=${NEXTAUTH_SECRET}     CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}     NODE_OPTIONS=--max-old-space-size=${MAX_OLD_SPACE_SIZE}
 ---> Using cache
 ---> f4f21e76c181
Step 10/40 : COPY calcom/package.json calcom/yarn.lock calcom/.yarnrc.yml calcom/playwright.config.ts calcom/turbo.json calcom/git-init.sh calcom/git-setup.sh ./
 ---> Using cache
 ---> 4aabdc5f8575
Step 11/40 : COPY calcom/.yarn ./.yarn
 ---> Using cache
 ---> c0d8a5ebc917
Step 12/40 : COPY calcom/apps/web ./apps/web
 ---> Using cache
 ---> 7ab36b8f007f
Step 13/40 : COPY calcom/packages ./packages
 ---> Using cache
 ---> e91456f9a954
Step 14/40 : COPY calcom/tests ./tests
 ---> Using cache
 ---> ba69ff7e1666
Step 15/40 : RUN yarn config set httpTimeout 1200000 &&     npx turbo prune --scope=@calcom/web --docker &&     yarn install &&     yarn db-deploy &&     yarn --cwd packages/prisma seed-app-store
 ---> Using cache
 ---> 99fd2583e702
Step 16/40 : RUN yarn turbo run build --filter=@calcom/web
 ---> Using cache
 ---> 3723e718d42a
Step 17/40 : RUN rm -rf node_modules/.cache .yarn/cache apps/web/.next/cache
 ---> Using cache
 ---> 09509178fca9
Step 18/40 : FROM node:18 as builder-two
 ---> b10a162def5c
Step 19/40 : WORKDIR /calcom
 ---> Using cache
 ---> 759ef8b1358f
Step 20/40 : ARG NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000
 ---> Using cache
 ---> 5d65649a072e
Step 21/40 : ENV NODE_ENV production
 ---> Using cache
 ---> c0662757f4de
Step 22/40 : COPY calcom/package.json calcom/.yarnrc.yml calcom/yarn.lock calcom/turbo.json ./
 ---> Using cache
 ---> 2b6433faf936
Step 23/40 : COPY calcom/.yarn ./.yarn
 ---> Using cache
 ---> 6051fad5e10d
Step 24/40 : COPY --from=builder /calcom/node_modules ./node_modules
 ---> Using cache
 ---> faa0069e4152
Step 25/40 : COPY --from=builder /calcom/packages ./packages
 ---> Using cache
 ---> 534e43c77cab
Step 26/40 : COPY --from=builder /calcom/apps/web ./apps/web
 ---> Using cache
 ---> c9c627f11165
Step 27/40 : COPY --from=builder /calcom/packages/prisma/schema.prisma ./prisma/schema.prisma
 ---> Using cache
 ---> 509cc6daddf3
Step 28/40 : COPY scripts scripts
 ---> Using cache
 ---> 419fa7847354
Step 29/40 : ENV NEXT_PUBLIC_WEBAPP_URL=$NEXT_PUBLIC_WEBAPP_URL     BUILT_NEXT_PUBLIC_WEBAPP_URL=$NEXT_PUBLIC_WEBAPP_URL
 ---> Using cache
 ---> f0e57d87d08d
Step 30/40 : RUN scripts/replace-placeholder.sh http://NEXT_PUBLIC_WEBAPP_URL_PLACEHOLDER ${NEXT_PUBLIC_WEBAPP_URL}
 ---> Using cache
 ---> 1599b9c63aab
Step 31/40 : FROM node:18 as runner
 ---> b10a162def5c
Step 32/40 : WORKDIR /calcom
 ---> Using cache
 ---> 759ef8b1358f
Step 33/40 : COPY --from=builder-two /calcom ./
 ---> 205e21aede08
Step 34/40 : ARG NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000
 ---> Running in 4b879d2502db
Removing intermediate container 4b879d2502db
 ---> e5ae306cbc6c
Step 35/40 : ENV NEXT_PUBLIC_WEBAPP_URL=$NEXT_PUBLIC_WEBAPP_URL     BUILT_NEXT_PUBLIC_WEBAPP_URL=$NEXT_PUBLIC_WEBAPP_URL
 ---> Running in 90de8f50d072
Removing intermediate container 90de8f50d072
 ---> 4eee05116194
Step 36/40 : ENV NODE_ENV production
 ---> Running in e04439648285
Removing intermediate container e04439648285
 ---> 3ea4fa56aa2f
Step 37/40 : EXPOSE 3000
 ---> Running in 48aee966ea14
Removing intermediate container 48aee966ea14
 ---> de0e3b3df046
Step 38/40 : HEALTHCHECK --interval=30s --timeout=30s --retries=5     CMD wget --spider http://localhost:3000 || exit 1
 ---> Running in e2a37632fc70
Removing intermediate container e2a37632fc70
 ---> ce742462eb5e
Step 39/40 : CMD ["/calcom/scripts/start.sh"]
 ---> Running in 8403a379f3b5
Removing intermediate container 8403a379f3b5
 ---> 1d8b447ed4af
Step 40/40 : LABEL com.docker.compose.image.builder=classic
 ---> Running in f93882d63c24
Removing intermediate container f93882d63c24
 ---> 9a6145477b1b
Successfully built 9a6145477b1b
Successfully tagged calcom.docker.scarf.sh/calcom/cal.com:latest
```

**Comment by krumware** [comment]
Looks good!

Note for others who may work on future ones and stumble on this, make sure you run `npm run clean` prior to testing dependency updates with the docker build. This will keep your updated package.json and package-lock.json but will make sure your installed node_modules don't make it into the build (which can create a false positive, since node_modules isn't wiped on a build)

**Comment by sakshambp** [comment]
@krumware thanks for suggestion probably we can put this in setup steps as well

Can this issue be closed by merging the PR?

**Comment by PeerRich** [comment]
we'll fix this in-house. it turns out we cant take contributor yarn.lock files

**Comment by sakshambp** [comment]
@PeerRich  any particular reason for that?
Also can i atleast get a tip?

**Pull request closed without merging**
