### PR TITLE
feat: Added zod schema 

### PR DESCRIPTION
**Pull request by abhinandan-thakur**
## What does this PR do?

Added Zod Schema to validate and parse app metadata stored in `config.json` to ensure consistency and better error handling.

-GitHub issue number - #14808 

- Fixes CAL-3584

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] yes

- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] no

- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.
- [ ] yes

## How should this be tested?

The schema should validate the config.json and pass without errors if the metadata is correct.

- Are there environment variables that should be set?
no

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
yes

- My code doesn't follow the style guidelines of this project
no

- I haven't commented my code, particularly in hard-to-understand areas
yes

- I haven't checked if my changes generate no new warnings
yes

### CODE REVIEW

**Comment by keithwillcode** [comment]
@hariombalhara Can you please take a look at this one?

**Comment by hariombalhara** [comment]
@realAbhi-web Thanks for the PR 🙏 

Could you take a look at this comment and see if it would improve things and is doable or not?

https://github.com/calcom/cal.com/pull/14997#issuecomment-2141367733

**Comment by realAbhi-web** [comment]
i looked at your comment, i didn't completly grasp the idea of what you were guiding for can you explain in detail, I will try my best but still i am a newbie

**Comment by hariombalhara** [comment]
Hey, so the requirement is to have type safety for config.json. We could do it in 2 ways I believe
- Parse each config.json through zod schema which adds runtime cost which keeps on increasing as more apps are added.
- Instead of using config.json directly we generate a ts file from it and use that instead.So, the code never imports config.json when using an app. We will commit the generated files. We do similar file generation in build file linked in the comment.  We could use zod at compile time this way before generating the ts files.

**Comment by zomars** [comment]
Closing this PR since is not the meeting our current requirements. Feel free re-open once feedback is addressed. 🙏

**Pull request closed without merging**
