### PR TITLE
Email Variables Bug

### LINKED ISSUE #6942: [CAL-1010] Emails in other languages showing variables
Scheduled emails show variables for attendees in the email

Created via Threads. See full discussion: [https://threads.com/messages/b0b1344b-24d6-4671-bb39-0b7ecbbdd28d?messageID=9925142c-bf54-4045-8888-819ca47487b6](https://threads.com/messages/b0b1344b-24d6-4671-bb39-0b7ecbbdd28d?messageID=9925142c-bf54-4045-8888-819ca47487b6)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1010](https://linear.app/calcom/issue/CAL-1010/emails-in-other-languages-showing-variables)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
Signed-off-by: Udit Takkar <udit.07814802719@cse.mait.ac.in>

## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/6942

all variables changed here https://github.com/calcom/cal.com/pull/6375

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Udit-takkar** [comment]
regression from https://github.com/calcom/cal.com/pull/6375

**Comment by Udit-takkar** [comment]
not sure how to make change in zh-CN language others are done

**Comment by emrysal** [comment]
@PeerRich for zh-CN should we just remove the key and have it re-translated then?

**Review by emrysal — APPROVED** [review]

**Comment by PeerRich** [comment]
> @PeerRich for zh-CN should we just remove the key and have it re-translated then?

yep

**Pull request merged**
