### PR TITLE
Got rid of doubled emails, introduced the EventManager, made several bugfixes, linting + code style improvements

### PR DESCRIPTION
**Pull request by Nico-J**
This PR is a typical example of "small task that got bigger and more complex the more you looked at it".

It all started when there was a request to get rid of the doubled emails when booking a video call event: the mail with and the mail without credentials.

This is a pretty good point and it led me to improving the overall event creation and update structure, because the API booking handler (`api/book/[user].ts`) was bloated more and more and the booking logic seemed to get even more complex when adding the mail stuff there.

That's why I added the EventManager. At first, it's just initialized by using its constructor `new EventManager(currentUser.credentials);`. By delivering the credentials to it, it automatically takes care of classifying the credentials into calendar credentials and video credentials.

Instead of the whole booking logic, we now simply use `await eventManager.create(evt);` in order to create a new booking. The default use case is:
1. Always create events for **all** calendar integrations.
2. If, and only if, the location is set to a specific integration (like Video), create an event just for that integration as well.

This logic is integrated into the event creation flow of the EventManager. The same goes for updating events.
Deleting events is independent from all this and is handled separately in the cancel file as before.

When it's a video integration event, the normal calendar confirmation emails are suppressed; only the video integration email including the credentials is being sent in this case. Also, I have put the credentials into the location as an EntryPoint:
image

Furthermore, there were several bugs that have been fixed. For example, the rescheduling didn't work properly anymore (probably due to an automatic merge). The rescheduleId wasn't forwarded after choosing a date, leading to the existing calendar event not being deleted (just a new one was created). This and some other things have been fixed.

Last, but not least, tons of linting and code style stuff has been fixed with this PR.

### CODE REVIEW

**Comment by Nico-J** [comment]
I've resolved all conflicts and combined Malte's create and update logic that was included in the booking handler with my EventManager logic. It should now fully work hand in hand.

I've tested creating, updating and canceling events for basic CalendarEvents, for events with both calendar and Zoom integration and the previously mentioned scenarios with required confirmation as well.

All of the above situations worked flawlessly in my case and no exceptions occured. Nevertheless, that should not replace testing by others.

**Review by femyeda — CHANGES_REQUESTED** [review]
Every thing looks good, and a lot cleaner. 

However, failing on creating events with Google Meet set as the location. 
Because the EventManager expects integrations:* to be a VideoEvent, in the case of Google Meet, there isn't actually in integration for Google Meet, it uses the Google Calendar credentials. There could be a hack to actually treat Google Meet as a Video Integration and mapping to the Google Calendar credentials. 

Note* It failed to properly process the location, the booking is created, and does add to Google Calendar.

**Comment by femyeda** [comment]
Note* Zoom Integration is a bit different because it's both a "Calendar Connection" and a "Meeting Location".

I think until the teams integration, which will give us more insight into the similarities of these video platforms, hard coding cases for the zoom integration would work, instead of calling the video client for every location matching "integration:*".

**Comment by Nico-J** [comment]
Hey @femyeda ,
thank you for your review, that's a good point! :) I've now hard-coded the check whether it's a "video" integration and renamed it to "isDedicated". "Dedicated" in that sense means that it's a fully distinct service (like Zoom) that doesn't allow the combined creation of calendar and video events in one step (like Google Meet would do, by just adding conferenceData to the API call).

I've tested creating events with Google Meet and it works without problems now.

**Review by femyeda — APPROVED** [review]

**Comment by baileypumfleet** [comment]
As soon as these conflicts are resolved, I'm happy to merge :)

**Comment by Nico-J** [comment]
@baileypumfleet All conflicts have been resolved. :) I've tested the basic Zoom functionality again and it still works.

**Review by pumfleet — APPROVED** [review]

**Pull request merged**
