### PR TITLE
fix: Webex app not working

### LINKED ISSUE #15476: [CAL-3823] Webex app not working
After installing and entering credentials, it leads to an empty page

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3823](https://linear.app/calcom/issue/CAL-3823/webex-app-not-working)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

- Fixes #15476 
- Fixes CAL-3823

https://github.com/calcom/cal.com/assets/74371312/62a3091a-cf89-48dd-bd27-51e5eb57092c

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

### CODE REVIEW

**Review by ibex088 — COMMENTED** [review]
Great Work as always @Amit91848 
can you confirm that adding webex as a location in events and booking it generates a link. I tried but for me it is throwing error, could be I have the scopes set up wrong

Screenshot 2024-06-21 at 9 31 14 PM

Screenshot 2024-06-21 at 9 30 34 PM

**Review by Udit-takkar — APPROVED** [review]
LGTM. tested and worked fine

**Comment by Amit91848** [comment]
> Great Work as always @Amit91848 can you confirm that adding webex as a location in events and booking it generates a link. I tried but for me it is throwing error, could be I have the scopes set up wrong
> 
> Screenshot 2024-06-21 at 9 31 14 PM
> 
> Screenshot 2024-06-21 at 9 30 34 PM

Hey @Udit-takkar 
I was trying this locally and am facing the same issue. Does this work for you?

**Comment by Udit-takkar** [comment]
@Amit91848 Yeah it worked fine for me.

Screenshot 2024-06-22 at 12 35 27 AM

**Comment by Udit-takkar** [comment]
@SomayChauhan did you add the client ID and Client secret in admin settings > apps in cal.com ?

**Comment by Amit91848** [comment]
> @Amit91848 Yeah it worked fine for me.
> 
> 
> 
> Screenshot 2024-06-22 at 12 35 27 AM
> 
> 

I did some digging and found out that only spark:kms scope was being set. Maybe it was some setup issue

**Pull request merged**
