### PR TITLE
fix: Allow impersonation from the /settings/admin/users page

### LINKED ISSUE #13240: [CAL-2975] Allow impersonation from the /settings/admin/users page.
### Is your proposal related to a problem?

We have a clear list of users, and then a seperate impersonation page, where we type in the user?

CleanShot 2024-01-17 at 13 09 23@2x

Why are these not just tied together? and/or better yet, inside the dropdown for the edit/lock/etc.

### Describe the solution you'd like

Add impersonation to the dropdown on the users row of /settings/admin/users
(Describe your proposed solution here.)

### Describe alternatives you've considered

Could just put the impersonation on this page?

---

##### House rules

* If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  * For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  * Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2975](https://linear.app/calcom/issue/CAL-2975/allow-impersonation-from-the-settingsadminusers-page)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
Fixes #13240 
/claim #13240

Screenshot 2024-01-17 205916

The pull request also addressed a minor issue by fixing the occurrence of the "License Required" message displaying twice.

eg:-
Screenshot 2024-01-19 160058

### CODE REVIEW

**Comment by Hybes** [comment]
hi @Udit-takkar and @anikdhabal, the functionality works, but when you click the impersonate button, it routes you to: /settings/admin/users as the new user. Which they would not have permission to.
also, I don't think the VenetianMask is the standard Icon to use for Impersonation

**Comment by anikdhabal** [comment]
> hi @Udit-takkar and @anikdhabal, the functionality works, but when you click the impersonate button, it routes you to: /settings/admin/users as the new user. Which they would not have permission to. also, I don't think the VenetianMask is the standard Icon to use for Impersonation

Yeah that's true. Let me fix that quickly.

**Comment by anikdhabal** [comment]
cc @Udit-takkar @PeerRich

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
It isn't working

https://github.com/calcom/cal.com/assets/53316345/8550b962-e368-4c84-8fcb-d2c53f6df107

you can look at /settings/teams/[id]/members page on how it should work

https://github.com/calcom/cal.com/assets/53316345/73b91f8d-a26e-4539-b112-afc9956cb85f

**Comment by anikdhabal** [comment]
https://github.com/calcom/cal.com/assets/81948346/2b11f7d1-d4f5-416a-9586-06c46fa246c4

But it's working fine for me @Udit-takkar.

**Comment by Udit-takkar** [comment]
@anikdhabal could you also add the modal like in the /teams? I re review this again or ask someone else to confirm

**Comment by anikdhabal** [comment]
> @anikdhabal could you also add the modal like in the /teams? I re review this again or ask someone else to confirm

Ok Let me quickly add this in the /teams.

**Comment by anikdhabal** [comment]
https://github.com/calcom/cal.com/assets/81948346/811aaf39-d393-4bd5-91bc-2fa8b902968a

@Udit-takkar

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Pull request merged**
