### PR TITLE
CALCOM-6362 - [CAL-728] App Sidebar. Child items aren't sized/spaced properly

### LINKED ISSUE #6362: [CAL-728] App Sidebar. Child items aren't sized/spaced properly
Our current child nav items under the App Store don't match the designs.

The result is "Installed Apps" looks closer to Routing forms than it does the "App Store". There's some sensitive spacing applied in the designs to counter this that's not reflected in the app.

I've pointed out the issues here:

[Sidebar Issues - ❖ Cal DS (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=23271%3A141827&t=nwPX8h3DkOoPC05z-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-728](https://linear.app/calcom/issue/CAL-728/app-sidebar-child-items-arent-sizedspaced-properly)</sub>

### PR DESCRIPTION
**Pull request by gitstart-calcom**
## What does this PR do?
Fixes #6362 

## Demo
https://www.loom.com/share/3fd2efbe97d54c55938ed5e8eef03d81

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
Screenshot 2023-01-12 at 6 07 08 PM

This header should be 24px

**Comment by gitstart-calcom** [comment]
Hi @Udit-takkar! Logo size has been updated now, please take a look

**Review by Udit-takkar — APPROVED** [review]
LGTM  your design was correct earlier @gitstart-calcom. 24px was for header element

**Comment by Jaibles** [comment]
The nav items look great but I'm seeing the logo jump around when I test it and land on "App Store".

Uploading CleanShot 2023-01-12 at 16.51.54.mp4…

@gitstart can you follow up with a fix for that?

**Pull request merged**
