### PR TITLE
feat: able docker to the app

### LINKED ISSUE #8591: Create a full independent docker environment to run the project on
### Is your proposal related to a problem?

I tried to get one "good first issue" and was kind of annoying to setup a database externally just to start to contribute to the project

### Describe the solution you'd like

It would be nice to have a `docker-compose.yml` setup with everything that we need to run the app, something that with a `docker-compose up` on the repo's source we'll be able to run the project easily.

### PR DESCRIPTION
**Pull request by wesleymatosdev**
- ci: add local Dockerfile
- ci: create docker-compose file
- ci: use host network on container
- refactor: simplify dockerfile
- build: add docker ignore
- build: delete db-up from turbo.json

## What does this PR do?

Fixes #8591

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] It should be able to successfully run the app by using `docker-compose up` in a brand new cloned repo
- [ ] Should be able to successfully run the app by using `docker-compose up` for the second time

## Checklist

- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

/claim #8591

### CODE REVIEW

**Comment by ologbonowiwi** [comment]
I'm stuck on this one, and getting help from the maintainers would be nice.

In the current state of the code, when I run `docker-compose up`, I see the following logs:
image

The deploy/seed for the database worked adequately, but the app never passes from this `compiled client and server successfully in` log.
I don't have any experience with turbo repo, so it's unclear how I should create new scripts to handle the stuff I did, or what I need to change to the app works.

**Comment by krumware** [comment]
I'm sorry, I'm coming at this a bit cold. I went back and looked at this through the original issue thread.
Naive question: Is this an necessary alternative to the calcom/docker repo? Is it an enhancement to the developer experience but isn't meant to replace calcom/docker? Just making sure I review this from the appropriate lens!

**Comment by ologbonowiwi** [comment]
Hey, @krumware, thank you for reviewing my PR!

This aims to improve the developer experience for new people that want to work on the project.
I'm trying to make running the project as easy as cloning the repo and running `docker-compose up` 😄 

I struggled a lot trying to make it work, as I mentioned in [this comment](https://github.com/calcom/cal.com/pull/9017#issuecomment-1556291475); do you have any advice to run the app/database/seeds for the first time using just one command ~`docker-compose up`~?

**Comment by ologbonowiwi** [comment]
How should we use the docker file of that image? Should I copy the docker file, or do I need anything else, like creating a git submodule or anything like that?

**Comment by PeerRich** [comment]
closing according to https://github.com/calcom/cal.com/pull/9017#issuecomment-1568381257

**Comment by ologbonowiwi** [comment]
I'll create another one using `calcom/docker` as the base image.

**Pull request closed without merging**
