### PR TITLE
feat: Add Eastern and Eastern Pacific time zones  #16880

### LINKED ISSUE #16880: [CAL-4434] feature request:  Add Eastern Time -US & Canada, Pacific Easter etc. in timezone picker
### Is your proposal related to a problem?

Screenshot 2024-09-30 at 1 53 23 PM

<sub>[CAL-4434](https://linear.app/calcom/issue/CAL-4434/feature-request-add-eastern-time-us-and-canada-pacific-easter-etc-in)</sub>

### PR DESCRIPTION
**Pull request by ShreyTanna29**
## What does this PR do?

Added Eastern Time - US Canada, Pacific Time , etc
In total 15 time zones are added.

- Fixes #16880
- Fixes CAL-4434

## Mandatory Tasks (DO NOT REMOVE)

- [ YES] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [N/A ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ YES] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

visit any page which has time zones options in it and you can see time zones like Eastern Time - US Canada, Central TIme, Mountain Time, Indian Standard TIme, etc.

- Are there environment variables that should be set? NO
- What are the minimal test data to have? No specific test data required
- What is expected (happy path) to have (input and output)?  Getting newly added time zones in time zones dropdowns 
- Any other important info that could help to test that PR. NO

### CODE REVIEW

**Comment by Praashh** [comment]
Hey @ShreyTanna29 Thanks for contributing, can you please sign CLA.

**Comment by ShreyTanna29** [comment]
> Hey @ShreyTanna29 Thanks for contributing, can you please sign CLA.

Hello, I have already signed the CLA, please check again.

**Comment by Praashh** [comment]
getTimezone should return the appropriate time zones for a given city name. @ShreyTanna29 could you please check this?

**Comment by Praashh** [comment]
> > Hey @ShreyTanna29 Thanks for contributing, can you please sign CLA.
> 
> Hello, I have already signed the CLA, please check again.

Also, test ``PR Update / Tests / Unit (pull_request_target) ``` isn't working as expected.

**Comment by ShreyTanna29** [comment]
> getTimezone should return the appropriate time zones for a given city name. @ShreyTanna29 could you please check this?

This was due to matching the " timezones recieved in addCitiesToDropDown" with the inlineSnapshot provided in getTimezone.test.ts, which was throwing error whenever a new timezone appeared, so I added new timezones in the snapshot , please check the latest commits, this issue is now solved.

**Comment by ShreyTanna29** [comment]
> > > Hey @ShreyTanna29 Thanks for contributing, can you please sign CLA.
> > 
> > 
> > Hello, I have already signed the CLA, please check again.
> 
> Also, test `PR Update / Tests / Unit (pull_request_target) ` isn't working as expected.

I checked 'PR Update / Tests / Unit (pull_request_target)` I couldn't find any issues over there. Please refer the attached screen shots, Please provide more details on it.
pr-update-test--unit
tests-units ScreeenShot

**Comment by Praashh** [comment]
> > > > Hey @ShreyTanna29 Thanks for contributing, can you please sign CLA.
> > > 
> > > 
> > > Hello, I have already signed the CLA, please check again.
> > 
> > 
> > Also, test `PR Update / Tests / Unit (pull_request_target) ` isn't working as expected.
> 
> I checked 'PR Update / Tests / Unit (pull_request_target)` I couldn't find any issues over there. Please refer the attached screen shots, Please provide more details on it. pr-update-test--unit tests-units ScreeenShot

yes, i was there and after fixing the timezones issue, it also got fixed.

**Review by emrysal — DISMISSED** [review]
Looks good to me 👍

**Comment by ShreyTanna29** [comment]
@Praashh @emrysal , it seems this pr isn't getting auto merge as it fails some tests that has nothing to do with changes iI made and also I dont know how to fix them, please help.

**Comment by Praashh** [comment]
> @Praashh @emrysal , it seems this pr isn't getting auto merge as it fails some tests that has nothing to do with changes I made in the code and also I dont know how to fix them, please help.

Hey @ShreyTanna29, don't worry about those tests, please make changes I suggested to maintain good practices and directory structure so I can approve it, although your code is working fine.

**Comment by ShreyTanna29** [comment]
> > @Praashh @emrysal , it seems this pr isn't getting auto merge as it fails some tests that has nothing to do with changes I made in the code and also I dont know how to fix them, please help.
> 
> Hey @ShreyTanna29, don't worry about those tests, please make changes I suggested to maintain good practices and directory structure so I can approve it, although your code is working fine.

 thank you ,and  please guide me if you think that anything in this code can be improved , also I have followed and applied your previous suggestions.

**Comment by Praashh** [comment]
> > > @Praashh @emrysal , it seems this pr isn't getting auto merge as it fails some tests that has nothing to do with changes I made in the code and also I dont know how to fix them, please help.
> > 
> > 
> > Hey @ShreyTanna29, don't worry about those tests, please make changes I suggested to maintain good practices and directory structure so I can approve it, although your code is working fine.
> 
> thank you ,and please guide me if you think that anything in this code can be improved , also I have followed and applied your previous suggestions and would love to change further anything required in this code.

Hey! I have already suggested you, please add those changes.

**Comment by ShreyTanna29** [comment]
> > @Praashh @emrysal , it seems this pr isn't getting auto merge as it fails some tests that has nothing to do with changes I made in the code and also I dont know how to fix them, please help.
> 
> Hey @ShreyTanna29, don't worry about those tests, please make changes I suggested to maintain good practices and directory structure so I can approve it, although your code is working fine.

sorry but what directory structure and good practices did you suggested, cause I cant see any comment regarding that.

**Comment by Praashh** [comment]
> > > @Praashh @emrysal , it seems this pr isn't getting auto merge as it fails some tests that has nothing to do with changes I made in the code and also I dont know how to fix them, please help.
> > 
> > 
> > Hey @ShreyTanna29, don't worry about those tests, please make changes I suggested to maintain good practices and directory structure so I can approve it, although your code is working fine.
> 
> sorry but what directory structure and good practices did you suggested, cause I cant see any comment regarding that.

please check this, https://github.com/calcom/cal.com/pull/16974/files/f5ece1f4dabaf68df5c44a6d8245ca6b7bb8f3f9#diff-22aa63d18fd13b882f1abed60dae3b1560e2b517602e8a6a0babad035a77fe58

**Comment by ShreyTanna29** [comment]
> > > > @Praashh @emrysal , it seems this pr isn't getting auto merge as it fails some tests that has nothing to do with changes I made in the code and also I dont know how to fix them, please help.
> > > 
> > > 
> > > Hey @ShreyTanna29, don't worry about those tests, please make changes I suggested to maintain good practices and directory structure so I can approve it, although your code is working fine.
> > 
> > 
> > sorry but what directory structure and good practices did you suggested, cause I cant see any comment regarding that.
> 
> please check this, https://github.com/calcom/cal.com/pull/16974/files/f5ece1f4dabaf68df5c44a6d8245ca6b7bb8f3f9#diff-22aa63d18fd13b882f1abed60dae3b1560e2b517602e8a6a0babad035a77fe58

sorry but i cant see any changes requested on the files , no conversation on the file page, no comments on the file, no inline comments or no commits from your side, have I missed any section to look for your suggestions, exactly where have you posted your suggestions on the file page, please guide me.

**Review by emrysal — APPROVED** [review]
Fixed availability test

**Comment by PeerRich** [comment]
regression: cities are not showing anymore

image

**Comment by ShreyTanna29** [comment]
> regression: cities are not showing anymore
> 
> image

Looking into it

**Comment by emrysal** [comment]
@PeerRich @ShreyTanna29  - I'll add a test to cover this in the follow up PR to fix

**Comment by ShreyTanna29** [comment]
> regression: cities are not showing anymore
> 
> image

I have solved the issue, please check Pull request #17064 , this was due to my mistake, I had by mistake added timezones as cities in the dropdown, I have fixed this everywhere, also I have improved naming of my new timezones in additionalTimezones.json, I have followed the cal.com prewritten naming convections, e.g. instead of identifier I named it as city, ect. Sorry for the mistake. Please check it out and let me know if any improvements needs to be done further. @PeerRich @emrysal

**Pull request merged**
