### PR TITLE
fix: show recordings even to free plan users

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes: for free plan users they should be able to see the recordings but with upgrade button. currently the api end point inly returns the recordings to teams plan user. 

https://files.slack.com/files-pri/T01N4FWPGPP-F04J87495RC/screenshot_2023-01-11_at_7.39.16_pm.png

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by zomars — APPROVED** [review]

**Comment by flexbox** [comment]
This is nice @Udit-takkar 

I was able to upgrade and create a team

BUT 
when I go back to the page I still do not have access to past recorded sessions 

image

Event If I am part of the team 😭 

image

**Comment by Udit-takkar** [comment]
@flexbox can you try logging out again and logging in again? your session would get updated as team plan user. do confirm if this works or not .

**Comment by flexbox** [comment]
It works!

image

So there "just a small state error" to fix 😅
—or as a quickwin add some text in the funnel to ask people to login again

**Comment by Udit-takkar** [comment]
@flexbox  ok will do

**Comment by flexbox** [comment]
Humm I answered to fast 

I have a `405` when I try to hit download

image


image

**Comment by Udit-takkar** [comment]
@flexbox checking

**Comment by Udit-takkar** [comment]
@flexbox try using this url https://cal.com/bookings/past ( replace app.cal.com with cal.com ) for now then you won't get this error. in the mean time i will raise a PR to make it work on both of the domains

**Comment by flexbox** [comment]
@Udit-takkar 

it works! 

image

Looks like the famous CORS issue

**Comment by flexbox** [comment]
@Udit-takkar 
I think the download button dissapeared again 😅

I tried on 
- https://cal.com/bookings/past
- https://app.cal.com/bookings/past

I have this with a recorded call

image

**Pull request merged**
