### PR TITLE
chore: Button Component Tidy up

### PR DESCRIPTION
**Pull request by sean-brydon**
For some reason we were using this function to apply conditional styles. I think we can do without it. 

Also added the correct disabled state for destructive buttons. 

Note: Focus state isnt correctly emulated in storybook in some browsers. Please tab over them :D 
CleanShot 2023-07-02 at 20 22 24@2x

Design Spec 📐: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=309-41600&mode=dev

### CODE REVIEW

**Review by PeerRich — DISMISSED** [review]
good refactor. tested and looks fine!

**Comment by PeerRich** [comment]
some types failing interestingly
image

**Comment by sean-brydon** [comment]
> some types failing interestingly image

Investigating

**Review by PeerRich — APPROVED** [review]

**Review by pumfleet — APPROVED** [review]
Code looks good to me

**Review by pumfleet — COMMENTED** [review]
Should we be worried about the failing UI check?

**Pull request merged**
