### PR TITLE
[Perf] Potential response time improvement of booking page

### PR DESCRIPTION
**Pull request by hariombalhara**
Parallelizes 2 queries to speed up SSR of [user] page. I also feel that there is something else apart from what is there in the repo which is causing the slow response time
This might have a marginal improvement in response time.

Motivation - PSI Score for [user] page is still in yellow and the biggest reason is response time now.
- cal.com takes ~45ms
- cal.com/hariom takes ~700ms. Why?

## Type of change

- [x] Perf (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Just see booking page like cal.com/hariom is loading

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by alishaz-polymath — APPROVED** [review]
Looks good to me.

**Review by zomars — CHANGES_REQUESTED** [review]
Code looks good. But will block merge until I test properly tomorrow. 🙏

**Review by zomars — APPROVED** [review]
Took your idea of parallel promises and refactored so the data is retrieved in a single prisma query. Thank you for your contribution 🙏🏽

**Comment by hariombalhara** [comment]
@zomars Thanks for the change. But I was trying out to see how nested reads work and what I found out was that it actually fires two sequential PG queries(surprising for me) which was the case earlier and don't improve the performance.

I would soon be posting some stats to compare the results of the two approaches

**Comment by zomars** [comment]
This is actually pretty interesting @hariombalhara. Would you consider this a worthwhile suggestion for the prisma team?

**Comment by hariombalhara** [comment]
@zomars Yeah atleast the behavior should be well documented. 

Also, do you think parallelizing the 2 queries would have significant impact on response time. As, don't know the ping time from Next backend to PG, it's hard to guess if the change would be worth it.

**Comment by hariombalhara** [comment]
@zomars Yeah that might be adding significant time to response. This is actually bad for PSI score. 

Can you measure if that's the case and may be redirection can be made faster if yes?

**Comment by zomars** [comment]
Just a little bit:

image
image

**Comment by hariombalhara** [comment]
Oh I didn't think I can access the same page through app.cal.com as well. 
I see some improvement in response time on app.cal.com but it is still high. 

I would first create a PR to measure the time to fetch data on server and then target improvement in it

**Comment by hariombalhara** [comment]
@zomars Opened a PR https://github.com/calcom/cal.com/pull/2042 to first measure what scope is there for optimization in Data Fetching from PG
If there is a scope then this PR makes sense, otherwise, we can close it.

**Comment by zomars** [comment]
> @zomars Opened a PR #2042 to first measure what scope is there for optimization in Data Fetching from PG
> If there is a scope then this PR makes sense, otherwise, we can close it.

That's actually pretty smart. Checking it 🙏🏽

**Comment by hariombalhara** [comment]
@zomars Out of 700ms
~50ms for latency(cal.com/ has similar latency)
~130ms from data fetching(with the newly added header log)

~500ms is still there which is a bigger problem to solve.
Beyond that data fetching measurement, there is 
- `ssr.dehydrate` and `crypto.createHash("md5")....` in `getServerSideProps` but those can't take that much time.
- There might be some overhead of getting it served from Vercel next server 
- redirection isn't probably adding much to latency.

But I still can't see why the huge difference.

**Comment by hariombalhara** [comment]
Closing this. Will reopen once there is something useful to be merged,

**Pull request closed without merging**
