### PR TITLE
fix: filter booking in upcoming

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://linear.app/calcom/issue/CAL-752/booking-list-has-duplicate-events

Screenshot 2023-01-11 at 5 50 32 PM

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
nice

**Comment by Udit-takkar** [comment]
@PeerRich what does this wipe mu cal account button does ? It's failing some tests

**Comment by zomars** [comment]
> @PeerRich what does this wipe mu cal account button does ? It's failing some tests

It's an app made by @alannnc to cancel all your bookings for today. It might be breaking the test since it expects to have some upcoming bookings for today in order to work.

**Comment by PeerRich** [comment]
i dont think the app is that important, we can remove the tests

**Comment by zomars** [comment]
> i dont think the app is that important, we can remove the tests

Is the non-calendar most installed app tho. I'm against removing the test. Let's update it or fix it.

**Review by emrysal — DISMISSED** [review]
WipeMyCalendar test should be fixed prior to merge 👍

**Comment by Udit-takkar** [comment]
@emrysal fixed now

**Review by emrysal — APPROVED** [review]
LGTM 🚀

**Pull request merged**
