### PR TITLE
fix: update rejectOnNotFound -> find(Fist|Unique)OrThrow

### PR DESCRIPTION
**Pull request by agustif**
## Upgrade  `rejectOnNotFound` -> `orThrow` new methods

More info:
https://github.com/prisma/prisma/releases
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#findfirstorthrow

### CODE REVIEW

**Comment by agustif** [comment]
@zomars this removes some custom HttpErrors, thoughts?

**Comment by agustif** [comment]
https://github.com/prisma/prisma/issues/12159 I see you already did some digging here

**Review by zomars — COMMENTED** [review]
Thanks for doing this @agustif let's add a prisma not found error handler to `defaultResponder` as well 🙏🏽

**Comment by agustif** [comment]
> Thanks for doing this Agusti Fernandez Pardo let's add a prisma not found error handler to `defaultResponder` as well 🙏🏽
@zomars is this what you meant?
Added on getServerErrorFromUnknown.ts
```
  if (cause instanceof NotFoundError) {
    return new HttpError({ statusCode: 404, message: cause.message, cause });
  }
```

**Review by zomars — APPROVED** [review]
Computer Reaction GIF by GitHub

**Pull request merged**
