### PR TITLE
fix: text overflowing in username change popup

### PR DESCRIPTION
**Pull request by niks-nikhil-anand**
fixes: #13846
**Before** 
WhatsApp Image 2024-02-28 at 13 20 58_5fcb92c6
After
WhatsApp Image 2024-02-28 at 13 21 48_b743c8c3

### CODE REVIEW

**Comment by niks-nikhil-anand** [comment]
Even i only fix text overflowing by changing some tailwind property, why that check is failed .
can you guide me through it .

**Review by sean-brydon — APPROVED** [review]
LGTM - the github action failure was due to the title - i have fixed

**Comment by niks-nikhil-anand** [comment]
So what shoud i do next , actually it's my first PR. sorry for silly questions.
Should i wait for the merge or do i need to do someting to fix (What?)
guide me through the step

**Comment by niks-nikhil-anand** [comment]
Should i wait to merge ?
actually its my first PR , can u guid me the further process , what should i do the next .?

**Review by Udit-takkar — APPROVED** [review]

**Pull request merged**
