### PR TITLE
Fix login page CTA disabled state

### LINKED ISSUE #2793: Button disabled when the user put the wrong password
Found a bug? Please fill out the sections below. 👍

A summary of the issue. This needs to be a clear detailed-rich summary.

Button disabled when the user put the wrong password 
Loom video: https://www.loom.com/share/56536011a7ff41fcb6153bd67658ecce

### Steps to Reproduce

1. Go to Login page
2. Put your email with one wrong password
3. Look the button is disabled

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

When the user put one wrong password the button needs to be enabled

### PR DESCRIPTION
**Pull request by palerdot**
This PR fixes the bug where login CTA/button is disabled when wrong password is entered once.

## What does this PR do?

The fix involves tracking the form submission with a dedicated state `submitInProgress` with React.
`formState` from `react-hook-form` does not take time taken for the network call into account. For example, if the api takes 5 seconds to complete, we would expect the `formState.isSubmitting` to be true for `5` seconds. But, surprisingly this is not the case and `formState` from `react-hook-form` resolves immediately after it makes a successful connection to the endpoint. Also, the existing condition `form.formState.isSubmitted && !twoFactorRequired` is ambiguous and always disables the login CTA for non two factor login.

A dedicated state (with `useState`) is introduced that is enabled when the user clicks on the login CTA, and disabled when the api call is resolved, either successfully or with an error.

Fixes #2793 (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Click the submit button in the login page. The button should be disabled when the api call is in progress, and should be enabled back when the api call is resolved.

## Checklist

- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by palerdot** [comment]
Unrelated: I also noticed that `react-hook-form` recommends de referencing `formState` (as seen in screenshot)
Screenshot 2022-05-20 at 8 14 52 PM. 

I also poked around if this is the cause of the issue. But, de referencing as shown in the docs still does not fix the issue and `formState` does not take time taken for the network call into account. But this is something that may need future attention.

**Review by zomars — CHANGES_REQUESTED** [review]
I'm not a fan of adding new state to patch these kinds of errors. Generally speaking this means that our method isn't rejecting/resolving properly. I'd rather lookup the core problem and solve it there.

We could use something like `isSubmitSuccessful`, from the RHF docs:

> Indicate the form was successfully submitted without any Promise rejection or Errorbeen thrown within the handleSubmit callback.

Since we're catching the error to display an error message we could throw the error again so the form knows that there was an actual error and enables the button again.

**Comment by palerdot** [comment]
> We could use something like isSubmitSuccessful, from the RHF docs:

I tried this and it didn't work. I'm not that familiar with react hook form, and maybe I didn't look in the right place.

**Comment by palerdot** [comment]
> I'm not a fan of adding new state to patch these kinds of errors

Typically, we get a `loading` state from libraries/abstraction that deal with async calls - eg: `react-query`, `apollo-client` etc which is typically used for disabling button when a network request in progress. Maybe there is a better way to do this with RHF, but as far as I checked none of the state from RHF does not work as expected.

**Comment by emrysal** [comment]
We should indeed be using RHF formState, if this is not working there must be a reason it is not. 

In this case that reason is that the form submit handler is invalid; it's a sync function that then calls the signIn function (The signIn function is async) - at this point RHF no longer knows the form is submitting as the form submit handler has finished execution.

Knowing this; getting isSubmitting to work is a matter of adding `async` and `await` in the right places:

```javascript
handleSubmit={async (values) => {
  telemetry.withJitsu((jitsu) => jitsu.track(telemetryEventTypes.login, collectPageParameters()));
  await signIn<"credentials">("credentials", { ...values, callbackUrl, redirect: false })
   .then((res) => {
     if (!res) setErrorMessage(errorMessages[ErrorCode.InternalServerError]);
     // we're logged in! let's do a hard refresh to the desired url
     else if (!res.error) router.push(callbackUrl);
     // reveal two factor input if required
     else if (res.error === ErrorCode.SecondFactorRequired) setTwoFactorRequired(true);
     // fallback if error not found
     else setErrorMessage(errorMessages[res.error] || t("something_went_wrong"));
   })
   .catch(() => setErrorMessage(errorMessages[ErrorCode.InternalServerError]));
}}
 ```

**Comment by emrysal** [comment]
Hi @palerdot could you have a look at #2771 and tackle that issue too as part of this PR? I mentioned a few helpful PR's to provide insight but would like to keep things simple and have a single PR to fix the login.

**Review by zomars — APPROVED** [review]
Updated, tested and confirmed it works

**Pull request merged**
