### PR TITLE
Disabling direct emails from workflow

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

Due to abuse episode.

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

### CODE REVIEW

**Review by pumfleet — APPROVED** [review]
Thank you!

**Comment by zomars** [comment]
I'm afraid this won't compile into prod

**Comment by PeerRich** [comment]
shit i force merged this

**Comment by leog** [comment]
No worries @PeerRich I fixed the type checks on the PR to PROD if that's what was worrying @zomars

**Pull request merged**
