### PR TITLE
fix: add allowOverflow property

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes:- all dropdown bugs mentioned here  https://threads.com/34443655935?s=mADSwgHK128iEkEZE7JFFU

Follow up :- https://github.com/calcom/cal.com/pull/6587

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by emrysal — CHANGES_REQUESTED** [review]
I think we should look at finding a solution that doesn't require `enableOverflow` - also it seems to do the inverse of the naming.

Enable overflow:
image

Disable overflow:
image

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/214042112-47cd6017-1fce-41ba-b738-38530eafd483.mov

@emrysal should work now. although i agree we will have to remove enableOverflow. I tried fixing react-select using menuPortalTarget but the dropdown was not unscrollable and i wasn't able to select any option

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/214043057-62602df8-776d-425d-9173-d605667abacf.mov

**Comment by Jaibles** [comment]
@Udit-takkar one of our customers is experiencing this in their routing forms. I'm assuming this will also fix this issue?
CleanShot 2023-01-24 at 11 48 33@2x

**Comment by Udit-takkar** [comment]
@Jaibles can you tell which page is that ?

**Comment by PeerRich** [comment]
could this be the routing form embed @hariombalhara ?

**Comment by hariombalhara** [comment]
@PeerRich Yeah that's a routing form embed only.

**Review by emrysal — APPROVED** [review]

**Comment by emrysal** [comment]
Looking at the code the routing form embed should work after this PR @hariombalhara

**Comment by Jaibles** [comment]
@hariombalhara @emrysal has this made it to production yet? A customer is still experiencing this issue - specifically re: my comment above with the screenshot in the routing form.

**Comment by Udit-takkar** [comment]
@CarinaWolli fixed that . Idk if it has been deployed yet

**Pull request merged**
