### PR TITLE
chore: enable eslint rule react/no-danger

### PR DESCRIPTION
**Pull request by chribjel**
## What does this PR do?

Introduces a new eslint-plugin-react rule "react/no-danger" to prevent XXS vulnerable PRs to be merged in the future.

This gives a linter error whenever dangerouslySetInnerHtml is used, and the team have to activelly ignore it.

ref: https://github.com/calcom/cal.com/pull/17972

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

No testing needed. Just a new eslint rule.

### CODE REVIEW

**Review by Praashh — CHANGES_REQUESTED** [review]
Hey @chribjel can you add a loom of the fix as well?

**Comment by chribjel** [comment]
> Hey @chribjel can you add a loom of the fix as well?

Yes i can! What do you want the loom to focus on? What needs more explaination? @Praashh

**Review by emrysal — APPROVED** [review]
Happy to approve, it's a nice extra needed step that calls out attention.

**Review by Praashh — APPROVED** [review]
Hey @chribjel, there were some misunderstandings about this PR. There's no need to. Add Loom now 🙏 . Thank you for your contribution.

**Pull request merged**
