### PR TITLE
fix: react unecessary bundling to prevent version mismatches on nextj…

### LINKED ISSUE #16656: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

Call Stack
eval
node_modules\@calcom\embed-react\dist\Cal.es.mjs (227:1)
vr
node_modules\@calcom\embed-react\dist\Cal.es.mjs (658:4)
eval
node_modules\@calcom\embed-react\dist\Cal.es.mjs (660:57)
(app-pages-browser)/./node_modules/@calcom/embed-react/dist/Cal.es.mjs

### LINKED ISSUE #17563: embed issue with react 19
looks like there is some problem with the react code for pop via element click. (using next15 and react 18.2)  
Code is in the comments below

image

image

### PR DESCRIPTION
**Pull request by KlotzJesse**
…s15 and react19

## What does this PR do?

Remove unecessary bundling

- Fixes #17563
- Fixes #16656 
- Fixes CAL-4694

## Mandatory Tasks (DO NOT REMOVE)

- [X] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [X] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox. N/A
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. Create a nextjs 15 project with react19
2. Embed react with the code provided by the issue / from cal.com
3. build
4. start / deploy

/claim #17563

### CODE REVIEW

**Review by Praashh — COMMENTED** [review]
hey @KlotzJesse can you please add a screen recording of the fix ?

**Review by Praashh — COMMENTED** [review]
Screenshot 2024-11-21 at 4 48 35 PM

don't think, this fixs the issue.

**Comment by KlotzJesse** [comment]
> don't think, this fixs the issue.

hmm, to verify it again i did install a new nextjs 15 project

with
`bunx create-next-app@latest`

then did manually patch it by forking the package, rebuild after the change the embed-react package. replaced the dist folder in the node_modules of the fork with the installed package from npm in my new nextjs project (renamed old dist to dist_old) and it started working seamless. when i switch the dist's it doesnt work.

Did you verify that you used it in a new project e.g. with nextjs 15 using react 19 and made sure to use a self build version with this change?

Don't know if theres a better, faster, simpler way :D

**Comment by KlotzJesse** [comment]
No problem, but as NextJs 15 is called stable by the nextjs devs, just react 19 not, even though it is RC and the first issue is about using nextjs 15 by @PeerRich and the second issue is all about nextjs 15, and I think this fix is a improvement (because react doesn't need to be bundled in this dependency) and therefore makes no problem, I would love if you reconsider this and think about merging. @Praashh

**Comment by lekterable** [comment]
I'd also appreciate a fix for this, this is the only package that causes issues after upgrading to v15.

It's quite frustrating having to decide between using the latest version of most popular framework or an embed for calendar which you've used previously.

**Comment by Ravipandey24** [comment]
I recently upgraded a client project to Next.js 15, where Cal.com has been used to book meetings on signup. The client is persistent for Cal.com, and they may lose business if it won't be fixed ASAP. Is there any workaround, or will I have to roll back to the previous version, which will be very frustrating (I have tried embedding via plain script instead of the react-embed library but have had no success)?

**Comment by KlotzJesse** [comment]
@Praashh For me #17790 did also fix this, can you check again?

**Comment by mxkxf** [comment]
1.5.2 doesn't work - I think the `@calcom/embed-react` package.json peer dependencies have been updated but no new version of the package has been published since that commit.

Repro steps:

```
mkdir calcomtest
cd calcomtest
npm init -y
npm i @calcom/embed-react
cat node_modules/@calcom/embed-react/package.json
``

The `peerDependencies` are still for React 18 😢 :

```
  // ...
  "peerDependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  // ...
```

**Comment by KlotzJesse** [comment]
> 1.5.2 doesn't work - I think the `@calcom/embed-react` package.json peer dependencies [have been updated](https://github.com/calcom/cal.com/blob/main/packages/embeds/embed-react/package.json#L32-L34) but no new version of the package has been published since that commit.

1.5.2 should work, because there is no wrong react version anymore bundled. The problem wasn't about that the package had wrong peer dependencies, it was because a react18 jsx-runtime was being bundled unecessary that lead to the problem that __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED was referenced in the bundled package, even though the users had used react 19, which doesn't provide __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED anymore, because it was renamed.

Did you verify that 1.5.2 doesn't work on your end?

**Comment by KlotzJesse** [comment]
@mxkxf 
> 1.5.2 doesn't work - I think the `@calcom/embed-react` package.json peer dependencies [have been updated](https://github.com/calcom/cal.com/blob/main/packages/embeds/embed-react/package.json#L32-L34) but no new version of the package has been published since that commit.

1.5.2 should work, because there is no wrong react version anymore bundled. The problem wasn't about that the package had wrong peer dependencies, it was because a react18 jsx-runtime was being bundled unecessary that lead to the problem that __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED was referenced in the bundled package, even though the users had used react 19, which doesn't provide __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED anymore, because it was renamed.

Did you verify that 1.5.2 doesn't work on your end?

**Comment by mxkxf** [comment]
@KlotzJesse Not working on my end in a dependabot update, you could use `--force` but this will break in certain CI/CD platforms:

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: my-app@0.1.0
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"^19" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.2.0" from @calcom/embed-react@1.5.2
npm error node_modules/@calcom/embed-react
npm error   @calcom/embed-react@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

**Pull request closed without merging**
