### PR TITLE
a11y: Exit the lexical Editor and button a11y on tab index

### LINKED ISSUE #7740: [CAL-1256] No way to exit Editor when in dialog
[d017b396-0927-4d23-aa31-5efcabe2e0c0](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/e9cd7293-c869-4fa8-a304-487d0a9167d4/d017b396-0927-4d23-aa31-5efcabe2e0c0)

Pressing escape closes dialog and does not leave focus from the editor

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1256](https://linear.app/calcom/issue/CAL-1256/no-way-to-exit-editor-when-in-dialog)</sub>

### LINKED ISSUE #8800: Tab on Create Event richt text doesn't skip to next field
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Tab on Create Event richt text doesn't skip to next field. Instead it adds a tab to the richt text.

### Steps to Reproduce

1. Create an event
2. In the description, hit TAB

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

grafik

### PR DESCRIPTION
**Pull request by g4rry420**
## What does this PR do?
- Lexical Editor in v0.5.0 (by default) has `Tab-to-Indent` feature enabled. In this pr, I have disabled the `tab` key to work on lexical editor. However, if we update the lexical to v0.7.0, then by default, they have removed this feature. Ref:- https://github.com/facebook/lexical/issues/2854
- The `Continue` button in the new event dialog is accessed before the `Close` button, which seems counter intuitive as per a11y perceptive. Disclaimer: I am not expert in a11y, I might be wrong here

Fixes #7740
Fixes https://github.com/calcom/cal.com/issues/8800

Before:
https://www.loom.com/share/9486b608c5614246b849bc0cc7109d9b

After:
https://www.loom.com/share/b3f39287bfd24a50acdefb6859b1d918

**Environment**: Staging(main branch) / Production

## Type of change

- New feature (might be a breaking change which adds functionality, if current users use `tab` and `shift + tab`  for indent in the editor)

## How should this be tested?
Using the `tab`, focus on different inputs of new event dialog

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by CarinaWolli — DISMISSED** [review]
Thank you for doing the research about the lexical versions 🙏  I just tested v0.9.0 and like you said this would fix it as well. As we are already behind quite a few versions, I think we should update the version. The version update didn't break anything for me

**Comment by CarinaWolli** [comment]
@g4rry420 Can you fix the type error? Looks like we need the `ErrorBoundary` property in `RichtTextPlugin`
Screenshot 2023-04-11 at 18 41 42

**Review by CarinaWolli — COMMENTED** [review]
Looking good, can you please fix the merge conflicts for yarn.lock? Then we are good to go 🙏

**Comment by Udit-takkar** [comment]
@g4rry420 there are still some conflict in this PR. just tag me after you fix them

**Comment by g4rry420** [comment]
@Udit-takkar Hi, I have resolved the conflicts, please let me know if you see any issues :)

**Review by Udit-takkar — APPROVED** [review]
LGTM @g4rry420.

**Review by zomars — APPROVED** [review]
LGTM 

Fixed yarn lock file

Thank you for your contribution 🙏

**Comment by felipe-muner** [comment]
🚀

**Pull request merged**
