### PR TITLE
fix: resolved troubleshoot-sidbar bug

### LINKED ISSUE #17610: Troubleshoot Jerky Sidebar
Found a bug? Please fill out the sections below. 👍

### Issue Summary
On the loading and also when we scroll on troubleshoot page the sidebar shows some weird behaviour.

### Steps to Reproduce

1.Go to Troubleshoot page.
2. Scroll very slow on the Troubleshoot page.
3. Chrome version:  130.0.6723.117 and OS: Window.

### Actual Results

- It feels like rendering again and again when we scroll.

### Technical details

- Browser: Chrome, version:  130.0.6723.117 , OS: Window 11.

https://github.com/user-attachments/assets/2ffb8c3b-11ae-479b-890c-a38216cfb4ed

### PR DESCRIPTION
**Pull request by sachinsiddhu112**
## What does this PR do?
This PR is resolving the UI bug in Troubleshoot page. On Troubleshoot page, If we scroll ,the sidebar shows some weird behaviour. If we scroll very slow ,we can clearly see that ,when we scroll the sidebar move upward.

I replaced the StickyBox wrapper for TroublshooterSidebar component in  Troubleshooter.tsx component with simple div tag with some tailwind class properties.

- Fixes #17610 (GitHub issue number)

## Mandatory Tasks (DO NOT REMOVE)

- [x] Yes, I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] NA,I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

To test it, You can go to Troubleshoot page in Availability section and scroll up and down very slow or even fast, but the sidebar will remain stick.

## Checklist

https://github.com/user-attachments/assets/2588b764-1b93-4ac9-af94-e5b8d0d6dff8

- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by Praashh** [comment]
hey @sachinsiddhu112 , can you please sign CLA?

**Review by Praashh — CHANGES_REQUESTED** [review]
Let's simplify it by getting rid of the children div and removing the StickyBox import if we're not using it

``` 
         <div className="sticky top-0 z-10 ps-6">
              <TroubleshooterSidebar />
          </div>
  ```

**Comment by sachinsiddhu112** [comment]
Do I need to make the changes you mentioned?

**Comment by sachinsiddhu112** [comment]
I have signed the CLA.

**Comment by Praashh** [comment]
> Do I need to make the changes you mentioned?

yes, that would make it consistent and also readable

**Comment by Praashh** [comment]
> I have signed the CLA.

you probably put the wrong username while signing the CLA, use sachinsiddhu112 username

**Comment by sachinsiddhu112** [comment]
How can I resign the CLA?

**Comment by sachinsiddhu112** [comment]
I have signed CLA again, but when I signed, It is taking username by default from Github.

**Comment by sachinsiddhu112** [comment]
And I have made the requested changes and committed them.

**Comment by Praashh** [comment]
> It's my very first contribution. So don't know much about it. Is my changes merged or do I have to do something to do that.

don't worry, go though it https://cla-assistant.io/calcom/cal.com?pullRequest=17613

**Comment by sachinsiddhu112** [comment]
I have signed CTA. Now my username should be correct. It is showing me verified.
 What about my PR, it has not merged because some checks had failed. 
What I have to do?

**Comment by sachinsiddhu112** [comment]
Can I start working on next issue?

**Comment by Praashh** [comment]
> I have signed CTA. Now my username should be correct. It is showing me verified. What about my PR, it has not merged because some checks had failed. What I have to do?

please, make the change that I suggested

**Comment by sachinsiddhu112** [comment]
Is there something wrong in this PR Or the merging process going on? I am asking because , it is not getting merged.

**Comment by Ryukemeister** [comment]
> Is there something wrong in this PR Or the merging process going on? I am asking because , it is not getting merged.

Hey Sachin, thanks a lot for you contribution! The PR is currently under review which means @Praashh will go through your code and make sure the code quality and logic are correct, once that is correct he'll approve it and then we'll make sure all checks are passing. Once its approved and all checks are passing, we'll make sure to merge it.

**Review by Praashh — COMMENTED** [review]
@sachinsiddhu112  please sign CLA, changes LGTM.

**Review by Praashh — APPROVED** [review]

**Comment by sachinsiddhu112** [comment]
I already  signed the CLA. Is it updated.

**Comment by Praashh** [comment]
> changes LGTM ?

looks good to me. don't worry I approved your PR, we'll merge it soon.

**Comment by sachinsiddhu112** [comment]
Thanks.

**Pull request merged**
