### PR TITLE
fix: changes "cancelled" to canceled

### LINKED ISSUE #9502: [CAL-1942] Update "Cancelled" to "Canceled" anywhere within the app
I recently canceled an event, and the British style of "cancelled" appeared. We should adjust to American, "Canceled." One "l" 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1942](https://linear.app/calcom/issue/CAL-1942/update-cancelled-to-canceled-anywhere-within-the-app)</sub>

### PR DESCRIPTION
**Pull request by Vivek7038**
## What does this PR do?

Fixes #9502
 
I changed the cancelled to canceled when it says This event is cancelled in common.json file at line 1043

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by CarinaWolli** [comment]
There are a lot more 'cancelled' in that file. Could you fix them too?

**Comment by Vivek7038** [comment]
> 



> There are a lot more 'cancelled' in that file. Could you fix them too?

yes i can

**Comment by Vivek7038** [comment]
i have sent a pull request to close this issue .If there need any changes feel free to share me .

**Review by keithwillcode — APPROVED** [review]
Nice! Thanks for your contribution. 🙏

**Comment by Vivek7038** [comment]
> Nice! Thanks for your contribution. 🙏

Would love work on more issues in ui like this.

**Pull request merged**
