### PR TITLE
fixed search icon and tablet menu

### LINKED ISSUE #4095: Sidebar: Sizing, spacing fixes, multiple
[View in Figma ](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17937%3A171148)

Image

### LINKED ISSUE #4132: tablet: icon not centered, too big and not squared
CleanShot 2022-09-02 at 21 42 42@2x

### PR DESCRIPTION
**Pull request by PeerRich**
before
CleanShot 2022-09-03 at 14 08 19

after
CleanShot 2022-09-03 at 14 06 44

- tooltip is being fixed in another PR

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]
LGTM nice :)

**Comment by PeerRich** [comment]
@zomars Meta Workflow is failing :(

**Review by pumfleet — APPROVED** [review]
Code looks good to me

**Comment by baileypumfleet** [comment]
Let's run this through the linter and try again

**Comment by PeerRich** [comment]
CleanShot 2022-09-05 at 11 47 09@2x

**Pull request merged**
