### PR TITLE
Images in slider will have fixed height, variable width

### LINKED ISSUE #2875: new app store slider
right now, the screenshots in the slider are currently distorted to a fixed width, however they should take a fixed height and then relative width based on their dimensions.

example:

image

I would much rather have a slider like product hunt https://www.producthunt.com/posts/lazy-search-by-sigmaos: 

image

### PR DESCRIPTION
**Pull request by aar2dee2**
## What does this PR do?

Edits image layout in slider on App page to have fixed height and variable width. Previously images had fixed height and fixed width.

Fixes #2875 

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

Loom: https://www.loom.com/share/2fce1c4844c54baaa874638cc0c2db6e

### CODE REVIEW

**Comment by hariombalhara** [comment]
@aar2dee2 Some linter checks are failing.

**Comment by aar2dee2** [comment]
> @aar2dee2 Some linter checks are failing.

@hariombalhara fixed now!

**Comment by PeerRich** [comment]
> https://www.loom.com/share/2fce1c4844c54baaa874638cc0c2db6e 

that loom video shows that the problem has not been fixed, has it? the images still have the wrong dimension

**Comment by aar2dee2** [comment]
> > https://www.loom.com/share/2fce1c4844c54baaa874638cc0c2db6e
> 
> that loom video shows that the problem has not been fixed, has it? the images still have the wrong dimension

Updated: https://www.loom.com/share/54cc135df5ad4c97b43223e338b21495

**Comment by PeerRich** [comment]
thank you @aar2dee2 🙏

**Pull request merged**
