### PR TITLE
fix: duplicate username when inviting to team

### LINKED ISSUE #13464: [CAL-3055] 500 when inviting a team member and there's a conflict in the generated username
The bug comes from here:

[https://github.com/calcom/cal.com/blob/d6927c504927223c2ac1e8b2a3a241d36038457e/packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts#L235-L258](https://github.com/calcom/cal.com/blob/d6927c504927223c2ac1e8b2a3a241d36038457e/packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts#L235-L258)

This is causing a weird edge case where there might be the possibility that the generated user may exist already. causing a prisma error. Example: we have `robert@example.com` being converted to `robert-example` username. Which already exists in prod. On production this only returns a 500 error:

On dev we get this:

```
Object { message: "Invalid `prisma.user.create()` invocation: Unique constraint failed on the fields: (`username,`)", code: -32603, data: {…} }
```

Originally posted by @zomars in [https://github.com/calcom/cal.com/pull/11238#discussion_r1470584485](https://github.com/calcom/cal.com/pull/11238#discussion_r1470584485)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3055](https://linear.app/calcom/issue/CAL-3055/500-when-inviting-a-team-member-and-theres-a-conflict-in-the-generated)</sub>

### PR DESCRIPTION
**Pull request by AnthonyJHizon**
## What does this PR do?

Fixes 500 case when duplicate username when inviting to team

Approach: Uses '@' instead of '-' to separate name and domain name for non auto accepted email domains.

Bug was caused by cases: 
Email 1, Email 2
adam-gmail@autoAcceptedEmailDomain.com,  adam@gmail.com
Generated usernames: adam-gmail, adam-gmail

Email 1, Email 2
joe-flowers@autoAcceptedEmailDomain.com,  joe@flowers.com
Generated usernames: joe-flowers, joe-flowers

Since '-' is a valid character in an email address.
Consider using '@' as a delimiter when identifying non auto accepted email domains.

Limited fix to only when inserting to database. 
Might cause mismatch when comparing _username queried from database_ and slugify(username)

Fixes #13464 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by sean-brydon** [comment]
> ## What does this PR do?
> Fixes 500 case when duplicate username when inviting to team
> 
> Approach: Uses '@' instead of '-' to separate name and domain name for non auto accepted email domains.
> 
> Bug was caused by cases: Email 1, Email 2 [adam-gmail@autoAcceptedEmailDomain.com](mailto:adam-gmail@autoAcceptedEmailDomain.com), [adam@gmail.com](mailto:adam@gmail.com) Generated usernames: adam-gmail, adam-gmail
> 
> Email 1, Email 2 [joe-flowers@autoAcceptedEmailDomain.com](mailto:joe-flowers@autoAcceptedEmailDomain.com), [joe@flowers.com](mailto:joe@flowers.com) Generated usernames: joe-flowers, joe-flowers
> 
> Since '-' is a valid character in an email address. Consider using '@' as a delimiter when identifying non auto accepted email domains.
> 
> Limited fix to only when inserting to database. Might cause mismatch when comparing _username queried from database_ and slugify(username)
> 
> Fixes #13464
> 
> ## Type of change
> * Bug fix (non-breaking change which fixes an issue)

I dont have much context on this issue but i dont think `@` is a good choice of delimiter to use here. 

We rely on our usernames for booking pages ->  cal.com/sean-brydon

We can't have cal.com/sean@brydon as `@` isnt IIRC a valid middle path segment of a URL.  To make this valid we'd need to encode it as `%40` which is a rabbit hole i dont think we should go down. 

CC: @zomars

**Review by sean-brydon — CHANGES_REQUESTED** [review]
As per comment

**Comment by AnthonyJHizon** [comment]
> As per comment

**Comment by AnthonyJHizon** [comment]
> > ## What does this PR do?
> > Fixes 500 case when duplicate username when inviting to team
> > Approach: Uses '@' instead of '-' to separate name and domain name for non auto accepted email domains.
> > Bug was caused by cases: Email 1, Email 2 [adam-gmail@autoAcceptedEmailDomain.com](mailto:adam-gmail@autoAcceptedEmailDomain.com), [adam@gmail.com](mailto:adam@gmail.com) Generated usernames: adam-gmail, adam-gmail
> > Email 1, Email 2 [joe-flowers@autoAcceptedEmailDomain.com](mailto:joe-flowers@autoAcceptedEmailDomain.com), [joe@flowers.com](mailto:joe@flowers.com) Generated usernames: joe-flowers, joe-flowers
> > Since '-' is a valid character in an email address. Consider using '@' as a delimiter when identifying non auto accepted email domains.
> > Limited fix to only when inserting to database. Might cause mismatch when comparing _username queried from database_ and slugify(username)
> > Fixes #13464
> > ## Type of change
> > 
> > * Bug fix (non-breaking change which fixes an issue)
> 
> RFC 3986 - https://datatracker.ietf.org/doc/html/rfc3986#section-2.2
> 
> I dont have much context on this issue but i dont think `@` is a good choice of delimiter to use here.
> 
> We rely on our usernames for booking pages -> cal.com/sean-brydon
> 
> We can't have cal.com/sean@brydon as `@` isnt IIRC a valid middle path segment of a URL. To make this valid we'd need to encode it as `%40` which is a rabbit hole i dont think we should go down.
> 
> I would probably recommend following one of the delimiters mentioned in the RFC above
> 
> `unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"`
> 
> CC: @zomars

I was not aware the usernames were used to generate page links for bookings.
All unreserved characters are valid in an email address so there's a chance this bug will reoccur if we use them as delimiters. 
What do you think about an approach where all usernames are generated by the same logic and we introduce a value to the Membership Table to identify auto accepted email domains? With this approach we might also have to consider creating an indicator for auto accepted members in the frontend as well.

**Review by zomars — CHANGES_REQUESTED** [review]
I'm going to agree with @sean-brydon  here. We don't want @ in URLs in here.

**Comment by zomars** [comment]
Closing for now. Feel free to re-open. 🙏🏽

**Pull request closed without merging**
