### PR TITLE
fix: padding in event-types advanced tab

### LINKED ISSUE #11797: [CAL-2605] chore: fix padding in event-types
CleanShot 2023-10-10 at 16 48 39@2x

<sub>[CAL-2605](https://linear.app/calcom/issue/CAL-2605/chore-fix-padding-in-event-types)</sub>

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Fix padding in event-types advanced tab

Fixes #11797

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
can you address the merge conflict and provide screenshots?

**Review by Udit-takkar — COMMENTED** [review]
@devuser200 I think i fixed this issue in my PR https://github.com/calcom/cal.com/pull/11615.

This is how it looks like in my PR

image

**Comment by devuser200** [comment]
@PeerRich  the issue has been solved and merged. (fix: improper border in event-types #11800)

**Comment by devuser200** [comment]
what should I do

**Comment by devuser200** [comment]
@PeerRich the issue has been solved and merged. (fix: improper border in event-types #11800)

**Pull request closed without merging**
