### PR TITLE
test: Refactor of handleNewBooking along with some unit tests. /claim #9284 

### PR DESCRIPTION
**Pull request by Veercodeprog**
## What does this PR do?

Moves the `handleNewBooking` function outside of the `handler` function and introduces a wrapper function for it. This PR aims to improve code organization and maintainability.

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@Veercodeprog only push yarn.lock when you make any change in package.json file.  Please remove yarn.lock from this PR. I think this was the command `git checkout origin/main yarn.lock `

**Comment by Veercodeprog** [comment]
> @Veercodeprog only push yarn.lock when you make any change in package.json file. Please remove yarn.lock from this PR. I think this was the command `git checkout origin/main yarn.lock `

i am getting this Please make sure your database server is running at `localhost`:`5450`.
do i have to update db link in order to contribute

**Comment by Udit-takkar** [comment]
@Veercodeprog are you running docker like mentioned in the instructions?

**Comment by Veercodeprog** [comment]
> @Veercodeprog are you running docker like mentioned in the instructions?

yes, i setup the project using yarn dx

**Comment by hariombalhara** [comment]
I don't think this PR fixes the said ticket. It just wraps a function in other function and that doesn't improve the maintainaibiity.

So, I am closing this ticket. Thanks @Veercodeprog for the PR.

**Pull request closed without merging**
