### PR TITLE
fix: #16126 for autofill in phoneinput

### LINKED ISSUE #16126: [CAL-5085] Phone Number Field / Location Not Working Due To Poor UX Around Country Code (bug)
### Issue Summary

Cal.com seems to put the responsibility of inputting the country code and/or the country on the user when inputting phone number as a field and/or location.

This is a very poor user experience as very few people enter their country code when inputting their phone number. Cal.com should have a default country code option in settings or something so that country and country code are prefilled for users when they come to a page. 

As it stands, cal.com is pretty much unusable as this user experience is so poor.

### Steps to Reproduce

1. Went to one of our calendars
2. Started entering phone number in phone number field without country code

### Expected behavior

There should be an option for country and country code to default and prefill to a certain country. It should not be the responsibility of the user to select their country and country code. 

### Other information

_No response_

### Screenshots

https://github.com/user-attachments/assets/07abf342-5e33-410f-9d2b-a4792348b237

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

<sub>[CAL-5085](https://linear.app/calcom/issue/CAL-5085/phone-number-field-location-not-working-due-to-poor-ux-around-country)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #16126 
- Fixes CAL-

Works well with both Autofill (with or without country code ) and manual entry scenarios.
Default Country is enabled.
Also country detection in case of manual entry also works. 

https://www.loom.com/share/da3298f29c4744078a84811ee3151ed0?sid=8a85337f-d00b-4b41-84c3-c62a767331e3

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by anikdhabal** [comment]
You create the similar pr again. As we told you before, currently we don't want the autofill feature here . Also we are discussing internally what to do here. Closing it until we finalize things

**Comment by hunterwilhelm** [comment]
@anikdhabal I hope we get to hear about the verdict soon. This issue is impacting our business as we speak.

**Comment by vijayraghav-io** [comment]
> You create the similar pr again. As we told you before, currently we don't want the autofill feature here . Also we are discussing internally what to do here. Closing it until we finalize things

This is with different approach, with default country enabled, we can handle these scenarios easily compared to earlier PR (where autodetection and default country were disabled).

**Comment by chasekeating** [comment]
> You create the similar pr again. As we told you before, currently we don't want the autofill feature here . Also we are discussing internally what to do here. Closing it until we finalize things

Any updates on this? I also agree that this is a usability issue as noted in https://github.com/calcom/cal.com/issues/15931 and https://github.com/calcom/cal.com/issues/16126

I have suggested this solution: https://github.com/calcom/cal.com/issues/16126#issuecomment-2608206095

**Pull request closed without merging**
