### PR TITLE
fix:  Validation error of Australian phone numbers beginning +61493 or +610493

### LINKED ISSUE #12394: Invalid Australian phone numbers beginning +61493 or +610493
### Issue Summary
- Phone validation issues with phone numbers in Australia starting with +61493 or +610493.    
  - A few work, most common as well with an 8 after the 3 as well. ie +61493800000
- these are valid phone numbers in Australia and prevents bookings

### Steps to Reproduce
Enter Australian phone number.  for example +61493812345

### Actual Results
- phone number is labelled as invalid, so cannot complete booking.

### Expected Results
- phone number should be seen as valid, and booking should be able to be completed

### Technical details
- calcom version 3.4.7

### Evidence
Screenshot 2023-11-17 at 11 42 26 am
Screenshot 2023-11-17 at 11 42 43 am

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #12394 
/claim #12394

Screenshot 2023-11-17 200357

### CODE REVIEW

**Comment by anikdhabal** [comment]
cc @Udit-takkar @CarinaWolli

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
@anikdhabal Nice attempt but this is not a good solution. we can't be add edge cases like this

**Comment by anikdhabal** [comment]
> @anikdhabal Nice attempt but this is not a good solution. we can't be add edge cases like this

So, how do we handle this? Any suggestions?

**Comment by Udit-takkar** [comment]
@anikdhabal i think this PR https://github.com/calcom/cal.com/pull/12519 is better

**Comment by hariombalhara** [comment]
Closing in favour of https://github.com/calcom/cal.com/pull/12519/files#diff-3daf7d552a4760d8b2dd5a1cd9d05fcba67b014e5ace23e28428f375f69b2a9a

**Pull request closed without merging**
