### PR TITLE
Add 23:59 as a valid availability select option

### LINKED ISSUE #5929: [CAL-563] Slots around midnight time
How to reproduce ? 

User wants to set availability to 8PM to 3AM . Monday to Saturday. 

Cal availability:- 

8PM to 11:45PM

12:00 AM to 3:AM

as 11:00 to 11:45 is less than hour the booker does not see 11 pm as a slot but the user wants to set complete 8PM to 3AM ( 7 hours).

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-563](https://linear.app/calcom/issue/CAL-563/slots-around-midnight-time)</sub>

### LINKED ISSUE #6054: Multi-day availability hours and event bookings.
### Is your proposal related to a problem?

- When using Availability hours, the last available time in the 'end time selector' is 23:45.
- This means that it isn't possible for events to be booked than run past 23:45.
- I would like to be able to have events booked across midnight.
- Availability hours are currently set per each single day, via specific time slot periods, each with start and end times, in "time periods" that can only start after the previously set "time period" has finished. This is quite annoying, because it isn't a great representation of "free time".

image

### Describe the solution you'd like

Events should be able to be booked across midnight.
I think allowing the Availability Hours to be set a different way would help fix this problem.
Perhaps by showing the whole week graphically, allowing people to "colour in" their free time AND having an option that says "allow multi-day events" or "allow events to cross midnight"

### Describe alternatives you've considered

I've tried using the "Add new time slot" button to counteract this problem, but it still won't allow events to be booked across midnight.

### Additional context

n/a

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

Fixes #5929

UTC-1
image

image

### CODE REVIEW

**Review by joeauyeung — APPROVED** [review]
LGTM

**Comment by ahmedsadman** [comment]
@emrysal Thanks for looking into this. Although, it didn't solve my problem fully. Please look into this unattended issue I reported quite some time ago: https://github.com/calcom/cal.com/issues/5587 for more context.
I just made my availablity upto 11:59PM. Given that my meeting duration is 60 minutes and the event increment is 30 mins, I should get a booking option at 11:30PM (so it would expand 11:30PM - 12:30AM), but the application only shows upto 11:00PM that day. This should be handled because people live in different timezones and might like to set a meeting at late nights.

**Comment by PeerRich** [comment]
> @emrysal Thanks for looking into this. Although, it didn't solve my problem fully. Please look into this unattended issue I reported quite some time ago: #5587 for more context. I just made my availablity upto 11:59PM. Given that my meeting duration is 60 minutes and the event increment is 30 mins, I should get a booking option at 11:30PM (so it would expand 11:30PM - 12:30AM), but the application only shows upto 11:00PM that day. This should be handled because people live in different timezones and might like to set a meeting at late nights.

can you open a new ticket?

**Comment by ahmedsadman** [comment]
> > @emrysal Thanks for looking into this. Although, it didn't solve my problem fully. Please look into this unattended issue I reported quite some time ago: #5587 for more context. I just made my availablity upto 11:59PM. Given that my meeting duration is 60 minutes and the event increment is 30 mins, I should get a booking option at 11:30PM (so it would expand 11:30PM - 12:30AM), but the application only shows upto 11:00PM that day. This should be handled because people live in different timezones and might like to set a meeting at late nights.
> 
> can you open a new ticket?

Opened a new ticket with details: https://github.com/calcom/cal.com/issues/6323 @PeerRich

**Pull request merged**
