### PR TITLE
feat: autosave availability after making changes

### LINKED ISSUE #14591: [CAL-3450] autosave availability after making changes
image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3450](https://linear.app/calcom/issue/CAL-3450/autosave-availability-after-making-changes)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #14591 

https://github.com/calcom/cal.com/assets/81948346/74cc516d-124c-4ab2-a1cd-1f3da62d95e1

### CODE REVIEW

**Review by supalarry — CHANGES_REQUESTED** [review]
## To fix
When day e.g. "Friday" is toggled 2 confirmation messages appear instead of 1.
Loom: https://www.loom.com/share/627cca63e7f44adcb3e32d63eacdbb2c

Screenshot 2024-05-03 at 11 05 23

## UX thoughts
1. Should we remove the "Save" button? It has no purpose if the form is autosaved.
2. I would also simplify confirmation messages when something is saved e.g. instead of changing timezone and seeing toast "✔ Working Hours schedule updated successfully" just display "✔ Saved" - the confirmation toast messages are too long IMO.

@itsberkaya @ciaranha thoughts?

**Comment by anikdhabal** [comment]
> ## To fix
> When day e.g. "Friday" is toggled 2 confirmation messages appear instead of 1. Loom: https://www.loom.com/share/627cca63e7f44adcb3e32d63eacdbb2c
> 
> Screenshot 2024-05-03 at 11 05 23
> ## UX thoughts
> 1. Should we remove the "Save" button? It has no purpose if the form is autosaved.
> 2. I would also simplify confirmation messages when something is saved e.g. instead of changing timezone and seeing toast "✔ Working Hours schedule updated successfully" just display "✔ Saved" - the confirmation toast messages are too long IMO.
> 
> @itsberkaya @ciaranha thoughts?

Thanks for the review, I will fix that.

**Comment by anikdhabal** [comment]
I think we should keep the save button because it's not optimal to save every time we change the title.

**Review by supalarry — DISMISSED** [review]
Tested locally works! Great work! : )

**Comment by keithwillcode** [comment]
@PeerRich or @ciaranha Can you approve this before we merge?

**Review by PeerRich — APPROVED** [review]

**Review by PeerRich — APPROVED** [review]

**Comment by shirazdole** [comment]
nice @anikdhabal — this will help our users a lot 🙏🏽

**Comment by anikdhabal** [comment]
> nice @anikdhabal — this will help our users a lot 🙏🏽

🙏🏽🙏🏽

**Comment by roeku** [comment]
> I think we should keep the save button because it's not optimal to save every time we change the title.

Regarding the save button, would it not make sense to disable it if no changes have occured? 
Right now you can just keep pressing the save button and notifications will keep stacking up.

**Pull request merged**
