### PR TITLE
feat: refactor filters on insights response table

### PR DESCRIPTION
**Pull request by eunjae-lee**
## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-4811 (Linear issue number - should be visible at the bottom of the GitHub issue description)

https://github.com/user-attachments/assets/63a41861-ed3a-481e-a4fa-fe19654e6c7c

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A - I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

## Explanation

(Had to split due to the file size limit)

Part 1.

https://github.com/user-attachments/assets/ec951226-9583-488a-93cc-fb11d2689f7b

Part 2.

https://github.com/user-attachments/assets/60ad063b-d578-4599-af2c-dccec78d4766

### CODE REVIEW

**Comment by eunjae-lee** [comment]
progress: @sean-brydon 

https://github.com/user-attachments/assets/0c2d776f-143a-49dd-be01-3af688cb6ea9

**Review by Udit-takkar — COMMENTED** [review]
@eunjae-lee There are a lot of unrelated changes in yarn.lock file. I don't think we should update all the dependencies in this PR

**Comment by eunjae-lee** [comment]
> @eunjae-lee There are a lot of unrelated changes in yarn.lock file. I don't think we should update all the dependencies in this PR

Hey @Udit-takkar, I made a change to `packages/prisma/package.json` but yes, I think my yarn.lock change might be wrong, because it's always changed even if I didn't touch package.json. Will it be solved if I configure submodules on my mac?

**Review by sean-brydon — CHANGES_REQUESTED** [review]
Nice work! Still got some changes that i think are blocking before merging as we need to make this perfect i think. 

loom: https://www.loom.com/share/df966a20c2d7453dbf475b6ce78495f0

But TLDR: 
* I can't seem to get contains/is/etc or any text filters to actually work
* We've lost the "clear filters" button 
* People shows as a default even when i havent selected the filter
* The "Add Filter" button seems to be on the wrong side of "All" Feels a bit weird when they appear on the right of the "all" button

Gimme a shout if you have any questions or would like to pair on getting these resolved

**Comment by eunjae-lee** [comment]
@sean-brydon As we discussed separately,

1. Fixed the text filter
2. Added "Clear filters" button back (but I re-created to clear both filters from FilterContext and DataTable filters state)

Note for others:
It's not ideal to have all the filters from FilterContext scattered on the header area, but it takes a lot of time to migrate the filters from FilterContext to DataTable's filters state (query params `activeFilters=...`), so we keep the both system for now.

**Review by sean-brydon — APPROVED** [review]
LGTM - im happy with this. We need to come back to the UI side tho. I know we have cal V3 designs that we should match for this even if we havent updated or DS just yet 

cc: @ciaranha

**Pull request merged**
