### PR TITLE
chore: bump trpc

### PR DESCRIPTION
**Pull request by KATT**
## What does this PR do?

Bumps tRPC

## Requirement/Documentation

- Where transformers are defined have moved (https://trpc.io/docs/migrate-from-v10-to-v11#transformers-are-moved-to-links-breaking)
- Someone might have to do `git checkout origin/main yarn.lock && yarn`, yarn diff looks big for some reason
 
## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

🤷 

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by PeerRich — DISMISSED** [review]

**Comment by keithwillcode** [comment]
@KATT thanks for the PR! Going to put in draft just while we inspect the yarn.lock file to make sure it’s good to merge.

**Comment by KATT** [comment]
> @KATT thanks for the PR! Going to put in draft just while we inspect the yarn.lock file to make sure it’s good to merge.

cc @keithwillcode if you have https://cli.github.com/

```shell
gh pr checkout 13515
git checkout origin/main yarn.lock
yarn 
git commit -m "fix lockfile" --no-verify
```

**Review by keithwillcode — DISMISSED** [review]

**Review by emrysal — DISMISSED** [review]
Nice 👍

**Review by zomars — DISMISSED** [review]

**Comment by keithwillcode** [comment]
Moving back to draft while we fix build errors

**Comment by keithwillcode** [comment]
Closing for now because these changes cause build errors. Will reopen when ready to upgrade.

**Pull request closed without merging**
