### PR TITLE
fix: Fixed Video Call UI Bug 

### LINKED ISSUE #16450: Video Call UI Bug
### Issue Summary

I was in a meeting today in the cal video meet. I noticed a minor 

### Steps to Reproduce

1. Join any video Call Meeting 
2. The Sheet Doesn't Close Properly and Blocks the Video on/off Switch Button

### Expected behavior

It should not cover the said button.

### Other information

_No response_

### Screenshots

image

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Windoms
- Node: v20.11.1
- npm: 10.2.1
```

### PR DESCRIPTION
**Pull request by dfordp**
## What does this PR do?

- Fixes #16450

## Mandatory Tasks (DO NOT REMOVE)

- [X ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [X ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [X ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

 
- Are there environment variables that should be set? No
- What are the minimal test data to have? No
- What is expected (happy path) to have (input and output)? No
- Any other important info that could help to test that PR Just Looking at the UI bug in produtctions

### CODE REVIEW

**Review by anikdhabal — DISMISSED** [review]

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
The arrow isn't visible
Screenshot 2024-09-02 at 5 24 42 PM

**Comment by Udit-takkar** [comment]
How do i reproduce the bug ? Could you share more details

**Comment by dfordp** [comment]
> The arrow isn't visible
> Screenshot 2024-09-02 at 5 24 42 PM
> 

I thought I may have miscalculated the value and I would have changed the value by now change it from 248 to 240 or 242

**Comment by dfordp** [comment]
@Udit-takkar can you check now?

**Comment by dfordp** [comment]
@Udit-takkar just join any call on cal.com meet/call interface in the current code

The bug exists there

**Comment by Amit91848** [comment]
Closing this because the issue cannot be reproduced https://github.com/calcom/cal.com/issues/16450#issuecomment-2356221218

**Pull request closed without merging**
