### PR TITLE
perf: enable prisma optimize #15795

### LINKED ISSUE #15795: perf: enable prisma optimize
### Is your proposal related to a problem?

(Write your answer here.)
We can enable prisma to enhance an existing application or explore its capabilities through a demo.

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

### Requirement/Document
It can be easily enabled with referring this [https://www.prisma.io/blog/prisma-optimize-early-access](https://www.prisma.io/blog/prisma-optimize-early-access)

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

### PR DESCRIPTION
**Pull request by harshsbhat**
## What does this PR do?

- Fixes #15795

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Review by PeerRich — COMMENTED** [review]
can you uncommit your removed yarn.lock? https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md#guidelines-for-committing-yarn-lockfile

**Review by keithwillcode — CHANGES_REQUESTED** [review]
This only wires up .$extends(withOptimize()); inside of the seed script. We'd need to also wire it up in https://github.com/calcom/cal.com/blob/main/packages/prisma/index.ts.

Also, is there any way we could put this behind an env var? I'd like to have the flexibility to only toggle it on when we want.

**Comment by harshsbhat** [comment]
> This only wires up .$extends(withOptimize()); inside of the seed script. We'd need to also wire it up in https://github.com/calcom/cal.com/blob/main/packages/prisma/index.ts.
> 
> Also, is there any way we could put this behind an env var? I'd like to have the flexibility to only toggle it on when we want.

Got it we will do it

**Comment by harshbhat04** [comment]
> This only wires up .$extends(withOptimize()); inside of the seed script. We'd need to also wire it up in https://github.com/calcom/cal.com/blob/main/packages/prisma/index.ts.
> 
> Also, is there any way we could put this behind an env var? I'd like to have the flexibility to only toggle it on when we want.

Sure I will work on this

**Comment by harshsbhat** [comment]
hey @keithwillcode and @PeerRich  I have created a new PR as this was not allowing me to reopen this PR. 

check it out: #16412

**Pull request closed without merging**
