### PR TITLE
refactor: No name typo fix

### PR DESCRIPTION
**Pull request by prateekjain98**
## What does this PR do?

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by keithwillcode** [comment]
@prateekjain98 can you please update the bullet points in the PR description

**Comment by prateekjain98** [comment]
> @prateekjain98 can you please update the bullet points in the PR description

Done

**Review by Udit-takkar — COMMENTED** [review]
@prateekjain98 i don't see any change in the value. what typo did you fixed ?

**Comment by prateekjain98** [comment]
> @prateekjain98 i don't see any change in the value. what typo did you fixed ?

Space was missing in the field causing eslint to auto format the file again and again and adding it to changes while making prs on our fork, so I created a pr for it.

**Review by Udit-takkar — APPROVED** [review]

**Review by hariombalhara — APPROVED** [review]

**Pull request merged**
