### PR TITLE
fix: setting sidebar improvements

### LINKED ISSUE #4643: [CAL-123] /settings sidebar doesn't match figma designs
There are some subtleties to spacing in the settings sidebar that make it easier to scan, particularly the sectioning of different settings areas that are not reflected from the Figma designs.

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17937%3A171647)

CleanShot 2022-09-20 at 22 06 16@2x

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/4643

Screenshot 2022-12-23 at 7 28 31 PM

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
@Jaibles is the hover of "back" supposed to be this small?

CleanShot 2022-12-26 at 10 52 57

**Comment by Udit-takkar** [comment]
yeah should be about 24px https://github.com/calcom/cal.com/issues/4643#issue-1379991748

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
tested and made a small improvement

**Comment by PeerRich** [comment]
great work

**Pull request merged**
