### PR TITLE
upgrade to next.js 12

### PR DESCRIPTION
**Pull request by KATT**
- upgrade next.js and remove babel-stuff as it's been replaced
- "react-timezone-select" is with swr failing so maybe it needs replacing

### CODE REVIEW

**Review by mihaic195 — APPROVED** [review]

**Review by mihaic195 — APPROVED** [review]

**Review by pumfleet — APPROVED** [review]

**Comment by PeerRich** [comment]
> "react-timezone-select" is with swr failing so maybe it needs replacing

fixed @KATT ß

**Comment by KATT** [comment]
> > "react-timezone-select" is with swr failing so maybe it needs replacing
> 
> fixed @KATT?

Doesn't seem like it yet - think @mihaic195 updated locally and didn't push upstream, I'll have a look tomorrow and try to get it across. Really want that swc compile speed in 🔥

**Comment by mihaic195** [comment]
@baileypumfleet @KATT for some reason the login test is failing here, but that is not happening locally. Need to investigate further.

**Comment by KATT** [comment]
> @baileypumfleet @KATT for some reason the login test is failing here, but that is not happening locally. Need to investigate further.

I'll have a look today!

**Pull request closed without merging**
