### PR TITLE
feat: disable update button unless any input value changed in general settings

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

after:
https://www.loom.com/share/d327cb0c7f2c41e580ae7e8b82298207

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
@Udit-takkar can you test this?

**Comment by Udit-takkar** [comment]
ok testing this out

**Comment by Udit-takkar** [comment]
@G3root Everything works fine. just the timezone when i changed from ( +5:30 -> +4:00 -> +5:30) should disable the update button

https://user-images.githubusercontent.com/53316345/205928355-5b60a5f0-5ca0-4796-842f-0bfd1f58ba88.mov

**Comment by G3root** [comment]
@Udit-takkar pushed some changes.

**Review by Udit-takkar — APPROVED** [review]
@G3root Although the problem that i mentioned before is still there but it is not blocking anything and the approach is also correct.  will figure this out later.

**Comment by PeerRich** [comment]
@Udit-takkar merging now, will you follow up with your NIT changes?

**Comment by Udit-takkar** [comment]
@PeerRich  yes

**Pull request merged**
