### PR TITLE
fix: team and org invite e2e tests

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

- Fixes e2e tests for organizations and team invites
- Removes the need for the clipboard fixture (introduced in #12241 ) as it resulted to be very flaky on CI
- Removes clipboard fixture altogether to prevent future flaky tests due to it's usage

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

Run tests for:
- apps/web/playwright/team/team-invitation.e2e.ts
- apps/web/playwright/organization/organization-invitation.e2e.ts

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by zomars** [comment]
Current dependencies on/for this PR:
* main
  * **PR #12566** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12566?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12566?utm_source=stack-comment).

**Review by zomars — COMMENTED** [review]
Self review done

**Comment by zomars** [comment]
As of now, all checks are passing 
image

**Review by sean-brydon — APPROVED** [review]
LGTM - good fix. Clipboard was very flaky even in local so this is great

**Pull request merged**
