### PR TITLE
fix: change max width to avoid overflow in dialog when creating new event type

### LINKED ISSUE #13783: New Event modal appears blurred
### Issue Summary

The modal for creating a new event type appears blurred

### Steps to Reproduce

1. Click on event types on the dashboard
2. Click on the new button in the top right-hand corner of the screen

### Actual Results

- The modal appears blurred.

### Expected Results

- The modal should be visible while its background blurred out

### Evidence

Screenshot from 2024-02-20 12-44-34

The blurry nature of the modal might not be very visible on this screenshot.

### PR DESCRIPTION
**Pull request by xylonx**
## What does this PR do?

This is an extend of  #14033, which only fixes overflow in setup tab described in #13784. I change the max width to avoid overflow described in #13783.

Fixes #13783, #13784

before:
image

after:
image

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

deploy the code and view the changed UI

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by sean-brydon — DISMISSED** [review]
Thanks for this change - do you think you can change it on the input specifically in the event type dialog? I'd rather not restrict the width of all our inputs to the size without design approval 

thanks

**Comment by xylonx** [comment]
Thanks for your reply and I will try that. 

And I have another idea about URL field in create event dialog. In current version, if the length of url is larger than 21, it will show on top of text input field instead of in front of the text. Since the addon is scrollable now, I want to make it consistent for whatever length of url. Do I need a design approval for this change? 

I show the change in the picture below

image

**Comment by xylonx** [comment]
I have confined the scope of changes only to the new event dialog. If it needs any further improvement, please don't hesitate to tell me.

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
fixing width won't work on smaller devices

Screenshot 2024-04-12 at 4 18 38 PM

**Comment by xylonx** [comment]
fixed. it now works on both big and small screen ratio. 


<table>
  <tr>
    <td>lg</td>
     <td>md</td>
     <td>sm</td>
  </tr>
  <tr>
    <td>image</td>
    <td>image</td>
    <td>image</td>
  </tr>
 </table>

**Review by Udit-takkar — APPROVED** [review]

**Pull request merged**
