### PR TITLE
feat: Assign recurring round-robin events to different hosts

### LINKED ISSUE #13937: [CAL-3250] Assign recurring round-robin events to different hosts
Right now, the same round-robin host is assigned to every recurring event instance. There are use cases where it makes more sense to assign different round-robin hosts for every instance. We want to allow the users to choose in the event-types settings how the hosts should be assigned.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3435](https://linear.app/calcom/issue/CAL-3435/[cal-3250]-assign-recurring-round-robin-events-to-different-hosts)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

Fixes #13937 
Fixes CAL-3250

Assign to different hosts is **false**

https://github.com/calcom/cal.com/assets/74371312/ff8c9d6e-753d-4ebd-9079-06af8319f8f4

Assign to different hosts is **true**

https://github.com/calcom/cal.com/assets/74371312/ae4471a2-b2d3-441d-8a0d-3aded34f6a94

## Type of change

- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
Thank you for working on that new feature 🙏 
There are some more things we need to take into account when assigning recurring events to different hosts. A few things I can think of:
- Every assigned host needs to get an email notification with the dates they were booked for 
- We need to have the bookings show up in each host's calendars (only the ones they were assigned to)
- Booking success page shows just one out of all the hosts. We maybe rather want to show something like 'members of Team Name' and maybe below show the host of the host assigned to the first booking

**Comment by Amit91848** [comment]
> Thank you for working on that new feature 🙏 There are some more things we need to take into account when assigning recurring events to different hosts. A few things I can think of:
> 
> * Every assigned host needs to get an email notification with the dates they were booked for
> * We need to have the bookings show up in each host's calendars (only the ones they were assigned to)
> * Booking success page shows just one out of all the hosts. We maybe rather want to show something like 'members of Team Name' and maybe below show the host of the host assigned to the first booking

Okay, will start working on these.

**Comment by Amit91848** [comment]
> * Every assigned host needs to get an email notification with the dates they were booked for

Should a normal event scheduled be sent to each user?

**Comment by Amit91848** [comment]
> > * Every assigned host needs to get an email notification with the dates they were booked for
> 
> Should a normal event scheduled email be sent to each host?

**Comment by Amit91848** [comment]
@CarinaWolli made some changes. 
Now host get a separate email for each individual booking. We can maybe send email at last when all bookings are done, and send only a single email per host with all its times in it. Lmk what you think about this. Also changed the booking page.


https://github.com/calcom/cal.com/assets/74371312/766ecb0b-3326-4802-9e94-db7805ef0f2c

**Comment by Amit91848** [comment]
Also unable to merge main even after resolving conflicts,

Screenshot 2024-03-31 at 9 55 45 PM

Parsing error: ESLint was configured to run on `<tsconfigRootDir>/next-i18next.config.js` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-fileeslint

**Comment by CarinaWolli** [comment]
> Now host get a separate email for each individual booking. We can maybe send email at last when all bookings are done, and send only a single email per host with all its times in it. Lmk what you think about this. Also changed the booking page.

Yes, we should definitely only send one email per host. That email should list all the dates the host is booked for

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
#### The booking detail page needs some changes: 
Screenshot 2024-05-10 at 10 54 11 AM
- Add team logo instead of avatar of host 
- I'd probably just remove 'You are meeting with Team Pro Example' for now. We can improve that text later
- In the 'Who' section, either list all hosts or no host


#### Emails 
- As mentioned in my comment, only one email per host that lists all the dates they are assigned to 
- I'd prefer the email to say 'A new recurring event has been scheduled`

#### Video location link
- I think it would be best to have the same video link for all events
- At least the video link in the email needs to fit the calendar event, right now every calendar event has another video link which will cause problems when we change it to only send one email per host

**Comment by Udit-takkar** [comment]
@Amit91848 any update on this?

**Comment by Amit91848** [comment]
> @Amit91848 any update on this? you can request re review if it's ready.

Some work is still left. Will try to finish it over the weekend

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
Code looks good, I found some more things when testing: 

Attendee Email: 
- Should show 'Members of [Team]' instead of the first host of the event

Video link: 
- It would be best if the video link would be the same for all recurring events. Right now it shows one video link in the attendee email but the video links are different between hosts

Tests: 
- Can you add some tests for this (at least one) in `recurring-event.tests.ts`
Let me know if you need help with the tests, but you should be able to copy paste a lot from the other tests in that file

**Comment by Amit91848** [comment]
@CarinaWolli for attendee the event title uses first host name for both booking page and email, should we change that too?

**Comment by CarinaWolli** [comment]
> @CarinaWolli for attendee the event title uses first host name for both booking page and email, should we change that too?

Yes, should also only show the team name not the first host 🙏

> Also cancel and reschedule links for host goes to first event of the respective host, should this be changed?

I saw that, I think that's fine 👍

> For same hosts, all bookings have different video links, only host and attendee email show same first video link.
> Do you want all bookings to have the same link, or only the email to have same link?

I think having one video link is the best and least confusing solution. So no matter what host, the video link in the emails and calendar events is always the same

**Comment by Amit91848** [comment]
@CarinaWolli I added a simple unit test and fixed email.

> I think having one video link is the best and least confusing solution. So no matter what host, the video link in the emails and calendar events is always the same

Can you look into this, I couldn't figure this out.

**Comment by keithwillcode** [comment]
Closing due to staleness. Please reopen if work continues.

**Pull request closed without merging**
