### PR TITLE
Introducing Playwright Fixtures - Users Factory

### LINKED ISSUE #2295: Cannot logout when using the logout path route (/auth/logout)
### Issue Summary

A little weird behavior that when I navigate to the logout path, I got the message feedback that I have successfully logged out, but I'm actually still logged in. Navigating to the root "/", takes me to my home events page as usual. 

### Steps to Reproduce

1. Log in.
2. Navigate to [http://localhost:3000/auth/logout](http://localhost:3000/auth/logout), or your live hosted copy of Cal  
3. You will get an instant feedback message of being successfully logged out.
4. Navigate to the root (or any page within Cal). 
5. You are still logged in.

### PR DESCRIPTION
**Pull request by denik1981**
## What does this PR do?

_Also fixes #2295 being the change small and using this PR for the test_

This PR is aimed to work in the problem of using the same pool of data for all of our tests making mutations unpredictable.
Also generating new users is costly because we have to constantly change the seeded data adapting it to our new needs.
This is expensive in terms of time and effort and forces us to reduce parallelism to prevent data collisions. 

Fixtures will allow us to recreate on the fly certain common tasks we do in our tests and make them work really isolated from each other. In this case, I'm adding the "users" fixture which will allow us to create "unique" users on the fly and manage core user tasks such as login and logout.  

PR #2294 (draft) is a demo linked to this one with some demo tests in it that will better explain what (and how) this fixture is doing although the API is small and very intuitive. Most answers to your questions are in the provided demo. 

If you want to keep the **Demo** available as a usage guide for contributors the only requirement is to make all the tests  "skipped" (`test.skip()`) so that they don't run in CI.   

In a nutshell:

Just like any other fixture, users are scoped to each test. 
username is timestamped to assure being unique.

Some examples,
```
users.create() // creates a "pro" user
users.create({plan:"free"}) // create a free user 
users.create({username:"jhon", plan:"trial", timezone:"us", locale: "es"}) 
```
And then,
```
const pro = users.create()
pro.login() // logins the pro user
```
You can create many user instances in the same test and re-login/out them as you need.

```
users.logout() // creates an anonymous session
```

You can insert debug messages in the user metadata field as well.
```
const pro = users.create()
pro.debug({message:"this-is-a-debug-message"})  
```
### Upcoming fixtures: 
**events**: Factory for events
**book**: Handler to book events
**teams**: Factory for teams 
**story**:  A collection of pools of data by using the created fixtures toolkit

---

Fixes #2295
_The test associated with this bug fix is using this fixture as well._

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

## How should this be tested?

Play the provided demo #2294

### CODE REVIEW

**Comment by hariombalhara** [comment]
This looks amazing 💯

**Review by zomars — APPROVED** [review]
This is a great improvement indeed. Can't wait to see where this is going! 🙏🏽

**Comment by denik1981** [comment]
> This is a great improvement indeed. Can't wait to see where this is going! 🙏🏽

@zomars  my personal roadmap is to give support on the tests need for the Apps Store and then retake this to add the other fixtures that complete the collection. If you people want to have this collection first, let me know. Besides the collection of fixtures, there would be a later step to reconvert the current tests to use the new fixtures so that we can decouple from the seeded data and run our tests in parallel.

**Comment by zomars** [comment]
Sounds like a plan 🙌

**Pull request merged**
