### PR TITLE
tweak `inferSSRProps` to not need `as const`

### PR DESCRIPTION
**Pull request by KATT**

### CODE REVIEW

**Comment by zomars** [comment]
Why not using a try catch block in `getServerSidePros` and throw on each exception?  That way inferred props will always be correct.

**Comment by KATT** [comment]
> Why not using a try catch block in `getServerSidePros` and throw on each exception?  That way inferred props will always be correct. 

Would give no control of the status codes. This does both.

**Comment by zomars** [comment]
> > Why not using a try catch block in `getServerSidePros` and throw on each exception?  That way inferred props will always be correct.
> 
> Would give no control of the status codes. This does both.

Why not? You can catch the error and return the status code as normal, and `InferGetServerSidePropsType` will work as well.

**Comment by KATT** [comment]
Where would you catch it? If you'd catch in the same function you'd still have to solve the same issue whilst adding complexity of a big try/catch-block.

I might be wrong, feel free to open an alternate PR with a better solution.

**Comment by zomars** [comment]
@KATT this is what I've meant: https://github.com/calendso/calendso/pull/597/files

**Comment by KATT** [comment]
Thank you, @zomars, I appreciate the effort you put into this, here are some reasons why this isn't an improvement in my opinion:

- First of all,`InferGetServerSidePropsType` is _also_ a utility type, but it didn't work well, which is why we added `inferSSRProps` in #551.
- How do I know what `throw "noUser"` actually does? In the other example, I can just read that we wanna redirect/404/whatever
- You are adding _both_ a `try/catch` _and_ a `switch()` instead of having a quick `return` - the amount of cognitive this adds is huge
- You should _never_ `throw` non-errors - they are really hard to handle (a string has no stack trace, etc.)
- Exception-based control flows are an anti-pattern popularised by Java-devs in the 90s and been declared bad for a long time since. Use `if`-blocks and return early.
- You are _still_ returning a redirect/notFound, so the issue of inference still stays the same. If you really hate writing `{ redirect: { /* ... */ }` twice, declare it as a `redirectToLogin`-variable and return the variable instead

**Comment by zomars** [comment]
Curious, I find it way more readable and reusable.

- Errors are handled gracefully
- The switch statement is optional
- by inserting another utility you're creating more fragmentation IMO

Different styles I guess. 🤷‍♂️

**Review by emrysal — APPROVED** [review]

**Comment by emrysal** [comment]
Hi @zomars - I had a look at your PR as well so I could give a bit of objective feedback for the two fixes and I concluded that I preferred @KATT 's implementation.

* Agree with your point on "by inserting another utility you're creating more fragmentation IMO". I agree on this, but the way I see it as well is that type inference currently does not work properly in NextJS - @KATT's fix is considerably easier to remove later down the line when a proper fix is released.
* Adding try {} catch {} in the way that you did wouldn't fly - this is not a problem with the concept per-se as it could work, but in this case actual application errors wouldn't be handled properly.
* Having throw / catch around an entire block of code is too easily done and the amount of potential side-effects or complications down the line are very hard to predict. 

But I think the ease of removal should be the deciding factor here, and it'll be much easier to remove inferSSR than to undo all the try - catches (which may have been used since for other stuff as well).

**Pull request merged**
