### PR TITLE
Fixed zapier template UI spacing issue

### LINKED ISSUE #7538: UI issue zapier templates
### Issue Summary

Button is in wrong position (/apps/installed/automation -> Zapier): 
Screenshot 2023-03-06 at 11 52 55

Figma: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=20611%3A168513&t=ztPbClcOgk7mbdfO-0

### PR DESCRIPTION
**Pull request by umairfarooq44**
## What does this PR do?

It fixes the 

Fixes [#7538 ](https://github.com/calcom/cal.com/issues/7538)

Screenshot 2023-03-08 at 4 34 26 PM

**Environment**: Staging(main branch) / Production

## Type of change

- [ X ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by CarinaWolli — COMMENTED** [review]
Can we make the gap between text and button 16px like shown in the figma design?
Screenshot 2023-03-08 at 11 02 08

Other than that it is looking good 🙌🏻

**Comment by umairfarooq44** [comment]
@CarinaWolli we surely can add 16px spacing between text and button but it won't fix the alignment of button. Thats because different height of Text, for some cards text is on two lines and for some its one line. This is how it looks if I only add spacing: 

Screenshot 2023-03-08 at 9 49 07 PM

and this is how it looks if we add spacing and also use flex

Screenshot 2023-03-08 at 9 50 20 PM
Should I go with the second one?

**Comment by CarinaWolli** [comment]
@umairfarooq44 second one looks good 👍

**Review by emrysal — APPROVED** [review]
LGTM & Thanks for your contribution, looking good 👍

**Pull request merged**
