### PR TITLE
fix: #15458 randomize tips

### LINKED ISSUE #15458: [CAL-3940] randomize "Tip Sidebar"
super easy, lets randomise this list, just in case people havent clicked through them:

image

<sub>[CAL-3940](https://linear.app/calcom/issue/CAL-3940/randomize-tip-sidebar)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

fixes #15458 
fixes CAL-3940

/claim #15458 

updated/latest with auto randomize -

https://www.loom.com/share/d1eab1c4f91b4c43b2b155d111eb36be?sid=51d34e26-13dd-4182-a2c8-ab86ec72f7c1

previous update without auto random -
https://www.loom.com/share/25b64310e3624930a2cd6ae0ca0d87c0?sid=ab43a8d9-af19-4f70-b62f-deec5b980607

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

### CODE REVIEW

**Review by PeerRich — CHANGES_REQUESTED** [review]
this looks like a lot less code and simplier, no?

https://stackoverflow.com/a/46545530

**Comment by vijayraghav-io** [comment]
> this looks like a lot less code and simplier, no?
> 
> https://stackoverflow.com/a/46545530

@PeerRich considering efficiency, Fischer Yates shuffles(currently implemented) is chosen over sorting based shuffle. Here is the detailed comparison. Please let know if still we want to go with sorting based shuffle.

Screenshot 2024-06-20 at 10 23 13 AM
Screenshot 2024-06-20 at 10 25 01 AM

**Comment by PeerRich** [comment]
> > this looks like a lot less code and simplier, no?
> > https://stackoverflow.com/a/46545530
> 
> @PeerRich considering efficiency, Fischer Yates shuffles(currently implemented) is chosen over sorting based shuffle. Here is the detailed comparison. Please let know if still we want to go with sorting based shuffle.
> 

my friend, this is not a university exam. we are shuffling 10 div containers. we don't need O(n)

**Comment by vijayraghav-io** [comment]
@PeerRich updated. Thanks for the review :)

**Comment by PeerRich** [comment]
merged in https://github.com/calcom/cal.com/pull/15469

**Pull request closed without merging**
