### PR TITLE
refactor: Paypal App UI & UX

### PR DESCRIPTION
**Pull request by supalarry**
## What does this PR do?

The goal of this PR is to reduce friction when adding PayPal for events and improve user experience.

Loom: https://www.loom.com/share/7b31f52e5da0474d88fddafd68134503?sid=e9de6867-9b5e-4a2b-949e-df14e1bd78a2

### Error fixed & UX improved
1 After enabling PayPal for an event and entering the amount and pressing save, the error "An unexpected error occurred. Try again." appeared in production, because by default "currency" app data is undefined. Now it has a default value of "USD" and the app works as expected. This also improves UX because people who want USD as the currency can simply enter price and save the event and for non-USD users it's a more consistent experience because the Price input has the same currency as the "Currency" dropdown. See [commit](https://github.com/calcom/cal.com/pull/11528/commits/29c79fde59132d3bd9cb8dc3cad6f59a2c27e51e).

<details>
  <summary>Technical implementation rationale ⭐</summary>
If you see the commit, you see that in `paypal/zod.ts` for the currency property I added `.default(defaultCurrency)`, so that if "Save" is clicked the app data "currency" has value. Then in the component "currency" either already exists `getAppData("currency")` or is set to `defaultCurrency` if PayPal was just added to the event.

This was my second approach, because before I tried simply using `useEffect` hook in the component to initialise "currency" if it's the first time adding PayPal to the event:
```
  useEffect(() => {
    if (!getAppData("currency")) {
      setAppData("currency",  defaultCurrency);
    }
  }, []);
```

However, this made E2E tests timeout:
Screenshot 2023-09-27 at 11 05 35

I researched the codebase and only saw the usage of `setAppData` within a callback function and did not find an example where `setAppData` is invoked within "useEffect" hook - `setAppData` seems to be invoked only on DOM events like "onClick" but not manually, so I needed to find an alternative above.

</details>

🟥 Before:
Screenshot 2023-09-25 at 17 25 54

🟩 After:
Screenshot 2023-09-25 at 17 27 01

### UX improvements
1 Whatever currency was selected under "Currency", the currency symbol in the "Price" input was always "$". So if someone selected "Euro" as "Currency" the price input symbol was still "$", but now it adapts to the currently selected currency. For all dollars, be it "United States dollar" or "Australian dollar", the symbol is "$" and the same for krone "kr", be it Danish or Norwegian. A further distinction could have been made to denote "Australian dollar" as "A$" but that overcomplicates the UX. See [commit](https://github.com/calcom/cal.com/pull/11528/commits/f1b4cb9c419f2132c3ba38f08bdaad951c46a683).

<details>
  <summary>Technical implementation rationale ⭐</summary>
If you see the commit, in `lib/currencyOptions.ts` I created a type-safe constant `currencySymbols` that stores symbols for each currency and ensures that if we add a new currency to `currencyOptions` that it will be required to add a new entry to `currencySymbols` too. The easiest would have been to add a "symbol" key to each object in `currencyOptions`, but I didn't, because `currencyOptions` stores information for the dropdown, which would mean that the dropdown would receive the "symbol" key which it does not depend on, and I wanted to extend code rather than mixing it. Then, in the component, I added a new reactive variable that finds the correct symbol based on the "currency" app data and then dynamically displays it. I did not add a new property "symbol" to app data as the symbol is not needed for any data processing down the line.
</details>

🟥 Before:
Screenshot 2023-09-25 at 17 32 47

🟩 After (see € symbol):
Screenshot 2023-09-25 at 17 32 56

### UI improvements
1 In the "Price" input increase / decrease arrows had big margin on the right. Removed it. See [commit](https://github.com/calcom/cal.com/pull/11528/commits/22490ac57855d885341631f62078657dca9f7cb4)

🟥 Before:
Screenshot 2023-09-25 at 17 29 51

🟩 After:
Screenshot 2023-09-25 at 17 29 55

2 "Price" input had gray top and bottom margin. Removed it. See [commit](https://github.com/calcom/cal.com/pull/11528/commits/99f130b1077c8f6d92fa1840b7ea480d4397f7e2).

🟥 Before:
Screenshot 2023-09-25 at 17 29 37

🟩 After:
Screenshot 2023-09-25 at 17 29 42

3 PayPal app "Currency" and "Payment option" dropdowns were crowded so made it more spacious. See [commit](https://github.com/calcom/cal.com/pull/11528/commits/6de58154a5ab585ff1da0e28277d260dc65719c8).

🟥 Before:
Screenshot 2023-09-25 at 17 31 10

🟩 After:
Screenshot 2023-09-25 at 17 31 16

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

1. Enable Paypal to an event only input "Price" amount and press "Save".
2. Change currency and see currency symbol updating. Hit "Save", browse "Event Types" and see the corresponding currency appearing next to the price.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- Fix TS error

### CODE REVIEW

**Comment by supalarry** [comment]
TODO: fix type-check error
https://github.com/calcom/cal.com/actions/runs/6314582326/job/17145190391?pr=11528

I couldn't figure it out, because now the "currency" key has a default value of "USD" in zog, so it won't be undefined. Also, in `schema.prisma` I see that `currency` in `EventType` and `Payment` models is a required `String` and not an optional `String?` so I think that zog schema matches it.

**Comment by supalarry** [comment]
@alannnc I saw that you created the PayPal app. Would appreciate it if you have time to check this PR and let me know if I can improve anything. Cheers.

**Comment by alannnc** [comment]
> @alannnc I saw that you created the PayPal app in #8797. Would appreciate it if you have time to check this PR and let me know if I can improve anything. Cheers.

It looks good! Thank you for your contribution, this week a new payment app is arriving with some changes on the backend. This should come after we merge that.

**Review by alannnc — DISMISSED** [review]
Awesome! Thanks for your contribution. I've also applied the same style to stripe app.

**Comment by supalarry** [comment]
@alannnc I see you reverted changes that gave a TS error. I wrote it in PR description but, just in case, want to provide the reasoning behind the reverted code in "[undo zod changes that give type error](https://github.com/calcom/cal.com/pull/11528/commits/3f172e1c3324698d438c6206aa4041447440030c)":

Before the reverted code, I tried simply using `useEffect` hook in the component to initialise "currency" if it's the first time adding PayPal to the event:
```
  useEffect(() => {
    if (!getAppData("currency")) {
      setAppData("currency",  defaultCurrency);
    }
  }, []);
```

However, this made E2E tests timeout just like it does now:
Screenshot 2023-09-27 at 11 05 35

I researched the codebase and only saw the usage of `setAppData` within a callback function and did not find an example where `setAppData` is invoked within "useEffect" hook - `setAppData` seems to be invoked only on DOM events like "onClick" but not manually, so I needed to find an alternative above.

My question is: How to set data returned by "useAppContextWithSchema" in the "useEffect" hook? The functionality itself when tested manually works but makes E2E tests timeout.

**Comment by alannnc** [comment]
> @alannnc I see you reverted changes that gave a TS error. I wrote it in PR description but, just in case, want to provide the reasoning behind the reverted code in "[undo zod changes that give type error](https://github.com/calcom/cal.com/pull/11528/commits/3f172e1c3324698d438c6206aa4041447440030c)" which had a goal to set the default currency in app data so that "No currency selected" in the Price input would not be shown.
> 
> Before the reverted code, I tried simply using `useEffect` hook in the component to initialise "currency" if it's the first time adding PayPal to the event:
> 
> ```
>   useEffect(() => {
>     if (!getAppData("currency")) {
>       setAppData("currency",  defaultCurrency);
>     }
>   }, []);
> ```
> 
> However, this made E2E tests timeout just like it does [now](https://github.com/calcom/cal.com/actions/runs/6346286395/job/17240007656): Screenshot 2023-09-27 at 11 05 35
> 
> I researched the codebase and only saw the usage of `setAppData` within a callback function and did not find an example where `setAppData` is invoked within "useEffect" hook - `setAppData` seems to be invoked only on DOM events like "onClick" but not manually, so I needed to find an alternative above.
> 
> My question is: How to set data returned by "useAppContextWithSchema" in the "useEffect" hook? The functionality itself when tested manually works but makes E2E tests timeout.

Yeah the change in the zod makes sense, but since it failed on type I decided for the norm on other payment apps as setting initial values on "didMount" if required. I guess in the future we might come up with a better initial/default values from the Form initialazion.

Also this just got merged: https://github.com/calcom/cal.com/pull/11623 so there was another bug around there.

**Review by alannnc — APPROVED** [review]

**Pull request merged**
