### PR TITLE
feat: add aws s3 upload app

### LINKED ISSUE #6939: [CAL-1011] App: File Upload (Starting with Amazon S3)
starting with S3, organisers can ask guests for a file upload (i.e. a CV or similar)

for security reasons, organisers need to provide their own S3 bucket since [Cal.com](http://Cal.com) does not want to host your files

this app would be of type "EventTypeApp"

in event-types:

booking page:

questions:

should this be always optional? or always required? or ability to decide?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1011](https://linear.app/calcom/issue/CAL-1011/app-file-upload-starting-with-amazon-s3)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #6939
/claim #6939

[Screencast 2023-09-07 15:01:31.webm](https://github.com/calcom/cal.com/assets/84864519/b199c630-7b8f-42a3-a20f-72413edd0797)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

### CODE REVIEW

**Comment by G3root** [comment]
@hariombalhara love to hear some feedback :⁠-⁠)

**Comment by PeerRich** [comment]
@G3root how generic is this implementation? can we make this very generic, maybe even an app store template "File upload App" where we can easily add Google Drive, Dropbox, etc.

**Comment by PeerRich** [comment]
sorry @G3root but weve decided to not do this right now

**Pull request closed without merging**
