### PR TITLE
Remove duplicated border in Calendar category

### LINKED ISSUE #7222: [CAL-1116] double border in installed apps
[https://www.loom.com/share/6abe035446d94e9faf29903ecde5e8cb](https://www.loom.com/share/6abe035446d94e9faf29903ecde5e8cb)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1116](https://linear.app/calcom/issue/CAL-1116/double-border-in-installed-apps)</sub>

### PR DESCRIPTION
**Pull request by esau-morais**
## What does this PR do?

Fixes #7222

Before
before

After
after

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Go to installed apps
- [ ] Check the difference between before and after

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by emrysal** [comment]
Thank you for this; However it is not the right fix for this issue as it's the wrong border that is removed - see the following from the design - tagging @sean-brydon for feedback:

image

**Comment by esau-morais** [comment]
> Thank you for this; However it is not the right fix for this issue as it's the wrong border that is removed - see the following from the design - tagging @sean-brydon for feedback:
> 
> image

Is this an updated version of the installed apps page? Because I followed the [Installed Apps design](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=27%3A97338&t=O8bN5kwTSwvRbmj2-4)

**Comment by esau-morais** [comment]
> Thank you for this; However it is not the right fix for this issue as it's the wrong border that is removed - see the following from the design - tagging @sean-brydon for feedback:
> 
> image

You're right. My mistake. I'll try to commit the right solution for this issue ASAP

**Comment by esau-morais** [comment]
Changelog:

Fixed wrong border for all installed apps

Before:
before

[After](https://www.loom.com/share/68efa8044309403faad1741c663cf6b4)

**Review by hariombalhara — APPROVED** [review]

**Comment by hariombalhara** [comment]
Thanks @esau-morais for your contribution 🙏

**Pull request merged**
