### PR TITLE
[Perf Improvement] Event Booking Date Picker 

### LINKED ISSUE #1970: Lag on events
### Issue Summary

There is a lag when clicking on months arrow

### Steps to Reproduce

1. Open an event
2. Click on the arrow next to the month name, to skip over to next month
3. Lag for around 4 to 6 seconds before the calendar moves over to next month

calcom lag

### Technical details

Browser : Brave (Chromium version 98.0.4758.109)
Node version : v12.18.2
Calcom version : latest pull

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
It improves the performance of Date Picker in Event Booking. The improvement is in 2 ways
1. Going to a month for the first time was taking ~9 seconds on 4x slowdown in Chrome. Now it takes ~4 seconds
2. Render dates in batches, so that user won't see blocking UI and he can skip multiple months faster
3. Revisiting an already visited month is superfast using memorization.

Fixes #1970 

With 4X Slowdown - Before [Check Total Blocking Time at the bottom]
4x slowdown - Before

With 4x  Slowdown - After [Check Total Blocking Time at the bottom]
4x slow down - After

Before GIF
before

After GIF

after

## Type of change

- [ ] Perf Improvement

## How should this be tested?

- [ ] In Event Booking Flow Go forward multiple months and then come backward multiple months
## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by baileypumfleet** [comment]
Wow this looks awesome! Can't wait for it to be ready

**Comment by zomars** [comment]
This looks impressive! Will take a look, test and deploy and get back to you. 🙏🏽

**Review by zomars — APPROVED** [review]
Couldn't find any issues with this. Nice work!

**Review by emrysal — APPROVED** [review]

**Comment by emrysal** [comment]
Closing #1984 in favour of this; these were made independent of eachother but each contains the same crucial fix (Dayjs being a turtle) but this one additionally contains some nice async/memo features.

**Comment by hariombalhara** [comment]
Wow. That was fast 👏 Thanks 👍

**Pull request merged**
