### PR TITLE
feat: Paid and confirmed booking should be able to be rescheduled v1

### LINKED ISSUE #11339: [CAL-2521] Make E2E test: Paid booking with payment confirmation should be able to be rescheduled
This is closer to what we made on #9368.

The difference is that on #10069, we needed a way to confirm the payment on Stripe stuff; we already have this now on [apps/web/playwright/fixtures/users.ts:482](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/fixtures/users.ts#L482~L511), and it's easily usable via `await user.confirmPendingPayment();` as on [apps/web/playwright/integrations-stripe.e2e.ts:126](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/integrations-stripe.e2e.ts#L126).

The test should be implemented on [apps/web/playwright/integrations-stripe.e2e.ts:147](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/integrations-stripe.e2e.ts#L147).

<sub>[CAL-2521](https://linear.app/calcom/issue/CAL-2521/make-e2e-test-paid-booking-with-payment-confirmation-should-be-able-to)</sub>

### PR DESCRIPTION
**Pull request by Ahmadkashif**
## What does this PR do?
Added a test case for rescheduling a paid and confirmed booking 

Fixes #11339 

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Are there environment variables that should be set?
-- Stripe keys

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by Ahmadkashif** [comment]
Hi @keithwillcode @emrysal @ologbonowiwi :wave: 

Please take a look at the attempt to close issue #11339. Let me know if there are any improvements I can add to make this work.

**Review by wesleymatosdev — APPROVED** [review]
LGTM

**Comment by Ahmadkashif** [comment]
Hi @keithwillcode @emrysal 👋 

What can I possibly do to move this forward?

**Review by zomars — APPROVED** [review]
Thank you for your contribution 🙏 @ologbonowiwi 

Code is looking good. Waiting for checks to pass before merging.

LGTM

**Review by zomars — APPROVED** [review]
Thank you for your contribution 🙏 @ologbonowiwi 

Code is looking good. Waiting for checks to pass before merging.

LGTM

**Pull request merged**
