### PR TITLE
feat: #1490 [CAL-422] Intercom App

### LINKED ISSUE #1490: [CAL-422] Intercom App
[https://developers.intercom.com/building-apps/docs/guidelines-tips](https://developers.intercom.com/building-apps/docs/guidelines-tips)

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by vachmara**
## What does this PR do?

This PR introduces an integration between Intercom and Cal.com, aimed at simplifying the process of scheduling meetings. Leveraging Intercom's OAuth framework, users can now seamlessly configure and utilize a "Book a Meeting" button directly within their Intercom Messenger. This integration enhances communication efficiency and offers users a convenient way to schedule meetings hassle-free. The PR encompasses OAuth authentication, configurable scheduling options, and real-time updates for a seamless user experience.

Fixes #1490 
/claim #1490

## Requirement/Documentation

To understand and implement the purpose of this PR, follow these steps:

1. **Cal.com App Setup:**
   - Create a [Cal.com app](https://developers.intercom.com/building-apps/docs).
   
2. **Intercom Configuration:**
   Activate and configure your app in Intercom's ***Authentification > OAuth***:
   - **Redirect:** Use `https://CAL_URL/api/integrations/intercom/callback`.
 
   Configure your app in Intercom's ***Canvas Kit > For Users, Leads, and Visitors***:
   
   - **Checkboxes:** Select relevant checkboxes (minimum one).
   - **Initialize Webhook:** Use `https://CAL_URL/api/integrations/intercom/initialize`.
   - **Submit Webhook (mandatory but not used):** Use `https://CAL_URL/api/integrations/intercom/submit`.
   - **Configure Webhook:** Use `https://CAL_URL/api/integrations/intercom/configure`.
   - **[EDIT] Submit Sheet Webhook** Use `https://CAL_URL/api/integrations/intercom/sheet`. 
   
4. **Admin Activation:**
   The admin account is responsible for activating the Intercom app in Cal dashboard. This involves providing the Client Id and Client Secret (available in the ***Authentication*** section of your Intercom app's configuration settings).

This PR facilitates OAuth integration and enables the "Book a Meeting" button in Intercom Messenger. Follow these steps meticulously for a seamless Cal.com and Intercom integration.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

To verify the changes made by this PR, follow these steps:

1. **Intercom App Configuration:**
   - If not already done, refer to the previous section to set up your Cal.com app in Intercom.

2. **OAuth Authentication:**
   - Log in to the Cal.com app as a user.
   - Navigate to the Cal.com app's store.
   - Activate the Intercom app using OAuth.

3. **Intercom Dashboard:**
   - Customize your [Messenger](https://www.intercom.com/help/en/articles/6612589-set-up-and-customize-the-messenger#h_0d6e0fb3cf) with the Cal.com App (if you checked the Messenger box before).
   - Save and set it live.
   - Integrate your Intercom Messenger into a test website.

5. **User Experience on Tested Website:**
   - Engage in a conversation as a user or lead in Intercom.
   - Notice the presence of the "Book a Meeting" button in the messenger.
   - Click the button and verify if it redirects to the Cal.com booking page.

By following these steps, you can validate the integration of the Cal.com Intercom app and ensure its smooth functionality.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't checked if my PR needs changes to the documentation
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by PeerRich** [comment]
we'll review this this week!"

**Comment by PeerRich** [comment]
will create an intercom app!

**Comment by PeerRich** [comment]
added: 
CleanShot 2023-08-31 at 13 02 54@2x


should we instead point this to a preview URL to test?

**Comment by PeerRich** [comment]
what do i have to setup here? 
CleanShot 2023-08-31 at 13 04 52@2x

**Comment by PeerRich** [comment]
@vachmara can you record a loom video showing:
- The OAuth flow
- Justification for scopes requested
- All app functionality
CleanShot 2023-08-31 at 13 06 15@2x

**Comment by vachmara** [comment]
> added: CleanShot 2023-08-31 at 13 02 54@2x
> 
> should we instead point this to a preview URL to test?

Exactly @PeerRich, to test it you should setup these with the preview URL, like this : `https://[PREVIEW_URL]/api/integrations/intercom/initialize`, etc. 


> what do i have to setup here?
> CleanShot 2023-08-31 at 13 04 52@2x

We need to configure OAuth. 

First, edit parameter and click on the `Use OAuth` checkbox, then configure the redirect URL like this : `https://[PREVIEW_URL]/api/integrations/intercom/callback`. 

Secondly, take the `client_id` and the `client_secret` to enable the app on Cal.com dashboard. Now the OAuth and the app on Cal.com should be activated! 

> @vachmara can you record a loom video showing:
> - The OAuth flow
> -  Justification for scopes requested
> - All app functionality

On it!
PS : This Pull request is a MVP of the Intercom integration. It may require improvement to have a perfect fit product!

**Comment by PeerRich** [comment]
@Vachmara can you record a loom video as a demo?

**Comment by vachmara** [comment]
> @vachmara can you record a loom video as a demo?

I am on it. I have just few problems on my self-hosted instance. Should be resolved today, though

**Comment by vachmara** [comment]
@PeerRich Regarding `OAuth` permissions we should only take the already checked one (used for Intercom's Canvas Kit), i.e : 

- Read and list users and companies
- Read conversations
- Read admins
- Read data when entered into the app

Here the [loom video](https://www.loom.com/share/655ba17ae7a4499caba85418c8aad81a?sid=cad37569-4b77-41ad-8e23-8f6fa3fcc740)

**Comment by PeerRich** [comment]
> 

thank you! submitting now to intercom

**Comment by PeerRich** [comment]
CleanShot 2023-09-07 at 18 29 30@2x
submitted

**Comment by PeerRich** [comment]
just got this feedback from intercom:

Couple of things to review and resubmit. 👇
[Scopes] You should only be selecting the scopes that are needed based on the app's current functionality. As this app involves Messenger Canvas Kit capabilities certain scopes are required (Read and list users and companies, Read conversations, Read admins, Gather App data) but the others would require justification based on current functionality. If you can resubmit with only the scopes that are needed and also provide a description in the app description section of the submission or in a new walkthrough video of why each scope is needed that would be helpful! More information in our docs [here](https://developers.intercom.com/docs/build-an-integration/learn-more/authentication/oauth-scopes/).
[Images] Images in the description section of the listing should be in marketing format. Currently the images included do not show context around how the app interacts specifically with Intercom data as it relates to your application. Please refer to the section [here](https://developers.intercom.com/docs/publish-to-the-app-store/listing-your-app/#app-images) in our docs for more information as well as examples of how they should be formatted.
[Install URL] Any apps that utilize our Canvas Kit (Messenger and Inbox apps) need the option to be installed via the Intercom App Store. Please include an Install URL as outlined [here](https://developers.intercom.com/docs/publish-to-the-app-store/review-publish-your-app/#submit-your-app-store-listing) in our docs.
[Promotional video] The [promotional video](https://developers.intercom.com/docs/publish-to-the-app-store/listing-your-app/#promotional-video-optional) should be in marketing format showing context around Intercom and Cal working together to provide the most value for mutual customers. Please include a new promotional video or feel free to omit this section as it's not a requirement for the listing.
Definitely feel free to let me know if you have questions on any of the above!

**Comment by vachmara** [comment]
Awesome, thanks for sharing, @PeerRich. 
I read that there are two different reviews: app review and app listing.

As mentioned in Intercom's documentation, app listing can be done afterward:
image

If the app review has not been accepted, I suspect that [Scopes] is the cause.
We need to only add these permissions from the Intercom's developer dashboard (default permissions that cannot be removed with Canvas Kit): 

- Read and list users and companies
- Read conversations
- Read admins
- Read data when entered into the app

On your developer dashboard, you should have something like this:
image

I suspect that [Images], [Install URL], and [Promotional Video] are related to the app listing.

Concerning the [Install URL](https://developers.intercom.com/docs/publish-to-the-app-store/review-publish-your-app/#or-through-your-website/app), we should specify the Cal.com link where the Intercom App details and installation process are available: https://cal.com/apps/intercom.

I am not very skilled at creating promotional images and videos, but I can ask my graphic designer to create something more visually appealing if needed!

**Comment by PeerRich** [comment]
fixed scope, adding new images:

**Review by PeerRich — DISMISSED** [review]

**Comment by vachmara** [comment]
Done ✅

**Review by PeerRich — DISMISSED** [review]

**Comment by PeerRich** [comment]
merging, lets test this in production before announcing. its behind a feature flag anyway

**Comment by PeerRich** [comment]
@vachmara some type check issues

CleanShot 2023-09-27 at 14 32 13@2x

**Comment by vachmara** [comment]
> @vachmara some type check issues
> 
> CleanShot 2023-09-27 at 14 32 13@2x

Should be all good now @PeerRich!

**Review by PeerRich — DISMISSED** [review]

**Comment by PeerRich** [comment]
can you replace screenshots 2 and 3 ?

**Comment by vachmara** [comment]
Done @PeerRich ✅

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
nice!!! will test today and publish later today 🙏

**Pull request merged**
