### PR TITLE
fix: teams upgrade banner on smaller screens

### LINKED ISSUE #8785: Teams page banner image breaks content on smaller screens
### Issue Summary

https://app.cal.com/teams banner background image makes text content unreadable on smaller screens.

### Steps to Reproduce

1. Go to app.cal.com/teams
2. Resize Screen

### Screenshot
Screenshot 2023-05-09 at 8 52 18 PM

### Suggestion
Perhaps remove background image entirely on smaller screens.

### PR DESCRIPTION
**Pull request by The-Robin-Hood**
## What does this PR do?

The issue was that the background image on the banner of the https://app.cal.com/teams page was making the text content unreadable on smaller screens. The issue was fixed by making changes to the CSS that controls the display of the background image. 

Fixes #8785

**Environment**: Production

## Type of change

- Bug fix (style fix for the background image of the banner)

## How should this be tested?

- [ ] Make sure that the background image on the banner (/teams, /insights) adapts on smaller screen and text was readable 

### Before :
image

### After : 
image

### CODE REVIEW

**Comment by PeerRich** [comment]
I dont think blurring is a good idea here, however, we could change the image position origin on that view point

**Review by PeerRich — CHANGES_REQUESTED** [review]
I dont think blurring is a good idea here, however, we could change the image position origin on that view point

**Comment by The-Robin-Hood** [comment]
Hope this works @PeerRich 
image

**Comment by The-Robin-Hood** [comment]
Hope this works @PeerRich 
image

**Review by Saga-sanga — APPROVED** [review]

**Review by sean-brydon — APPROVED** [review]
Happy with this :) Thanks @The-Robin-Hood

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
