### PR TITLE
Opt-in booking confirmation page & email are inconsistent

### LINKED ISSUE #2816: Opt-in booking confirmation page & email are inconsistent
After making a booking request with someone who has Opt-In bookings enabled, it is not obvious the booking is not confirmed. The icon looks like a success and at a glance the header reads like one too. The title actually needs to read more like the subtitle. It's also inconsistent with the email.

The confirmation page
Image

The email:
Image

### PR DESCRIPTION
**Pull request by gitstart**
## What does this PR do?

Fixes #2816

### More intuitive and clear Opt-in bookings confirmation page titles, as well as the icon

Opera Instantâneo_2022-06-27_104110_localhost

Opera Instantâneo_2022-06-27_104032_localhost

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by CarinaWolli** [comment]
Isn't the booking confirmation page and email for opt-in bookings still inconsistent? @Jaibles How should it look like, like in this PR or like our current emails?

**Comment by Jaibles** [comment]
@CarinaWolli here's a side by side: 
https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=7634%3A132667

The main difference between the browser and the email is just that we don't try to do 2 columns in email

**Comment by gitstart** [comment]
Hi @CarinaWolli @Jaibles ! Any update on the discussion?

**Comment by CarinaWolli** [comment]
> Hi @CarinaWolli @Jaibles ! Any update on the discussion?

@gitstart As mentioned in #2816, email and booking confirmation page should be consistent, that's not the case here (tell me if I am wrong). So we probably should use the icons we currently use in emails. We also need to agree on one title for emails and booking confirmation page. Let's wait for @Jaibles's opinion, he will be back in a few days

**Comment by Jaibles** [comment]
@gitstart can you upload updated screenshots for me here so I can see what I'm evaluating now since there's no preview URL available for me 🙏

**Comment by MuriloAmarals** [comment]
Hey @Jaibles, so the screenshots are the same as above yet. Want me to send you where?

**Comment by Jaibles** [comment]
@MuriloAmarals it looks like the icons in the emails don't match the browser ones you shared above. Can you ensure that all match these: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=7634%3A132667

**Review by leog — CHANGES_REQUESTED** [review]
Very good initiative!

As mentioned by @Jaibles the icon to be used is the outline version for `ClockIcon` to be consistent with design. Also, noticed the emails are still showing different icons (and a missing text translation as well).

Organizer email:
image

Attendee email:
image

**Comment by leog** [comment]
Are you able to work on this @gitstart? I can take over otherwise

**Comment by MuriloAmarals** [comment]
> Very good initiative!
> 
> As mentioned by @Jaibles the icon to be used is the outline version for `ClockIcon` to be consistent with design. Also, noticed the emails are still showing different icons (and a missing text translation as well).
> 
> Organizer email: image
> 
> Attendee email: image

Hey @leog, do you want me to change all the icons for the one in the email?

**Comment by MuriloAmarals** [comment]
image

image

Is it close ?

**Comment by leog** [comment]
> Is it close ?

By outline version of the icon I mean importing it from outline instead of solid: 
`import { ClockIcon } from "@heroicons/react/outline";`

**Comment by leog** [comment]
> > > Hey @leog, do you have any help on how I could change the ClockIcon for outline design ?
> 
> > 
> 
> > By outline version of the icon I mean importing it from outline instead of solid: `import { ClockIcon } from "@heroicons/react/outline";`
> 
> 
> 
> image
> 
> 

Looks good to me, any other suggestion @Jaibles?

**Review by PeerRich — APPROVED** [review]
thank you for the changes, looks good!

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
> @MuriloAmarals it looks like the icons in the emails don't match the browser ones you shared above. Can you ensure that all match these: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=7634%3A132667

The icons still don't match: 

Email: 
Screenshot 2022-07-11 at 14 00 51

Success page: 
Screenshot 2022-07-11 at 14 01 31

Also I think we should keep the icon for a scheduled meeting green (in the email it is still green)

**Comment by MuriloAmarals** [comment]
> > @MuriloAmarals it looks like the icons in the emails don't match the browser ones you shared above. Can you ensure that all match these: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=7634%3A132667
> 
> The icons still don't match:
> 
> Email: Screenshot 2022-07-11 at 14 00 51
> 
> Success page: Screenshot 2022-07-11 at 14 01 31
> 
> Also I think we should keep the icon for a scheduled meeting green (in the email it is still green)

Hey @CarinaWolli , no problem, I can change it again, but I had understood just like @PeerRich  who replied above that it was fine. I thought the only pattern was the design and not the icon itself. Don't you think ?
But I also agree that we should keep the icon for a scheduled meeting green.

**Comment by CarinaWolli** [comment]
> Hey @CarinaWolli , no problem, I can change it again, but I had understood just like @PeerRich who replied above that it was fine. I thought the only pattern was the design and not the icon itself. Don't you think ?

According to the Figma design (https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=7634%3A132667) we should have the same icons for email and success page. The figma uses this icon: 
Screenshot 2022-07-13 at 13 52 41

So I think it's best to use this icons for both, email and success page. @Jaibles correct me if I am wrong

**Comment by MuriloAmarals** [comment]
> > Hey @CarinaWolli , no problem, I can change it again, but I had understood just like @PeerRich who replied above that it was fine. I thought the only pattern was the design and not the icon itself. Don't you think ?
> 
> @MuriloAmarals According to the Figma design (https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=7634%3A132667) we should have the same icons for email and success page. The figma uses this icon: Screenshot 2022-07-13 at 13 52 41
> 
> So I think it's best to use this icons for both, email and success page. @Jaibles correct me if I am wrong

Hey @CarinaWolli , I must have looked wrong in figma then, but I saw that the email had a different icon than the success page.
If you think better I can change.😃

**Comment by CarinaWolli** [comment]
> Hey @CarinaWolli , I must have looked wrong in figma then, but I saw that the email had a different icon than the success page. If you think better I can change.😃

@MuriloAmarals Yes, please make the changes so we have same icons for success page and email. Thank you 🙏

**Comment by MuriloAmarals** [comment]
> > Hey @CarinaWolli , I must have looked wrong in figma then, but I saw that the email had a different icon than the success page. If you think better I can change.😃
> 
> @MuriloAmarals Yes, please make the changes so we have same icons for success page and email. Thank you 🙏

@CarinaWolli But just to be clear, do you want me to use the clock or calendar icon?

**Comment by MuriloAmarals** [comment]
> > @CarinaWolli But just to be clear, do you want me to use the clock or calendar icon?
> > Another question, Which do you prefer ?
> 
> @MuriloAmarals I prefer the first one with the green check mark and let's use the clock icon like in the Figma

Like this @CarinaWolli ?
image

**Comment by CarinaWolli** [comment]
> Like this @CarinaWolli ?
> image

@MuriloAmarals Yes, let's use this one

**Comment by MuriloAmarals** [comment]
> > Like this @CarinaWolli ?
> > image
> 
> @MuriloAmarals Yes, let's use this one

Hey @CarinaWolli, i can't use this icon in email, because ClockIcon doesn't have a png like the others. So do you prefer to change the icons for Calendar or do you need to deploy ClockIcon png

email code
email header

**Comment by CarinaWolli** [comment]
> Hey @CarinaWolli, i can't use this icon in email, because ClockIcon doesn't have a png like the others. So do you prefer to change the icons for Calendar or do you need to deploy ClockIcon png

Ok sorry didn't know that. Maybe @Jaibles can help here

**Comment by Jaibles** [comment]
There's an export option in Figma: https://share.cleanshot.com/hIaZ8x
Icon

**Comment by MuriloAmarals** [comment]
> > Hey @CarinaWolli, i can't use this icon in email, because ClockIcon doesn't have a png like the others. So do you prefer to change the icons for Calendar or do you need to deploy ClockIcon png
> 
> @MuriloAmarals there's an export option in Figma: https://share.cleanshot.com/hIaZ8x Icon

Hi @Jaibles! I am seeing at your codebase that you use the icons from deployed images image
Do you want me to export the icon, put it on the folder that deploys that image and use it from local reference or already considering that it will work after deploy?

**Comment by MuriloAmarals** [comment]
I was able to export the icon, but it comes with the name of checkCircle, which already exists
https://www.loom.com/share/abfd1f60297b49d592a4339f75966c0d
renamed it on my computer to clockCircle@2x.png
image

**Comment by gitstart** [comment]
Closing this PR since the required design is not yet finalized

**Pull request closed without merging**
