### PR TITLE
fix: Booking Cancelled Webhook - Organiser webhook payload is missing id. #14697

### LINKED ISSUE #14697: Booking Cancelled Webhook - Organiser webhook payload is missing id.
### Issue Summary
Booking Created and Booking Rescheduled webhooks contain the `id` param on the `organiser` object. 

But this is missing from the Booking Cancelled webhook.  

### Steps to Reproduce
cancel a booking.  The organiser object is missing the `id` information that is available on the Created and Rescheduled webhook payloads.

### Actual Results
- missing `id`

### Expected Results
- organiser object to be consistent with create/reschedule flows

### Technical details
4.0.1

### Evidence
- file `packages/features/bookings/lib/handleCancelBooking.ts` 
- line 257 is not passing in `id` for the `organizer` object

### PR DESCRIPTION
**Pull request by vikaspatil0021**
Fixes: #14697 
## What does this PR do?

fixes the missing `id` and `username` information that is available on the Created and Rescheduled webhook payloads.

### CODE REVIEW

**Comment by vikaspatil0021** [comment]
@alishaz-polymath Please review.

**Review by Udit-takkar — COMMENTED** [review]
LGTM. @vikaspatil0021 could you also add this in tests?

**Comment by vikaspatil0021** [comment]
Hey @Udit-takkar,
https://github.com/calcom/cal.com/blob/8fbb1ed4260449a0e07260283b16122b834e2a59/apps/web/test/utils/bookingScenario/bookingScenario.ts#L942

https://github.com/calcom/cal.com/blob/8fbb1ed4260449a0e07260283b16122b834e2a59/packages/features/bookings/lib/handleSeats/test/handleSeats.test.ts#L1389
here `organizer` structure is different and `id` already exists. should i add `username` to them?

**Comment by Udit-takkar** [comment]
> here `organizer` structure is different and `id` already exists. should i add `username` to them?

No not here. check `expectBookingCreatedWebhookToHaveBeenFired` function in apps/web/test/utils/bookingScenario/expects.ts. create a similar function to check booking cancelled webhook

**Comment by Udit-takkar** [comment]
@vikaspatil0021 use prettier and then push the code

**Comment by vikaspatil0021** [comment]
@Udit-takkar Please check

**Review by Udit-takkar — COMMENTED** [review]
@vikaspatil0021 you don't have to push yarn.lock file in this PR.  Please use

 git checkout origin/main -- yarn.lock  
and then pushing yarn.lock file to undo the changes in yarn.lock file.

2) You haven't added the test. you are not calling the function that you created anywhere.

**Review by Udit-takkar — APPROVED** [review]
LGTM.

TODO: https://github.com/calcom/cal.com/issues/14886

**Pull request merged**
