### PR TITLE
fix/event-type-location-select

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Fixes usage of dialog components

Fixes # (issue)
When trying to edit location of a event type you receive this error
image

Now:
image

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by zomars — COMMENTED** [review]
/shipit

**Comment by saschafoerster** [comment]
I updated with this fix, but now I can only select webconferences, no more locations or phone calls. 
Bildschirm­foto 2022-11-26 um 17 15 18

**Comment by PeerRich** [comment]
@Udit-takkar or @alannnc can you investigate?

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/204136235-7f213c58-6bd3-4406-a204-969d66aa8701.mov

this is on the latest main. did you try scrolling ?

**Comment by saschafoerster** [comment]
I built again, it's working as expected. Thank you for checking again!

**Pull request merged**
