### PR TITLE
feat: Redirect when event type does not match booking type

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

Bit of a complex one TS wise, should speed up TS performance however.

* Redirects to the "owning" event type when the booking reschedule UID belongs to another event type.
* Also fixes handling of rescheduleUid if supplied to the URL like rescheduleUid[]="trying"&rescheduleUid[]="to-break-the-system"

### CODE REVIEW

**Review by zomars — DISMISSED** [review]

**Comment by CarinaWolli** [comment]
@emrysal can you solve merge conflicts 🙏

**Comment by CarinaWolli** [comment]
@emrysal can fix the merge conflicts 🙏

**Comment by Udit-takkar** [comment]
@emrysal can you fix the merge conflicts?

**Review by keithwillcode — CHANGES_REQUESTED** [review]
@emrysal Requesting changes here since there are conflicts to fix

**Review by keithwillcode — APPROVED** [review]

**Pull request merged**
