### PR TITLE
fix: text beyond X icon

### LINKED ISSUE #8976: Text beyond the X icon
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The text on this input is overwriting the X icon space

### Steps to Reproduce

1. Edit some event-type
2. Go to "Advance"
3. Add a question and select "MultiSelect" type
4.Add more than two options

Loom video: https://www.loom.com/share/259ab60b675f497abb986d712e745fd9

### PR DESCRIPTION
**Pull request by AkhilG87**
Fixes  #8976

Screenshot 2023-05-25 at 2 08 18 AM

### CODE REVIEW

**Comment by AkhilG87** [comment]
@PeerRich please review

**Review by Udit-takkar — COMMENTED** [review]
@sean-brydon suggested this https://github.com/calcom/cal.com/pull/8981#pullrequestreview-1443342370

cc: @AkhilG87

**Comment by sean-brydon** [comment]
Thanks for the contribution @VinoV1999 

closing in favour of https://github.com/calcom/cal.com/pull/9198?no-redirect=1 as it was a cleaner approach!

**Comment by sean-brydon** [comment]
Thanks for the contribution @AkhilG87 

closing in favour of https://github.com/calcom/cal.com/pull/9198?no-redirect=1 as it was a cleaner approach!

**Pull request closed without merging**
