### PR TITLE
feat: added aws,digitalocean and hetzner guide

### LINKED ISSUE #12560: [CAL-2767] Documentation: How to deploy Cal.com on various providers
We currently lack comprehensive documentation on deploying our application on various cloud providers and hosting platforms such as AWS, GCP, DigitalOcean, Flightcontrol, Railway, Netlify, and others. Current docs are [here](https://cal.com/docs/introduction/quick-start/self-hosting/installation#app-store-seeder).

### Desired Features:

* **Platform-specific Guides**: Develop detailed guides for deploying the app on AWS, GCP, DigitalOcean, Flightcontrol, Railway, Netlify, and any other relevant providers.
* **Step-by-Step Instructions**: Provide clear, concise, and easy-to-follow step-by-step instructions for each provider, covering the setup, configuration, and deployment processes.
* **Environment Variations**: Address any provider-specific configurations or nuances, ensuring the documentation accommodates different hosting environments seamlessly.
* **Best Practices**: Include best practices for deployment on each platform, optimizing performance, security, and scalability.

### Requirements:

* **Consistency**: Ensure a consistent format and structure across all provider-specific documentation to ease navigation and comparison.
* **Testing**: Validate the documentation by deploying the app on each specified platform, verifying the accuracy of the provided instructions.

### Additional Considerations:

* **Environment Variable Management**: Provide guidance on managing environment variables specific to each hosting environment.
* **Security Considerations**: Include security best practices for deploying our app on each platform.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2767](https://linear.app/calcom/issue/CAL-2767/documentation-how-to-deploy-calcom-on-various-providers)</sub>

### PR DESCRIPTION
**Pull request by smyja**
## What does this PR do?

Fixes #12560 
 Loom Video: https://www.loom.com/share/eb92be92590442a2a1118c77f51b63ca

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?
I added a loom video showing it, here's a deployed link also.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by PeerRich** [comment]
hey thank you, however, for security reasons we do not link to external websites that we dont have control over. Our team will write these guides and host them on cal.com/docs

I've cc'ed @alishaz-polymath here to mention your work in the new docs.

**Comment by smyja** [comment]
> hey thank you, however, for security reasons we do not link to external websites that we dont have control over. Our team will write these guides and host them on cal.com/docs
> 
> I've cc'ed @alishaz-polymath here to mention your work in the new docs.

Oh, sorry about that. Someone from the team told me it was okay to do it. It's my osshack submission.

**Comment by alishaz-polymath** [comment]
Hey @smyja it was me, and the purpose was to allow you to have as easy submission for the documentation as possible. The idea was always to then convert your linked docs to our docs and mention your contribution. As @PeerRich said, we cannot merge the PR, but we will be taking the docs once we have confirmed their accuracy. I hope this makes sense 🙌

**Comment by smyja** [comment]
> Hey @smyja it was me, and the purpose was to allow you to have as easy submission for the documentation as possible. The idea was always to then convert your linked docs to our docs and mention your contribution. As @PeerRich said, we cannot merge the PR, but we will be taking the docs once we have confirmed their accuracy. I hope this makes sense 🙌

Alright, ping me if there's an update or you need clarification.

**Pull request closed without merging**
