### PR TITLE
fix: CAL-2126 url layout query param is source of truth for layout

### LINKED ISSUE #10000: [CAL-2126] New Booker: Sync month/week/column view with URL
Currently the selected view is only saved in a local state. Meaning that a refresh or browser back/forward button won't have any effect. We should use the URL as the main source of truth. Also this will allow to share a link with a pre-selected view.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2126](https://linear.app/calcom/issue/CAL-2126/new-booker-sync-monthweekcolumn-view-with-url)</sub>

### PR DESCRIPTION
**Pull request by satya-nishanth**
## What does this PR do?

Fixes #10000

 Earlier without this fix
 Loom Video: https://www.loom.com/share/f0c5d871bd5f4c12bba25091d6cfbce2

 After this fix
  Loom Video: https://www.loom.com/share/d90820a146fa43c8805cde94fe22f77e

## Requirement/Documentation

We should use the URL as the main source of truth for the layout view. Also, this will allow users to share a link with a pre-selected view

## Type of change
  - [ ] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

  - Go to an event-type to book. ( like this URL : https://cal.com/pro-fw5qyl/30min)
  - Change the layout option in the left top with the selection of month, week, and column. Select week or column (as the default is month)
Screenshot 2023-07-12 at 9 01 29 PM

 - Refresh the URL and still, the layout selection persists 
 
## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nish9142** [comment]
@zodman can you review this PR?

**Comment by nish9142** [comment]
@PeerRich can you review this?

**Comment by PeerRich** [comment]
> @PeerRich can you review this?

thank you for the contribution, keep in mind its a weekend hehe. we'll review your PR this week 🙏

**Comment by nish9142** [comment]
> > @PeerRich can you review this?
> 
> thank you for the contribution, keep in mind its a weekend hehe. we'll review your PR this week 🙏

Thank you so much for the reply, this was my first contribution so I actually forgot about the weekend thing😅

**Review by Udit-takkar — APPROVED** [review]
LGTM. Great work @satya-nishanth

**Pull request merged**
