### PR TITLE
fix: Fix wrong footer Button in some languages

### PR DESCRIPTION
**Pull request by gitstart-calcom**
## STEPS TO REPRODUCE

1. Create a team
2. Click on "add members" button

Issue:

image

## DEMO

PR with the current changes: https://www.loom.com/share/ef12c7306f28452295a5e9f978061583?sid=8aa3288b-384c-40b7-8228-3dc4d3674de4

We followed the suggestion [here](https://github.com/calcom/cal.com/pull/10873#issuecomment-1702958534) and set this button to show just the icon in mobile cases. We tried to implement the Peer [suggestion](https://github.com/calcom/cal.com/pull/10873#issuecomment-1702988267), but in this case we would need some designs:

image

### CODE REVIEW

**Review by Udit-takkar — DISMISSED** [review]
Not responsive

Screenshot 2023-08-22 at 4 59 54 PM

**Comment by gitstart-calcom** [comment]
Hi @Udit-takkar what should be the correct behavior? This button will override the cancel button. Maybe we could let this button out of the footer for mobile cases, what do you think?

**Comment by Udit-takkar** [comment]
> Hi @Udit-takkar what should be the correct behavior? This button will override the cancel button. Maybe we could let this button out of the footer for mobile cases, what do you think?

cc: @ciaranha

**Review by keithwillcode — DISMISSED** [review]

**Review by PeerRich — APPROVED** [review]

**Comment by sean-brydon** [comment]
Hey :)  - thanks for this.

We were thinking in mobile if we could make the copy link button a icon button? 

Either a Three dot more that opens a context menu or simpily a copy button. 

Saves this from overflowing and being a mess for languages that are longer than normal

**Review by PeerRich — DISMISSED** [review]

**Comment by PeerRich** [comment]
why dont we just line break?

copy invite link
cancel send invite

**Comment by gitstart-calcom** [comment]
Hey @sean-brydon @PeerRich We made the requested changes, please take a look at the updated description 😄

**Review by PeerRich — APPROVED** [review]
CleanShot 2023-09-05 at 20 34 12@2x
CleanShot 2023-09-05 at 20 34 28@2x


CleanShot 2023-09-05 at 20 34 38@2x

CleanShot 2023-09-05 at 20 34 48@2x

**Comment by PeerRich** [comment]
LGTM

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Pull request merged**
