### PR TITLE
fix: 11378 editor toolbar to left

### LINKED ISSUE #11378: [CAL-3954] Hard to Focus on Text Area to enter User About description
### Is your proposal related to a problem?

It is very hard to focus on the text area to enter the description in About section. And also the formatting options are just above the text area. So we i can't able to find the focus of text area.

### Describe the solution you'd like

Try to increase the text area height so that we can easily focus to text area. And also shift the formatting options to right of text area .

<sub>[CAL-3954](https://linear.app/calcom/issue/CAL-3954/hard-to-focus-on-text-area-to-enter-user-about-description)</sub>

### PR DESCRIPTION
**Pull request by tanav29**
closes https://github.com/calcom/cal.com/issues/11378

changed the stylng of toolbar and also shifted toolbar to left in editor.
made border in bottom of toobar

### CODE REVIEW

**Comment by PeerRich** [comment]
@tanavdev  can you provide screenshots?

**Comment by tanavdev** [comment]
Sure

**Comment by tanavdev** [comment]
here the screenshot of my updated style in "editor"

image

**Comment by tanavdev** [comment]
> @tanavdev  can you provide screenshots?

Yes I provided below

**Pull request closed without merging**
