### PR TITLE
Fix cancellation success page for unauthorized users

### PR DESCRIPTION
**Pull request by mlazowik**
## What does this PR do?

`session` itself is null when the user is anonymous, see https://github.com/calendso/calendso/blob/4cd7a4ce5b3812bfdb05dbb8f936e9c308570d86/components/Shell.tsx#L58

Prior to this change the page fails as it tries to access a property of `null`

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Go to the cancellation link as an anonymous user, hit "cancel"

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by zomars — APPROVED** [review]
LGTM 👍🏽 Nice job!

**Comment by PeerRich** [comment]
for whatever reason there is a merge conflict. will merge after fixed

**Review by PeerRich — APPROVED** [review]
lgtm after merge conflict resolved

**Comment by mlazowik** [comment]
Looks like this got fixed by https://github.com/calendso/calendso/commit/84d75cf69318584ec075752405a28f6b3e54740a#diff-4910bb9e089026024d606eb189d4201a50e61a839b7ef01cd27b726e763e5543

**Pull request closed without merging**
