### PR TITLE
Use modularizeImports for @heroicons

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

* Loads @heroicons through modularizeImports, preventing full import of @heroicons.

### CODE REVIEW

**Comment by PeerRich** [comment]
i dont think we want to continue using heroicons at all. lucide.dev has pretty much all the icons we need

**Review by PeerRich — DISMISSED** [review]
https://github.com/calcom/cal.com/issues/8423 opened an issue and assigned @gitstart-calcom to fully remove heroicons instead

**Comment by emrysal** [comment]
My testing is showing such gains that we may want to merge regardless @PeerRich

**Review by keithwillcode — APPROVED** [review]

**Comment by PeerRich** [comment]
fair point, good merge

**Pull request merged**
