### PR TITLE
Prepare for deprecated radix-ui IdProvider

### PR DESCRIPTION
**Pull request by denik1981**
## What does this PR do?

Prepares Cal for the announced deprecated IdProvider that is was used to generate unique id between SSR and client hydration and helps prevent the React mismatch error.

Cal codebase not only is using IdProvider for radix components but also the useId hook provided by the same radix package.
However, the useId hook can still be used to generate unique Ids for (radix and non-radix) components as it is used currently in `fields.tsx` and `Switch.tsx`, and it is not dependent on IdProvider as its context. Check the [source code](https://github.com/radix-ui/primitives/blob/main/packages/react/id/src/id.tsx).

As a follow-up, once React 18 becomes stable and used by Cal, this PR can be revisited to replace the radix version of `useId`  with the new native React.useId hook.
   
## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

 - yarn test
 - yarn test e2e
 - Also checked the rendered html and lookup for unique id in where it is used.
  
## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by denik1981** [comment]
I'm wondering if I should add code comments as a refactoring remainder to replace useId[radix] with useId[react18] once we start using react18.

**Comment by PeerRich** [comment]
just to confirm: all you did was remove ID?

**Comment by denik1981** [comment]
> just to confirm: all you did was remove ID?

Yup. I've only removed the wrapper. It is doing nothing.
 
I have previously checked with the Radix team as well cause Cal is using a radix internal hook to generate unique ids which we still need to use it to prevent SSR id mismatch errors. This hook is not marked as deprecated and is not dependent on the `IdProvider`. In fact, `IdProvider`, currently (I linked the radix code in this PR) is only logging the deprecated warning to the console. No business logic at all. 

If needed, we could also replaced their id hook with a custom one ( I don't think is necessary) or wait for the upcoming useId hook in React18 (when stable and available).

**Comment by PeerRich** [comment]
> Yup. I've only removed the wrapper. It is doing nothing.

Ok, is it safe to merge @denik1981? or do we need to wait for something else first? or update any package

**Comment by denik1981** [comment]
Safe to merge. Nothing else is needed from our side. Leaving or removing it won't make any difference besides cleaning up our console from their warning message. However, this PR will be necessary if **Radix** decided to remove IdProvider in a future release.

From radix [source](https://github.com/radix-ui/primitives/blob/main/packages/react/id/src/id.tsx). 
`IdProvider` is only rendering the children and throwing a warning to the console.
```
// DEPRECATED
function IdProvider({ children }: { children: React.ReactNode }) {
  React.useEffect(() => {
    if (process.env.NODE_ENV === 'development') {
      console.warn(ID_PROVIDER_DEPRECATED);
    }
  }, []);
  return <>{children}</>;
}
```

**Review by pumfleet — APPROVED** [review]

**Review by zomars — APPROVED** [review]

**Pull request merged**
