### PR TITLE
Improving recurring info in bookings

### LINKED ISSUE #5231: [CAL-261] Events Remaining display wrong time of remaining events on event reschedule
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Booking -> Recurring -> Events Remaining not displaying the correct event time and day after rescheduling

### Steps to Reproduce

1. Create a recurring event
2. Go to Bookings -> Upcoming and reschedule time or date and time of an event from recently created recurring event list.
3. Go back to Bookings -> Recurring -> under  "Events remaining" it does not change the time and date of the rescheduled event and displays the same date and time

### Technical details

Self hosted on main branch V2.1.1

> From [Linear-GitHub Sync](https://synclinear.com)

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

Recurring event in bookings was not showing the right information when it came to the dates tooltip.

This PR introduces fixes and additional visualization for cancelled instances:
<kbd></kbd>

Pending:
 - [x] @emrysal I need your help about DST, look at the example screenshot above, 8:10pm converts into 7:10pm at certain point

Fixes #5231 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Book a recurring event and cancel one instance, and reschedule another instance. New date/time for rescheduled and cancelled instances should be shown correctly.

### CODE REVIEW

**Comment by newz666** [comment]
It's displaying the wrong data at the creation, but it's getting fixed on it's own after 15 minutes

**Comment by leog** [comment]
@emrysal reminder about this PR waiting for your love!

**Comment by emrysal** [comment]
@leog DST issue was not actually due to your PR but due to recurring bookings being booked in the at the wrong time entirely. With the fixes that have gone into main now, this can be merged too 👍

**Review by sean-brydon — APPROVED** [review]
LGTM Nice job @emrysal  and @leog  

DST is always a pain in the ass - Love the UI for the tooltip too :)

**Pull request merged**
