### PR TITLE
fix: inviting a team member dosent work when he login in via Google

### LINKED ISSUE #11261: teams - inviting a member dosent work when he login in via `Google`
Found a bug? Please fill out the sections below. 👍

### Issue Summary

teams - inviting a member dosent work when he login in via `Google`,
i think the token is lost when we try to log in via google  

### Steps to Reproduce

1. Go to teams
2. click on invite team member
3. click on `copy invite link`
4. open a new tab (prefreably a new incognito tab), where you are redricted to the login page
5. instead of entering the details manually, click on `Sign in with Google`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* when it redricts back from google, the token in url is lost
* it dosen't redricts to teams page and show "you have been invited to {x} team"

### Expected Results

after sucessfully logging in should redrict to teams page
and continue with the invite team flow normally, like when you login by entering your details manually

### Evidence

[Screencast from 10-09-23 12:04:30 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/f1e2f714-9938-4ab9-8412-65aa68773910)

### PR DESCRIPTION
**Pull request by ibex088**
Fixes #11261

[Screencast from 10-09-23 12:33:58 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/d78687b9-e4a5-49b5-a349-8b64d5f2e435)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by PeerRich** [comment]
is this unrelated? thank you for the PR 

CleanShot 2023-09-11 at 13 04 11@2x

**Comment by SomayChauhan** [comment]
@PeerRich yes!! i think its unrelated

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Comment by Udit-takkar** [comment]
@SomayChauhan why did you closed this PR?

**Comment by SomayChauhan** [comment]
Opps my bad 😬

**Comment by SomayChauhan** [comment]
I was messing around, and I kinda messed up my main branch, so I removed the fork from my account and reforked it,
Now I know that would close all of my PR'S 🥹

**Pull request closed without merging**
