### PR TITLE
fix: Properly encoded metadata OpenGraph image parameters

### LINKED ISSUE #17931: [CAL-4823] metadata and og image is broken
for team events:

https://www.opengraph.xyz/url/https%3A%2F%2Fi.cal.com%2Fsales%2Fexploration%3Fmonth%3D2024-12%26date%3D2024-12-02

broken og image URL: https://cal.com/_next/image?w=1200&q=100&url=%2Fapi%2Fsocial%2Fog%2Fimage?type=meeting&title=&meetingProfileName=

image

--

for personal events:

og image for [i.cal.com/peer](http://i.cal.com/peer) since recently is broken too:

https://cal.com/_next/image?w=1200&q=100&url=%2Fapi%2Fsocial%2Fog%2Fimage?type=meeting&title=Meeting&meetingProfileName=Peer%20Richelsen&meetingImage=https%3A%2F%2Fcal.com%2Fapi%2Favatar%2Fc0e68239-b19e-4d30-b4f8-cf0b4b4cf457.png&names=Peer%20Richelsen&usernames=peer

see: 
https://www.opengraph.xyz/url/https%3A%2F%2Fi.cal.com%2Fpeer

<sub>[CAL-4823](https://linear.app/calcom/issue/CAL-4823/metadata-and-og-image-is-broken)</sub>

### PR DESCRIPTION
**Pull request by itsalam**
## What does this PR do?

In the metadata, the OpenGraph image attribute (og-image) is malformed due to its API parameters not being completely encoded, leading to an incorrect API call to the dynamic opengraph image endpoint (i.e /api/social/og/image?type=generic&title=a+title&description=a+desc)

- Properly encoded OpenGraph image parameters, fully encoding the resulting string from constructGenericImage()
- Fixes #17931
- Fixes CAL-4823

- Loom Video with fix: https://www.loom.com/share/4f89328dd04b4871bb0f91d5d4905c1c?sid=559512f8-724d-40bd-ac6b-64bb513b0714
- Loom Video without fix (notice some of the URL params are not encoded): https://www.loom.com/share/a86bdadc1c6f4e448e9824a8bd5b9180 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. Before changes, get the metadata's og-image attribute and try to access it on the browser.
2. View logs and observe API errors for the /api/social/og/image endpoint
3. Add changes in and repeat steps to see fixes

- Are there environment variables that should be set? 
  - N/A
- What are the minimal test data to have?
  - N/A
- What is expected (happy path) to have (input and output)?
  - No malformed api call to /api/social/og/image
- Any other important info that could help to test that PR
  - N/A 

/claim #17931

### CODE REVIEW

**Comment by Praashh** [comment]
Hey @itsalam thank you so much for your contribution but we already have https://github.com/calcom/cal.com/pull/17897 PR from the cal team. closing it for now 🙏 .

**Comment by itsalam** [comment]
@Praashh Just for my understanding, how does your team issue bounties? If the fix is already posted why bring in outside work?

**Comment by Praashh** [comment]
> @Praashh Just for my understanding, how does your team issue bounties? If the fix is already posted, why bring in outside work?

it wasn't for metadata but our high priority, so we solved it.

**Comment by itsalam** [comment]
Since the fix from your team is also for the metadata, I'm going to assume you meant that it's just a high-priority ticket for your team.

**Pull request closed without merging**
