### PR TITLE
fix: Troubleshooter - Vertical scrolling not working on left panel or calendar #12751

### LINKED ISSUE #12751: [CAL-2796] Troubleshooter - Vertical scrolling not working on left panel or calendar
When the left panel is higher than the viewport, you are unable to scroll.

In addition to this, there is some weird behaviour causing it to show the content from the bottom up, rather than the top down. As a result, you can't access the back button

This scenario is most likely to occur if you have more than one calendar connected, however it of course depends on the viewport height.

Also, scrolling on the right panel does not appear to be working.

[https://github.com/calcom/cal.com/assets/4536123/48485486-7dc2-47fa-8b4c-ea7e89bb2db7](https://github.com/calcom/cal.com/assets/4536123/48485486-7dc2-47fa-8b4c-ea7e89bb2db7)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2796](https://linear.app/calcom/issue/CAL-2796/troubleshooter-vertical-scrolling-not-working-on-left-panel-or)</sub>

### PR DESCRIPTION
**Pull request by AsbarK**
## What does this PR do?

I have changed the css for the calender, So it is scrollable.(i have also changed the TroubleshooterSidebar.tsx according to prettier.)

Fixes #12751

https://github.com/calcom/cal.com/assets/106991686/e942217d-68eb-436a-a425-4c59ddef2572

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

u can visit http://localhost:3000/availability/troubleshoot?eventType and u can see scrolable calender.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by sean-brydon — DISMISSED** [review]
Awesome man this fixes the issue - the only thing i can see is that in our booker the header is a bit messed up 
CleanShot 2024-02-09 at 15 44 54@2x

http://localhost:3000/pro/30min?date=2024-02-12&month=2024-02&layout=week_view

**Comment by AsbarK** [comment]
> Awesome man this fixes the issue - the only thing i can see is that in our booker the header is a bit messed up CleanShot 2024-02-09 at 15 44 54@2x
> 
> http://localhost:3000/pro/30min?date=2024-02-12&month=2024-02&layout=week_view

ohh i will try to fix this.

**Comment by AsbarK** [comment]
hey @sean-brydon, this update fixes the  booker the header


https://github.com/calcom/cal.com/assets/106991686/6627df75-f557-4db1-a5b4-6e21ca9d8ca0

**Comment by sean-brydon** [comment]
> hey @sean-brydon, this update fixes the booker the header
> 
>  Screen.Recording.2024-02-09.at.6.56.32.PM.mov

Awesome thanks for that - We've hit another weird issue where we can't actually scroll to the bottom of the booker now 🤔 

CleanShot 2024-02-10 at 14 26 30

**Comment by sean-brydon** [comment]
Thanks for the inspo - took some of your work and merged it into just changes for troubleshooter file (best approach here i think as booker wasnt broken) 

https://github.com/calcom/cal.com/pull/13631

Thanks for this @AsbarK

**Comment by AsbarK** [comment]
> Thanks for the inspo - took some of your work and merged it into just changes for troubleshooter file (best approach here i think as booker wasnt broken)
> 
> #13631
> 
> Thanks for this @AsbarK

U r Welcome @sean-brydon  has the brooker scroll fixed? in ur pr.

**Comment by sean-brydon** [comment]
> > Thanks for the inspo - took some of your work and merged it into just changes for troubleshooter file (best approach here i think as booker wasnt broken)
> > #13631
> > Thanks for this @AsbarK
> 
> U r Welcome @sean-brydon has the brooker scroll fixed? in ur pr.

Yeah booker scroll is fixed in this PR also - only changes to troubleshooter file was made. 

Thank you very much!

**Comment by keithwillcode** [comment]
Closing in favor of #13631

**Pull request closed without merging**
