### PR TITLE
test: Paid booking should be able to be canceled

### LINKED ISSUE #9369: [CAL-1883] Make E2E test: Paid booking should be able to be canceled
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1883](https://linear.app/calcom/issue/CAL-1883/make-e2e-test-paid-booking-should-be-able-to-be-canceled)</sub>

### PR DESCRIPTION
**Pull request by JaideepGuntupalli**
## What does this PR do?

Added a new `Paid booking should be able to be canceled` test.

/claim #9369
Fixes #9369

## Type of change
  - Chore (refactoring code, technical debt, workflow improvements)
  - New feature (non-breaking change which adds functionality)

## How should this be tested?

  - Are there environment variables that should be set?
     - Yes, Stripe keys

## Mandatory Tasks

  - [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by zodman** [comment]
duplicate of #10119

**Comment by JaideepGuntupalli** [comment]
> duplicate of #10119

I have made this earlier right?

**Comment by ologbonowiwi** [comment]
Yeah @JaideepGuntupalli, but I set my attempt first than you and I spent a lot of hours setting up Stripe to get this done in order to work on the implementation.

It would be nice if you check how it's going with the person that is already working on the issue, before go over someone else's effort.

**Comment by JaideepGuntupalli** [comment]
> Yeah @JaideepGuntupalli, but I set my attempt first than you and I spent a lot of hours setting up Stripe in order to get this done.
> 
> It would be nice if next time you check how it's going with the person that is already working on the issue, before go over someone else's effort.

Hey i went through the same effort when i made other prs which required Stripe, so i understand how much effort is required. Also I have already coded this part before since i was waiting for my other pr to be merged as it would have led to merge conflicts.

I know it was my mistake not mentioning that i was working on the issue. But as soon as I got to know my other pr got merged i made this. My intention was never to go over someones effort but to not make my effort go in vain.

Anyways hoping you will continue contributing to the project, i am pretty sure your effort will not go in vain.

**Comment by ologbonowiwi** [comment]
If there's no issue for you, we can split up the bounty; but I agree with you keeping it since you worked on rescheduling and it helped a lot in solving this issue (and on my understanding of this work flow also).

I'll close my PR and you can keep the bounty 😄 only ask you to be sure next time to check if there's someone else attempting an issue.

All the best for you!

**Comment by JaideepGuntupalli** [comment]
> If there's no issue for you, we can split up the bounty; but I agree with you keeping it since you worked on rescheduling, and it helped a lot in solving this issue (and on my understanding of this work flow also).
> 
> I'll close my PR and you can keep the bounty 😄 only ask you to be sure next time to check if there's someone else attempting an issue.
> 
> All the best for you!

Hey @ologbonowiwi , I was also planning to make a PR for #9370, but I am happy to help drop that and also help you out if you need any for the same. I am sorry that we got to a bad start but hopefully, we can collaborate on other PRs in the future. 

All the best for you too!

**Comment by ologbonowiwi** [comment]
I'll try to work on this one by this week, if I don't succeed on it I can step over for you to handle it.

Thank you!

**Comment by JaideepGuntupalli** [comment]
> I'll try to work on this one by this week, if I don't succeed on it I can step over for you to handle it.
> 
> Thank you!

Just a reminder to mention that on the issue too! 😅😂

**Pull request closed without merging**
