### PR TITLE
refactor: Bump LangChain to 0.1 & update other LangChain imports

### PR DESCRIPTION
**Pull request by bracesproul**
## What does this PR do?

- Bumps `langchain` to latest (0.1!)
- Adds `@langchain/core` for `DynamicStructuredTool` imports
- Adds `@langchain/openai` for `ChatOpenAI` imports

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
thank you!

**Comment by keithwillcode** [comment]
Screenshot 2024-02-13 at 11 06 29 AM

Turns out this PR broke the AI build. Any ideas @bracesproul?

**Comment by keithwillcode** [comment]
Might be a duplicate because of [this](https://github.com/calcom/cal.com/pull/13622/files#diff-75cff2f00e1815c71a63070fbe9975a42b6ec8f9831446118e177b40cca4ae36L9)? Going to try.

**Comment by keithwillcode** [comment]
Looks like it's an issue with compatability with zod version 3.22.2. No error thrown when using 3.21.4

**Comment by bracesproul** [comment]
> Looks like it's an issue with compatibility with zod version 3.22.2. No error thrown when using 3.21.4

Hmm weird, I can see if there's something we can fix on the LangChain side about this.

**Comment by keithwillcode** [comment]
@bracesproul Upgrading to zod 3.22.4 fixes it too. https://github.com/calcom/cal.com/pull/13657

**Pull request merged**
