### PR TITLE
fix: modal content blur

### LINKED ISSUE #13783: New Event modal appears blurred
### Issue Summary

The modal for creating a new event type appears blurred

### Steps to Reproduce

1. Click on event types on the dashboard
2. Click on the new button in the top right-hand corner of the screen

### Actual Results

- The modal appears blurred.

### Expected Results

- The modal should be visible while its background blurred out

### Evidence

Screenshot from 2024-02-20 12-44-34

The blurry nature of the modal might not be very visible on this screenshot.

### LINKED ISSUE #15915: New event type modal is blurry
### Issue Summary

The modal content is blurry

### Steps to Reproduce

1. open the modal that creates a new event type
2. blurry text

### Expected behavior

text is clear

### Screenshots

image

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome 126
```

### PR DESCRIPTION
**Pull request by clicktodev**
## What does this PR do?

fix blurry content in modals

- Fixes #15915
- Properly fixes #13783

it's hard to demonstrate with screenshots but it's def there.

before:
image

after:
image

video transition for clarity (compression makes the effect less noticeable):

https://github.com/user-attachments/assets/2f5eff01-4d58-4914-bfbd-135be8baee31

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by anikdhabal** [comment]
@hichemfantar can you share a loom video with both problem and fix.

**Comment by hichemfantar** [comment]
> @hichemfantar can you share a loom video with both problem and fix.

I'm afraid with video compression the change won't be noticeable at all.

**Comment by anikdhabal** [comment]
> > @hichemfantar can you share a loom video with both problem and fix.
> 
> I'm afraid with video compression the change won't be noticeable at all.

Let me test it locally. And can you explain the reason of the problem and also your changes?

**Comment by hichemfantar** [comment]
> > > @hichemfantar can you share a loom video with both problem and fix.
> > 
> > 
> > I'm afraid with video compression the change won't be noticeable at all.
> 
> Let me test it locally. And can you explain the reason of the problem and also your changes?

It only happens on Windows for me.
this [thread](animation-fill-mode) should inform you better
the changes i made fix the issue in this particular case but my fix doesn't seem to be documented so i'll report it the chromium team.

**Comment by hichemfantar** [comment]
@anikdhabal I modified [packages/platform/atoms/globals.css](https://github.com/calcom/cal.com/pull/15919/files#diff-e99e2b72272963f40c4c428af07fe153ded350355ecb4d6b91896d187516de6e) directly but let me know if it's auto generated and i'll revert the changes in this file.

**Comment by anikdhabal** [comment]
@hichemfantar Tested, and it looks good to me. I don't find any blurry effect. Closing it, but I'm expecting more PR from you

**Comment by hichemfantar** [comment]
> @hichemfantar Tested, and it looks good to me (in windows). I don't find any blurry effect. Closing it, but I'm expecting more PR from you

I added a video to the pr, take a look and you'll notice a small shift in the content which indicates the content going from blurry to clear.

**Comment by hichemfantar** [comment]
I'm not the only with this issue
check out #13783
it seems the issue isn't consistent and requires certain conditions but it happens and it's annoying enough to warrant a fix because it personally makes me squint and is very uncomfortable to look at.

**Comment by anikdhabal** [comment]
Hey @hichemfantar, let it go. The dialog looks good. Regarding the tag issue, our team members also can’t reproduce it, you can see there. The blurriness isn’t significant enough to cause discomfort. I’ve seen your videos, and the changes are too minor. We don’t need any changes for this at the moment. Thank you

**Pull request closed without merging**
