### PR TITLE
Implemented Button, hide 'Prev step' on first step

### PR DESCRIPTION
**Pull request by emrysal**
Some minor tweaks.

### CODE REVIEW

**Comment by emrysal** [comment]
Schedule selection now looks like:

image

Just display changed - values are still 00:00:00 for simplicity sake.

**Comment by emrysal** [comment]
localizedFormat is useless for now as it does not autodetect the locale. https://github.com/iamkun/dayjs/issues/1346

**Review by femyeda — APPROVED** [review]
Beautiful

**Comment by femyeda** [comment]
Also once the option for setting which time format you prefer 24 hour vs 12 hour, then the clock lib will be used to choose the format format.

**Comment by femyeda** [comment]
> localizedFormat is useless for now as it does not autodetect the locale. [iamkun/dayjs#1346](https://github.com/iamkun/dayjs/issues/1346)

I remember there being a setting for this format.

**Review by pumfleet — APPROVED** [review]

**Pull request merged**
