### PR TITLE
feat: Add fresh chat to list of support integration

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes CAL-1163

[Screencast 2023-03-01 15:51:35.webm](https://user-images.githubusercontent.com/84864519/222113092-948f14e6-b81e-4ae8-96f3-2847a5af532e.webm)

**Environment**: Staging(main branch) / Production

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by G3root** [comment]
@zomars  do the support providers env variables has to included in the `turbo.json` ?

**Comment by PeerRich** [comment]
is it possible to immediately open the chat box? I know some chat sdks have something like:

chat.openWindow() or similar

that way if you press "Chat" it immediately opens it vs just showing the floating action button only

**Comment by G3root** [comment]
> is it possible to immediately open the chat box? I know some chat sdks have something like:
> 
> chat.openWindow() or similar
> 
> that way if you press "Chat" it immediately opens it vs just showing the floating action button only

possible pushed some changes for that.

[Screencast 2023-03-01 19:06:02.webm](https://user-images.githubusercontent.com/84864519/222154577-7fb54e8f-8d08-4891-ad50-08cd093e61da.webm)

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
lets merge this but not use it yet. no need to add .env on vercel just yet.

it wont show the box if no .env is visible right?

**Pull request merged**
