### PR TITLE
Fix for #1518

### LINKED ISSUE #1518: Cannot destructure property 'client_id' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The calendso/docker automated build started failing last night after the automatic submodule update.
This is the error:

```
#13 71.59 > Build error occurred
#13 71.59 TypeError: Cannot destructure property 'client_id' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
#13 71.59     at Object.491 (/app/.next/server/chunks/9241.js:72:20)
#13 71.59     at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
#13 71.59     at /app/.next/server/pages/auth/signup.js:32:80
#13 71.59     at Function.__webpack_require__.a (/app/.next/server/webpack-runtime.js:98:13)
#13 71.59     at Object.8444 (/app/.next/server/pages/auth/signup.js:11:21)
#13 71.59     at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
#13 71.59     at __webpack_exec__ (/app/.next/server/pages/auth/signup.js:626:39)
#13 71.59     at /app/.next/server/pages/auth/signup.js:627:141
#13 71.59     at Function.__webpack_require__.X (/app/.next/server/webpack-runtime.js:182:21)
#13 71.59     at /app/.next/server/pages/auth/signup.js:627:47 {
#13 71.59   type: 'TypeError'
#13 71.59 }
```

It looks like there were several changes related to authentication, so perhaps a type issue was introduced?

linking with https://github.com/calendso/docker/issues/72

### Steps to Reproduce

Repo admins can find the run logs here:
https://github.com/calendso/docker/runs/4822358078?check_suite_focus=true

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
- Node.js version
- Anything else that you think could be an issue.

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Fixes #1518 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Try building app with `GOOGLE_API_CREDENTIALS` undefined.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by deepakprabhakara — APPROVED** [review]
LGTM, this was the one we were discussing yesterday but thought it was related to Github Actions and external PRs.

**Review by PeerRich — APPROVED** [review]

**Comment by searsaw** [comment]
Thoughts on why this wasn't automerged? I believe this would fix an issue with the Docker build as well.

**Comment by PeerRich** [comment]
> Thoughts on why this wasn't automerged? I believe this would fix an issue with the Docker build as well.

yeah it seems like this issue https://github.com/calendso/calendso/issues/1527 is blocking some automerges. Will force-merge now!

**Comment by krumware** [comment]
This fixed the docker build. Thanks!

**Pull request merged**
