### PR TITLE
fix: Update slug for zoom app

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Updates the slug as it is supposed to be
From `zoomvideo` -> `zoom`

## Requirement/Documentation

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by PeerRich — DISMISSED** [review]
this will cause sideeffects.

**Comment by Udit-takkar** [comment]
@PeerRich i think we should wait for @joeauyeung's reply before we close this.

refreshOAuthTokens requires appSlug in the second parameter which should have been "zoom" not "zoomvideo" which is the name of directory but not the appSlug

**Comment by joeauyeung** [comment]
@Udit-takkar is right. This should be the app slug. I think we can improve on this PR by instead of hard coding "zoom" we can use the `app.slug` directly.

@PeerRich there won't be any side effects in our app. The app slug is being passed into `refreshOAuthToken` which only uses the slug when a self-hoster wants to sync app credentials.

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
> I think we can improve on this PR by instead of hard coding "zoom" we can use the app.slug directly.

lets do a follow up PR

**Pull request merged**
