### PR TITLE
Remove custom select implementation

### PR DESCRIPTION
**Pull request by sean-brydon**
No Longer needed as react select shipped unstyled

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
oddly merge conflicted

**Comment by hariombalhara** [comment]
@sean-brydon There are conflicts

**Review by hariombalhara — CHANGES_REQUESTED** [review]
There are merge conflicts that need resolution.
Requesting changes so that it goes away from the PR review list

**Comment by PeerRich** [comment]
friendly ping @sean-brydon

**Review by hariombalhara — APPROVED** [review]
It's just removing files. Relying on typescript for this.

**Pull request merged**
