### PR TITLE
fix: Use org logo for organization's teams

### LINKED ISSUE #12956: [CAL-2844] organisation subteams should have org logo
for organisations we've removed logos for subteams, however we still show them in the main view

we should show the org logo instead for organsations (normal teams should still show the team logo)

before:

CleanShot 2023-12-28 at 13 01 20@2x

after:

CleanShot 2023-12-28 at 13 02 49@2x

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2844](https://linear.app/calcom/issue/CAL-2844/organisation-subteams-should-have-org-logo)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #12956 #12957

## When organization has no logo uploaded
Non-Org teams still show their logo but org sub-teams now show the logo of the org.
image

Create Event Type Dropdown
image

Teams listing
image

New Webhook dropdown
image

Engineering Team Booking Page -  Engineering Team is a team inside Org1
image

## When organization has logo uploaded.
Non-Org teams still show their logo but org sub-teams now show the logo of the org.
image

Create Event Type Dropdown
image

Teams listing
image

New Webhook dropdown
image

Engineering Team Booking Page - Engineering Team is a team inside Org1
image

Seeded Team booking Page
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
See the screenshots

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #12961** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12961?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12961?utm_source=stack-comment).

**Review by PeerRich — DISMISSED** [review]
about to be deprecated according to @emrysal

**Comment by sean-brydon** [comment]
I think https://github.com/calcom/cal.com/pull/12716 Should do this and it is also a bit cleaner. I need to fix e2e tests when i get a chance but i think this is a better approach? 

Let me know if there is something i am missing here

**Comment by hariombalhara** [comment]
@sean-brydon your PR is certainly cleaning things up and would be happy to merge it but I don't think it's fixing the bugs(didn't test though). 

I can clearly see that there are no changes in event-types/index.tsx and TeamListItem.tsx in that PR

**Comment by sean-brydon** [comment]
> @sean-brydon your PR is certainly cleaning things up and would be happy to merge it but I don't think it's fixing the bugs(didn't test though).
> 
> I can clearly see that there are no changes in event-types/index.tsx and TeamListItem.tsx in that PR

Yeah youre right - that PR did not fix any bugs just cleaned up the approach to handle the orgLogo. Would you be up for migrating this PR over to that approach? It does require fetching more info for the orgs other than just the organizationID - but i think we should have that in session. 

Just ping me if you want me to take this over instead

**Comment by keithwillcode** [comment]
@sean-brydon @hariombalhara should we close this one?

**Comment by hariombalhara** [comment]
Yeah I think someone fixed it already.

**Pull request closed without merging**
