### PR TITLE
chore: add inlang ide extension for i18n

### PR DESCRIPTION
**Pull request by samuelstroschein**
## What does this PR do?

Adds the ide extension from https://github.com/inlang/inlang to the repo as requested by @PeerRich.  

The ide extension shows translations directly in source code with fast extraction of messages and more. 

CleanShot 2023-06-17 at 17 19 01@2x

## Changes 

- create the `inlang.config.js` file
- add the ide extension to the workspace recommendations
- formatted the English resource file (I assume someone edited the file directly on GitHub)

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

### CODE REVIEW

**Comment by samuelstroschein** [comment]
@PeerRich Do you want the inlang CLI too?

- I ran the inlang CLI on the repo with `inlang lint`. Cal.com has many missing translations. 
- You could embed `inlang lint` in your regular lint CI/CD to avoid pushing to production with missing translations
- You could also run `inlang machine translate` in CI/CD to avoid having missing translations at all at the risk of lower quality translations

CleanShot 2023-06-17 at 17 28 04@2x

**Review by PeerRich — APPROVED** [review]
interesting! worth trying 🙏

**Comment by PeerRich** [comment]
>I ran the inlang CLI on the repo with inlang lint. Cal.com has many missing translations.
> You could embed inlang lint in your regular lint CI/CD to avoid pushing to production with missing translations
> You could also run inlang machine translate in CI/CD to avoid having missing translations at all at the risk of lower quality translations

this looks dope! whats your thoughts @keithwillcode @zomars or @emrysal ?

**Comment by PeerRich** [comment]
the CLI in a separate PR tho

**Comment by samuelstroschein** [comment]
> the CLI in a separate PR tho 

Will add the CLI in a separate PR after this one is merged. 

FYI it's only adding the `@inlang/cli` to some package.json and changing an NPM scripts to include the commands you want like `... other lint commands && npx inlang lint`.

**Comment by emrysal** [comment]
IMO leave out inlang CI - that's tooling that's not needed not even under --dev, but we could check it out and recommend it in certain situations. The extension itself looks worth it tho

**Comment by samuelstroschein** [comment]
@emrysal Regardless of cal.com adding the CLI: What made you determine that the CLI/CI is not needed?

**Comment by zomars** [comment]
This is definitively an improvement to developer experience. Nice job!

> * You could also run `inlang machine translate` in CI/CD to avoid having missing translations at all at the risk of lower quality translations

About this, I don't think we want to block for every single language to be up to date as we depend on external contributors for this.

**Review by zomars — APPROVED** [review]

**Comment by felixhaeberle** [comment]
@PeerRich would you also like to see inlang GitHub Actions?

Providing you with current CLI functionality (lints, machine translate, *more soon*) but at the convenience of a GitHub Action? 

- simple to integrate, just a few lines. 
- lints your translations, fits perfectly in your [lint workflow](https://github.com/calcom/cal.com/blob/main/.github/workflows/lint.yml).
- can automatically create (or comment in) PR's when something broke & auto-fix?

We would build it for you if you simply say "Yes" :)

**Pull request merged**
