### PR TITLE
fixes available times overflow bug on safari

### LINKED ISSUE #6201: Too big extra space between timeslots on mobile safari
### Issue Summary

Sometimes I get extra space between time slots on my iPhone Safari. It happens in 50% cases. Also I could reproduce this behaviour on desktop safari with <500px width (when cal.com goes to vertical layout). It works fine on Google Chrome.

### Steps to Reproduce

1. go to  https://cal.com/anyusername/anymeetingname on mobile safari
2. chose any date 
3. see extra space between time slots. 

Also I found way to reproduce this bug on desktop Safari. 
https://share.cleanshot.com/G4hpzGKWVYJjLfW89Mhg
1. set Safari width to minimal
2. open https://cal.com/anyusername/anymeetingname
3. sometime time slots will be normal, but sometimes not. 
4. If it ok then refresh page 1 or 2 times
5. expand Safari to full screen → time slots goes to side panel 
6. set minimal width on Safari again
7. time slots will be normal

### Technical details

- iPhone 11, ios 16.2
- https://share.cleanshot.com/DJJLbLHyM8PF2TSWZ7FP
- macOS 13.0.1 (22A400)
- Safari on macOS Version 16.1 (18614.2.9.1.12)

### PR DESCRIPTION
**Pull request by phishy**
## What does this PR do?

Fixes overflow bug on Safari, where there was too much space between available times.

Fixes #6201 

**Environment**: Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

* Make an event type with a duration of 90 minutes
* Load in mobile Safari or desktop safari in really small window
* Notice that the space between available times is back to normal

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Udit-takkar — DISMISSED** [review]
Screenshot 2023-01-02 at 9 02 45 PM

Although this solves the spacing issue but size of last slot is vary small in mobile version
and in desktop version there is no scrollbar so i can't see all slots

**Comment by phishy** [comment]
@Udit-takkar and now?

**Comment by PeerRich** [comment]
tested, seems to work. waiting for @Udit-takkar's re-review

**Review by Udit-takkar — APPROVED** [review]
🙏 It works fine now. just one thing grid-cols-1 and gap-x-2 aren't necessary now as you have removed grid.

**Comment by phishy** [comment]
> 🙏 It works fine now. just one thing grid-cols-1 and gap-x-2 aren't necessary now as you have removed grid.

Ah yeah. I thought I had removed `grid-cols-1`. Nice catch on `gap-x-2`. I'll push it now.

**Pull request merged**
