### PR TITLE
feat: Lock timezone on booking page

### LINKED ISSUE #11873: Lock timezone on booking page
For an in-person event type, it may be useful to lock the timezone on the booking page, as attendees could be coming from different timezones.

We should add a toggle 'Lock timezone' to the advanced event type settings.

### PR DESCRIPTION
**Pull request by siddharth-movaliya**
## What does this PR do?

For an in-person event type, locks the timezone on the booking page, as attendees could be coming from different timezones.

Fixes #11873 

https://github.com/calcom/cal.com/assets/94699055/e9929118-9d33-4074-9305-1b3ce7ed4748

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

Create an event-type that and set location to `In Person` (attendee or organiser). Go to the booking page for that event. Try to click on Timezone.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
The toggle was meant to be in the advanced event-type settings. We shouldn't always lock it for in-person events, only when toggled in the settings.

**Comment by Siddharth-2382** [comment]
Okay. Will make the changes and commit it to this PR for your review.

**Comment by Siddharth-2382** [comment]
@CarinaWolli can you help me with this error? I don't fully understand how form handling is done here. All what I have done is created a new controller in the advanced event-type component and given it a new controller called `lockTimeZoneToggleOnBookingPage` as it is done with other controller components.

https://github.com/calcom/cal.com/assets/94699055/14932e4f-4663-43a2-a4ce-d42fa1aca737

**Comment by Siddharth-2382** [comment]
> The toggle was meant to be in the advanced event-type settings. We shouldn't always lock it for in-person events, only when toggled in the settings.

Done :). Can review these changes. Here's a how it is now:

https://github.com/calcom/cal.com/assets/94699055/52c77de5-66ed-4260-9e68-d9d402b2979d

**Review by CarinaWolli — DISMISSED** [review]
Great work, thank you for your contribution 🙏

I made some small UI adjustments, but everything else looked good 👍

**Comment by Siddharth-2382** [comment]
@hariombalhara Is the unit test failing due to my changes? I don't know much about it so if there is anything to fix it can you tell me where to do it. Thanks!

**Review by CarinaWolli — APPROVED** [review]
Tests pass now 👍

**Pull request merged**
