### PR TITLE
perf: removed page_view tracker

### LINKED ISSUE #8266: [CAL-1495] remove "page_view" tracking
reduce calls to telemetry

<sub>[CAL-1495](https://linear.app/calcom/issue/CAL-1495/remove-page-view-tracking)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
reduce invocations

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
LGTM

**Review by zomars — CHANGES_REQUESTED** [review]
Are we planning to re-add them later? If not, then let's remove the code altogether.

What's the reason for this change? Let's just put it on the description for historical purposes.

**Comment by PeerRich** [comment]
> Are we planning to re-add them later? If not, then let's remove the code altogether.
> 
> What's the reason for this change? Let's just put it on the description for historical purposes.

potentially planning to read later. this is for testing purposes

@keithwillcode and @emrysal have context -- was peer programming with them

**Review by zomars — APPROVED** [review]
Let's shipit then

**Pull request merged**
