### PR TITLE
WIP: Moved linting to pre-push to speed up commits

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by zomars** [comment]
This is getting harder than expected. TODO:

- [We cannot easily run tsc for the changes files only](https://github.com/microsoft/TypeScript/issues/27379).
- Eslint doesn't catch type errors in this context
- Can't get to work reliably

**Comment by PeerRich** [comment]
good idea. i think someone asked for this before

**Comment by PeerRich** [comment]
> This is getting harder than expected. TODO:
> 
> * [We cannot easily run tsc for the changes files only](https://github.com/microsoft/TypeScript/issues/27379).
> * Eslint doesn't catch type errors in this context
> * Can't get to work reliably

ok lets keep on commit in that case

**Comment by PeerRich** [comment]
closing for now due to being too hard to do and on commit is not tooo bad

**Pull request closed without merging**
