### PR TITLE
chore: Sync packages mismatches

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

- Syncs mismatched module versions between packages
- Adds missing packages in various packages
- Fixes linting and formatting issues where previously were not erroring
- Fixes type checks that were not being checked

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] yarn
- [ ] yarn build
- [ ] yarn e2e

## Mandatory Tasks
- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by alannnc — APPROVED** [review]
Everything looks good!

**Review by emrysal — APPROVED** [review]
good to go

**Comment by Hybes** [comment]
@zomars getting build errors with @calcom/web:build now:
`@calcom/web:build: cache miss, executing 3fc343117f0b393c
@calcom/web:build: Duplicate value found in:  org_upgrade_banner_action
@calcom/web:build: Duplicate value found in:  all
@calcom/web:build: Duplicate value found in:  layout
@calcom/web:build: Duplicate value found in:  count_members_one
@calcom/web:build: Duplicate value found in:  count_members_other
@calcom/web:build: Duplicate value found in:  learn_more
@calcom/web:build: Duplicate value found in:  get_in_touch
@calcom/web:build: Duplicate value found in:  organization_url_taken
@calcom/web:build: Duplicate value found in:  org_name
@calcom/web:build: Duplicate value found in:  org_url
@calcom/web:build: Enabling New Booker for Non-Embed
@calcom/web:build: - info Linting and checking validity of types...
@calcom/web:build: 
@calcom/web:build: Failed to compile.
@calcom/web:build: 
@calcom/web:build: ./pages/api/email.ts
@calcom/web:build: 11:9  Warning: 'evt' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./pages/booking/[uid].tsx
@calcom/web:build: 683:33  Warning: 'target' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./pages/event-types/[type]/index.tsx
@calcom/web:build: 340:7  Warning: 'bookerLayouts' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
@calcom/web:build: 371:13  Warning: 'availability' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
@calcom/web:build: 453:21  Warning: 'availability' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./pages/event-types/index.tsx
@calcom/web:build: 731:40  Error: Replace `me-2·ms-2·relative·-top-px` with `relative·-top-px·me-2·ms-2`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: ./pages/settings/my-account/appearance.tsx
@calcom/web:build: 58:47  Warning: 'hasPaidPlan' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./components/team/screens/Team.tsx
@calcom/web:build: 33:29  Error: Replace `line-clamp-4·mt-2` with `mt-2·line-clamp-4`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
@calcom/web:build: ERROR: command finished with error: command (/Users/admin/Documents/calcom/apps/web) yarn run build exited (1)
command (/Users/admin/Documents/calcom/apps/web) yarn run build exited (1)

 Tasks:    5 successful, 6 total
Cached:    0 cached, 6 total
  Time:    40.701s 
Failed:    @calcom/web#build`

**Comment by Hybes** [comment]
also realised, it's wrong about the tailwind order anyway?

**Pull request merged**
