### PR TITLE
feat: Add min max chars for long text

### LINKED ISSUE #15577: [CAL-3973] booking questions for long text: add min and max characters (both optionally)
CleanShot 2024-06-26 at 12 25 44@2x

validate: 

CleanShot 2024-06-26 at 12 29 59@2x

<sub>[CAL-3973](https://linear.app/calcom/issue/CAL-3973/booking-questions-for-long-text-add-min-and-max-characters-both)</sub>

### PR DESCRIPTION
**Pull request by rajesh-jonnalagadda**
/claim #15577 
## What does this PR do?
 adds an optional min and max character limit to long text questions in the booking form.

- Fixes #15577 
- Fixes CAL-15577 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Loom Video: 
https://www.loom.com/share/9cf492626bf044b1a753576ed7d76156

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by rajeshj11** [comment]
@hariombalhara please review. I have added test cases

**Comment by rajeshj11** [comment]
@anikdhabal  I think the remaining checks need approval from the internal team.

**Comment by anikdhabal** [comment]
Hey, as you can see this pr https://github.com/calcom/cal.com/pull/15592 is under review with a good amount of feedback provided. The contributor has addressed some of them, but I've noticed that the contributor is unable to proceed further. And someone wants to collaborate with him and complete the task. So, let's @hariombalhara decide which one he considers.

**Comment by rajeshj11** [comment]
> Hey, as you can see this pr https://github.com/calcom/cal.com/pull/15592 is under review with a good amount of feedback provided. The contributor has addressed some of them, but I've noticed that the contributor is unable to proceed further. And someone wants to collaborate with him and complete the task. So, let's @hariombalhara decide which one he considers.

Previously, my pr changes were closed due to active dev changes. Now, as he is not active. Thought I could fix those issues and raised the pr. No issues, let  @hariombalhara  decide.

**Comment by rajeshj11** [comment]
> > Hey, as you can see this pr #15592 is under review with a good amount of feedback provided. The contributor has addressed some of them, but I've noticed that the contributor is unable to proceed further. And someone wants to collaborate with him and complete the task. So, let's @hariombalhara decide which one he considers.
> 
> Previously, my pr changes were closed due to active dev changes. Now, as he is not active. Thought I could fix those issues and raised the pr. No issues, let @hariombalhara decide.

@hariombalhara ^^

**Comment by hariombalhara** [comment]
@rajeshj11 I would really want that PR to be continued. If you like you can fork from that branch and do fixes as suggested in [that PR.](https://github.com/calcom/cal.com/pull/15592)

**Pull request closed without merging**
