### PR TITLE
Removes e2e retries and videos

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

- Retries aren't being useful in our context and are just delaying tests
- Also since we can use traces to debug, we don't need to save videos anymore.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
Agree, never looked at them. Retries may make sense though

**Comment by zomars** [comment]
> Agree, never looked at them. Retries may make sense though

Many of these tests aren't designed to be "retry-able". For example the Stripe one always expects for the integration to be disconnected. So if it connects on the first try and the paid booking fail, it will retry and since it's already connected it will time out. We can decide later if we should address that or just disable retries for now.

**Comment by emrysal** [comment]
I think with the recent fail on #1488 - retries weren't run, that was definitely a temporary problem and the reason @KATT put the retry there in the first place is to fix those "Yeah, playwright is just weird, sometimes" cases.

**Comment by zomars** [comment]
Let's hope playwright isn't that weird anymore

**Pull request merged**
