### PR TITLE
The Dotenv Refactor

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Adds a `.env` linter (yes, a linter). With the recent launch of the App Store and the upcoming apps, it will be increasingly difficult to manage and keep env variables in order. This PR installs a nifty tool that will compare your root `.env` file with the one provided in the `.example` and will warn/update your local file whenever you run a `dev` script.

It's like migrations for env files

image

Also this PR removes duplicated env variables and unifies confusing variables like `BASE_URL`. The main replacements are as the following:

- `NEXT_PUBLIC_WEBAPP_URL`  is replacing: `BASE_URL`, `NEXT_PUBLIC_BASE_URL` and `NEXT_PUBLIC_APP_BASE_URL `
- `NEXT_PUBLIC_WEBSITE_URL`  is replacing: `BASE_URL` (from apps/website context) and `NEXT_PUBLIC_WEBSITE_BASE_URL `

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Run `yarn dev`,  `yarn dx`

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
great job

**Comment by zomars** [comment]
It also let's you know when variables are removed neat! 
image

**Review by alannnc — APPROVED** [review]
I just run it and it modified my env, so if I had anything on it will it be overwritten? Instead of overwriting can we just save a new one with a different name or save current as .env.backup
What should happen with my /apps/web/.env file?

**Comment by zomars** [comment]
> I just run it and it modified my env, so if I had anything on it will it be overwritten? Instead of overwriting can we just save a new one with a different name or save current as .env.backup

It doesn't overwrite any values that you already set. It just rearranges them.

> What should happen with my /apps/web/.env file?

It should be gone.

**Comment by denik1981** [comment]
Nice!

**Pull request merged**
