### PR TITLE
fix: google calendar event not deleted on updating the default calendar for a cal.com event

### LINKED ISSUE #13902: [CAL-3425] desination calendar of old bookings changes when default calendar of event is updated
When the default calendar of an event is changed the destination calendar of all previous bookings changes as well. So when canceling the event, the calendar event is not deleted

Discussed here: https://github.com/calcom/cal.com/issues/13827
> each booking have a destination calendar that should be not change on changing event's default calendar.
[Loom](https://www.loom.com/share/63412c140f33466ba2478e4cce0b3e7c?sid=5e7170d2-6093-4b05-b1b9-d871fa67ac78)

<sub>[CAL-3425](https://linear.app/calcom/issue/CAL-3425/desination-calendar-of-old-bookings-changes-when-default-calendar-of)</sub>

### PR DESCRIPTION
**Pull request by Shaik-Sirajuddin**
## What does this PR do?

- Fixes  #13902
- Fixes CAL-3425 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

-Update default calendar to google calendar for an event ( account A )
-create a booking with alternative account ( account B ) 
-update default calendar of event to a different calendar  ( account A ) 
( google calendar supports multiple calendar instances , a second instance can be used for update)
-cancel booking
-verify the event is deleted in google calendar ( initial calendar linked to account A ) ,
the event remains undeleted before fix.

### CODE REVIEW

**Review by Amit91848 — COMMENTED** [review]
Cannot reproduce the issue. Am I doing it right @Shaik-Sirajuddin? Can you also please record a before / after loom for clarity 🙏


https://github.com/calcom/cal.com/assets/74371312/a9d66df3-8ccf-4a3d-ac61-99b3da5049a5

**Comment by anikdhabal** [comment]
Hey @Shaik-Sirajuddin, I'm closing it for now. Feel free to address the review given by @Amit91848 and reopen it.

**Comment by Shaik-Sirajuddin** [comment]
> Cannot reproduce the issue. Am I doing it right @Shaik-Sirajuddin? Can you also please record a before / after loom for clarity 🙏
> Recording.2024-06-29.195347.mp4

Testing process loom : [video](https://www.loom.com/share/a138e0b4d8cc4acda40f7ba8a10f0509?sid=3e021ddb-3430-4968-848b-5e6d8e4fe848)

**Comment by Shaik-Sirajuddin** [comment]
@anikdhabal Could you reopen the PR , I don't seem to have access for reopening PR

**Comment by Shaik-Sirajuddin** [comment]
> Cannot reproduce the issue. Am I doing it right @Shaik-Sirajuddin? Can you also please record a before / after loom for clarity 🙏
> 
>  Recording.2024-06-29.195347.mp4

Google calendar allows to create multiple calendar instances
The default instance is linked to email

You can try creating a new instance and setting it to event type before scheduling a booking

After Scheduling booking , please try updating the events Calendar to alternative instance , Before cancelling booking

**Comment by anikdhabal** [comment]
@Shaik-Sirajuddin Reopen it and pls provide a fix video

**Review by Amit91848 — APPROVED** [review]
LGTM! Thanks @Shaik-Sirajuddin

**Comment by keithwillcode** [comment]
@joeauyeung @emrysal Can you please review this before we merge 🙏

**Comment by emrysal** [comment]
@keithwillcode I think this is good to merge, the externalCalendarId is meaningless outside of the context of the currently authenticated google calendar so the extra check we do to ensure it is contained within the destination calendar is a bit redundant. It does cause the issue when the destination calendar changes that the reference is no longer found - tried against the "primary" which is wrong.

**Comment by keithwillcode** [comment]
@Shaik-Sirajuddin E2E tests are consistently failing on this. Can you please take a look?

**Pull request merged**
