### PR TITLE
fix: Currency Not Reflecting Correctly #13845

### LINKED ISSUE #13845: [CAL-3223] Currency Not Reflecting Correctly
A severe bug has occurred where amounts set in Japanese Yen are being settled in dollars during actual transactions. As a result, customers have been charged 100 times the intended amount. The UI consistently displays the amount in Japanese Yen right up to the final stage, so customers only realize the massive overcharge when it is already too late.

For the time being, I have paused the settlement calendar, hoping that this issue will be resolved.

## Stripe Settings

スクリーンショット 2024-02-24 10 26 57

## Payment UI

At this point, the amount is still correct in Japanese Yen.

スクリーンショット 2024-02-24 10 25 03

## Stripe Dashboard

In reality, an amount 100 times greater is being charged by Stripe.🥶

スクリーンショット 2024-02-24 10 20 33

---

Thank you for your support!

<sub>[CAL-3223](https://linear.app/calcom/issue/CAL-3223/currency-not-reflecting-correctly)</sub>

### PR DESCRIPTION
**Pull request by Pritam-sd-dev**
## What does this PR do?

Fixes #13845 

Before 
as mentioned in the issue.

After
https://www.loom.com/share/5ea4fa237e10453da42007aef8919ef0?sid=be6495b3-5520-4ac2-9728-63802b649238

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
To test changes in this PR, make a paid event with currency JPY and try to book a time slot and see if amount is getting 100x or not. 

## Checklist

- I haven't checked if my changes generate no new warnings
- I haven't checked if existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Pritam-sd-dev** [comment]
code is working fine but I think code is not organized.
functions which are used at multiple places should be in some utils file or something like that.

**Review by Udit-takkar — COMMENTED** [review]
@Pritam-sd-dev ~the changes look fine but i am not able to test it. I am getting this error~

Screenshot 2024-02-28 at 4 54 58 PM

**Review by Udit-takkar — APPROVED** [review]

**Comment by Pritam-sd-dev** [comment]
@Udit-takkar 
just go to your stripe account and see the transaction section you will find in faild section

**Comment by Udit-takkar** [comment]
@Pritam-sd-dev could you also add test for these changes ?

**Comment by Pritam-sd-dev** [comment]
> @Pritam-sd-dev could you also add test for these changes ?

sure, i will add tests and will open another PR.

**Pull request merged**
