### PR TITLE
fix: webhooks container under event settings overflowing

### PR DESCRIPTION
**Pull request by Chiranjeev-droid**
## What does this PR do?
---
When we go to edit the settings of an event and we want to see webhooks , now try adding an big webhook url, lets say of airtable and then the whole container will overflow.This pr fixes this odd behaviour.

## Before making changes
 Loom Video: https://www.loom.com/share/f6102f29d5c1479b93a00c1024c8c56e?sid=c101c131-0435-46c9-842e-1fda13eb4fb4

## After making changes

Loom Video: https://www.loom.com/share/253510cf9fa14c339cea38e3a7519990?sid=8c8b7243-4783-468d-94fe-14f21938bcbe

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Go to settings of already created event
- Go to webhooks tab of the event.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@Chiranjeev-droid I can't reproduce the bug. this is what i see without your changes

Screenshot 2023-10-13 at 3 02 18 PM

**Comment by Chiranjeev-droid** [comment]
On safari also it is showing me the same thing , @Udit-takkar can you try with this url . The below url is a vailid url which airtable provides . The problem i guess occur when you enter a big url.
https://hooks.airtable.com/workflows/v1/genericWebhook/appgZkdpepUXb4YLz/wflc4kfxyeriCuTp8/wtrgvnOivYzXBKswW

Screenshot 2023-10-13 at 4 38 54 PM

---

Also from my localhost after pulling latest changes from main branch 
image

**Comment by sean-brydon** [comment]
CleanShot 2023-10-13 at 12 29 07@2x
Able to replicate with that URL - thanks for the fix. 

Your branch seems to fix it <3

**Review by sean-brydon — APPROVED** [review]

**Comment by PeerRich** [comment]
image
this has caused a regression

**Comment by Chiranjeev-droid** [comment]
Can you elaborate a little more on what is the issue because i am not able to reproduce. Also  i tried reverting the change i made and dont see any difference.

**Pull request merged**
