### PR TITLE
fix: Link Meeting value hidden from user on payment page

### LINKED ISSUE #8059: [CAL-1393] Link Meeting value shown to user on payment page.
Location Link Value shown for Paid Event event(on payment/[uid] page) if 'Display on booking page' is not checked
Screenshot 2023-04-03 at 5 02 41 PM

Screenshot 2023-04-03 at 5 01 36 PM

It works correctly for other pages.
Screenshot 2023-04-03 at 5 00 58 PM

<sub>[CAL-1393](https://linear.app/calcom/issue/CAL-1393/link-meeting-value-shown-to-user-on-payment-page)</sub>

### PR DESCRIPTION
**Pull request by JaideepGuntupalli**
## What does this PR do?

Fixed where link meeting value was visible on the payment page.

Previously:
c9057f6934fc20878ae1a0ebb3f07bcb

Now:
a283eff8fd34e5fa395728cbfa1bb716

The changes didn't break other meetings methods or events containing multiple meetings:
15df93018cd7a632fc999b7137c4e001

### How did I accomplish this?
I made changes to `packages/features/ee/payments/pages/payment.tsx` file where I have added logic to check if eventType.locations array has type link and the link is equal to booking.location and has displayLocationPublicly, replace booking.location with null. This was added in the `getServerSideProps` function.

Fixes #8059

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Make a paid event with Link Meeting; try booking it with the display booking link to the user setting turned off.
- Make a paid event with Link Meeting; try booking it with the display booking link to the user setting turned on.

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by JaideepGuntupalli** [comment]
@Udit-takkar can pls review this pr

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
@JaideepGuntupalli when i select display on booking page option. i don't actually see the location "where" in payment/[uid].

**Comment by JaideepGuntupalli** [comment]
@Udit-takkar Yup i have hidden it, if the organiser enabled the option. Shall i instead show it as "Link Meeting"?

**Comment by JaideepGuntupalli** [comment]
> @Udit-takkar Yup i have hidden it, if the organiser enabled the option. Shall i instead show it as "Link Meeting"?

hey @Udit-takkar can you pls confirm this, i will make the necessary changes required.

**Review by joeauyeung — COMMENTED** [review]
Hi @JaideepGuntupalli, thanks for your contribution.

Have you considered reusing the location that's displayed on the booking page? It would probably be easier to reuse the logic that's found on `apps/web/pages/booking/[uid].tsx` line 290.

**Pull request closed without merging**
