### PR TITLE
feat: Salesforce choose how to save attendees & other options

### LINKED ISSUE #16984: [CAL-4476] Extend salesforce for contacts, leads or accounts
null

<sub>[CAL-4476](https://linear.app/calcom/issue/CAL-4476/extend-salesforce-for-counts-leads-or-accounts)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

- Allows users to choose whether to create events or new leads, contacts, or contacts under accounts
- If contacts under accounts is selected displays the following options
	- Give the ability to create new contacts under the account if there are other contacts that match the email domain
	- Creates a new lead if the account is not found

image

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

https://www.loom.com/share/b6cdf0bb4d72493184acc3cb3e5d7602

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Connect a Salesforce account
- Test the three options to create events on contacts, leads, and contacts under leads
	- An event should be created under those record types
- Enable the option to create contacts under leads but don't select any of the options
- Create a booking with an email where the contact doesn't exist
	- Nothing should be created in Salesforce
- In Salesforce create an account with contacts that share the same email domain
- Enable create new contacts under an account
- Create a booking with an email that shares the same domain as the previously created contacts but does not exist
	- A new contact should be created from that email under the account
- Enable creating new leads option
- Create a booking with an email domain that does not exist as other contacts
	- A new lead should be created

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Review by CarinaWolli — COMMENTED** [review]
tested 'Lead' and 'Contact' and works 👍 Not sure how to test 'Contact under an account'

One small thing I noticed: When I have it set to add a 'Lead' and the user already exists as a contact it doesn't create the lead (same the other way around). Not sure if that's intended

**Comment by joeauyeung** [comment]
> tested 'Lead' and 'Contact' and works 👍 Not sure how to test 'Contact under an account'
> 
> One small thing I noticed: When I have it set to add a 'Lead' and the user already exists as a contact it doesn't create the lead (same the other way around). Not sure if that's intended

Thanks for the review @CarinaWolli. 

You can't have duplicate emails of leads and contacts so nothing happening is expected.

To test "Contact under an account", you can create an account and add contacts that share the same email domain. Then create a booking with an attendee email that shares the same email domain as the other contacts under the account but doesn't already exist.

**Review by CarinaWolli — APPROVED** [review]
Nice work, changes look good 👍

**Review by joeauyeung — COMMENTED** [review]
I forgot to publish my self-review comments

**Pull request merged**
