### PR TITLE
chore: E2E tests for org redirection=true param

### LINKED ISSUE #14516: [CAL-3395] E2E tests for orgRedirection=true param
For the PR [https://github.com/calcom/cal.com/pull/14337](https://github.com/calcom/cal.com/pull/14337), we need to add a few e2e tests to verify atleast the following. 

* Team Profile works on unpublished organization
  * Browsing to an event also works from there
* Team Event works on unpublished organization
  * It is bookable
* Same for User Event and User Profile
* Same for Private Link

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3395](https://linear.app/calcom/issue/CAL-3395/e2e-tests-for-orgredirection=true-param)</sub>

### PR DESCRIPTION
**Pull request by balthazur**
## What does this PR do?

This PR adds E2E tests for orgRedirection="true" param, that makes profiles and event booking work on unpublished organizations.

The following 6 scenarios are tested:

1. Team Profile & Event
a. Cannot see team profile by default
b. Can see team profile and book event with orgRedirection=true query param

2. User Profile & Event
a. Cannot see user profile by default
b. Can see user profile and book event with orgRedirection=true query param

3. Private URL
a. Cannot see event by default
b. Can see page and book event with orgRedirection=true query param

During the implemention, I discovered 2 two potential bugs. So the following two tests are expected to fail until the bugs are fixed on main.
- Hydration error for team profile page when event type renders an Avatar. Makes test case _1.b._ fail (Team event booking). 
(Issue: #15305) 
(PR with fix: #15306)

- orgRedirection="true" does nothing for private URL. Makes test case _3.b._ fail (Private URL Booking).
(Issue: #15311) 
(PR with fix: #15312)

Additionally, the following changes were made to existing code:

- The function `getOrgOrigin ` was moved from booking.e2e.ts to testUtils.ts to reuse it in the new test file as well.
- `createTeamAndAddUsers` from `/fixtures/users.ts` was extended by `orgRequestedSlug?: string;` so it is possible to reuse the existing function but be able to optionally add a specific requested slug instead of generated one.

---

- Fixes #14516 
- Fixes CAL-3395

/claim #14516

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

Run `yarn playwright test organization-redirection.e2e.ts`

env.ts
```
LOCAL_TESTING_DOMAIN_VERCEL="cal.local:3000"
NEXT_PUBLIC_ORG_SELF_SERVE_ENABLED="1"
NEXT_PUBLIC_WEBAPP_URL='http://app.cal.local:3000'
# Change to 'http://localhost:3001' if running the website simultaneously
NEXT_PUBLIC_WEBSITE_URL='http://app.cal.local:3000'
NEXTAUTH_URL='http://app.cal.local:3000'
ORGANIZATIONS_ENABLED="true"
```

/etc/hosts
```
127.0.0.1 app.cal.local
127.0.0.1 org-210-1717178624606.cal.local
127.0.0.1 example.cal.local
```

### CODE REVIEW

**Comment by balthazur** [comment]
Currently, the test urls for organizations are constructed in the following way. E.g.

```
const orgSlug = "example"
${getOrgOrigin(orgSlug)}/${orgOwner.username} 
// resolves to "http://example.cal.local:3000/...."
```
This relies on /etc/hosts to configured to resolve example.cal.local to localhost. I don't think this will work on automated CI runs, right? If not, please tell me how I should handle the org domains in tests. @hariombalhara @PeerRich

**Comment by hariombalhara** [comment]
@balthazur thanks for the patience and sorry I couldn't check it earlier.

 We don't need to have a working org domain(like acme.cal.com). I think we can just check the redirect. Playwright shouldn't have an issue verifying the redirection for a page that has failed to load.

We right now run the tests for org domains through `doOnOrgDomain` function which uses the regular domain but fakes the org domain through `x-cal-force-slug` header.

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Hey @balthazur pls fix the conflict and address @hariombalhara comment.

**Comment by keithwillcode** [comment]
This PR is being closed due to staleness. Please reopen if work is to continue.

**Pull request closed without merging**
