### PR TITLE
fix: ui of reschedule dialog

### LINKED ISSUE #5669: [CAL-444] [CAL-445] Reschedule dialog UI is broken
### Issue Summary

Reschedule dialog UI is broken.

How to reproduce?

1. go to bookings
2. Click request reschedule

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Signed-off-by: Udit Takkar <udit.07814802719@cse.mait.ac.in>

Fixes https://github.com/calcom/cal.com/issues/5669

https://user-images.githubusercontent.com/53316345/204037912-7e23df1e-5d51-4fd0-b123-7527fb12f923.mov

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
while this fixes it, it kinda misuses the use of DialogFooter and its buttons. @sean-brydon any idea why the default dialog componens arent working?

**Review by PeerRich — APPROVED** [review]
i am fine merging this as hotfix but i think we need to address DialogFooter @sean-brydon in a follow up PR

**Comment by Udit-takkar** [comment]
@PeerRich  this is how EditLocationDialog in /components/eventtype was structured. we'll also have to fix that in a follow up PR.

**Comment by sean-brydon** [comment]
@Udit-takkar @PeerRich I plan on tackling Dialog API / how we use dialogs across the app this week. This PR is good to merge and I'll do the follow up

**Comment by PeerRich** [comment]
@sean-brydon  perfect, feel free to ask @JeroenReumkens too who comes back from OOO monday

**Comment by PeerRich** [comment]
test failing maybe @zomars can help merge

**Comment by JeroenReumkens** [comment]
Retried the E2E tests since locally they are successful.

**Pull request merged**
