### PR TITLE
Event Cancelled/Rescheduled By

### LINKED ISSUE #2477: Event Cancelled/Rescheduled By
### Is your proposal related to a problem?

Currently, we don't provide any details about who cancelled the event. It is obvious for single user event types as it is either the organizer or the booker who cancels it, and both parties are aware. However, when we talk about collective events (Dynamic or Team), it would be nice to know who cancelled/rescheduled the event. 

(Write your answer here.)

### Describe the solution you'd like

- Everytime an event is cancelled or rescheduled, it should contain information of who cancelled or rescheduled the event.

### PR DESCRIPTION
**Pull request by gitstart**
## What does this PR do?

Added to the email body who is the author of a cancellation or rescheduling of the event.

Fixes #2477 

cancelado
rescheduled
https://www.loom.com/share/285e1338865644b6934185d5c96f9648

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
@zomars @zlwaterfield  this touches a ton of files so i am careful to review & merge

**Comment by zomars** [comment]
The issue #3899 is not on our Core roadmap nor has been properly discussed. We should not have PRs for features that haven't been approved. Even if this is a relative simple feature, it is still way too vague to know all the ramifications that can result into maintaining and improving upon this feature.

Some examples:
- Do we want to show the cancellation author email each time? If not, that another settings to add
- Do we want to save the cancellation author in the DB?
- Are there cases where this behavior is unexpected/unintented?

**Comment by alishaz-polymath** [comment]
@zomars I agree that this needs more discussion and that it isn't well planned or core. However, I think it is still one worth discussion because there are a few use cases where it becomes important. For example, i feel that in case of collective team booking (including dynamic booking), it might be useful to know who cancelled or rescheduled or requested to reschedule the booking. Thoughts?

**Comment by zomars** [comment]
Let's let @Jaibles decide this. We "feel" we haven't had any actual requests from users from this. So we shouldn't just go with our gut feeling about design changes.

**Comment by alishaz-polymath** [comment]
> Let's let @Jaibles decide this. We "feel". We haven't had any actual requests from users from this. So we shouldn't just go with our gut feeling about design changes.

Got it. Makes sense!

**Comment by zlwaterfield** [comment]
Should we close this PR for now?

**Comment by aasargsian** [comment]
@Jaibles @zomars 
Just for additional context if you reconsider re-opening the PR, we typically used the cancelledBy attribute to better define the next action. Calendly, our previous scheduling tool, saved the cancelledBy attribute in the database among with cancelledAt and cancellationReason.

How we use the attribute?
For example, If the teleconsultation is canceled by the host - we call back the attendee to rescheduled. If the teleconsultation is cancelled by attendee - there is usually no action required.

This doesn't seem like a high priority for us. But it's definetely useful.

**Pull request closed without merging**
