### PR TITLE
fix(team-description): break lines rendering

### LINKED ISSUE #15056: [CAL-3713] Line breaks not reflecting in the event type description
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3713](https://linear.app/calcom/issue/CAL-3713/line-breaks-not-reflecting-in-the-event-type-description)</sub>

### PR DESCRIPTION
**Pull request by SySagar**
## What does this PR do?

- Fixes #15056 
- [CAL-3713] Line breaks not reflecting in the event type description

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Can be tested on the latest production code.

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Hey, pls uncommit the lock file also type checks are failing

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Not changes visible for even type description:-
Screenshot 2024-07-28 070057

Screenshot 2024-07-28 070147

Extra space added in event Meta , it was correct before:-
Screenshot 2024-07-28 065913
 before:-
 
Screenshot 2024-07-28 070318

**Comment by anikdhabal** [comment]
closing it for, feel free to reopen after correcting it

**Comment by SySagar** [comment]
According to the issue, whenever the user enter a new empty line, it wasn't displaying on the ui. So now in the evenTypes list it is getting rendered as it is. Regarding  eventMeta shoudn't  it render it the same way as is in the description. Hence if it is one extra line then that should put one extra line rather than wrapping.  If I am wrong please can you be exact what is required of to do?

**Pull request closed without merging**
