### PR TITLE
feat: Round-Robin Reassignment Feature

### LINKED ISSUE #5608: [CAL-411] Round Robin Handover
The scenario is when there is an Account Executive (Person A) on a Fixed Round Robin with a DevRel (Person B) Round Robining on their link.

When an AE has a call booked, but they want to reschedule the Round Robin Dev Rel to another Dev Rel, there is not an easy way to do that.

* Person A is the Fixed Attendee and Person B is the Round Robin Attendee
* If Person B (DevRel) is already selected, *the ask is to be able to* reassign Person B
* You can then pick from a drop down from Person C, Person D, Person E (etc) of who you want to reschedule in.
* Bonus points if you can see who is actual available at that time (Maybe a green dot next to their name)

Another ask is to have the ability to easily see everyones availability in one place for the reschedule as well. Potentially show a list of available DevRels that could be slotted in (this is kind of the same thing being asked but in a different format presented).

> From [SyncLinear.com](https://synclinear.com) | [CAL-411](https://linear.app/calcom/issue/CAL-411/easily-reschedule-person-b-in-a-round-robin)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-411](https://linear.app/calcom/issue/CAL-411/easily-reschedule-person-b-in-a-round-robin)</sub>

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

Implements a multi-step reassignment dialog action on the /bookings page in order to easily reassign a booking to another team member or let the system choose another member dynamically.

image

image

Resolves #5608

### TODO

- [ ] t() translations
- [ ] Availability indicator functionality
- [ ] BE implementation
- [ ] Check role, Reassignment should only be allowed by ADMIN or OWNER role (https://github.com/calcom/cal.com/issues/5608#issuecomment-1330991981).

### CODE REVIEW

**Comment by PeerRich** [comment]
how do we move forward here? should someone else finish this?

**Comment by CarinaWolli** [comment]
@emrysal and/or I will revisit this PR once we are done with the new slots logic. There is still a lot missing for this to be ready

**Comment by emrysal** [comment]
Closing due to staleness, but this feature will be implemented shortly as we've now done the underlying backend work to support this.

**Comment by aaronjedwards** [comment]
Is there any update on the status of this? Would love to see this feature land.

**Comment by CarinaWolli** [comment]
> Is there any update on the status of this? Would love to see this feature land.

This will be coming soon, there is already a PR up for it https://github.com/calcom/cal.com/pull/14308

**Pull request closed without merging**
