### PR TITLE
feat: Support running webapp and embed-core playground on HTTPS. It allows to test SameSite cookie attribute easily in embed

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Allow running app and embed playground on HTTPS. It is a zero config approach.
Existing env variable URLs that are in HTTP are automatically converted to HTTPS

It was needed for two reasons:
- SameSite=None requires HTTPS. I needed to test SameSite=None for embed
- Link copying in the app crashes on HTTP.

Demo - https://www.loom.com/share/8de890617a61465b9a6506ee53aa57fb

## Mandatory Tasks (DO NOT REMOVE)
- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?
- Run app with `yarn dev-https` from apps/web
- Run playground with `yarn dev-https` from packages/embeds/embed-core

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#15272** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/15272?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sean-brydon** [comment]
Hey @hariombalhara 

apps/web seems to be working fine for me but as soon as run embed playground i am getting this error 
CleanShot 2024-06-24 at 09 18 38@2x

**Comment by hariombalhara** [comment]
@sean-brydon It works fine for me. Just re-tested. Could it be that it is a caching thing? Could you try opening embed playground URL in Safari or flush socket pool in Chrome/Arc
Screenshot 2024-06-25 at 1 07 35 PM

https://www.loom.com/share/8de890617a61465b9a6506ee53aa57fb

**Comment by sean-brydon** [comment]
> @sean-brydon It works fine for me. Just re-tested. Could it be that it is a caching thing? Could you try opening embed playground URL in Safari or flush socket pool in Chrome/Arc Screenshot 2024-06-25 at 1 07 35 PM
> 
> https://www.loom.com/share/8de890617a61465b9a6506ee53aa57fb

Yep that was it - nice job!

**Review by sean-brydon — APPROVED** [review]
LGTM - clearing cache fixed the issue locally

**Pull request merged**
