### PR TITLE
Upgrade to Radix 1.0

### LINKED ISSUE #3631: Upgrade Radix UI to v.1.0
related: https://github.com/radix-ui/primitives/issues/1241#issuecomment-1201361667

would fix: https://github.com/calcom/cal.com/issues/2328

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
Had a play and this indeed to me seems like a fairly painless 0.1 to 1.0 move, some breaking changes according to https://www.radix-ui.com/docs/primitives/overview/releases but I couldn't find any that affect us in practise.

**Comment by krumware** [comment]
@emrysal this is suspected to have broken the build
For example:
Screen Shot 2022-09-29 at 10 58 41 AM

**Comment by om-ray** [comment]
I think the reason this error is appearing may be due to this breaking change in the new release of radix https://www.radix-ui.com/docs/primitives/overview/releases
Screen Shot 2022-09-29 at 3 01 50 PM

**Comment by krumware** [comment]
I can confirm that the commit prior to this merge does build without issue

**Comment by joeauyeung** [comment]
Thanks for bringing this up. Fix is here #4767

**Pull request merged**
