### PR TITLE
fix: Mails are sent to the organizer twice

### PR DESCRIPTION
**Pull request by dasJ**
## What does this PR do?

The `ics` package doesn't support setting the `SCHEDULE-AGENT` parameter, there is a PR (https://github.com/adamgibbons/ics/pull/248), but it is not merged.

This is a workaround that relies on the fact that the `ics` package does not properly escape the `name` field of the organizer. In a perfect world, they would merge the PR and create a new release, but this is unfortunately not the world we live in.

Fixes # (issue)

This resolves one of the listed issues in #9485 which also affects NextCloud and SOGo users via WebDav.

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Pretty much the reproduce section of #9485

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by neilj** [comment]
It looks like this just adds `SCHEDULE-AGENT=CLIENT` to the organizer. As per [RFC6638](https://datatracker.ietf.org/doc/html/rfc6638#section-7.1), you need to set this on each attendee that the client is handling the scheduling for.

**Comment by dasJ** [comment]
Fair point, I wanted to start with this but it makes sense to also set this to every attendee.

**Comment by dasJ** [comment]
Since the question may come up: I tried calling the ics package as-is and replacing the attendee into the resulting string. This did not work as well as I hoped because the ical event has a line limit of 75 so either my regex doesn't match or it may produce lines that are too long.

**Review by zomars — CHANGES_REQUESTED** [review]
Thank you for your contribution 🙏 

Can we come up with a simple test to prevent a future regression?

**Comment by dasJ** [comment]
I'd love to but I don't see how unfortunately. My typescript is not the best (which you may see from the number of pushes I did ;) and the `createEvent` function seems to call a lot of things that don't seem to be currently mocked.
In fact, the `createEvent` function (that I modify) is usually mocked in tests.
Do you have any pointers for me how to get started?

**Comment by dasJ** [comment]
bruh

**Comment by alishaz-polymath** [comment]
@dasJ removed from stale state, that wasn't intended I'm sure 😅
But we do need tests for it still. 
@Udit-takkar can you please take a look?

**Comment by Udit-takkar** [comment]
I am not sure about these changes @joeauyeung might be the best person to review this

**Review by joeauyeung — CHANGES_REQUESTED** [review]
Tested this with Mailfence emails are still being sent from the CalDAV provider. Looking at the ics file, it seems like your changes aren't being applied to to the organizer and attendee fields.

ORGANIZER;CN=Free Example:mailto:free@example.com
ATTENDEE;RSVP=TRUE;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Test:mailto:*****@gmail.com

**Pull request closed without merging**
