### PR TITLE
added a few desktop only improvements

### PR DESCRIPTION
**Pull request by PeerRich**
browser:
CleanShot 2022-08-06 at 23 36 34@2x

desktop app:

CleanShot 2022-08-06 at 23 36 09@2x

### CODE REVIEW

**Comment by PeerRich** [comment]
tested on normal website https://cal-2f6l0i5hk-cal.vercel.app/ and had no impact. I think this is save to merge. I am now testing if the effects happen on the desktop app (building takes so long tho)

**Comment by PeerRich** [comment]
test changes here: https://dl.todesktop.com/220806en6dm2h1l

**Review by sean-brydon — APPROVED** [review]
Blessing the holy desktop app :)

**Review by sean-brydon — DISMISSED** [review]
Waiting till Monday

Due to Vercel error

**Review by zomars — APPROVED** [review]
LGTM

**Comment by leog** [comment]
Wow, this is great! NIT: I just happen to have the app window open very small and couldn't help to notice the window controls (close, maximize, minimize) overlap the first icon when smaller resolution styles kicks in.
image

**Pull request merged**
