### PR TITLE
Further sanitation for the auth callback URL. Removal of double forward slashes in the path.

### LINKED ISSUE #2196: Login auth callback is not fully sanitized.
### Issue Summary

A double forward slash is injected into the callback and next-auth is sounding about it.

image

### Steps to Reproduce

1. Clean up your session.
2. Login with example credentials, or your own
3. Check the console.

Seems next-auth is fixing this for us despite complaining about it. Probably by compressing the double forward slash into one. 
I suspect this because redirection to the home page (event-types) is done well but I think this is a minor bug that can potentially lead to some other issues if we don't take care of it.

### PR DESCRIPTION
**Pull request by denik1981**
## What does this PR do?
It further sanitizes the auth `callbackURL` from the changes made in #2086.
It assures only one forward slash will be used to join the base URL and the callback path  
 
Fixes #2196

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Simulate a login flow with any credentials you have. Be sure to clean up the session to start with an empty callback
- Check the console before this PR and after. You will note that the next-auth error is gone.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by agustif — CHANGES_REQUESTED** [review]
Could a motivator attacker still pass that regex by obfuscating callbackUrl somehow?

Rest looks good to me, let's see if @zomars agrees

**Review by agustif — APPROVED** [review]

**Comment by denik1981** [comment]
> Could a motivator attacker still pass that regex by obfuscating callbackUrl somehow?
> 
> Rest looks good to me, let's see if @zomars agrees

I'm not a regex fan. I tried to keep a little bit of consistency with the rest of the code. 
But in terms of injecting a malicious callback, the callback is public (in the URL) and as an attacker, you will have to first authorize yourself and bypass the login. Then the WEBSITE_URL, which is built from your local env, will assure you are tripping to your own website instead of the attacker one. This can (or should) be stressed out further to put Cal into severe security tests. It is very good question @agustif and a valid concern.  Thanks!

**Review by zomars — APPROVED** [review]
Good enough for now, but we may want to come up with a `sanitizeUrl` or something similar in a follow up.

**Comment by denik1981** [comment]
@zomars I totally agree. This looks like hard-coded to me and it is not free from errors or malicious code.
See [https://github.com/braintree/sanitize-url/blob/main/src/index.ts](https://github.com/braintree/sanitize-url/blob/main/src/index.ts)

It is doing sanitation of the [protocol + full domain] to prevent malicious code. 
I don't think we need an extra dependency. We can extend that code to what we need. 
We could the necessary checks to glue our WEBSITE_URL with the Callback PATH. 

Something to start with, better than nothing.

**Pull request merged**
