### PR TITLE
experiment: disco border 

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

Prototypes:

image

image

### CODE REVIEW

**Comment by PeerRich** [comment]
uhh exciting!

**Comment by PeerRich** [comment]
i wonder if we should only show it on loading. I would also slow it down a bit

**Comment by emrysal** [comment]
image

Lightmode isn't offensive either :)

**Comment by emrysal** [comment]
@PeerRich Depends if we want to show it on loading or always, I think on loading is more subtle but have a look; I slowed the animation down 6x.

**Comment by emrysal** [comment]
There's another option to showing it always, if we show it always we should tune it down, like:

image

But my opinion is that we should only animate when something is in progress, not always.

**Review by PeerRich — APPROVED** [review]
looks awesom! do we have screenshots for light mode?

**Comment by Jaibles** [comment]
@emrysal let's make sure we keep this as an experiment for now. While I think it's really cool, we can not turn this on for all users by default for a lot of reasons. This needs to be an opt-in feature - how exactly we make it opt-in (whether via themes or something else) we can discuss.

**Pull request merged**
