### PR TITLE
Don't show readonly action buttons

### PR DESCRIPTION
**Pull request by Geczy**
## What does this PR do?

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by CarinaWolli** [comment]
When we remove the edit, duplicate and delete buttons, then we should probably also remove the embed button (as far as I tested it, it doesn't work with read-only). Also, the user can still click on the event type to get redirected to the editing page. So either we disable that too (but that would mean that the user also can't see all the detailed settings of the event type anymore) or we could at least disable the update button or maybe even disable all input fields on the editing page. Maybe @Jaibles could give some input here, what do you think would make the most sense?

**Comment by Geczy** [comment]
i think setting all input fields to readonly makes sense

**Comment by zlwaterfield** [comment]
@Geczy are you able to finish up this PR?

**Comment by zomars** [comment]
Closing due stale changes

**Pull request closed without merging**
