### PR TITLE
feat: #3921 Added v2 design for booking details.

### LINKED ISSUE #3767: 2.0 Booking / Single {View}
[View in Figma →](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=14383%3A104294)

Image

### LINKED ISSUE #3921: 2.0 Public Booking Confirmation Card {component}
Turn this into a component

Success state
Image

Cancelled state

Image

Unconfirmed state

### PR DESCRIPTION
**Pull request by JeroenReumkens**
## What does this PR do?

Implements new v2 design for booking details. 
The template in this PR contains only styling changes, no logic touched. The file is copy over to v2 to not break v1 🙂 

Fixes #3921

image

Loom Video: https://www.loom.com/share/4694769e865e4edd99b74f5e529dbbd6

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Verify that implemented design matches design in Figma (see #3921)

### CODE REVIEW

**Comment by Jaibles** [comment]
@JeroenReumkens looks great! 

Are the same changes applied to the cancelled state or is it just confirm?

**Comment by JeroenReumkens** [comment]
@Jaibles  I'm so sorry, totally forgot to include the cancelled state in my video. It is indeed also included in this PR. I created a new Loom showing that part for you: 

https://www.loom.com/share/f3fcca38c16f48e382b6c87a8734cfc1


As for the opt-in booking, how can I exactly create such a booking? Then I can test locally and see what I can do 😄

**Comment by sean-brydon** [comment]
@PeerRich Correct me if I'm wrong - should this override the V1 screen for this page? 

Like we are doing with public booking page?

**Comment by Jaibles** [comment]
Fantastic cancel looks great. Left a comment in Loom :)

To test opt-in: 
https://user-images.githubusercontent.com/4536123/188125502-e163a88b-56f4-4b83-81ee-36e92ededde3.mp4

**Comment by sean-brydon** [comment]
> @Jaibles I'm so sorry, totally forgot to include the cancelled state in my video. It is indeed also included in this PR. I created a new Loom showing that part for you:
> 
> [loom.com/share/f3fcca38c16f48e382b6c87a8734cfc1](https://www.loom.com/share/f3fcca38c16f48e382b6c87a8734cfc1)
> 
> As for the opt-in booking, how can I exactly create such a booking? Then I can test locally and see what I can do 😄

@JeroenReumkens  for opt-in booking please toggle this switch in the Advanced tab :) 

CleanShot 2022-09-02 at 11 58 57

**Comment by JeroenReumkens** [comment]
> @PeerRich Correct me if I'm wrong - should this override the V1 screen for this page?
> 
> Like we are doing with public booking page?

Would actually love it if we could copy less. This way we also maintain git history etc for these pages and less bug fixing if a bug occurs in any of these copied pages 🙂

**Comment by sean-brydon** [comment]
> > @PeerRich Correct me if I'm wrong - should this override the V1 screen for this page?
> > Like we are doing with public booking page?
> 
> Would actually love it if we could copy less. This way we also maintain git history etc for these pages and less bug fixing if a bug occurs in any of these copied pages 🙂

Agreed - we will be replace V1 with V2 in the upcoming month I believe

**Review by PeerRich — APPROVED** [review]
looks good to me! thank you jeroen

**Comment by JeroenReumkens** [comment]
@Jaibles  Updated the icon and colors for the opt-in event. Created a new Loom showing all 3 states: 
https://www.loom.com/share/c941f904dee64f6b9d1097e516318c18

While I was looking at the icons I also noticed the icons were slightly smaller in the new design, which I missed. So I've also made them smaller in this video and commit. Let me know what you think!

**Pull request merged**
