### PR TITLE
Fixing GCal emailing notif and sequential deleting

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

Making sure Google Calendar does not send deleted events notifications when deleted by API, as we handle the notification for them. Also, Google Calendar delete was causing problems when using its API in parallel, changing it to be sequential.

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Try to cancel a recurring event with lots of instances and you shouldn't see Google sending cancelled notification for each instance nor a 500 error when doing so.

### CODE REVIEW

**Comment by PeerRich** [comment]
i think some scheduling serivces still send the notification if I am not incorrect

**Review by zomars — APPROVED** [review]
LGTM

**Comment by zomars** [comment]
I think is good enough. But is it possible to suppress notifications only in recurring events?

**Comment by leog** [comment]
> I think is good enough. But is it possible to suppress notifications only in recurring events?

@zomars wouldn't we want to also avoid notifications for single events too? Cal already sends a notification for those too

**Comment by zomars** [comment]
> > I think is good enough. But is it possible to suppress notifications only in recurring events?
> 
> @zomars wouldn't we want to also avoid notifications for single events too? Cal already sends a notification for those too

I don't know, hence the question. But merging for now. 🙏🏽

**Pull request merged**
