### PR TITLE
Update booking filters design 

### LINKED ISSUE #6540: [CAL-817] component: multi-select: Should be able to click the whole list item
[908f5c20-9d8e-4684-af72-cec478a31c9a](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b31f30fc-f0f5-4791-8d74-54667e9213ca/908f5c20-9d8e-4684-af72-cec478a31c9a)

**Selection issues**

* Currently can't click the entire list item
* Should we stop the ability to edit text? I find when I click in places I'm often ending up selecting all text

**Icon issues**

* The icon alignment doesn't look vertically centered. [Is there a margin top on it?](https://share.cleanshot.com/wbHhWfMn)
* When I select a few items, it resizes relative to the text.
* It should be 16x16px, looks like 14px in implementation. Not sure we can fix that?

Left is live, right is figma.

Other minor nit: Use sentence case everywhere. "All users", "All bookings [etc.ES](http://etc.ES)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-817](https://linear.app/calcom/issue/CAL-817/component-multi-select-should-be-able-to-click-the-whole-list-item)</sub>

### LINKED ISSUE #6558: [CAL-826] /bookings user filter - Pending members show up empty in the dropdown
[https://user-images.githubusercontent.com/8019099/213470222-176addfa-06e4-45ab-8ef6-4cbd081725d2.mp4](https://user-images.githubusercontent.com/8019099/213470222-176addfa-06e4-45ab-8ef6-4cbd081725d2.mp4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-826](https://linear.app/calcom/issue/CAL-826/bookings-user-filter-pending-members-show-up-empty-in-the-dropdown)</sub>

### PR DESCRIPTION
**Pull request by sean-brydon**
## What does this PR do?

Making the items breath a bit and fixing over states 

CleanShot 2023-01-18 at 10 57 06@2x

Fixes #6540
Fixes #6558

### CODE REVIEW

**Comment by Jaibles** [comment]
@sean-brydon I still see all the same issues on this [preview url](https://cal-git-ui-cal-817-animated-popover-issues-cal.vercel.app/auth/login) 🤔

https://user-images.githubusercontent.com/4536123/213171036-fe6949c4-e2ba-4eb7-b954-95bee80eca7f.mp4

Also, any reason these show up later than everything else when loading? Does it fetch with the list items? Anyway they can be there with the filters no?
https://user-images.githubusercontent.com/4536123/213171048-ba3f1475-b02f-4dcd-8c9d-fcfe286176ee.mp4

**Comment by Jaibles** [comment]
@sean-brydon are we also missing the "Mine" option? As an admin, I want to be able to filter away all bookings on the Cal team and just see my personal ones.

CleanShot 2023-01-18 at 12 28 52@2x

**Comment by Jaibles** [comment]
> So we have duplicate was of selecting yourself?

Because we have different spaces/profiles or whatever we call them,  ie me and my teams, the way they're split in event types the intention was...

- Selecting "yours" in the teams booking select will just show bookings made on cal.com/ciaran and no teams bookings. Just my personal ones. 
- Selecting myself in users would show any bookings I'm in across all teams and including personal unless I've filtered that out. 

Perhaps we should make the "yours" select item a little clearer and show the user profile photo like it is in event types?

**Comment by PeerRich** [comment]
i noticed the border has different colors. has this been addressed here @sean-brydon ?

CleanShot%202023-01-19%20at%2011 14 56@2x

**Comment by sean-brydon** [comment]
> i noticed the border has different colors. has this been addressed here @sean-brydon ?
> 
> CleanShot%202023-01-19%20at%2011 14 56@2x

Seems to be on hover? Only time i can see the color diff

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
