### PR TITLE
fix: Caching key for CI database

### PR DESCRIPTION
**Pull request by keithwillcode**
Fixes issues in `main` where e2e pipeline is completely broken due to caching issues. See comment added to this yml file for more details.

### CODE REVIEW

**Review by emrysal — DISMISSED** [review]

**Review by emrysal — APPROVED** [review]
Approved the comment too

**Review by zomars — APPROVED** [review]

**Comment by keithwillcode** [comment]
We need to force merge this to main since the pipeline is broken without this change.

**Comment by keithwillcode** [comment]
> We need to force merge this to main since the pipeline is broken without this change. I have manually kicked off the full suite targeted at this branch and we will only merge when that succeeds.

I take this back. Now seeing that GitHub uses the last run, manual or automatic, to determine if the checks passed. The current manual run I kicked off is currently running for this PR's checks.

**Comment by keithwillcode** [comment]
> We need to force merge this to main since the pipeline is broken without this change. I have manually kicked off the full suite targeted at this branch and we will only merge when that succeeds.

Never mind, GitHub is using the latest manual run as the principal checks. Just succeed and auto-merge went through.

**Pull request merged**
