### PR TITLE
Enable prisma json protocol

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Following the recommendations from the @prisma team this PR enabled the new json protocol, which according to [their docs](https://github.com/prisma/prisma/issues/18095) should help increasing speeds for our  previously reported cold boots.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] Measure cold boot endpoint on preview

### CODE REVIEW

**Comment by emrysal** [comment]
Nowadays we know that cold boot isn't prisma related, but still this should be an improvement, trying to get this in for todays tag if it all passes.

**Comment by emrysal** [comment]
Closing this for now @zomars @keithwillcode - IMO we need to wait until it's (more) stable.

Tested out the branch and Prisma currently has one breaking bug for the jsonProtocol:
https://github.com/prisma/prisma/issues/18598

Let's keep an eye on this and re-open once the time is right 👍

**Comment by janpio** [comment]
Hey, Prisam 4.13.0 is out since Tuesday and fixed https://github.com/prisma/prisma/issues/18598, and almost all other known issues with `jsonProtocol`- so please try it out!

**Comment by zomars** [comment]
> Hey, Prisma 4.13.0 is out since Tuesday and fixed [prisma/prisma#18598](https://github.com/prisma/prisma/issues/18598), and (almost) all other known issues with `jsonProtocol`- so please try it out!

Awesome @janpio will update an re-open ASAP. 🙏🏽

**Comment by PeerRich** [comment]
image

😢

**Review by keithwillcode — APPROVED** [review]

**Comment by zomars** [comment]
Same here: 16s cold start

image

**Comment by janpio** [comment]
What is the before without `jsonProtocol`?

**Pull request merged**
