### PR TITLE
fix /components/dialog/editlocation

### PR DESCRIPTION
**Pull request by Udit-takkar**
Signed-off-by: Udit Takkar <udit.07814802719@cse.mait.ac.in>

Fixes  follow up PR https://github.com/calcom/cal.com/pull/5647 and fixes 
add location

After:-

https://user-images.githubusercontent.com/53316345/203841821-0e9b78db-93ea-4402-83df-3c25ff2470e7.mov

This PR https://github.com/calcom/cal.com/pull/5647 was tested fine but most probably it break due to changes made in calcom/ui thttps://github.com/calcom/cal.com/pull/5561 . 

Even reschdule dialog ui seems to be broken

Screenshot 2022-11-24 at 11 14 32 PM

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
> Even reschdule dialog ui seems to be broken

is this broken on main or after your PR? @Udit-takkar

**Comment by Udit-takkar** [comment]
@PeerRich  on the PR branch it was working fine but after it got merged it was not working.

**Comment by Udit-takkar** [comment]
most probably the reason was that earlier different versions of dialog was being used 
import { Dialog, DialogContent } from "@calcom/ui/v2"; 
import { Dialog, DialogContent } from "@calcom/ui";

but it was changed to use only one type here in this PR https://github.com/calcom/cal.com/pull/5561/files#diff-e4b1edda68f5ae51e8d6781481d154a08a266f279d3babfa574cc81b53721645

**Review by CarinaWolli — APPROVED** [review]
Works now 🙌🏻 Thank you for the fix!

**Comment by Udit-takkar** [comment]
Looks like @alannnc merged the PR to fix these issue https://github.com/calcom/cal.com/pull/5692. this is not duplicate now.

**Pull request closed without merging**
