### PR TITLE
fix: Updates autoanimate to latest version

### PR DESCRIPTION
**Pull request by sean-brydon**
Fixes the auto animate error about not being iteratable

Fixes: 

CleanShot 2023-10-05 at 09 58 42@2x

### CODE REVIEW

**Comment by sean-brydon** [comment]
Current dependencies on/for this PR:
* main
  * **PR #11707** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/11707" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/11707?utm_source=stack-comment).

**Review by keithwillcode — DISMISSED** [review]

**Review by Udit-takkar — DISMISSED** [review]
works fine

**Comment by Udit-takkar** [comment]
@sean-brydon can you retrigger tests? some are failing.

**Comment by sean-brydon** [comment]
Closing - seems to be causing issues. with routing forms - upgrade not needed right now 

CC @hariombalhara just keeping you in the loop

**Pull request closed without merging**
