### PR TITLE
chore: prettier pre-commit hook

### LINKED ISSUE #10334: [CAL-2232] Add more instructions for contributors
We need to add more instructions for open source contributors in docs or [CONTRIBUTING.md](http://CONTRIBUTING.md)

some common mistakes in the PR

1. Not using prettier formatting

Screenshot 2023-07-24 at 3 13 23 PM

2. Commiting yarn.lock file even when there is no change in the package.json file and how to uncommit it if pushed to the branch
3. Not linking the PR to issue.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2232](https://linear.app/calcom/issue/CAL-2232/add-more-instructions-for-contributors)</sub>

### PR DESCRIPTION
**Pull request by rkreddy99**
## What does this PR do?

Uses pre-commit hook for prettier formatting.

The pre-commit hook to trigger prettier formatting is already there but since .husky/_ isnt added to github, the contributor has to manually postinstall script once they clone the repo locally. I have removed the "_" from gitignore which allows husky.sh file to be added to git. Now once the contributor makes a commit it automatically triggers prettier formatting.

Fixes #10334

 Loom Video: https://www.loom.com/share/9d957dae25fa4a2aba28fb733e193bf1?sid=6fbffc9e-c933-4b4c-94c8-c6f4dab79d36

## Requirement/Documentation

- .husky folder should be uploaded to git so that the contributor doesnt has to run postinstall script on their machine.

## Type of change

- [ ] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- add unformatted dummy code to any file.
- stage and commit the changes, the pre-commit should trigger and make the formatting changes.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nicktrn** [comment]
Sorry, but this is not a good idea. That gitignore file is created by `husky install` and it's important to leave it alone. Adding the husky shell script to the repo will sadly not fix the issue either. The reason your commit hooks are working is because you ran `husky install` (probably manually). Automatic install doesn't work because yarn 2+ ignores prepare scripts.

**Comment by rkreddy99** [comment]
oh yeah makes much more sense to add that command in postinstall rather than pushing the husky.sh

**Comment by rkreddy99** [comment]
not a good approach

**Comment by rkreddy99** [comment]
not a good approach

**Pull request closed without merging**
