### PR TITLE
fix: issue #9523 limited scroll range on mobile device

### LINKED ISSUE #9523: [CAL-4156] Stripe App - overflow-y-auto limits scroll range on mobile device
### Issue Summary

On the Stripe Payments page in the embedded CalCom React Component, the tailwind setting overflow-y-auto limits the scroll range on a mobile device.   User is unable to scroll to bottom of page and / or stripe component unless user clicks into form to fill out payment info. 

Please note, in developer tools, scrolling behavior seems to work ok although there is a scroll inside scroll behavior.  On an iPhone device, the behavior breaks, and user is unable to scroll the page as expected. 

### Steps to Reproduce

1.  Open site on physical device (not developer tools emulation)
2.  Attempt to scroll page. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Considered a bug as user is unable to scroll through page as expected unless they begin to click into form fill out payment info.  Even then scroll behavior is odd as it is a scroll (form) within scroll (page) behavior.  

### Technical details

This line causes behavior
```
<div class="fixed inset-0 z-50 overflow-y-auto scroll-auto">
```

Changing to 
```
<div class="fixed inset-0 z-50">
```

Could fix the behavior.  I'm unable to test on my mobile device, but the scroll in scroll behavior stops in dev tools, so I'm optimistic.

<sub>[CAL-4156](https://linear.app/calcom/issue/CAL-4156/stripe-app-overflow-y-auto-limits-scroll-range-on-mobile-device)</sub>

### PR DESCRIPTION
**Pull request by stefanmuljadi**
## What does this PR do?

As per the suggestion in #9523, overflow-y-auto and scroll-auto are removed to prevent having a double scroll wheel that causes the users to be unable to scroll through the page as expected unless they begin to click into the form and fill out payment info.

- Fixes #9523

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

### CODE REVIEW

**Comment by Ryukemeister** [comment]
@stefanmuljadi it looks like you've pushed the changes for the `yarn.lock` file. We generally update the `yarn.lock` while updating or deleting packages and it doesn't seem like we're doing that here, can you revert the `yarn.lock` file changes?

**Comment by hariombalhara** [comment]
@stefanmuljadi Could you please record a before and after loom/video for both embedded and non-embedded booker

**Review by hariombalhara — CHANGES_REQUESTED** [review]
As this is a small change but would need to be tested well. Requesting some screenshots to verify it works

**Comment by anikdhabal** [comment]
> As this is a small change but would need to be tested well. Requesting some screenshots to verify it works

@stefanmuljadi

**Comment by keithwillcode** [comment]
This PR is being closed due to staleness. Please reopen if work is to continue.

**Pull request closed without merging**
