### PR TITLE
feat: Drag & drop for re-ordering event types (without any external library)

### LINKED ISSUE #14701: [CAL-3514] Drag & drop for re-ordering event types
It takes too long to click every time over and over and over and over to move an event up when I have 10+ events.

<sub>[CAL-3514](https://linear.app/calcom/issue/CAL-3514/drag-and-drop-for-re-ordering-event-types)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #14701

### CODE REVIEW

**Comment by anikdhabal** [comment]
> This is quite clever. Good job. Could you please attach a loom or video demoing it? 🙏

Sure @zomars 🙏


https://github.com/calcom/cal.com/assets/81948346/dc59af77-61cd-486c-9ecb-2cf8ef51e8cb

**Review by Udit-takkar — COMMENTED** [review]
Tested this and worked fine but it swaps both the event types instead of moving only one. is this fine @ciaranha?

https://github.com/calcom/cal.com/assets/53316345/69f311f6-4a44-4880-8506-d22626a396f5

**Comment by sean-brydon** [comment]
> Tested this and worked fine but it swaps both the event types instead of moving only one. is this fine @ciaranha?
> 
>  Screen.Recording.2024-04-24.at.2.08.42.PM.mov

Yeah I was testing this and notice this too - i was checking a few drag and drop instances across a few different apps and they all seem to have a mixture of inserting it where you dropped it and swapping. I think its just a matter of preference. 

I would lean to inserting as that is kinda what happens when you use the arrows

**Comment by ciaranha** [comment]
> Tested this and worked fine but it swaps both the event types instead of moving only one. is this fine @ciaranha?

No, this is weird.

**Comment by ciaranha** [comment]
I'd like for us to have a specific draggable area rather than the whole thing draggable as re-ordering is not a super high need, but in terms of the interaction, this is more what I would hope for:

https://github.com/calcom/cal.com/assets/4536123/ab6ffbcd-ea8e-4ffe-91b1-a8e4ba93ede0

Requirements
- It's clear what I'm dragging
- It's clear where I'm going to drop it and how that will impact the items around it
- It should feel smooth and predictable

**Comment by keithwillcode** [comment]
Closing for now based on @ciaranha comments. Feel free to reopen if changes are made.

**Comment by anikdhabal** [comment]
> Closing for now based on @ciaranha comments. Feel free to reopen if changes are made.

Yeah, I will fix it shortly and reopen it.

**Pull request closed without merging**
