### PR TITLE
chore: plain text plugin for Editor

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A-I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] N/A-I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by anikdhabal** [comment]
Logging the message in the component currently works, we need to test it with an actual SMS message using the Twilio key🙏
(ps:- i don't have)

**Review by Udit-takkar — COMMENTED** [review]
can you mention the issue/bug as well as how to test it?

**Comment by anikdhabal** [comment]
Bug:-

image

Look How the link is rendered

WhatsApp Image 2024-10-29 at 14 53 09_f2228970
cc @Udit-takkar

**Review by Udit-takkar — COMMENTED** [review]
LGTM. i'll wait fot @CarinaWolli review

**Review by Praashh — APPROVED** [review]

**Pull request merged**
