### PR TITLE
Add password on confirmation when changing email

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR prompts the user to confirm their password before changing their email.

Fixes # (issue)

https://www.loom.com/share/314277d527d0453a894f1d41741ce248

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Go to the profile settings
- Try changing your email
	- In the prompt enter  the incorrect password
	- Now enter the correct password
- You should now be able to change your email

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
This works; but the UX experience isn't great.

**Review by zomars — CHANGES_REQUESTED** [review]
Blocking. Let's make this right. I'd rather disable email changes until then.

**Comment by joeauyeung** [comment]
Thanks for the feedback @zomars and @emrysal. The confirm password modal now appears only if the email was changed.
https://www.loom.com/share/f3adbe9e03914166b498e17bd20d80ee

**Review by zomars — COMMENTED** [review]
LGTM

**Pull request merged**
