### PR TITLE
chore: Identify and Split Large Code Files

### LINKED ISSUE #12559: [CAL-2766] Refactor: Identify and Split Large Code Files for Improved Testability
Our codebase currently contains large files that could benefit from refactoring into smaller, more modular components. Example: [handleNewBooking.ts](https://github.com/calcom/cal.com/blob/230b82d3bf3692cbe415f2ed6305ebc643bede1b/packages/features/bookings/lib/handleNewBooking.ts).

This refactoring effort is essential for improving the maintainability of the code and facilitating more effective unit and integration testing. The goal is to identify these large files, break them down into smaller, logically organized modules, and create a structure that enables comprehensive testing.

### Desired Features:

* **Adhere to current system design**: The idea of this is not to introduce a new architecture or system design (e.g. DDD) but instead to break down large files into smaller, more testable units of code.
* **Unit and Integration Testing**: Create or enhance unit and integration tests for the refactored components to ensure their correctness and reliability.
* **Documentation**: Document the refactoring process, including the rationale behind splitting specific files, to aid future development and maintenance efforts.

### Requirements:

* **Maintainability**: Ensure that the refactored codebase remains maintainable and comprehensible, with clear separation of concerns. **No major functionality changes will be accepted.**
* **Testability**: Design the smaller components with testing in mind, making it easier to write meaningful unit and integration tests.
* **Performance Considerations**: Evaluate the performance impact of the refactoring and address any potential bottlenecks or inefficiencies.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2766](https://linear.app/calcom/issue/CAL-2766/refactor-identify-and-split-large-code-files-for-improved-testability)</sub>

### PR DESCRIPTION
**Pull request by Shyam-Raghuwanshi**
## What does this PR do?

this PR Identify and Split Large Code Files

Fixes #12559

- [] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Tests (Unit/Integration/E2E or any other test)
- [ ] This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by PeerRich** [comment]
hey @Shyam-Raghuwanshi whats missing here to leave draft? Also there are 2 merge conflicts. Can you investigate?

**Comment by Shyam-Raghuwanshi** [comment]
Hi @PeerRich, I am working on resolving this issue and would like to confirm if I am on the right track. I have created a draft pull request (PR).

**Comment by sean-brydon** [comment]
> Hi @PeerRich, I am working on resolving this issue and would like to confirm if I am on the right track. I have created a draft pull request (PR).

Hi @Shyam-Raghuwanshi looking great so far - there are some merge conflicts that are present if you get a change could you please fix them? 

If you dont i have time - i will take over this PR in a few days to get this work over the line. Great job

**Comment by sean-brydon** [comment]
> Dear @sean-brydon, I hope this message finds you well. I wanted to inform you that I am currently engaged in another GSOC project and am unable to address the conflict at the moment. I appreciate your understanding and would be grateful if you could kindly resolve the conflict. Thank you for your cooperation.

No worries at all! Thanks for your contribution.

**Comment by Shyam-Raghuwanshi** [comment]
Hi @sean-brydon should i remove this from Draft?

**Comment by Shyam-Raghuwanshi** [comment]
hi @sean-brydon i resolve the conflict

**Pull request closed without merging**
