### PR TITLE
feat: Added Drag and Drop for Event Types

### LINKED ISSUE #10016: Allow drag and drop to rearrange event types
### Is your proposal related to a problem?

It would be nice if we could drag and drop the event types instead of using arrows to move them one step up or down.

https://github.com/calcom/cal.com/assets/47350983/71919323-eeba-4828-8ec5-1e95414f35b8

### Describe the solution you'd like

Implement drag and drop using [react-beautiful-dnd](https://www.npmjs.com/package/react-beautiful-dnd?activeTab=readme).

### Describe alternatives you've considered

There are other libraries like react-dnd but react-beautiful-dnd seems to be the most popular one.

### Additional context

There was an issue that was raised before and was closed as it was low priority and since drag and drop tends to be flaky: https://github.com/calcom/cal.com/issues/7125.
With this in mind this feature can be considered a prototype, which will need extensive testing before it can be submitted.

### PR DESCRIPTION
**Pull request by valdemartti**
## What does this PR do?

This PR adds support for Drag and Drop in the Event Types list. The PR adds `@dnd-kit/core`, `@dnd-kit/modifiers`, `@dnd-kit/sortables` and `@dnd-kit/utilities`, which are widely used packages for handling Drag and Drop.

Fixes #10016
/claim #10016

[https://www.loom.com/share/7da594acde784c86858b8cf756616c1c?sid=d28c278a-c189-48ea-a6ee-1ddab6367444](https://www.loom.com/share/7da594acde784c86858b8cf756616c1c?sid=d28c278a-c189-48ea-a6ee-1ddab6367444)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

The change is primarily a UI functionality change. To test the change, you can drag around the list items on `/event-types`. Refresh the page to confirm that items have moved places. Also test that the original buttons still work.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't checked if my PR needs changes to the documentation
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by valdemartti** [comment]
The `SortableListItem`'s are occasionally (on release) moving back to their original positions and then flicking to where they were dragged. It's not a dealbreaker in my opinion, but I will still try to fix that issue.

Also, just recognized an issue with using a state in between for event types, will work on that a bit more too.

**Comment by PeerRich** [comment]
we have previously decided to not offer drag and drop for event-types

**Pull request closed without merging**
