### PR TITLE
fix: If the input type "Name" is selected, the label can't be changed from our default label "Your Name"

### LINKED ISSUE #10390: [CAL-2261] If the input type "Name" is selected, the label can't be changed from our default label "Your Name"
[https://app.birdeatsbug.com/sessions/-ZDXRm7sd1JSyC-NEoXm8ZHSyTbWMWezvkAllOzlsN2Z](https://app.birdeatsbug.com/sessions/-ZDXRm7sd1JSyC-NEoXm8ZHSyTbWMWezvkAllOzlsN2Z)
Created via Threads. See full discussion: [https://threads.com/34513965502](https://threads.com/34513965502)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2261](https://linear.app/calcom/issue/CAL-2261/if-the-input-type-name-is-selected-the-label-cant-be-changed-from-our)</sub>

### PR DESCRIPTION
**Pull request by ZainGulbaz**
## What does this PR do?

If we wanted to update the label for field types of config variants in field form of event's booking question, it was not updating in the main ui. In this PR, now instead of showing the default label for config variants we get their dynamic values and show them on the UI.

Fixes #10390

https://www.loom.com/share/4927bb0ca9d848f7b6ea60679072c4af

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

The user can edit the event and from advanced setting he can edit the "name" field and change the label.

### CODE REVIEW

**Comment by ZainGulbaz** [comment]
@CarinaWolli should I close this PR?

**Review by hariombalhara — APPROVED** [review]
Thanks @ZainGulbaz 🙏 Great fix !!

**Comment by MehulZR** [comment]
- When the inputs are empty it doesn't read the *default label* defined for the variants from *configMap*.
- For split inputs, it doesn't show the *last name label*.

https://github.com/calcom/cal.com/assets/86384652/c9d43b13-3900-418b-9336-6ac5e12ef5f2

**Comment by ZainGulbaz** [comment]
> * When the inputs are empty it doesn't read the _default label_ defined for the variants from _configMap_.
> * For split inputs, it doesn't show the _last name label_.
> 
>  video.mp4

Hi @MehulZR , Thanks for the insights. I have addressed your issues in PR #10727. Kindly do have a look and let me know.

**Pull request merged**
