### PR TITLE
chore: cleanTranslation script

### PR DESCRIPTION
**Pull request by Shyam-Raghuwanshi**
## What does this PR do?

This PR is adding a script for cleaning the i18n translation files
Fixes #15623
/claim #15623

## Mandatory Tasks (DO NOT REMOVE)

- [X] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). N/A
- [X] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Shyam-Raghuwanshi** [comment]
hi @Amit91848, I got why the test are falling because when we push yarn file we need to push with --no-verify sometime then it's not fix the lint so we go errors

then i just created this PR then when we good to go i will push the yarn file because the yarn files got the conflicts easily and its hard to solve every time

**Comment by Amit91848** [comment]
Screenshot 2024-08-29 193122

@Shyam-Raghuwanshi command does not seem to be working. I did a yarn install when I switched to your branch

**Comment by Shyam-Raghuwanshi** [comment]
> Screenshot 2024-08-29 193122
> 
> @Shyam-Raghuwanshi command does not seem to be working. I did a yarn install when I switched to your branch

You should have ts-node installed in your machine like node

**Comment by Shyam-Raghuwanshi** [comment]
hi @Amit91848  you try the solution?

**Comment by Amit91848** [comment]
Thank you @Shyam-Raghuwanshi for your time and efforts but we have decided not to pursue this

**Pull request closed without merging**
