### PR TITLE
chore: downgrade react query atoms

### PR DESCRIPTION
**Pull request by supalarry**
One of platform customers uses React 16 while react-query v5 requires at least React 18, so react-query is downgraded to v4.

Only difference is that queries do not return "isPending" but "isLoading", so refactored that in code.

Tested with examples app and it runs.

### CODE REVIEW

**Review by sean-brydon — COMMENTED** [review]
I understand this works and im happy with this downgrade. Lets just make sure for context wise that we are aware isLoading !== isPending

https://github.com/TanStack/query/discussions/6297#discussioncomment-7467010

**Review by sean-brydon — CHANGES_REQUESTED** [review]
Also just spotted type check failing in embed still 

Looks like there is a use of isPending

**Comment by supalarry** [comment]
> Also just spotted type check failing in embed still
> 
> Looks like there is a use of isPending

Thanks for checking the PR! Type check now passes!

**Review by sean-brydon — APPROVED** [review]
LGTM! Thanks for making them changes - Lets keep an eye out to see if we see anything un expected with using isLoading > isPending

**Pull request merged**
