### PR TITLE
feat: element call app added

### LINKED ISSUE #10235: Please add Element Call as a conferencing app option
It is a great open source conferencing solution (my personal favorite) and I would love to see it as an option on Cal.com!

https://call.element.io/

### PR DESCRIPTION
**Pull request by suyash5053**
## What does this PR do?
Fixes #10235 
/claim #10235

 Loom Video: https://www.loom.com/share/bb6a582a277d42e383e00c88bcfacc05?sid=63c7d8e1-adbf-4856-bcfd-4c9d7e324d0a

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
Please take a look @sean-brydon @PeerRich

### CODE REVIEW

**Comment by hariombalhara** [comment]
Codewise looks good !! Thanks @suyash5053 🙏
I will fix the yarn.lock and test it and then approve.

**Comment by suyash5053** [comment]
> Codewise looks good !! Thanks @suyash5053 🙏 I will fix the yarn.lock and test it and then approve.

You're welcome. I'm glad I could help. If there's anything else needed in this PR, feel free to ask.

**Comment by suyash5053** [comment]
@hariombalhara Hey, any updates?

**Review by hariombalhara — APPROVED** [review]
All good in testing. Thanks @suyash5053. Great work !!

**Comment by pReya** [comment]
@hariombalhara How did this pass the review process? This app doesn't do anything at all. It does not create video meetings at all.

**Comment by hariombalhara** [comment]
It is a static video link app where organizer enters a fixed link for element

**Pull request merged**
