### PR TITLE
Implements copy day functionality into Availability

### LINKED ISSUE #2223: Availability time dropdown starts at random hour
### Issue Summary

When clicking into the hour dropdown in the availability schedule, the start time seems to be at a random hour so when I create a new schedule and want to move all days from 5pm to 6pm, it's very tedious. 

### Steps to Reproduce

1. Go to Availability. 
2. Edit an existing or create a new one.
3. Try to edit the time on any input.
4. You will see that where the dropdown starts is nowhere near the current time in the input.
5. Also if you type in a time and hit enter, it submits the whole form and takes you back to Availability home.

### Current behaviour
CleanShot 2022-03-21 at 10 14 40@2x

### Desired behaviour
CleanShot 2022-03-21 at 10 19 19@2x
Note: it would also be great if we didn't get that blue outline box appearing in the input

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

image
image

Fixes #2223

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Bugfix

### CODE REVIEW

**Comment by emrysal** [comment]
@PeerRich & @Jaibles especially, updates the the "Schedule" component for mainly improved mobile support and also adhere more strictly to the designs.

image
image

**Review by PeerRich — APPROVED** [review]
works almost perfect, however you need to save the availability first, before you can duplicate it: https://app.birdeatsbug.com/sessions/wDK2nwKg-DpTAgkv1iCJQEGDgkwzyWxX8Oc1-hyfVO7M

we should fix in a follow up PR

**Comment by PeerRich** [comment]
> @PeerRich & @Jaibles especially, updates the the "Schedule" component for mainly improved mobile support and also adhere more strictly to the designs.
> 
> image image

looks so much better! great refactor

**Review by alishaz-polymath — APPROVED** [review]
Unable to copy to the other days while changing it unless I save before attempting to copy. Other than that, works well. Been waiting for this for a while so super excited 🎉

**Comment by PeerRich** [comment]
> Unable to copy to the other days while changing it unless I save before attempting to copy. Other than that, works well. Been waiting for this for a while so super excited 🎉

yeah reported the same 🙌

**Comment by emrysal** [comment]
> works almost perfect, however you need to save the availability first, before you can duplicate it: https://app.birdeatsbug.com/sessions/wDK2nwKg-DpTAgkv1iCJQEGDgkwzyWxX8Oc1-hyfVO7M
> 
> we should fix in a follow up PR

This is now fixed :)

**Pull request merged**
