### PR TITLE
fix: update z-index for intercom app launcher

### LINKED ISSUE #15491: z-index: show intercom below dialogs
before:
CleanShot 2024-06-19 at 12 56 48@2x

after:
CleanShot 2024-06-19 at 12 56 31@2x

### PR DESCRIPTION
**Pull request by osamajandali**
## What does this PR do?

- Fixes #15491
- Fixes CAL-3948 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] N/A - I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] N/A -I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

This is a UI fix that should be tested by triggering a modal and make sure the modal overlap the intercom icon

### CODE REVIEW

**Comment by ThyMinimalDev** [comment]
Screenshot 2024-06-21 at 16 02 08
it seems this class already sets the highest possible z-index, in which browser is this issue happening ?

**Comment by skmanoj322** [comment]
@osamajandali i have tried to reproduce the error but not able to find intercom in dev but in production i am able to see that.
can you please tell how you reproduced?

**Comment by osamajandali** [comment]
@ThyMinimalDev if you take a look into the issue Peer want it to be underneath the modal so people can hit Copy code button easily if there is an overlap happens

@skmanoj322 You need to add intercom app id in .env

**Review by sean-brydon — APPROVED** [review]
LGTM thanks  :)

**Pull request merged**
