### PR TITLE
fix: update profile picture to be clickable on cal.com/[user]/[type]

### LINKED ISSUE #5594: [CAL-402] make profile picture clickable and go to cal.com/<user>
> From [SyncLinear.com](https://synclinear.com) | [CAL-402](https://linear.app/calcom/issue/CAL-402/make-profile-picture-clickable-and-go-to-calcomuser)

### PR DESCRIPTION
**Pull request by ShaneMaglangit**
## What does this PR do?

- UserAvatar: Derive `cal.com/<username>` link from profile and members that will be the redirect link when profile pictures are clicked.
- AvatarGroup: Accepts an optional `href` parameter. Wraps avatar in a Link tag if href is not falsey.
- AvatarSSR: Add isChild attribute to remove the `<button>` added by Radix and make cursor adapt properly (pointer for links).

Fixes #5594 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Create a new event type.
- Go to /[user].
- Click an event.
- Click profile picture on the top left corner of the card.

No automated tests were added (I don't think you have UI tests?)

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Udit-takkar** [comment]
Screenshot 2022-11-21 at 2 52 57 PM
 
there are private booking links which are meant to protect the booking page of the user.  currently after your changes the url href points to /undefined .  can you avoid passing href in case of private link ?

**Comment by ShaneMaglangit** [comment]
Sure thing! I'll revisit the PR 👌

**Comment by PeerRich** [comment]
tested so far and worked. waiting for either @alannnc or @CarinaWolli review

**Review by CarinaWolli — APPROVED** [review]
Looks good to me! Thank you for your contribution 🙏

**Pull request merged**
