### PR TITLE
using WEBAPP_URL instead of BASE_URL in constants.ts

### PR DESCRIPTION
**Pull request by servusrene**
## What does this PR do?

Using WEBAPP_URL instead of BASE_URL in constants.ts

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
i believe there is a reason for this, asking @zomars why

**Comment by zomars** [comment]
Is this is not fixing something specifically, then there's no reason to merge.

**Comment by rene-mueller** [comment]
@zomars true this does not fix a bug, but the use of a variable marked as deprecated
fyi @PeerRich

**Comment by zomars** [comment]
> @zomars right this does not fix an error, but the use of a variable marked as deprecated
> fyi @PeerRich

Thank you for your contribution 🙏 In this case it would make sense to handle all deprecation replacements in one single PR at once.

**Pull request closed without merging**
