### PR TITLE
added new teams empty screen

### LINKED ISSUE #5806: [CAL-513] /teams - Improve the empty state
[Teams Empty State 5 - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=1010%3A107690&t=TtPJpYisjxaiJsao-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-513](https://linear.app/calcom/issue/CAL-513/teams-improve-the-empty-state)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
CleanShot 2022-12-03 at 17 15 00

### CODE REVIEW

**Review by PeerRich — COMMENTED** [review]
oh, just noticed the background:
team-banner-background


 is 1.8MB. @Jaibles it must be the peoples avatars.

can you send me a low size image instead?

**Comment by PeerRich** [comment]
> oh, just noticed the background: team-banner-background
> 
> is 1.8MB. @Jaibles it must be the peoples avatars.
> 
> can you send me a low size image instead?

replaced the background with a 49kb jpg

**Comment by baileypumfleet** [comment]
I think the three boxes below should not have the gradient as the gradient is for primary things like the hero only

**Comment by PeerRich** [comment]
> I think the three boxes below should not have the gradient as the gradient is for primary things like the hero only

I followed @Jaibles designs, that's up to him

**Comment by Jaibles** [comment]
Happy to not have the gradient in the 3 boxes below and just use `bg-gray-50`

**Comment by zomars** [comment]
Should self-hosted see this screen as well? If not, can we fallback to the previous one for them?

**Comment by PeerRich** [comment]
> Should self-hosted see this screen as well? If not, can we fallback to the previous one for them?

oh right totally. i think maybe show this screen but different headline? "Work better in teams"?

**Comment by zomars** [comment]
> > Should self-hosted see this screen as well? If not, can we fallback to the previous one for them?
> 
> oh right totally. i think maybe show this screen but different headline? "Work better in teams"?

This is more tailored to our branding/marketing. I would rather have the boring empty state for self-hosted.

**Comment by PeerRich** [comment]
why? whats wrong with this for self-hosters?

**Comment by zomars** [comment]
> why? whats wrong with this for self-hosters?

Nothing. I'm just stating my view. This is more tailored to OUR branding/marketing. And trying to make white labelling as easy as possible.

**Comment by PeerRich** [comment]
the whitelabeling is a good point

**Review by zomars — APPROVED** [review]
Ship it

**Pull request merged**
