### PR TITLE
fix: Allow editing guests when rescheduling or editing a booking

### LINKED ISSUE #9167: At the time of edit or rescheduling event, there is no option to add guest
Screenshot 2023-05-29 at 9 41 00 AM

Screenshot 2023-05-29 at 9 51 16 AM

### Is your proposal related to a problem?

No, my proposal is not related to any problem

### Describe the solution you'd like

We should add "add guest" option at the time of edit or rescheduling the event.

### PR DESCRIPTION
**Pull request by jemiluv8**
## What does this PR do?
It allows users to add/remove from the gusts list when rescheduling a booking

Fixes #9167
/claim #9167

Editing Guests
https://www.loom.com/share/318584ebf2b44745a10867955a5484e8?sid=68ee2b32-9e64-4813-8587-90e13ca4dec2

Viewing New Booking Success Screen - To confirm edited guests
https://www.loom.com/share/e27797530e044f39a87bfdbf43d2adc4

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Book a meeting
- [ ] On the successful booking page click "Reschedule"
- [ ] Select new date and time for meeting
- [ ] On the confirmation screen, you should now see guests added
- [ ] You should also be able to remove existing guests and add new ones

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- ~~I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)~~
- ~~My code doesn't follow the style guidelines of this project~~
- ~~I haven't commented my code, particularly in hard-to-understand areas~~
- ~~I haven't checked if my PR needs changes to the documentation~~
- ~~I haven't checked if my changes generate no new warnings~~
- ~~I haven't added tests that prove my fix is effective or that my feature works~~
- ~~I haven't checked if new and existing unit tests pass locally with my changes~~

### CODE REVIEW

**Review by alannnc — COMMENTED** [review]
@jemiluv8 Can you help us here with a self review?
I think I should make some test for this one too. Don't want bookers can edit reschedule if not booking owner.

**Comment by jemiluv8** [comment]
@alannnc, I've completed the self review.

**Review by shivamklr — DISMISSED** [review]
Tested locally. Works as expected.

**Review by shivamklr — CHANGES_REQUESTED** [review]
@jemiluv8 Kindly resolve the conflicts.

**Comment by jemiluv8** [comment]
Merge conflicts resolved.

**Review by shivamklr — COMMENTED** [review]
LGTM.

**Review by shivamklr — APPROVED** [review]

**Pull request merged**
