### PR TITLE
Add Web Share in mobile

### LINKED ISSUE #1768: implement "web-share" on mobile devices instead of copying the event-type
this button:

image

should open the android or iOS "web share" bottom panel:

image

we can use: https://web.dev/web-share/

```
if (navigator.share) {
  navigator.share({
    title: 'web.dev',
    text: 'Check out web.dev.',
    url: 'https://web.dev/',
  })
    .then(() => console.log('Successful share'))
    .catch((error) => console.log('Error sharing', error));
}
```

### PR DESCRIPTION
**Pull request by Jenietoc**
## What does this PR do?

In this PR we added the mobile functionality to be able to share the link of an event through social networks.

Fixes #1768 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- The functionality is tested on mobile, it should be noted that Web Share is not compatible with all browsers and versions.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
> > @Jenietoc closed by accident? looks good to me, no?
> 
> 
> 
> Hi @PeerRich , I want to create a test in playwrigth if you like I will soon reopen the PR with the test.

sure but not sure if this needs a test. feel free to reopen without a test

**Comment by Jenietoc** [comment]
> > > @Jenietoc closed by accident? looks good to me, no?
> > 
> > 
> > Hi @PeerRich , I want to create a test in playwrigth if you like I will soon reopen the PR with the test.
> 
> sure but not sure if this needs a test. feel free to reopen without a test

perfect, I reopen. thank you @PeerRich

**Comment by PeerRich** [comment]
> > > > @Jenietoc closed by accident? looks good to me, no?
> 
> > > 
> 
> > > 
> 
> > > Hi @PeerRich , I want to create a test in playwrigth if you like I will soon reopen the PR with the test.
> 
> > 
> 
> > sure but not sure if this needs a test. feel free to reopen without a test
> 
> 
> 
> perfect, I reopen. thank you @PeerRich 

hey can you check this settings:

"allow mantainers to commit to the PR” so we can update the branch

**Comment by Jenietoc** [comment]
> > > > > @Jenietoc closed by accident? looks good to me, no?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Hi @PeerRich , I want to create a test in playwrigth if you like I will soon reopen the PR with the test.
> > 
> > 
> > > 
> > 
> > 
> > > sure but not sure if this needs a test. feel free to reopen without a test
> > 
> > 
> > perfect, I reopen. thank you @PeerRich
> 
> hey can you check this settings:
> 
> "allow mantainers to commit to the PR” so we can update the branch

Hi @PeerRich , I'm sorry I can't find this option, could you tell me where it is?

**Comment by zomars** [comment]
Hey @Jenietoc you can see more [info about this setting here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Review by zomars — CHANGES_REQUESTED** [review]
Some observations:
1. We have a type error
2. We will lose the copy to clipboard functionality in macOS since it supports the navigator.share API but there's no option to Copy to clipboard there.

**Comment by PeerRich** [comment]
> Some observations:
> 
> 1. We have a type error
> 
> 2. We will lose the copy to clipboard functionality in macOS since it supports the navigator.share API but there's no option to Copy to clipboard there.

oh yeah on MacOS we should copy to clipboard

**Comment by PeerRich** [comment]
getting a type error here
image

**Comment by Jenietoc** [comment]
> getting a type error here image

this removes the `This condition will always return true since this function is always defined` . do you think it solves the type error?
code

**Comment by PeerRich** [comment]
@Jenietoc saw this? 🤔


> 2. We will lose the copy to clipboard functionality in macOS since it supports the navigator.share API but there's no option to Copy to clipboard there.

**Comment by Jenietoc** [comment]
> @Jenietoc saw this? 🤔
> 
> > 2. We will lose the copy to clipboard functionality in macOS since it supports the navigator.share API but there's no option to Copy to clipboard there.

Hi @PeerRich , yes I am thinking about the solution for this problem, when I have something I will let you know immediately.

**Comment by Jenietoc** [comment]
> 2\. We will lose the copy to clipboard functionality in macOS since it supports the navigator.share API but there's no option to Copy to clipboard there.

Hi @PeerRich , the problem that is arising with MacOs is that it enters to the if of the `navigator.share` but it cannot deploy the functionality of sharing that is to say it remains without the option to share neither to copy in the clipboard, the solution that I raise is the following one in the `catch` rewrite the functionality of copying in the clipboard something to if:
codee

Let me know what you think. thank you very much

**Comment by zomars** [comment]
@Jenietoc @PeerRich How about we keep the current "copy to clipboard" button and add a new "share to" button only if the navigator supports it?

**Comment by Jenietoc** [comment]
> @Jenietoc @PeerRich How about we keep the current "copy to clipboard" button and add a new "share to" button only if the navigator supports it?

Hi @zomars , Simulating a bit what you say, keeping the `Copy link to event` button and when the browser is compatible show the `Share` button should show both buttons so MacOs users can use the `Copy link to event`. ?? 
image

**Comment by agustif** [comment]
> Hello @agustif , I will apply the `!!` to remove the alert. I have been looking for an alternative to `Navigator` but I can't find it, any ideas?

Hey there, Id rather not add an extra dependency. But a little digging shows me react-use-clipboard uses copy-to-clipboard which seems to use prompt internally.

Not sure if ok to add the dependency for such a small task. What do you think @zomars 

https://www.npmjs.com/package/react-use-clipboard

https://www.npmjs.com/package/copy-to-clipboard

There's also this more recently updated one and no internal deps

https://www.npmjs.com/package/react-hook-clipboard

**Comment by Jenietoc** [comment]
> > Hello @agustif , I will apply the `!!` to remove the alert. I have been looking for an alternative to `Navigator` but I can't find it, any ideas?
> 
> Hey there, Id rather not add an extra dependency. But a little digging shows me react-use-clipboard uses copy-to-clipboard which seems to use prompt internally.
> 
> Not sure if ok to add the dependency for such a small task. What do you think @zomars
> 
> https://www.npmjs.com/package/react-use-clipboard
> 
> https://www.npmjs.com/package/copy-to-clipboard
> 
> https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData
> 
> There's also this more recently updated one 'react-hook-clipboard' and no internal deps
> 
> https://www.npmjs.com/package/react-hook-clipboard
> 
> Seems it uses navigator too, but with some extra permission checks
> 
> https://github.com/bence-toth/react-hook-clipboard/blob/master/src/index.js

But all those dependencies is to be able to copy the link? what we need is an alternative to `navigator.share` to be able to share the link with other applications? or am I wrong?

**Comment by agustif** [comment]
> But all those dependencies is to be able to copy the link? what we need is an alternative to `navigator.share` to be able to share the link with other applications? or am I wrong?

You're correct, all those were only to see what other people where doing.

I think https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData its the most promisingon browser support

**Comment by Jenietoc** [comment]
> > ¿Pero todas esas dependencias es poder copiar el enlace? lo que necesitamos es una alternativa para `navigator.share`poder compartir el enlace con otras aplicaciones? o estoy equivocado?
> 
> Tienes razón, todo eso fue solo para ver lo que otras personas estaban haciendo.
> 
> Creo que https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData es el más prometedor en compatibilidad con navegadores .

look at this 
https://www.npmjs.com/package/react-web-share

**Comment by zomars** [comment]
> Hi @zomars , Simulating a bit what you say, keeping the `Copy link to event` button and when the browser is compatible show the `Share` button should show both buttons so MacOs users can use the `Copy link to event`. ??

That would be optimal IMO. @Jenietoc 

> Not sure if ok to add the dependency for such a small task. What do you think @zomars

We should avoid it unless strictly necessary yes. @agustif 

Let's just stick with the native navigator API for now. We could encapsulate in a `ShareButton` component and render only on browser with `useEffect`, [here's an example](https://stackoverflow.com/a/66932490/6297100). That way we don't need to use double bang in navigator variable.

**Comment by zomars** [comment]
I think I didn't made myself clear enough. The idea was to keep the "copy to clipboard" button for every one and only add the "share" button where `navigator.sharing` is available. Not replacing it.

**Comment by Jenietoc** [comment]
> I think I didn't made myself clear enough. The idea was to keep the "copy to clipboard" button for every one and only add the "share" button where `navigator.sharing` is available. Not replacing it.

I understand... then the `copy to clipboard` button should always be there and only when `navigator.share` is compatible add the `share` button without replacing the `copy to clipboard` button. 
Have both `copy to clipboard` and `share` buttons when it is compatible with `navigator.share`. ?

**Comment by zomars** [comment]
> > I think I didn't made myself clear enough. The idea was to keep the "copy to clipboard" button for every one and only add the "share" button where `navigator.sharing` is available. Not replacing it.
> 
> I understand... then the `copy to clipboard` button should always be there and only when `navigator.share` is compatible add the `share` button without replacing the `copy to clipboard` button. Have both `copy to clipboard` and `share` buttons when it is compatible with `navigator.share`. ?

Exactly, that way we don't lose any current functionality. 🙏🏽

**Comment by Jenietoc** [comment]
> > > I think I didn't made myself clear enough. The idea was to keep the "copy to clipboard" button for every one and only add the "share" button where `navigator.sharing` is available. Not replacing it.
> > 
> > 
> > I understand... then the `copy to clipboard` button should always be there and only when `navigator.share` is compatible add the `share` button without replacing the `copy to clipboard` button. Have both `copy to clipboard` and `share` buttons when it is compatible with `navigator.share`. ?
> 
> Exactly, that way we don't lose any current functionality. 🙏🏽

compatibility with navigator.share
image

no compatibility with navigator.share
image

**Comment by PeerRich** [comment]
> > > > I think I didn't made myself clear enough. The idea was to keep the "copy to clipboard" button for every one and only add the "share" button where `navigator.sharing` is available. Not replacing it.
> 
> > > 
> 
> > > 
> 
> > > I understand... then the `copy to clipboard` button should always be there and only when `navigator.share` is compatible add the `share` button without replacing the `copy to clipboard` button. Have both `copy to clipboard` and `share` buttons when it is compatible with `navigator.share`. ?
> 
> > 
> 
> > Exactly, that way we don't lose any current functionality. 🙏🏽
> 
> 
> 
> compatibility with navigator.share
> 
> image
> 
> 
> 
> no compatibility with navigator.share
> 
> image
> 
> 
> 
> 
> 
> 

great idea, lets do it.

we should us the heroicons

`<UploadIcon/>` for share

and `<ClipboardCopyIcon/>` for copy to clipboard

image

image

**Comment by Jenietoc** [comment]
image

**Comment by PeerRich** [comment]
> image

awesome lets merggeee @zomars

**Review by PeerRich — APPROVED** [review]
cool stuff

**Comment by zomars** [comment]
Will merge and monitor from here. Thank you for your contribution 🙏

**Pull request merged**
