### PR TITLE
removed imgur from emails, added missing / to footer logo

### PR DESCRIPTION
**Pull request by PeerRich**
removed imgur from emails for staging and fixed broken footer image:

image

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
This is OK for now, better proposal soonTM..

**Comment by PeerRich** [comment]
> This is OK for now, better proposal soonTM..

yea we likely wanna get rid of IS_PROD

**Comment by emrysal** [comment]
I propose we use VERCEL_URL much like NextAuth to dynamically determine the BASE_URL based on the Vercel environment, otherwise defaulting to the normal process (Also, like NextAuth) - 

https://github.com/nextauthjs/next-auth/blob/4dcdb62dcabad8cbc14a5357cf6c5690bb12c3d1/src/next/index.ts#L24

This approach will allow us to make our own install simpler by removing BASE_URL from our hosted installs - whilst still allowing the flexibility and remove the need for IS_PRODUCTION.

**Comment by PeerRich** [comment]
> I propose we use VERCEL_URL much like NextAuth to dynamically determine the BASE_URL based on the Vercel environment, otherwise defaulting to the normal process (Also, like NextAuth) -
> 
> https://github.com/nextauthjs/next-auth/blob/4dcdb62dcabad8cbc14a5357cf6c5690bb12c3d1/src/next/index.ts#L24
> 
> This approach will allow us to make our own install simpler by removing BASE_URL from our hosted installs - whilst still allowing the flexibility and remove the need for IS_PRODUCTION.

sure, wanna follow up with a PR?

**Pull request merged**
