### PR TITLE
feat: make the meeting duration time more visually toggleable

### LINKED ISSUE #15327: [CAL-3894] Make the meeting duration time more visually toggleable
### Is your proposal related to a problem?

When a user goes to book a meeting, it is not immediately obvious that there is a way for them to alter the meeting duration. Everyone knows the middle section is where you pick the date, and the list of time slots on the right clearly invites the user to pick one. However, it is not obvious to everyone that the meeting duration time on the left can be toggled. Most of the items on the left are simply metadata that are not toggleable. While the timezone can be toggled, since it's determined automatically, most won't bother. This means that people are not focusing their attention on the left panel.

image

### Describe the solution you'd like

There are some nice solutions by people on Twitter when I posted about this: https://x.com/peer_rich/status/1782166947636932930.

One suggestion: "**I would try it on the right above the time selection. Maybe reduce target size of 12hr/24hr bc that seems less important to me than duration, and might be mostly inferred by region?**"

Another suggestion was a slider of sorts that makes it clearer it can be toggled:

image

Either is reasonable to consider, but the former seems more straightforward.

### Describe alternatives you've considered

Not changing it, naturally.

##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3894](https://linear.app/calcom/issue/CAL-3894/make-the-meeting-duration-time-more-visually-toggleable)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

- Fixes #15327 
- Fixes [CAL-3894](https://linear.app/calcom/issue/CAL-3894/make-the-meeting-duration-time-more-visually-toggleable)
Screenshot 2024-06-07 023031

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Review by hariombalhara — DISMISSED** [review]
Blocked on confirmation from @ciaranha about the design

**Comment by itsberkaya** [comment]
https://www.figma.com/design/UajFu4M1APhn2AywAEJkJr/New-Features?node-id=21929-1276&m=dev

Ekran Resmi 2024-07-16 17 17 29

**Comment by anikdhabal** [comment]
@hariombalhara this is ready for review now.

**Review by Amit91848 — DISMISSED** [review]
@anikdhabal it needs some changes as it is varying from the designs. 
- There should be no border
- background and selected time colour is different from the designs for both light and dark mode

Screenshot 2024-07-18 140748


- Breaks on smaller screen (I had selected 14 Pro Max here)
- Duration becomes vertical. Times are going of the screen instead of going to the next line.

Screenshot 2024-07-18 140816

**Comment by anikdhabal** [comment]
> @anikdhabal it needs some changes as it is varying from the designs.
> 
> * There should be no border
> * background and selected time colour is different from the designs for both light and dark mode

Hey, we have our own ToggleGroup component that follows the same design and style throughout our app. I haven't added any external styles. The Figma files show a ToggleGroup design that differs from our app. For example, look at other components like time format and calendar view; they are also different compared to our app

Currently, the only thing that needs fixing is the problem on small screens

**Review by Udit-takkar — COMMENTED** [review]
@anikdhabal i fixed the e2e test "dynamic booking info prefilled by query params". It was failing because disabled property didn't exist on ToggleGroup button which you were trying to get. i just added a new property data-active to get the active duration like we did previously

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
you can't prefill 45 minutes on dynamic bookings links for some reason.

https://github.com/user-attachments/assets/94e0a123-12ae-4e6c-8243-bd88e8d0f547

**Comment by anikdhabal** [comment]
@Udit-takkar thanks for fixing the E2E, and I will address the issue you mentioned

**Comment by anikdhabal** [comment]
@udit, thanks for fixing the e2e. I found that the issue did not arise due to the changes in this PR; it was present before

https://github.com/user-attachments/assets/ef14ddf0-39df-4e90-b140-51b53f5ec764

**Comment by anikdhabal** [comment]
Fixed the problem. All things are up now.

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
UI isn't responsive. maybe @itsberkaya can help here

Screenshot 2024-07-25 at 7 31 56 PM

**Review by Udit-takkar — COMMENTED** [review]
@anikdhabal Great work. 

Can you also make sure that the selected duration is visible on page load? Like if default duration/duration in query param is 60m then 60m should be visible 

https://github.com/user-attachments/assets/9cec3511-91c3-4ed8-a852-0eccdde4f587

**Comment by anikdhabal** [comment]
> Can you also make sure that the selected duration is visible on page load? Like if default duration/duration in query param is 60m then 60m should be visible

Sure Udit, that would be great

**Review by Udit-takkar — COMMENTED** [review]
https://github.com/user-attachments/assets/eb55f2a1-633e-40bf-9f52-53aeae026c27

@anikdhabal still not fixed

**Comment by anikdhabal** [comment]
@Udit-takkar thanks, it works now

https://github.com/user-attachments/assets/dcf2155b-f4da-4844-9ced-725634fe743b

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Pull request merged**
