### PR TITLE
fixes #17536 : When expanding Reason for rejecting text box button doesn't move and obscures the box 

### LINKED ISSUE #17536: When expanding Reason for rejecting text box button doesn't move and obscures the box
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When expanding Reason for rejecting text box button doesn't move and obscures the box

### Steps to Reproduce

1. Go to a booking I need to reject
2. Write a long reason, expand the text box so I can see it all
3. Get frustrated by the buttons obscuring the text box like this:

Screenshot 2024-11-07 115122

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- see screenshot above

### Expected Results

-  the buttons should move when expanding the text box

### Technical details

- This is using the hosted cal.com version with the latest Chrome on Windows 11

### Evidence

- see screenshot above

### PR DESCRIPTION
**Pull request by Prajyot05**
## What does this PR do?

This PR fixes the position of the buttons when expanding the text box.

- Fixes #17536 (GitHub issue number)

Video showing the final result:

https://github.com/user-attachments/assets/0fb8497e-19d6-4d8f-b8ef-8b3975f63427

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Praashh** [comment]
Hey @Prajyot05 can you please sign the CLA?

**Review by Praashh — COMMENTED** [review]
hey @Prajyot05, it's working fine, don't think we need this atm. Thanks for your contribution.

**Comment by Prajyot05** [comment]
alright, no problem

**Comment by Prajyot05** [comment]
should I close the PR?

**Comment by Praashh** [comment]
closing it for now.

**Pull request closed without merging**
