### PR TITLE
respect local set timezone and update url on mismatch

### LINKED ISSUE #2482: Bug when checking availability and switching time zones
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When trying to book an event, if I switch the time zone before clicking a specific date, then the proposed times do not update to the correct time zone.

### Steps to Reproduce

1. Go to any cal.com invite link.
2. Select a time zone different from the default _before_ selecting a date.
3. Select a date.

Notice that the proposed times are not updated, even though the time zone at the left reflects the updated time zone. Reselecting a time zone also does not help.

### Technical details

Using latest version of Google Chrome in Incognito mode.

### PR DESCRIPTION
**Pull request by buschco**
### 1. will keep `timeZone()` and the offset from url in sync. 

If URL offset does not match local set `timeZone()`, the URL will be fixed. However if we want, we can  
- either maintain a list of offsets to timezones and set the `timeZone()`
- add another query param representing the timezone (this would be a breaking change tho)

### 2. Ensure the local selected timezone will make its way to the URL
If no date is selected, the URL contains no offset. By selecting the first date, the local set timezone (`timeZone()`) will be used.

Fixes [#2482](https://github.com/calcom/cal.com/issues/2482)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Test A 

1. Go to booking page
2. Select a time zone different from the default before selecting a date.
3. Select a date.

=> now the offset from the picker and the offset in the URL should match. Also the timeslots should be in the right timezone.

- [x] Test B

1. Go to booking page
2. Select a time zone
3. Select a date
4. Modify the URL (eg: `http://localhost:3000/free/30min?date=2022-04-18%2B0300` -> `http://localhost:3000/free/30min?date=2022-04-18%2B0100`)

=> the effect should trigger and the URL will be changed back (`http://localhost:3000/free/30min?date=2022-04-18%2B0300`)

=> now the offset from the picker and the offset in the URL should match. Also the timeslots should be in the right timezone.

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
Looks good to me! I've considered both options in the past, and I lean most to introducing a new URL parameter (and ditch localStorage entirely). 

The other option aligns most with a library we are using: https://github.com/ndom91/react-timezone-select, have a look if you see something interesting there.

Thank you!

**Comment by buschco** [comment]
@emrysal thanks for the feedback 🙏 
I just noticed that https://github.com/ndom91/react-timezone-select exports all the timezones, so another query param would be possible without maintaining a list of timezones 🎉 

I might look into building this if the breaking change in the URLs is no big problem 🙃

**Review by alishaz-polymath — APPROVED** [review]
Looks good. Thanks for your contribution! 🙏

**Comment by buschco** [comment]
@alishaz-polymath can this be merged? 🙏

**Comment by alishaz-polymath** [comment]
> @alishaz-polymath can this be merged? 🙏

Yeah, there are a couple of failed e2e tests (unrelated to your changes, I'm certain, but we need to wait until they pass). Once that's set, I'll proceed with the deployment and subsequently merge. :)

**Comment by hariombalhara** [comment]
@buschco Would try to merge it today. Rerunning tests.

**Review by zomars — APPROVED** [review]

**Pull request merged**
