### PR TITLE
fix: If Invalid Calendar Credentials Then Skip Listing Calendars [CAL-2340]

### LINKED ISSUE #10719: [CAL-2340] Unable to remove failed GCal connection
[https://app.birdeatsbug.com/sessions/wQSg5sU5TAdfBFG8XTp1dmFkZfnPwhAKNwkUZ2--RXdY](https://app.birdeatsbug.com/sessions/wQSg5sU5TAdfBFG8XTp1dmFkZfnPwhAKNwkUZ2--RXdY)

Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=bdd8c76b-1c7f-4a90-942a-e6826edf082d](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=bdd8c76b-1c7f-4a90-942a-e6826edf082d)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2340](https://linear.app/calcom/issue/CAL-2340/unable-to-remove-failed-gcal-connection)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR wraps listing deleted selected calendars in a try/catch block so if the credentials are invalid the user are still able to delete the calendar app.

Fixes #10719 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Add GCal
- In the DB manipulate the access token to make it an invalid credential
- Delete the integration

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pumfleet — APPROVED** [review]
Read through code and it looks good to me

**Comment by zomars** [comment]
>  so if the credentials are invalid the user are still able to delete the calendar app.

What are invalid credentials in this context? Does this means that invalid credentials cannot be deleted anymore?

**Comment by emrysal** [comment]
@zomars rather the other way around in this case, when deleting a credential, selectedCalendar would be removed first which triggered an error - crashing credential deletion.

**Comment by joeauyeung** [comment]
> @zomars rather the other way around in this case, when deleting a credential, selectedCalendar would be removed first which triggered an error - crashing credential deletion. @joeauyeung how does a user get rid of the selectedCalendar?

Let's say that a user sees an error on the calendar page that there was an error fetching their calendar and to reinstall the integration. If there was a problem with fetching their calendars to begin without, without the try/catch block it would throw an error saying that calendars could not be retrieved. @zomars @emrysal

**Pull request merged**
