### PR TITLE
Feature/multiple schedules post turbo

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

This implements availability schedules, which introduces a one-to-many relation between entities. So before where you had:

**before**:
user->availability
user->timeZone
eventType->availability
eventType->timeZone

**after**:
user->schedule->availability,timeZone
eventType->schedule->availability,timeZone
         
The Schedule table has been re-used, as it has been deprecated a long time ago.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How should this be tested?

Run migrations, go to /availability

## Feedback

> Zomars questions (Rel. backwards compatibility)
> 
> 1. What's going to happen to currently set availabilities?
> 2. Will each user is going to have to set they new Schedules?
> 3. What happens if an user doesn't do it?
> 4. If we merge as it is, will users experience undesired behavior until they set up their Schedules?
> 5. Can we migrate in a way that users don't have to do anything before hand?
> 6. EventType Availabilities are gone, will this break those blocked times until user actions is performed?

The way it currently works is that existing eventType.availability and user.availability are second class - but still functional (1,5,6). When there is no schedule set (neither default or otherwise) it will default to legacy (2,3); ensuring that no users will break until they themselves create a new schedule (4), after which the new system will take over.

- [ ] getting started availability should create my default availability with Default name
- [ ] can we use uuid as availability id when edit?
- [ ] In availability name change: can we display as boxed input while editing
It's currently consistent with Event Type name change - but I have talked to @PeerRich before about this so we may want to change this in both spots.
- [x] availability section in /event-type doesn't takes much space now, should we move it before advanced settings?
Up to @PeerRich 
- [ ] long availability names pushes actions buttons away

### CODE REVIEW

**Comment by baileypumfleet** [comment]
There's no empty state on the availability page yet

**Comment by baileypumfleet** [comment]
There's no empty state on the availability page yet

**Comment by baileypumfleet** [comment]
I notice that default is lowercase, is this due to no localization string? Also, delete_schedule is not localized yet

**Comment by baileypumfleet** [comment]
I notice that default is lowercase, is this due to no localization string? Also, delete_schedule is not localized yet

**Comment by baileypumfleet** [comment]
Screenshot 2022-03-15 at 16 39 54

The radio buttons are now somehow broken

**Comment by baileypumfleet** [comment]
Screenshot 2022-03-15 at 16 39 54

The radio buttons are now somehow broken

**Comment by emrysal** [comment]
> The radio buttons are now somehow broken

Fixed

> I notice that default is lowercase, is this due to no localization string? Also, delete_schedule is not localized yet

Yeah entirely correct; missed that because "default" reads like it's translated.

> There's no empty state on the availability page yet

What do we want the "Default" to be? Currently when you add a new schedule it's just entirely empty.

**Review by zomars — COMMENTED** [review]
Removed index renames from migration (and moved them to #2162), will re-redeploy to test out.

**Review by zomars — CHANGES_REQUESTED** [review]
Tested and is working flawlessly. Will block merge until we clarify these questions:
- What's going to happen to currently set availabilities?
- Will each user is going to have to set they new Schedules?
- What happens if an user doesn't do it?
- If we merge as it is, will users experience undesired behavior until they set up their Schedules?
- Can we migrate in a way that users don't have to do anything before hand?
- EventType Availabilities are gone, will this break those blocked times until user actions is performed?

**Review by alannnc — COMMENTED** [review]
It's working great!! 👍 
A few things I found
- getting started availability should create my default availability with Default name
- can we use uuid as availability id when edit?
- In availability name change: can we display as boxed input while editing
- availability section in /event-type doesn't takes much space now, should we move it before advanced settings?
- long availability names pushes actions buttons away

image

**Review by zomars — APPROVED** [review]

**Review by PeerRich — APPROVED** [review]
awesome! loom video is great

**Review by pumfleet — APPROVED** [review]
Testing works fine for me, and code looks good

**Comment by PeerRich** [comment]
> availability section in /event-type doesn't takes much space now, should we move it before advanced settings?

yes, as intended in the figma: https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/Cal-Web-App?node-id=3412%3A41822

image

**Comment by baileypumfleet** [comment]
Let's do that as a follow-up PR rather than blocking this

**Comment by zomars** [comment]
Will deploy to staging to test.

**Comment by PeerRich** [comment]
image

NIT: lack of padding and I believe we have an` <EmptyScreen/>` component already no?

**Comment by PeerRich** [comment]
every account will start by default with a "Working Hours" default schedule right?

**Comment by PeerRich** [comment]
missing padding left on mobile 

image

**Comment by PeerRich** [comment]
weird scroll behavior, maybe some h-full or similar usage?
https://user-images.githubusercontent.com/8019099/158845888-c1b84f98-e8f0-46db-a7c6-0955e75e258b.MOV

**Pull request merged**
