### PR TITLE
WIP: SIU: Maximum call stack size exceeded fix?

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

- It seems that we have a circular import/function/dependency that the TS wasn't catching before
- The main suspect relies on `@calcom/ui`
- No other PRs will pass the type checks until the issue is found and resolved.
- Tried to solve most imports that I've found but still getting the `Maximum call stack size exceeded` error

Here's a comment describing a way to debug this: https://github.com/microsoft/TypeScript/issues/40819#issuecomment-700379873

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] `yarn type-check --filter=@calcom/ui`
- [ ] `yarn type-check`

### CODE REVIEW

**Comment by zomars** [comment]
Turns our prisma client extensions is way too much for our TS codebase. Fixed by doing this

image

**Review by joeauyeung — APPROVED** [review]
Assuming that all the changes are just import fixes and it's just the schema file that needed changing, LGTM.

**Review by emrysal — CHANGES_REQUESTED** [review]
Some instances remain of `import { Icon } from '../icon';` which shouldn't be used anymore (instead using the icons directly).

**Comment by zomars** [comment]
Will fix types in a bit

**Review by emrysal — APPROVED** [review]

**Pull request merged**
