### PR TITLE
fix: usage of CAL_URL

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes reverts this PR https://github.com/calcom/cal.com/pull/12973

https://threads.com/thread/34561538856/34561538859?s=dUJjVzSUcZCeQtprQ7CdUc

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by alishaz-polymath — APPROVED** [review]

**Review by PeerRich — DISMISSED** [review]

**Review by alishaz-polymath — DISMISSED** [review]
Holding off the revert until further discussions conclude. Please wait 🙏

**Comment by keithwillcode** [comment]
Converted back to draft while until decision is made

**Review by keithwillcode — CHANGES_REQUESTED** [review]
Merge conflicts, failing type checks

**Review by keithwillcode — DISMISSED** [review]

**Comment by Udit-takkar** [comment]
@keithwillcode we should wait for @zomars or @hariombalhara  approval before merging

**Comment by hariombalhara** [comment]
I still don't think we should revert this.

Also, if we need to revert this, it should just be the changes you made in the PR https://github.com/calcom/cal.com/pull/12973. Right now it seem to be doing a complete replacement of CAL_URL.

Also, CAL_URL handles the case of our previews, where website isn't setup and then we use WEBAPP_URL only. We need to consider that in any new approach that we use.

Are there any more reports of broken links except the one case reported on threads?

**Review by hariombalhara — DISMISSED** [review]
Left a comment

**Comment by keithwillcode** [comment]
@hariombalhara @Udit-takkar @zomars What do we need to do to move forward on this one?

**Review by zomars — APPROVED** [review]
Fixed conflicts. LGTM

**Comment by keithwillcode** [comment]
@zomars So merging this as is addresses @hariombalhara concerns?

**Comment by zomars** [comment]
Seems like we have regression of this fix #10172

**Pull request merged**
