### PR TITLE
feat: App Lever.co

### LINKED ISSUE #3717: App: Lever.co
similar to Greenhouse

### PR DESCRIPTION
**Pull request by suyash5053**
## What does this PR do?

Fixes #3717 
/claim #3717 

Seeking review for the code, if any changes are needed please let me know.

## Type of change

- New feature (non-breaking change which adds functionality)
- This change might require a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't checked if my PR needs changes to the documentation
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by keithwillcode — CHANGES_REQUESTED** [review]
Type check, linter and unit tests are failing.

**Comment by suyash5053** [comment]
> Type check, linter and unit tests are failing.

Hey @keithwillcode, thanks for the review, 
the tests and lints are failing because I accidenly commited a different yarn.lock, which was not neede and then due to that I deleted the whole yarn.lock file.

**Review by Udit-takkar — COMMENTED** [review]
@suyash5053 to undo yarn.lock changes 

 git checkout origin/main -- yarn.lock
 
 then push that yarn.lock file

**Review by joeauyeung — CHANGES_REQUESTED** [review]
Thanks for your contribution @suyash5053.

I noticed one of the app keys needed is `userId`. This isn't scalable because those keys are applied to all users that use the app. 

Ideally we would authenticate through OAuth

**Comment by suyash5053** [comment]
> Thanks for your contribution @suyash5053.
> 
> I noticed one of the app keys needed is `userId`. This isn't scalable because those keys are applied to all users that use the app.
> 
> Ideally we would authenticate through OAuth


Hey @joeauyeung,

I've considered your input, and I'm on the same page. I thought for the initial version, I thought moving forward with the base version is the best step. However, I'm committed to enhancing the authentication process soon, transitioning to OAuth. Thanks for your valuable review and feedback!

**Comment by Amit91848** [comment]
@suyash5053 closing this because of inactivity, feel free to reopen or open a new one once you incorporate changes for OAuth

**Pull request closed without merging**
