### PR TITLE
Fix/canceled rescheduled events not updated in calendar

### LINKED ISSUE #2009: Rescheduled/Cancelled Events Showing on Google Calendar
### Issue Summary

I would like to report a bug (or feature request) with Cal.

One of my clients scheduled and cancelled an event with me. When I went to check on my Google Calendar, I noticed the event was showing on my schedule. In other words, Cal did not delete my Google Calendar event.

I assume that Cal has user permissions to delete events on Google Calendar. If so, then the event should be deleted and should not appear on my schedule.

If Cal does not have user permissions to delete events on Google Calendar, then it would be great if Cal user interface shows “allow Cal to modify or delete events”.

cal-bug

### Steps to Reproduce

When I clicked on the “Need to reschedule or cancel” link, I saw that the “This booking was already cancelled.”

cal-bug-2

### Technical details

I assume this is a Cal app permission issue with Google Calendar.

### LINKED ISSUE #2170: Unpaid/Unconfirmed bookings should not block availability
### Issue Summary

Found out that unconfirmed/unpaid bookings are blocking availability when they should only do if they're confirmed/paid.

### Steps to Reproduce

1. Connect a Stripe account
2. Create a priced event type
3. Remove Stripe account (so we can trigger an error)
4. Try to book paid event type
5. You'll get this error `ERROR [api] book:user Creating payment failed`
6. Try to book again, you'll get this error:
    ```sh
    10:34:57.582 timeZoneName DEBUG [api] book:user Booking Pro Example failed
    {
      errorCode: 'BookingUserUnAvailable',
      message: 'Pro Example is unavailable at this time.'
    }
    ```
7. Go to `/bookings` you'll se and unconfirmed/unpaid booking

### PR DESCRIPTION
**Pull request by andreaestefania12**
## What does this PR do?

Fixes #2009 #2434

I noticed that this issue happens when you change the destination calendar, so if you saved a reservation in the "Primary" calendar and then changed the destination calendar to "Birthday" when you want to reschedule or cancel the booking, the app will try to look for the booking in `Birthday` because that is the target calendar you have at the moment.

Fixed bug when an event is rescheduled or canceled, it is updated only in the database and not in Google Calendar.
To solve this issue I edited the Booking model in `packages/prisma/schema.prisma`, and CalendarEvent 
 interface in `packages/types/Calendar.d.ts`, adding to them `externalIdCalendar`  element, this is going to save the id from the calendar where the booking was saved.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How should this be tested?

- Create a booking with the primary calendar and go to Google Calendar to check.
- Change the destination calendar.
- Try to cancel or reschedule the booking. Go to Google Calendar and you going to see the booking was updated or deleted

### CODE REVIEW

**Comment by joeauyeung** [comment]
Hey @andreaestefania12 thanks for looking into this. I'm wondering instead of adding `externalIdCalendar` to the booking schema we could just write that id to the `DestinationCalendar` schema instead. It looks like that was the original idea but it somehow got lost.

**Comment by joeauyeung** [comment]
Hey @andreaestefania12, thanks again for the PR. Since we're still seeing the error and some time has passed I can take it over from here. Thanks again for your contribution!

**Comment by andreaestefania12** [comment]
> Hey @andreaestefania12 thanks for looking into this. I'm wondering instead of adding `externalIdCalendar` to the booking schema we could just write that id to the `DestinationCalendar` schema instead. It looks like that was the original idea but it somehow got lost.

Hey @joeauyeung, I added to the booking schema because in DestinationCalendar schema the externalId changes every time that you change your DestinationCalendar,  so when you want to cancel or reschedule a booking that was saved to a different calendar than the one you have now, the project is going to look the booking in the DestinationCalendar saved and not in the one that was saved the booking.

**Comment by zomars** [comment]
Closed in favor of #2671

**Pull request closed without merging**
