### PR TITLE
fix: background-colors-in-dark-mode

### LINKED ISSUE #10883: [CAL-2373] Dark mode badges
Current Badges:-

the badges should have different colours in dark mode. figma [https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=37611-2419&mode=design&t=HFnrHHX2EdFAec3N-0](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=37611-2419&mode=design&t=HFnrHHX2EdFAec3N-0)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2373](https://linear.app/calcom/issue/CAL-2373/dark-mode-badges)</sub>

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
## What does this PR do?

This PR fixes the background colors in dark mode as per figma.

Fixes #10883 

## Requirement/Documentation

https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=37611-2419&mode=design&t=HFnrHHX2EdFAec3N-0

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ijishnupr** [comment]
can i do it?

**Comment by ujwalkumar1995** [comment]
Hey Folks,
Could someone please review this PR and let me know if anything needs to be changed on this?

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
Screenshot 2023-08-28 at 7 17 57 PM

text color not visible

**Comment by ujwalkumar1995** [comment]
Hey @Udit-takkar 
Thanks for the review. Have fixed the text colours.

**Comment by Udit-takkar** [comment]
same issue https://github.com/calcom/cal.com/pull/10901#pullrequestreview-1598666080

**Comment by ujwalkumar1995** [comment]
Hey @Udit-takkar 
We can fix all the occurrences of the global css so it does not break anything. I think that might be a bit overkill. Another possible fix I could think of is to modify the css for the Badge component something like what we have already for the grayWithoutHover variant for badge. Not sure if we can get the exact colours as mentioned in figma with this approach.  Let me know what do you feel on the approach and if you have any other suggestions.
```
grayWithoutHover: "bg-gray-100 text-gray-800 dark:bg-darkgray-200 dark:text-darkgray-800"
```

**Review by Udit-takkar — COMMENTED** [review]
this PR https://github.com/calcom/cal.com/pull/11004 fixes the issue

**Pull request closed without merging**
