### PR TITLE
add checkbox for send confirmation after event booking

### PR DESCRIPTION
**Pull request by dezerb**
## What does this PR do?
Add possibility to disable standard mail notification after event booking.

Fixes # (issue)
https://github.com/calcom/cal.com/issues/3680

By default it is unchecked
Screenshot 2022-08-05 at 2 15 05 PM

**Environment**: Staging(main branch) / Production

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by PeerRich** [comment]
as I mentioned before, I think it would be better if it is negated and default false

"Don't send confirmation"

**Comment by PeerRich** [comment]
it's better to have no check box checked initially, if that makes sense?

**Comment by dezerb** [comment]
@PeerRich it's make perfect sense, I will make adjustment ;)

**Comment by dezerb** [comment]
updated
https://www.loom.com/share/93b27bbfa00d45888e4de46675d823c0

**Comment by hariombalhara** [comment]
@dezerb Thanks for your contribution 🙏

This is the behaviour right now @PeerRich.

Once I select the option(which is by default unchecked)
- On a booking, no email is sent
- On cancellation, emails are sent as usual
- On rescheduling, no email is sent.
- On Request Reschedule, emails are sent as usual.

I am a little confused as to the usage of this option. What if the user wants to set up his own cancellation email? Do we give a separate checkbox then?

Also, because confirmation emails are important to be sent, it should somehow be made more clear to user(what if he checks this option and forgets to setup his own emails). Maybe we can integrate it with Workflows more seamlessly, automatically detecting that confirmation/cancellation emails are setup so that it is foolproof.

**Comment by PeerRich** [comment]
> @dezerb Thanks for your contribution 🙏
> 
> This is the behaviour right now @PeerRich.
> 
> Once I select the option(which is by default unchecked)
> 
> * On a booking, no email is sent
> * On cancellation, emails are sent as usual
> * On rescheduling, no email is sent.
> * On Request Reschedule, emails are sent as usual.
> 
> I am a little confused as to the usage of this option. What if the user wants to set up his own cancellation email? Do we give a separate checkbox then?
> 
> Also, because confirmation emails are important to be sent, it should somehow be made more clear to user(what if he checks this option and forgets to setup his own emails). Maybe we can integrate it with Workflows more seamlessly, automatically detecting that custom confirmation/cancellation emails are setup and then this option can be automatically checked or allowed to be checked.

yeah, now that i think about it, i don't think you should be able to disable such core functionality.

i think a better alternative would be to customise the email which then overwrites the old confirmation mail

this feature has a lot of risks of unintended misbehavior

**Comment by CarinaWolli** [comment]
> yeah, now that i think about it, i don't think you should be able to disable such core functionality.
> 
> i think a better alternative would be to customise the email which then overwrites the old confirmation mail
> 
> this feature has a lot of risks of unintended misbehavior

@PeerRich  What about putting it into workflows? So once a user creates a workflow with the trigger 'when event is created' and the action 'Send email to ...' we show a checkbox that asks if the user wants to disable the standard confirmation email?

**Comment by dezerb** [comment]
@hariombalhara @PeerRich  @CarinaWolli 
in last iteration I introduced some new approach. 
While confirming the booking the backend will check if there is a suitable workflow and if so, it will skip the default notification. Thus, no new checkbox is required, assuming if someone has created a workflow, he does not need a standard confirmation.
Please take a look and comment.

**Comment by hariombalhara** [comment]
I would leave it to @CarinaWolli to decide on the approach as she owns workflows.

**Comment by PeerRich** [comment]
> I would leave it to @CarinaWolli to decide on the approach as she owns workflows.

I think its a good idea to have the checkbox in workflows to replace the default mail. that's where you would expect it

**Comment by dezerb** [comment]
@PeerRich ok I will take care about that and introduce the new checkbox. Should it be b default checked?

**Comment by PeerRich** [comment]
> @PeerRich ok I will take care about that and introduce the new checkbox. Should it be b default checked?

default: off

**Comment by dezerb** [comment]
@PeerRich  updated
https://www.loom.com/share/75f63bf46b85438b8dccfd0a1b312a22

**Comment by CarinaWolli** [comment]
@Jaibles Can you take a look at this? https://www.loom.com/share/75f63bf46b85438b8dccfd0a1b312a22
I think the should adjust the text and design a little bit

**Review by zomars — COMMENTED** [review]
Code LGTM. Delegating my approval to @CarinaWolli since she owns workflows and @Jaibles since it's a core product change

**Review by CarinaWolli — COMMENTED** [review]
Code looks good to me and it works as expected 👍  But I think we need to rethink the design. Currently, we have an issue when we have the same action more than once:

Screenshot 2022-08-12 at 20 22 35
 
It will also be hard to keep track for what event types the confirmation email is disabled (especially if you have several active workflows). So thinking of the v2 design, it would probably be best to somehow add this to the event-type settings in the workflow tab. @Jaibles What do you think?

**Comment by PeerRich** [comment]
closing for now, moving to 2.1

**Pull request closed without merging**
