### PR TITLE
feat: Expose booking created at in v2 API response

### LINKED ISSUE #10670: Add "create time" to the /bookings responses
### Is your proposal related to a problem?

I am currently using web hooks to find out when bookings are completed but in the event of a missed webhook by Cal or my receiver, there doesn't seem to be anyway to see the timestamp of when the attendee made the booking in the app or API

### Describe the solution you'd like

Something like a `created_time` in the booking record

(Describe your proposed solution here.)

### Describe alternatives you've considered

I'm sure some people will like having the timestamp of other events like the organizer approval or reschedule but my purpose is only when the booking is initiated by the attendee.

### Additional context

n/a

### Requirement/Document

n/a

### PR DESCRIPTION
**Pull request by asadath1395**
## What does this PR do?

Expose booking created at in v2 API response

- Fixes #10670 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
Run the v2 API and checking the response for `/v2/bookings` and `/v2/bookings/{uid}`, you should see the `createdAt` in the response

### CODE REVIEW

**Review by anikdhabal — DISMISSED** [review]
Hey @asadath1395 thanks for your work. Let's just focus on the API for now. Will focus on the UI later

**Comment by asadath1395** [comment]
Hey @anikdhabal 
Remove UI related changes from the PR, please review and let me know if you find anything. Thanks!

**Comment by supalarry** [comment]
Great job! One last thing to do is to update e2e tests by adding "createdAt" in the expect statements. When booking is created we expect its  defined and when fetching we check its exact value.

You can add the checks to "apps/api/v2/src/ee/bookings/2024-08-13/controllers/user-bookings.controller.e2e-spec.ts" - just couple is fine - when creating booking, when fetching individual booking, when fetching all bookings and when updating.

Thank you! 🙏

**Comment by asadath1395** [comment]
@supalarry I am seeing a lot of errors when running the v2 API now, so the tests are failing for me locally, are you aware of those?

**Comment by supalarry** [comment]
> @supalarry I am seeing a lot of errors when running the v2 API now, so the tests are failing for me locally, are you aware of those?

Can you:
1. Run `yarn install` to install latest dependencies
2. Rebuild types package `yarn workspace @calcom/platform-types build`

let me know if it resolves the issues

**Comment by asadath1395** [comment]
> > @supalarry I am seeing a lot of errors when running the v2 API now, so the tests are failing for me locally, are you aware of those?
> 
> Can you:
> 
> 1. Run `yarn install` to install latest dependencies
> 2. Rebuild types package `yarn workspace @calcom/platform-types build`
> 
> let me know if it resolves the issues

It did work, thank you!. I have added tests to validate `createdAt` for creating a booking and fetching individual booking. I couldn't find any tests for updating a booking, did you mean re-scheduling?

**Comment by supalarry** [comment]
> > > @supalarry I am seeing a lot of errors when running the v2 API now, so the tests are failing for me locally, are you aware of those?
> > 
> > 
> > Can you:
> > 
> > 1. Run `yarn install` to install latest dependencies
> > 2. Rebuild types package `yarn workspace @calcom/platform-types build`
> > 
> > let me know if it resolves the issues
> 
> It did work, thank you!. I have added tests to validate `createdAt` for creating a booking and fetching individual booking. I couldn't find any tests for updating a booking, did you mean re-scheduling?

Great work thank your for adding the tests! Yes I meant rescheduling.

**Comment by asadath1395** [comment]
@supalarry Added tests, please review whenever you get time. Thanks :)

**Review by supalarry — DISMISSED** [review]
Great work Anwar! Thank your for your help!

**Review by Praashh — DISMISSED** [review]
LGTM!! thank you so much for your contribution @asadath1395 🙏

**Comment by anikdhabal** [comment]
@asadath1395 pls fix the conflicts

**Review by Praashh — APPROVED** [review]
Let's go now.

**Pull request merged**
