### PR TITLE
chore: adds future opt-in banner for ADMINS only

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

- Allows ADMINs of the Cal.com Instance to override the middleware so we can opt-in for future app dir routes so we can start testing on prod.

image

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by zomars** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #13315** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/13315?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/13315?utm_source=stack-comment).

**Comment by PeerRich** [comment]
curious why cal.com admins only not more people?

**Comment by zomars** [comment]
> curious why cal.com admins only not more people?

For now. It is prone to break so we should test carefully before releasing to more users.

**Comment by supalarry** [comment]
> > curious why cal.com admins only not more people?
> 
> For now. It is prone to break so we should test carefully before releasing to more users.

Should we also add "X" close button to the `UserV2OptInBanner` that sets a cookie with an expiration of let's say a month - if a user does not want to try out the new version, then the banner will be there. We want that at some point users switch to the new version though - and if the cookie is set don't show `UserV2OptInBanner`.

**Comment by supalarry** [comment]
❓ I want to test this locally, but given a user with ADMIN role I do not see the banner appearing. What else do I need to enable to see the banner?

**Comment by zomars** [comment]
> ❓ I want to test this locally, but given a user with ADMIN role I do not see the banner appearing. What else do I need to enable to see the banner?

Are you running on dev mode?

**Comment by supalarry** [comment]
> ❓ I want to test this locally, but given a user with ADMIN role I do not see the banner appearing. What else do I need to enable to see the banner?

Could test after logging out and in and session data was updated so check `if (session.data?.user.role !== "ADMIN") return null;` could be passed.

**Review by supalarry — APPROVED** [review]
Code looks good and works locally too!

**Review by keithwillcode — DISMISSED** [review]
Availability E2E test is consistently failing

**Pull request merged**
