### PR TITLE
fix: remove app dialog while removing installed calendar

### LINKED ISSUE #10179: Delete modal style issue for Calendar apps.
### Issue Summary
The styling for the Calendar app delete modal is broken.

### Steps to Reproduce
1. Delete a calendar app.

### Actual Results
Monosnap Installed Apps | Cal com 2023-07-16 10-59-06

### Expected Results
Monosnap Installed Apps | Cal com 2023-07-16 11-00-03

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
## What does this PR do?

This PR fixes the alignment of remove app dialog while removing an installed calendar.

Fixes #10179 

https://github.com/calcom/cal.com/assets/20976813/70ea1588-bcb7-4d76-9e2f-ccd43648ae69

## Requirement/Documentation

N/A

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

  Try to remove an installed calendar app. The alignment of the remove app dialog should be as per designs. 

## Mandatory Tasks

  - [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@ujwalkumar1995 Dialog works fine. I found few more dialogs that needs to be fixed so I'll update in this PR

**Comment by ujwalkumar1995** [comment]
Hey @Udit-takkar 
Thanks for the review.
Do you have a list or any plan on what other dialog needs to be updated?
Would be happy to help to fix those.

**Comment by Udit-takkar** [comment]
Screenshot 2023-07-18 at 11 22 07 PM

Create webhook dialog.

we would have to try each dialog to check if looks fine or not

**Review by zomars — DISMISSED** [review]
LGTM

**Review by Udit-takkar — DISMISSED** [review]

**Review by emrysal — APPROVED** [review]
Re-approve after main merge.

**Pull request merged**
