### PR TITLE
ci: add Azure Static Web Apps workflow file

### PR DESCRIPTION
**Pull request by priyanshikathuria**
on-behalf-of: @Azure opensource@microsoft.com

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
can you explain in detail what this is and why we should add it?

**Comment by priyanshikathuria** [comment]
Hi peer,

I'm honestly so sorry to put you through a meaningless ping!
Consider me a novice! I'm simply exploring azure and learning my way
through deploying an application!

I came across Cal.com and it seems like a wonderful project to undertake,
and pretty OBVIOUSLY I'm struggling!

So ignore the ping, and in case you can help me with some documentation
other than that on GitHub, which would help me simpify the deployment plz
PLZ PLZ send it over!

I would be truly grateful!

Warm Regards

**Comment by PeerRich** [comment]
docs.cal.com

**Comment by priyanshikathuria** [comment]
Thank you!

**Pull request closed without merging**
