### PR TITLE
fix: fix ui overflow on phone for calendar settings

### LINKED ISSUE #16652: UI Bug: Adding events to - label in the setting/calendar page is overflowing in mobile view
### Issue Summary
 when viewing the app in mobile device or smaller resolution , Adding events to : label in the setting/calendar path is overflowing.

### Steps to Reproduce

Open the app on a mobile device or simulate a mobile screen resolution using Chrome Developer Tools
Navigate to the settings tab and open calendar option

### Technical details

- Node.js version : NA
- Browser : Chrome 

### Evidence

Screenshot 2024-09-15 222900

### PR DESCRIPTION
**Pull request by mhetreayush**
## What does this PR do?

This PR fixes a UI bug in the calendar settings page on mobile which leads to the overflow of the `Adding events to` label. Check the screenshots below for a clear understaning.

- Fixes #16652
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Before fix screenshots:
- Desktop: 
desktop-before

- Mobile: 
mobile-before

## After fix screenshots:
- Desktop:
desktop-after

- Mobile:
mobile-after

## Mandatory Tasks (DO NOT REMOVE)

- [X] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

### CODE REVIEW

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Thanks for the pr @mhetreayus. This works but it does not look that good. We want to maintain the same layout, can you have the email go to the next line

**Comment by mhetreayush** [comment]
@Amit91848 

> can you have the email go to the next line

By this, do you mean label should be above the email?

**Comment by mhetreayush** [comment]
Screenshot 2024-09-16 at 4 00 41 PM

I guess this is what you are asking for @Amit91848 (I have hardcoded the value in the codebase to check for overflow issues)

**Comment by Amit91848** [comment]
Let me just confirm the layout and get back to you @mhetreayush

**Comment by mhetreayush** [comment]
@Amit91848 Any updates here?

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Hey @mhetreayush ,  you can revert it back to "Adding events to"  text below the email. Sorry for the extra work you had to do 🙏

- Mobile:
mobile-after

**Comment by mhetreayush** [comment]
No worries @Amit91848 , I reverted to the first commit (20cc4cb7154375f22486e746c34c1c297a4faf55) .

**Comment by mhetreayush** [comment]
@Amit91848 Any updates here?

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Gap between Adding Events To and gmail should be reduced, keep it the same as it is currently. Otherwise changes look good 👍
Your changes: Screenshot 2024-09-22 121327

Current: Screenshot 2024-09-22 121345

**Review by anikdhabal — APPROVED** [review]

**Pull request merged**
