### PR TITLE
fix: don't show tool-tip when negative or zero recurring events

### LINKED ISSUE #9604: Showing blank notification box and negative numbers for recurring events
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When there are 5 or less than that, it's showing 0 or the difference between 5 and the recurring numbers. Also, an empty/blank notification box is shown.

### Steps to Reproduce

1. Set a recurring event type with 3 events recurring (issue is between 5 and 1)
2. Copy the event link and open it in another tab
3. Set a day and time
4. Check the list of events. You can see a "-2" together with "+ more" 
5. Mouse over that list to see the blank box notification 

Tested on Vercel preview (https://cal-5luk9i0hk-cal.vercel.app/event-types)

### Technical details

- Tested on Chrome v114.0.5735.134
- Windows 11 PRO

image

image

image

image

image

### PR DESCRIPTION
**Pull request by kemilbeltre**
## What does this PR do?

Avoid show blank or negative recurring event tool-tip

Fixes #9604 (issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks
- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
It's still showing a negative number and an empty tooltip for me: 
Screenshot 2023-06-19 at 12 08 28

**Comment by kemilbeltre** [comment]
> It's still showing a negative number and an empty tooltip for me: Screenshot 2023-06-19 at 12 08 28

@CarinaWolli could show how did you reproduce this state? Thanks

**Comment by CarinaWolli** [comment]
> @CarinaWolli I guess that you tested this in the Vercel Preview environment, could you provide me a user in order to test this? Thanks

I tested it locally with the feature booker-layouts enabled

**Comment by kemilbeltre** [comment]
> 

@CarinaWolli did you mean this option?

```
#Enables New booker for Embed only
NEW_BOOKER_ENABLED_FOR_EMBED=1
```

**Comment by kemilbeltre** [comment]
> 

@CarinaWolli any hints on how to enable this flag? Thanks

**Comment by CarinaWolli** [comment]
> @CarinaWolli any hints on how to enable this flag? Thanks

You can also just add `new-booker` to the URL. So for example: http://localhost:3000/new-booker/teampro/15min this should always show the new booker layout

**Comment by kemilbeltre** [comment]
> > @CarinaWolli any hints on how to enable this flag? Thanks
> 
> You can also just add `new-booker` to the URL. So for example: http://localhost:3000/new-booker/teampro/15min this should always show the new booker layout

@CarinaWolli  Thanks for sharing, but that didn't work. I passed the  `new-booker` flag as param and now seems to be working. :)

**Comment by kemilbeltre** [comment]
@CarinaWolli I think now is solved, please review it. thx!

**Review by CarinaWolli — APPROVED** [review]
Nice, looking good now 🙌🏻 Thank you 🙏

**Pull request merged**
