### PR TITLE
fix: padding in shell for mobile

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

after:
Screen Shot 2023-02-01 at 14 15 15

Screen Shot 2023-02-01 at 14 14 53

Screen Shot 2023-02-01 at 14 10 07

Screen Shot 2023-02-01 at 14 09 38

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]

**Comment by PeerRich** [comment]
CleanShot 2023-02-01 at 13 14 21@2x
seeing this now, unrelated to this ticket. should we find a way to make this look better?

**Review by PeerRich — CHANGES_REQUESTED** [review]
CleanShot 2023-02-01 at 13 20 13@2x

**Review by PeerRich — CHANGES_REQUESTED** [review]
CleanShot 2023-02-01 at 13 21 00@2x

**Comment by PeerRich** [comment]
@G3root please compare this with figma for exact measures for tablet <3

**Comment by G3root** [comment]
new changes

- [x] convert breakpoints from `sm:`  to `md:`

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
