### PR TITLE
docs: Added command in manual section

### LINKED ISSUE #9414: need a change in documentation
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In README.md -> in Manual setup section .  Both migration command should be there one for development environment and other for production environment.  Now there is only one  **yarn workspace @calcom/prisma db-deploy.**  It should be mentioned like it i mentioned in Upgrading section.

### Steps to Reproduce

1. check the readme.md.
2. Go to Manual setup section .
3.  Step 4 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

-

### PR DESCRIPTION
**Pull request by KavanGandhi**
## What does this PR do?

This PR is about making required changes according to the issue in documentation i.e the README.MD file.

Fixes #9414

## Type of change

This change requires a documentation update
- In ReadMe.md file, manual setup section didn't had the migration command for development environment, it only had the command for production environment. So now it's fixed.
readme-md

## How should this be tested?

There is no need of testing. You can take a glance at changes made.

## Mandatory Tasks
Yes I have self reviewed the code and made the required changes.

### CODE REVIEW

**Comment by PeerRich** [comment]
not sure if its a good idea to have a env committed.

definitely uncommit yarn.lock 🙏

**Comment by KavanGandhi** [comment]
I have removed env file and yarn.lock file. Sorry for adding this files I didn't know as it was my first contribution. Please review PR

**Review by Udit-takkar — COMMENTED** [review]
@KavanGandhi you would have to remove env and yarn.lock file.

you can look up on the internet. I think this command could help `git checkout origin/main yarn.lock` and then pushing the changes.

**Comment by KavanGandhi** [comment]
@Udit-takkar I have done the same thing you

**Comment by KavanGandhi** [comment]
@Udit-takkar Actually I have done the same thing you told. But the problem is if I don't upload these files then some checks here in pull requests are getting failed. So what should I do? Can you suggest.

**Comment by KavanGandhi** [comment]
@Udit-takkar I have removed both files. Now can you review my PR?

**Review by Udit-takkar — APPROVED** [review]
LGTM

Do not delete yarn.lock just had to use the command `git checkout origin/main yarn.lock`.  I have fixed this PR now

**Comment by PeerRich** [comment]
thank you @KavanGandhi

**Pull request merged**
