### PR TITLE
Old teams page in v2

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

As requested, the teams page brought up from v1

Loom: https://www.loom.com/share/e52d02180fb8487a8bbcbd66f567efa7

**Environment**: Staging(main branch) / Production

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How should this be tested?

See a new item in the left menu as well as the mobile menu

### CODE REVIEW

**Comment by PeerRich** [comment]
awesome work! I was just about to add my own PR of this but you already did it!!

**Comment by PeerRich** [comment]
@leog i opened a similar PR a minute ago: https://github.com/calcom/cal.com/pull/4555

mine is missing a lot of functionality but you can steal my empty screen and use the new v2 buttons

**Comment by leog** [comment]
> mine is missing a lot of functionality but you can steal my empty screen and use the new v2 buttons

@PeerRich copied your empty screen and shell button (with standard plus icon too), this is how it looks now:

<kbd>image</kbd>

**Review by PeerRich — APPROVED** [review]
great work, waiting for final approval from @zomars and lets cherry pick this to prod afterwards, too!

**Pull request merged**
