### PR TITLE
Create Google Meet and add organizator to invite

### PR DESCRIPTION
**Pull request by diegosoek**
### Small adjusts in Google Calendar integration

-  Create Google Meet link automaticaly

- Add calendso user to invite as organizer of event

### CODE REVIEW

**Comment by baileypumfleet** [comment]
Hey Diego, thanks for the contribution. However, it looks like it just automatically sends the link whatever, and doesn't allow the host user to choose if they want to send an invite.

**Comment by MaZderMind** [comment]
I was just looking into implementing Google Meet Support, too. I was about to add this as an Option to the "Availability"-Items, because that's how we use it in calendly. Would that be alright with you, @baileypumfleet or did you have something else in mind?

If @diegosoek does not mind I'd like to continue and finish this PR.
I'd also like to add it to the Success-Screen and with #117 to the Mail that'll be send to both parties.

**Comment by baileypumfleet** [comment]
@MaZderMind if you're happy to take lead on this, go for it :)

**Comment by baileypumfleet** [comment]
Closing this as we've added our own Google Meet integration. Thanks for all of your help guys :)

**Pull request closed without merging**
