### PR TITLE
refactor: only keep webhook and disable sent email

### PR DESCRIPTION
**Pull request by hoangbits**
## What does this PR do?

1. Disable sending email 
2. keep existing webhooking triggering code

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@hoangbits some people don't use recorded-daily-video webhook and just want the email with the recording download link sent to organiser and all attendees.

we can probably skip sending emails when there is a webhook present

**Review by PeerRich — CHANGES_REQUESTED** [review]
many issues with this PR
- dont commit yarn.lock
- I don't think we should disable emails for everyone, even if a webhook is available
- disabling emails is dangerous and will always lead to edge cases where people expect an email
- why is it so bad if we also send an email?
- if anything, let people decide if they should send an email or not

I don't find an issue for this PR, please explain why you are doing this

**Comment by hoangbits** [comment]
Sorry I create PR in wrong place.

**Comment by hoangbits** [comment]
Sorry I create PR in wrong place.

**Comment by hoangbits** [comment]
> many issues with this PR
> 
> * dont commit yarn.lock
> * I don't think we should disable emails for everyone, even if a webhook is available
> * disabling emails is dangerous and will always lead to edge cases where people expect an email
> * why is it so bad if we also send an email?
> * if anything, let people decide if they should send an email or not
> 
> I don't find an issue for this PR, please explain why you are doing this

Hello Guys.
I think not all the company will using SendGrid And if the code on this line stuck: https://github.com/calcom/cal.com/blob/3e08c668882ca24ec756438838699c7479d92dd2/apps/web/pages/api/recorded-daily-video.ts#L66
The subsequent line which trigger webhook will not be run.
I think We should handle it in a way that webhook don't be stop even if user don't adding config for SendGrid.

**Pull request closed without merging**
