### PR TITLE
Implemented @radix-ui/dialog for creating new event types

### PR DESCRIPTION
**Pull request by emrysal**
Hi @peduarte 

I've started adapting your PR to our latest changes; have a look; (We've got a large in progress design overhaul),

I've opted for creating a custom `Dialog.tsx` file which wraps Dialog(Primitive) - and then implement our typical Tailwind CSS config as per usual. I took some time to wrap my head around DialogTrigger but am now of the opinion this will reduce our dependency on `useState` significantly; something I quite like.

Really curious to your opinion on this PR.

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
great component

**Comment by PeerRich** [comment]
what about the use of Dialogs in other files? i.e. integrations? should that happen in another PR?

**Comment by emrysal** [comment]
@PeerRich Yes, this is just number one so we can have a look, change the API if needed without having to go through many other extra hoops. Also so @peduarte can quickly see what we're up to.

**Review by pumfleet — APPROVED** [review]

**Comment by peduarte** [comment]
Yes, this looks absolutely spot-on 👌

**Pull request merged**
