### PR TITLE
fix: double slash in copying event link

### LINKED ISSUE #642: [bug] Copying event link includes double slashes
### Issue Summary
If you click "Copy Link" under Event Types, you get a link that has a double slash in it, for example: `https://calendso.com//username/meeting`

### Steps to Reproduce
1. Go to /event-types
2. Click on "Copy Link"
3. Look at the clipboard

### Technical details

I think the culprit is this line here:
https://github.com/calendso/calendso/blob/2574006f07fe90f0538b73e40024c5f474f49079/pages/event-types/%5Btype%5D.tsx#L845

This could potentially be a good first issue to check if the host has a trailing slash, and then not include the double slash if so. It might be elsewhere, but this was just an initial search!

### PR DESCRIPTION
**Pull request by codedsun**
fix #642

### CODE REVIEW

**Comment by codedsun** [comment]
@baileypumfleet Review please

**Comment by zomars** [comment]
We may want to replace this with the new `NEXT_PUBLIC_APP_URL`

**Comment by baileypumfleet** [comment]
I agree @zomars, that would be better

**Comment by codedsun** [comment]
@zomars how do i get the key value? and where it's defined. Sorry to ask noob questions but I didn't get any key with this name.

**Comment by PeerRich** [comment]
this PR will be replaced with NEXT_PUBLIC_APP_URL in the next update! Thank you for your contribution but I'll be closing this 🙏

**Pull request closed without merging**
