### PR TITLE
refactor(booking-single-view): Refactor RecurringBookings and add hoo…

### PR DESCRIPTION
**Pull request by AranzalesO**
## Refactor Overview
The primary goal was to reduce the complexity of the RecurringBookings component as identified by Codescene. The refactors included breaking down the component into smaller, more manageable pieces, and moving specific logic into utility functions and subcomponents.

## Changes Made

1. Utility Functions: Created utility functions for sorting bookings and formatting date/time.

- sortRecurringBookings
- formatDateTime

2. Subcomponents: Introduced a subcomponent RecurringEvent to handle individual event rendering.

3. Component Refactor: Updated the RecurringBookings component to utilize the new utility functions and subcomponent, improving readability and maintainability.

## Codescene Analysis
Codescene identified the RecurringBookings component as a complex method due to numerous conditional statements and nested logic. The refactor addresses these issues by modularizing the code.

image_2024-06-10_225313061

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Hey @AranzalesO, thanks for the PR. You don't need to push the lock file unless there are any updates or deleted packages.

**Review by anikdhabal — COMMENTED** [review]
Can we extract this condition and the bottom one.
Screenshot 2024-06-28 000257

**Comment by Ryukemeister** [comment]
@AranzalesO type checks also seem to be failing :(

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Requesting changes on behalf of @anikdhabal @Ryukemeister

**Comment by anikdhabal** [comment]
hey @AranzalesO closing it for now. Feel free to address the requested changes and reopen it.

**Pull request closed without merging**
