### PR TITLE
remove back button on public page

### LINKED ISSUE #5056: Add ability to hide back button on event type booking page
### Describe the solution you'd like

We send our users booking links to specific event types, when we ask them to schedule a time, we don't want them to be able to see our Cal.com homepage with all the other public event types:

CleanShot 2022-10-17 at 15 47 44@2x

### Describe alternatives you've considered

Right now we hide all of our event types so when they go back they see an ugly empty page:

CleanShot 2022-10-17 at 15 50 48@2x

### LINKED ISSUE #5765: [CAL-491] Remove the back arrow
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-491](https://linear.app/calcom/issue/CAL-491/find-a-better-spot-for-the-back-arrow)</sub>

### PR DESCRIPTION
**Pull request by gitstart**
## What does this PR do?

Removes the back button on public page

Fixes #5765 #5056 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Demo
image

### CODE REVIEW

**Comment by gitstart** [comment]
Hi @PeerRich! PR up for review

**Review by PeerRich — APPROVED** [review]
pretty simple solution. i think this is safe to merge but waiting for @zomars

**Comment by gitstart** [comment]
Hey @zomars, please take a look at the PR 🙏

**Comment by PeerRich** [comment]
I think we're actually removing the back button for now, right @Jaibles ?

**Comment by PeerRich** [comment]
> > I think we're actually removing the back button for now, right @Jaibles ?
> 
> Do you want this PR to handle removing the back button or are we closing this one?

yeah i think we can do it here

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
sorry @sean-brydon, you tried! 🥲

**Comment by zomars** [comment]
@sean-brydon 

The More You Know Nice Try GIF by reactionseditor

**Pull request merged**
