### PR TITLE
[Perf Improvement] Booking Page score should be in green now

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
It would probably take the score to 90+ for Booking page by doing the following:
- Avoid crypto-browserify to land in the browser - Similar mistake by others https://github.com/vercel/next.js/discussions/13631#discussioncomment-344113
- Don't do overly eager prefetch [user]/[type] page. Prefetching would still occur on hover

My instance of cal.com with the change

Screenshot 2022-03-04 at 6 36 36 PM

## Type of change

- [x] Performance Improvement

## How should this be tested?

- [x] See that booking page is loading

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by alannnc — APPROVED** [review]
Tested on my end and it did increased lighthouse score 👍

**Review by pumfleet — APPROVED** [review]

**Comment by hariombalhara** [comment]
Score has improved but it's quite flaky. 
Hydration and slow response time seems to be the issue now.

**Comment by agustif** [comment]
What if we moved this page to getStaticProps and ISR every time an event-type is updated?

It only needs to be updated on created/delete/hiding of events, and profile changes right

https://blog.logrocket.com/incremental-static-regeneration-with-next-js/

Moving from SSR to SSG + ISSR should be an improvement on serving a non blocking html version first and re-hydrating later after second fetch?

**Comment by PeerRich** [comment]
amazing stuff!

**Pull request merged**
