### PR TITLE
feat: added i18n cleanup

### PR DESCRIPTION
**Pull request by ezhil56x**
## What does this PR do?

Fixes #15623
/claim #15623

https://www.loom.com/share/b8e6737ad9d24220a5ac93993a35917c?sid=5c460ed1-5cf0-4bf0-bc4b-ccd605f7f176

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

### CODE REVIEW

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Thanks for the pr @ezhil56x ! But it still needs some working on. Not all translation keys are being accounted for. 
For example it shows that only 1 unused key is present in `en/common.json`, when there are many more. 
Also as you can see in the attached video `"trial_days_left"` key is not used anywhere in the application, but it only shows up as unused in some of the translations. After using the fix command, it is still present in many translations.
This is just one of many, please investigate more 🙏.


https://github.com/calcom/cal.com/assets/74371312/26d8cb7d-ddda-4c11-abb9-fee03356f251

**Comment by ezhil56x** [comment]
@Amit91848 
Looks strange
Raised an issue on https://github.com/mxmvshnvsk/i18n-unused/issues/45

**Comment by Amit91848** [comment]
Can you fix it in this pr itself @ezhil56x

**Comment by ezhil56x** [comment]
@Amit91848 
I hope `i18n-unused remove-unused` is the right way to remove unused translations, but not sure why it's not working. I think there might be some issue with `i18n-unused`. What do you think of this?

**Comment by Amit91848** [comment]
> @Amit91848 I hope `i18n-unused remove-unused` is the right way to remove unused translations, but not sure why it's not working. I think there might be some issue with `i18n-unused`. What do you think of this?

You can search for other ways too. I think the regex is not correct

**Comment by keithwillcode** [comment]
This PR is being closed due to staleness. Please reopen if work is to continue.

**Pull request closed without merging**
