### PR TITLE
The road to zero TypeScript errors

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Reduces Ts errors to 0. We can activate strict mode now.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] run `yarn type-check`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jamiepine** [comment]
CleanShot 2022-02-09 at 17 45 18@2x
I got some errors still

**Comment by zomars** [comment]
> CleanShot 2022-02-09 at 17 45 18@2x
> 
> I got some errors still

Have you run yarn locally?

**Review by PeerRich — COMMENTED** [review]
lets gooo

**Review by pumfleet — APPROVED** [review]
Great fix, it's awesome to now have no TypeScript errors 🚀

**Review by alishaz-polymath — APPROVED** [review]
Super Clean 😄

**Pull request merged**
