### PR TITLE
feat: add other payment options

### LINKED ISSUE #18049: [CAL-4858] Paid Bookings: Use "Payment Element" instead of custom UI
lets use: https://docs.stripe.com/payments/payment-element

for:

image

so we can enable all possible stripe connect payment methods:

CleanShot 2024-12-06 at 21 53 08@2x

<sub>[CAL-4858](https://linear.app/calcom/issue/CAL-4858/paid-bookings-use-payment-element-instead-of-custom-ui)</sub>

### PR DESCRIPTION
**Pull request by rajesh-jonnalagadda**
## What does this PR do?

- Fixes #18049  (GitHub issue number)
- Fixes CAL-4858 (Linear issue number - should be visible at the bottom of the GitHub issue description)
/claim #18049 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by itsalam** [comment]
@rajesh-jonnalagadda, were you able to populate other payment options with either accordion/tabs view? That's what I'm currently stuck on.

**Comment by rajesh-jonnalagadda** [comment]
> @rajesh-jonnalagadda, were you able to populate other payment options with either accordion/tabs view? That's what I'm currently stuck on.

@itsalam can i see your changes. Are they same as mine

**Comment by itsalam** [comment]
@rajesh-jonnalagadda Basically the same, but I think I found the issue:

https://github.com/calcom/cal.com/blob/main/packages/app-store/stripepayment/lib/PaymentService.ts#L90
https://github.com/calcom/cal.com/blob/main/packages/app-store/stripepayment/lib/PaymentService.ts#L170,

These are hard-coded throughout the codebase when making a Stripe payment, meaning the changes won't actually reflect new payment options.

@PeerRich, can/should any of these be removed?

**Comment by rajesh-jonnalagadda** [comment]
> @rajesh-jonnalagadda Basically the same, but I think I found the issue:
> 
> https://github.com/calcom/cal.com/blob/main/packages/app-store/stripepayment/lib/PaymentService.ts#L90 https://github.com/calcom/cal.com/blob/main/packages/app-store/stripepayment/lib/PaymentService.ts#L170,
> 
> These are hard-coded throughout the codebase when making a Stripe payment, meaning the changes won't actually reflect new payment options.
> 
> @PeerRich, can/should any of these be removed?

I think you can give it a try by tweaking.

**Review by Praashh — CHANGES_REQUESTED** [review]
Hey @rajesh-jonnalagadda , can you add a loom of the fix ?

**Comment by rajesh-jonnalagadda** [comment]
> Hey @rajesh-jonnalagadda , can you add a loom of the fix ?

@Praashh 
I could if I had proper credentials with me. I am stuck right now. is there any way I can get test mode credentials? (I don't have a work email(for India it is mandatory) and I am from India). so made it as a draft.

**Comment by Praashh** [comment]
Hi @rajesh-jonnalagadda , this PR doesn't fully resolve the issue, closing it for now.

—you can create a new one with Loom and proper testing.

**Pull request closed without merging**
