### PR TITLE
fix: Time Buttons Should be Scroll not the Whole Right Side

### PR DESCRIPTION
**Pull request by gutogalego**
## What does this PR do?

Fixes # [11392](https://github.com/calcom/cal.com/issues/11392)

 Loom Video: https://www.loom.com/share/9a20f728cc9d4d3496b466a999978797

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- My code doesn't follow the style guidelines of this project
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sean-brydon — DISMISSED** [review]
Hi @gutogalego this looks pretty good.

However the 
CleanShot 2023-09-18 at 14 41 26@2x
column view seems to have some issues. From what i can see it comes from this PR

**Comment by gutogalego** [comment]
@sean-brydon hey, thanks! I'll take a look and try to fix it today

**Comment by gutogalego** [comment]
Fixed column view
https://www.loom.com/share/9299b2fd96314e7a813705bca44863f2

**Review by sean-brydon — APPROVED** [review]
LGTM - thanks for the quick change

**Pull request merged**
