### PR TITLE
Add contributing to app store doc - V2

### PR DESCRIPTION
**Pull request by joeauyeung**
To be merged with #1869 

## What does this PR do?

Adds the "Contributing to App Store" doc. This time test building docs ran successfully.

## How should this be tested?

- Run `yarn docs-build` and go to localhost:4000

### CODE REVIEW

**Comment by zomars** [comment]
Let's check those conflicts with main first @joeauyeung 🙏🏽

**Comment by joeauyeung** [comment]
@zomars fixed merge conflicts

**Review by zomars — APPROVED** [review]
Code looks good, let's just wait for the checks to pass.

**Comment by PeerRich** [comment]
@joeauyeung what needs to be changed for this to go live?

**Comment by joeauyeung** [comment]
The docs should be live at the same time we release the app store.

**Comment by zomars** [comment]
We got new merge conflicts @joeauyeung

**Comment by PeerRich** [comment]
> The docs should be live at the same time we release the app store.

I think lets do it earlier because some of our integrations partners are waiting for it

**Pull request merged**
