### PR TITLE
[CAL-1030] fix flickering border issue in menu layout for mobile

### LINKED ISSUE #6992: [CAL-1030] mobile dropdown menu layout issues
found another issue on mobile

- [ ] flickering border
- [ ] double border for delete button

https://user-images.githubusercontent.com/8019099/217485440-22d1d56d-4c65-4475-ac3a-a8008bb5073a.mp4

_Originally posted by @PeerRich in https://github.com/calcom/cal.com/pull/6854#pullrequestreview-1288750773_
            

<sub>[CAL-1030](https://linear.app/calcom/issue/CAL-1030/mobile-dropdown-menu-layout-issues)</sub>

### PR DESCRIPTION
**Pull request by amirfakhrullah**
## What does this PR do?

- Fixing the flickering border issue in menu layout for mobile

Fixes #6992

https://user-images.githubusercontent.com/73758525/218095690-1f1816a0-c52c-4bc5-8cc0-30fdef2db578.mov

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Run the web app locally and go to `/event-types`
- Test the menu layout

### CODE REVIEW

**Comment by Udit-takkar** [comment]
@amirfakhrullah try to use DropdownItem inside DropdownMenuItem if possible just like it is used in other parts of codebase

**Comment by amirfakhrullah** [comment]
@Udit-takkar I just changed it. I can confirm that all pages/sections that use the `DropdownMenuItem` component working fine:


https://user-images.githubusercontent.com/73758525/218243129-25e06737-5d68-44eb-8ae0-47260ae306f0.mov


https://user-images.githubusercontent.com/73758525/218243116-301efdaa-b030-46ec-a47b-ac05991f095d.mov

**Comment by Udit-takkar** [comment]
@amirfakhrullah Works great 👏. In the first video just make sure there are no double borders in the delete item

**Comment by amirfakhrullah** [comment]
Done @Udit-takkar . Here's the vid:

https://user-images.githubusercontent.com/73758525/218245939-4316ddee-bd63-49c1-9c58-c83a67e3481b.mov

**Review by Udit-takkar — APPROVED** [review]
@amirfakhrullah thanks for working on this. 
I have made some changes. just to be consistent on how we are using dropdown in codebase

**Comment by amirfakhrullah** [comment]
I see. Happy to contribute 🚀

**Pull request merged**
