### PR TITLE
fix: RTL issues on booking pages + email confirmation

### LINKED ISSUE #10515: [CAL-2280] RTL issues on booking pages + email confirmation
See discord thread for a summary of all the issues with RTL

[https://discord.com/channels/1125390093386010654/1135177184542195892/1135177184542195892](https://discord.com/channels/1125390093386010654/1135177184542195892/1135177184542195892)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2280](https://linear.app/calcom/issue/CAL-2280/rtl-issues-on-booking-pages-email-confirmation)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fix All RTL related issues on booking page + email confirmation.
Before:-
Screenshot 2023-08-02 185847
Screenshot 2023-08-03 020502
Screenshot 2023-08-03 020526

Screenshot 2023-08-02 185935
Screenshot 2023-08-02 191026
Screenshot 2023-08-02 192415

Now:-

Screenshot 2023-08-02 180928
Screenshot 2023-08-03 020213
Screenshot 2023-08-03 170615

Screenshot 2023-08-03 170639

Screenshot 2023-08-02 192326

Fixes #10515 
/claim #10515

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by PeerRich** [comment]
great job! we will test this PR this week

**Comment by anikdhabal** [comment]
> great job! we will test this PR this week

Thank you

**Comment by anikdhabal** [comment]
> great job! we will test this PR this week

@PeerRich can you test this one?
Thank you.

**Review by zomars — APPROVED** [review]
LGTM

**Pull request merged**
