### PR TITLE
feat: Overlay Calendar v2 and Troubleshooter v2

### LINKED ISSUE #12752: [CAL-2797] Troubleshooter v2 - Pull the calendar info for "busy" events
The v1 shipped with just showing busy for events

We should show which calendar the event is coming from [as per designs](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?node-id=5966%3A558458&mode=dev).

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2797](https://linear.app/calcom/issue/CAL-2797/troubleshooter-v2-pull-the-calendar-info-for-busy-events)</sub>

### LINKED ISSUE #12763: [CAL-2801] Overlay my calendar v2
We recently added a v1 of "Overlay my calendar". This currently allows you to access this feature if you have a Cal.com account. 

For v2 we need to 

1. Add other providers
   * Sign in with Google
   * Sign in with Microsoft
   * Any others?

2. Replace "Busy" events with the actual info from the calendar it is pulling from

[View in Figma](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/New-Features?node-id=5679%3A305336&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2801](https://linear.app/calcom/issue/CAL-2801/overlay-my-calendar-v2)</sub>

### PR DESCRIPTION
**Pull request by kart1ka**
## What does this PR do?

- This PR currently only fetches event titles for Google Calendar.
- This PR allows users to use Overlay Calendar feature by signing in using their Google Account.
- It also pulls actual event title from the google calendar instead of just showing "Busy" for both overlay calendar and troubleshooter.
- This feature upgrade does not need any Google scope changes.

Fixes #12763  
Fixes #12752 

Overlay Calendar v2
https://www.loom.com/share/8e3889f4f7034596adb2bfdc640cba11?sid=7242ef08-ef5e-4b9a-a102-c19eded1d882

Troubleshooter v2
https://www.loom.com/share/8024891797574a748b99c3c40979398c?sid=248174de-8abe-4fd3-a42e-c9146b86ddf1

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update:
  - Under Authorized redirect URI's in google cloud add the URI: `<Cal.com URL>/api/auth/callback/google-for-overlay`
replacing Cal.com URL with the URI at which your application runs.

## How should this be tested?

- Please make sure to obtain google cloud API Credentials as mentioned [here](https://github.com/calcom/cal.com?tab=readme-ov-file#obtaining-the-google-api-credentials).
- No new scopes required.
- Edit the credential in the google cloud.
- Under Authorized redirect URI's in google cloud add the URI: `<Cal.com URL>/api/auth/callback/google-for-overlay`
replacing Cal.com URL with the URI at which your application runs.

### Testing Overlay Calendar v2
- Just go to a booking page and toggle the Overlay Calendar switch.
- Choose Continue with Google and sign in with a google id.
- You will see that now event titles are being displayed instead of just "Busy" for the calendar busy events.

### Testing Troubleshooter v2
- Just go to the Troubleshooter and make sure that google calendar is connected and the app is checking google calendar for conflicts. 
- You will see that now event titles are being displayed instead of just "Busy" for the calendar busy events.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by sean-brydon — CHANGES_REQUESTED** [review]
Hi - awesome work on this. 

However, we do not wish to have a new OOauth provider and wish to use our current google sign in implementation. We should continue to stick with our `user` model and not this new `OverlayUser` model. If you signup with google for the first time here we should create a normal cal.com user. 

This was on my task list for this week so let me know if you want me to take this over. Thank you very much for your contribution.

**Comment by sean-brydon** [comment]
> Hi - awesome work on this.
> 
> However, we do not wish to have a new OOauth provider and wish to use our current google sign in implementation. We should continue to stick with our `user` model and not this new `OverlayUser` model. If you signup with google for the first time here we should create a normal cal.com user.
> 
> This was on my task list for this week so let me know if you want me to take this over. Thank you very much for your contribution.

On top of this we need to ensure we are re-using all the code we already have for users and credentials instead of implementing it from scratch for this single feature.

**Comment by kart1ka** [comment]
> Hi - awesome work on this.
> 
> However, we do not wish to have a new OOauth provider and wish to use our current google sign in implementation. We should continue to stick with our `user` model and not this new `OverlayUser` model. If you signup with google for the first time here we should create a normal cal.com user.
> 
> This was on my task list for this week so let me know if you want me to take this over. Thank you very much for your contribution.

Hi @sean-brydon.  Thanks for the review.

I have a couple of questions:

1. When we use the current google sign in implementation, after the user signs in do we just show the "Connect Your Calendar" page (see below) and once the user connects the google calendar we redirect them back to the booking page?
Screenshot from 2024-04-15 17-26-44

2. In the "Connect Your calendar" page, do we let users connect only their google calendar or other calendar as well just like in the normal sign up process?  
3. Regarding using the existing User model, Do you expect other providers to be added for Overlay Calendar because they do not exist for normal cal.com sign up?

**Comment by sean-brydon** [comment]
> > Hi - awesome work on this.
> > However, we do not wish to have a new OOauth provider and wish to use our current google sign in implementation. We should continue to stick with our `user` model and not this new `OverlayUser` model. If you signup with google for the first time here we should create a normal cal.com user.
> > This was on my task list for this week so let me know if you want me to take this over. Thank you very much for your contribution.
> 
> Hi @sean-brydon. Thanks for the review.
> 
> I have a couple of questions:
> 
 1. When we use the current google sign in implementation, after the user signs in do we just show the "Connect Your Calendar" page (see below) and once the user connects the google calendar we redirect them back to the booking page?
 - Yes i think we can actually auto signup with the button on the overlay calendar -> you click continue with google we auto signup and connect the calendar - we can skip the onboarding until the user actually uses the app.

3. In the "Connect Your calendar" page, do we let users connect only their google calendar or other calendar as well just like in the normal sign up process?
Yes - if we can't auto sign up we can go with this approach

5. Regarding using the existing User model, Do you expect other providers to be added for Overlay Calendar because they do not exist for normal cal.com sign up?
- We only have the ones on the figma file planned however, other calendar providers will still work (ideally) 

Please reachout if you have any questions on here on in discord. Happy to help!

**Comment by kart1ka** [comment]
Thanks. I will get on it. I will let you know if I have any other questions.

**Comment by kart1ka** [comment]
Raised a new PR with requested changes as per the review.
PR #14693

**Comment by sean-brydon** [comment]
Will close this in favour of the second PR you have created <3

**Pull request closed without merging**
