### PR TITLE
I think we're ready for this

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

No more eslint and type errors before build

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
exciting and terrifying

**Review by pumfleet — APPROVED** [review]

**Comment by zomars** [comment]
Do not merge until we figure out why TS is broken

**Comment by agustif** [comment]
It seems the typescript error comes due to taconfig compiler options `declaration and declarationMap` from tsconfig/base.json file.

Disabling those makes gh action pass and ts compiler happy

**Comment by zomars** [comment]
Closed in favor of #2354

**Pull request closed without merging**
