### PR TITLE
feat: Identify and Split Large Code Files

### LINKED ISSUE #12559: [CAL-2766] Refactor: Identify and Split Large Code Files for Improved Testability
Our codebase currently contains large files that could benefit from refactoring into smaller, more modular components. Example: [handleNewBooking.ts](https://github.com/calcom/cal.com/blob/230b82d3bf3692cbe415f2ed6305ebc643bede1b/packages/features/bookings/lib/handleNewBooking.ts).

This refactoring effort is essential for improving the maintainability of the code and facilitating more effective unit and integration testing. The goal is to identify these large files, break them down into smaller, logically organized modules, and create a structure that enables comprehensive testing.

### Desired Features:

* **Adhere to current system design**: The idea of this is not to introduce a new architecture or system design (e.g. DDD) but instead to break down large files into smaller, more testable units of code.
* **Unit and Integration Testing**: Create or enhance unit and integration tests for the refactored components to ensure their correctness and reliability.
* **Documentation**: Document the refactoring process, including the rationale behind splitting specific files, to aid future development and maintenance efforts.

### Requirements:

* **Maintainability**: Ensure that the refactored codebase remains maintainable and comprehensible, with clear separation of concerns. **No major functionality changes will be accepted.**
* **Testability**: Design the smaller components with testing in mind, making it easier to write meaningful unit and integration tests.
* **Performance Considerations**: Evaluate the performance impact of the refactoring and address any potential bottlenecks or inefficiencies.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2766](https://linear.app/calcom/issue/CAL-2766/refactor-identify-and-split-large-code-files-for-improved-testability)</sub>

### PR DESCRIPTION
**Pull request by Shyam-Raghuwanshi**
## What does this PR do?

this PR Identify and Split the Large Code Files

Fixes #12559

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by keithwillcode — CHANGES_REQUESTED** [review]
There are failing type checks, unit tests and E2E tests.

**Comment by Shyam-Raghuwanshi** [comment]
Hi @keithwillcode i fix type checks but i don't why the unit tests and E2E test failed you have any idea about this ?

**Comment by keithwillcode** [comment]
@Shyam-Raghuwanshi Looks like 56 unit tests are failing. Likely related to how the mocks were configured before this refactor.

**Comment by keithwillcode** [comment]
Converting to draft while conflicts and unit tests are fixed up.

**Review by keithwillcode — CHANGES_REQUESTED** [review]
@Shyam-Raghuwanshi have you been making sure the new files you made contain changes that have been going into main?

I’m concerned that with a PR this big and open this long and with as many changes we’ve made to bookings recently that regressions will sneak in. 

what I prefer we do at this point is open new, smaller PRs that we can review and merge more quickly, ensuring nothing is going stale and because smaller PRs are easier to test in isolation and revert if needed.

**Pull request closed without merging**
