### PR TITLE
feat: use ui-avatar.com for placeholder

### LINKED ISSUE #10475: [CAL-2273] Use ui-avatar.com only for all default avatars
Possible Followup: Avatar component has fallback image support but it uses [gravatar.com](http://gravatar.com) maybe we can just switch it with [ui-avatars.com](http://ui-avatars.com) and automatically enable fallback.

There is one concern that sometimes we show a initials based avatar and sometimes the silhouette avatar.

\*Originally posted by @hariombalhara in \*[*https://github.com/calcom/cal.com/pull/10383#discussion_r1275991923*](https://github.com/calcom/cal.com/pull/10383#discussion_r1275991923)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2273](https://linear.app/calcom/issue/CAL-2273/use-ui-avatarcom-only-for-all-default-avatars)</sub>

### PR DESCRIPTION
**Pull request by rkreddy99**
## What does this PR do?

Fixes #10475 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

-Fallback images should be taken from ui-avatar.com

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rkreddy99** [comment]
image

**Comment by rkreddy99** [comment]
@hariombalhara is this the type of change required for this pr?

**Comment by rkreddy99** [comment]
**PS: THIS IS NOT MERGEABLE YET. JUST CREATED A DRAFT PR TO GET COMMENTS**

**Comment by PeerRich** [comment]
we've decided to not go with ui-avatar. thank you for the try tho!

**Pull request closed without merging**
