### PR TITLE
hotfix: locale not changeable 

### LINKED ISSUE #7976: [CAL-1354] Can't change language in settings
### Issue Summary

When trying to change the language in settings it says 'Settings successfully updated' but the language is still the old one when reloading the page. 

Loom: https://www.loom.com/share/2f93f4604ae7446694ba034bb64beecf

<sub>[CAL-1354](https://linear.app/calcom/issue/CAL-1354/cant-change-language-in-settings)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes  https://github.com/calcom/cal.com/issues/7976

after

[Screencast 2023-03-28 20:49:49.webm](https://user-images.githubusercontent.com/84864519/228286704-2f4281bc-bacf-438d-a237-51ff3812fc09.webm)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by Udit-takkar — APPROVED** [review]
LGTM. tested it

**Comment by Udit-takkar** [comment]
@G3root can you fix type errors here ?

**Comment by G3root** [comment]
> @G3root can you fix type errors here ?

@Udit-takkar looks like it's from some where else 🤔 . same failed checks in all the other PR's as well

**Review by keithwillcode — APPROVED** [review]
Looks good. Tested and now can change locale without issues.

**Pull request merged**
