### PR TITLE
fix:  pwa nav improvements

### PR DESCRIPTION
**Pull request by axcellence**
## What does this PR do?

This PR resolves some UI issues when in standalone mode (PWA).

Added:
* `viewport-fit=cover` to the meta tags
* `env(safe-area-inset-bottom)` so the nav has enough padding at the bottom of the screen

https://www.loom.com/share/c1624daacc644f3bb821a2215158324b

## Requirement/Documentation

- Webkit resource [(Safe Areas)](https://webkit.org/blog/7929/designing-websites-for-iphone-x/#:~:text=Respecting%20the%20Safe%20Areas)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Add Cal.com to Home Screen an iOS device or in the simulator and see that the nav is now as expected
- Test on different mobile devices and screen sizes to ensure the navigation padding and viewport adjustments behave as expected.

## Mandatory Tasks

- [x] Self-reviewed the code.

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@axcellence Great work. can you sign the CLA https://cla-assistant.io/calcom/cal.com?pullRequest=11972 ?

**Comment by PeerRich** [comment]
nice PR, we should pump the position of the floating action button tho so it doesn't overlap: 
CleanShot 2023-10-19 at 14 36 33@2x

**Comment by axcellence** [comment]
> nice PR, we should pump the position of the floating action button tho so it doesn't overlap: CleanShot 2023-10-19 at 14 36 33@2x

@PeerRich  you're exactly right I noticed it after the loom and I had addressed in [commit #3](https://github.com/calcom/cal.com/pull/11972/commits/eb7b96fe193fc2dcee3e94b0bbfa27142b98b3a0?diff=unified&w=0). 
However, thinking more about it. It would be better to utilise the same `safe-area-inset-bottom` rather than guessing there's enough clearance. Updated in [commit #4](https://github.com/calcom/cal.com/pull/11972/commits/f0d038546d6007f6e7dad9f4b76ec0fc66234a6f)

**Comment by PeerRich** [comment]
good solution!

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
