### PR TITLE
Feature/location visible before booking

### LINKED ISSUE #2519: Location of in-person meeting not visible before booking
### Issue Summary

Location of in-person meeting not visible before booking

### Steps to Reproduce

1. Select a time for a meeting, e.g., at https://cal.com/marvin/coffee
2. Continue until you have the option to decide between "Zoom Video" and "In-person meeting"
3. Since you can't see where the in-person meeting is supposed to take place, no one will actually choose this option

→ It should be opt-out to display the actual location somewhere on the booking page, e.g., as "In-person meeting _in Amsterdam ℹ︎_" and by clicking on the location or ℹ︎, one can see the full address, so that people can see if this would actually be an option for them

### PR DESCRIPTION
**Pull request by andreaestefania12**
## What does this PR do?

Fixes #2519

I edited the modal window where you create the event and when you select location **In person** you could add the city and the address of the meeting.

image

I changed to the booking page when you have the option **In Person** it going to show you the city 
image

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Booking an event.
- Select a time for a meeting.
- You are going to see **In-person meeting** with the city info

### CODE REVIEW

**Comment by hariombalhara** [comment]
Looks good @andreaestefania12. But I don't understand why we need city field. 

@Jaibles Looks like the right thing to do. Solves real problem,

**Comment by Jaibles** [comment]
@andreaestefania12 this is an interesting solution to a clear problem you've identified. We currently aren't showing location at all to the booker (whether in-person or virtual) and this is something we need to solve. Let me just discuss this with the team and explore some solutions to see if we need to take your idea a little further. Will get back to you on this one - thank you pointing this out 🙏

**Comment by andreaestefania12** [comment]
> 
@hariombalhara @Jaibles Thank you for your comments, let me know anything about it :)

**Comment by zomars** [comment]
Closed in favor of #2752

**Pull request closed without merging**
