### PR TITLE
fix: event location not translated in booking page

### LINKED ISSUE #5666: [CAL-441] i18n: translate attendee phone number and other video options if possible
Hello

I am a new user - very interesting application! I like it very much
I changed the language (-> French) and some pieces of text are not translated. Surely you knew that? In doubt I put you some screenshots.

> From [SyncLinear.com](https://synclinear.com) | [CAL-441](https://linear.app/calcom/issue/CAL-441/i18n-translate-attendee-phone-number-and-other-video-options-if)

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #5666

after:
Screenshot 2023-03-06 at 11-35-22 60min Pro Example Cal com

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
Screenshot 2023-03-06 at 3 10 24 PM

The location is not translated. we use attendeeInPerson as key and not attendeeinperson. similar problem in some other locations also

**Comment by G3root** [comment]
new changes :

- [x] snake cased i18n keys `attendeeInPerson` and `inPerson` 
- [x] snake case location labels
- [x] some refactoring in `getLocationGroupedOptions` utility function.
- [x] fixed requested changes.
- [x] made some location labels translatable
   
before:
Screenshot 2023-03-06 18:45:31

after:
Screenshot 2023-03-06 18:47:09

- [x] show the url in selected link location

before:
Screenshot 2023-03-06 at 18-52-09 sadas Event Type Cal com

after:
Screenshot 2023-03-06 at 18-51-29 60min Type d'événement Cal com

**Comment by PeerRich** [comment]
great job! lots of people were asking for this

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
There are some file that use older value

like here https://github.com/calcom/cal.com/blob/6a6faf30ffbc2da1ef8a2e6a7d8ea661d9437327/apps/web/components/dialog/EditLocationDialog.tsx#L298

  location.options.filter((l) => l.value !== "attendeeInPerson");
 
 just do a quick search of old location names
 
 Edit: there are also some type errors

**Comment by G3root** [comment]
> There are some file that use older value
> 
> like here
> 
> https://github.com/calcom/cal.com/blob/6a6faf30ffbc2da1ef8a2e6a7d8ea661d9437327/apps/web/components/dialog/EditLocationDialog.tsx#L298
> 
> location.options.filter((l) => l.value !== "attendeeInPerson");
> 
> just do a quick search of old location names
> 
> Edit: there are also some type errors

pushed some changes. modified the loop, only to filter by the `value` not `label` as it might break in the future because of some i18n changes

**Review by Udit-takkar — APPROVED** [review]
Great work. LGTM ! 🚀

**Review by emrysal — COMMENTED** [review]
This is excellent 🙏 @G3root - thanks for the reviews @Udit-takkar

**Review by emrysal — APPROVED** [review]

**Review by roae — APPROVED** [review]
it looks good, how did you do the translations? did you use a translator?

**Comment by emrysal** [comment]
> it looks good, how did you do the translations? did you use a translator?

@roae Just a key change, the translations were already there 👍

**Comment by roae** [comment]
> > it looks good, how did you do the translations? did you use a translator?
> 
> @roae Just a key change, the translations were already there 👍

sure, but then those translations were done by the community?

**Pull request merged**
