### PR TITLE
fix: wrong avatars in new workflow dropdown

### LINKED ISSUE #16859: [CAL-4426] wrong avatars in "new workflow" dropdown
this is not using the org logos

CleanShot 2024-09-27 at 15 13 30@2x

<sub>[CAL-4426](https://linear.app/calcom/issue/CAL-4426/wrong-avatars-in-new-workflow-dropdown)</sub>

### PR DESCRIPTION
**Pull request by ymohit1603**
- Fixes #16859 
cal_avatar_fix

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Praashh** [comment]
Hey @ymohit1603 Thanks for contributing, can you please fix this 
image

**Comment by anikdhabal** [comment]
Hey @Praashh, it is failing because our other tests are skipped for now. Once those tests run and pass, it will automatically pass. Also, those workflow runs will be triggered if we add the 'ready-for-e2e' label

**Comment by Praashh** [comment]
> Hey @Praashh, it is failing because our other tests are skipped for now. Once those tests run and pass, it will automatically pass. Also, those workflow runs will be triggered if we add the 'ready-for-e2e' label

ahh, make sense. thanks for clearing @anikdhabal

**Review by emrysal — CHANGES_REQUESTED** [review]
Hi @ymohit1603 - thanks for your contribution.

However this is not the right fix, for org users we want users to fall back on their org logo (not the cal com logo) and for personal users we want to fall back on ui-avatars.

Have a look into using `getOrgOrTeamAvatar` - which isn't used in the new workflow dropdown (apparently)

**Pull request closed without merging**
