### PR TITLE
feat: multi round robin hosts

### PR DESCRIPTION
**Pull request by david-m-l21s**
## What does this PR do?

Adds the possibility to select several round-robin-hosts for the respective event-type.

Fixes # [11953](https://github.com/calcom/cal.com/issues/11953)

Crucial changes which were necessary:

**1. Frontend:** 
Adds an input-field to the Event-Team-Tab by which the number of round-robin hosts which need to participate
in the event can be specified

**2. Availability:**
For multiple round-robin-hosts the way how the collective availability is determined needs to be changed.

**3. Select the correct number of hosts in the booking-handler**  
 
Cal_com

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How should this be tested?

1. Create a Round-Robin Event-Type 
2. Under "Assignment" select some users which have a common availability
3. Provide the number of users which you want to particiate in a Round-Robin fashion
4. Now when trying to book the event, the datepicker should respect the new constraints
5. The hosts selection should now select the number of hosts which you provided with Round-Robin

A test is provided in the PR.

### CODE REVIEW

**Comment by PeerRich** [comment]
ahhh so instead of one random it selects N random people that must join?

**Comment by ciaranha** [comment]
@david-m-l21s really nice work on this! Curious is this solving an existing need you have in the product for this feature?

**Comment by david-m-l21s** [comment]
> ahhh so instead of one random it selects N random people that must join?

Yes exactly.



> @david-m-l21s really nice work on this! Curious is this solving an existing need you have in the product for this feature and if you could elaborate on the scnerio if you don't mind 🙏?

Sure. The reason we approached this is that we have many meetings (for now mostly recruitment) where we want to apply the "4 eyes principle" and thereby at least 2 poeple from the team should participate.
We have several stages for a typical recruitment process and different roles should participate. For example at the tech-interview, we might need 2 Senior Engineers to participate whereas at the final level 2 poeple from management should be present and so on. Ideally the meetings should additionally be distributed among the role-members.   

Obviously setting this up manually is tedious. The Round-Robin behavior in cal.com would solve that issue except that it works just for one RoundRobin participant. With the changes in this PR we are almost were we want to be.

**Comment by ciaranha** [comment]
@david-m-l21s thank you for clarifying. That makes perfect sense. Very interesting use case and sounds like something that would be great to have in the product 👍

**Comment by tobilarscheid** [comment]
Hey guys, this looks super interesting! Would love to see this merged

**Review by ciaranha — COMMENTED** [review]
@emrysal is there anything preventing us from merging this?

**Comment by tobilarscheid** [comment]
@ciaranha @emrysal just wanted to catch your attention before this is being marked as stale again :-)

**Comment by keithwillcode** [comment]
Closing for now since the resolve conflict list is quite long. If able to address, let's reopen this then.

**Pull request closed without merging**
