### PR TITLE
Suggestion: let prettier sort imports order

### PR DESCRIPTION
**Pull request by zomars**
- Added a plugin to sort imports
- We should discuss if we want separators or not:
https://github.com/calendso/calendso/blob/ccb416df5f16816dfe8cf25ebd9260469a3c6019/.prettierrc.js#L11
- Sorted the imports of `pages/event-types/index.tsx` to demo it.

### CODE REVIEW

**Review by KATT — APPROVED** [review]
Questions

- is there a more "official" import sorter than trivago?
- is the autofix reliable? Otherwise its really annoying. If you can run lint-fix on the whole project without manually touching files I'm all for it

**Comment by zomars** [comment]
> * is there a more "official" import sorter than trivago?

This is the more robust one that I'm aware of
 
> * is the autofix reliable? Otherwise its really annoying. If you can run lint-fix on the whole project without manually touching files I'm all for it

You can just run `prettier --write .` on the whole project.

**Comment by KATT** [comment]
> You want me to run `npx prettier --write {pages,components,lib}` and update my PR? @KATT

Yeah, I do, but if there are a lot of open features we might want to do this at a later point as it causes a lot of conflicts.

I think we should merge together with the other lint branch, #497, and merge it early next week.

**Comment by zomars** [comment]
I'll redraft it meanwhile @KATT

**Comment by zomars** [comment]
It's now or never @baileypumfleet

**Pull request merged**
