### PR TITLE
updates to all public booking pages

### PR DESCRIPTION
**Pull request by ciaranha**
## What does this PR do?

Makes font-size, color & spacing changes to the public booking pages.

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
awesome

**Comment by Jaibles** [comment]
Don't merge this yet. There's a 0 appearing in the event types list and I can't find where it's coming from
CleanShot 2022-08-03 at 12 31 03@2x

**Review by hariombalhara — APPROVED** [review]

**Comment by hariombalhara** [comment]
Screenshot 2022-08-05 at 1 31 39 PM
Don't see the 0 now. Looks like it was due to some other branch and got fixed due to main automerge.

**Comment by hariombalhara** [comment]
Screenshot 2022-08-05 at 1 34 02 PM
Alignment of calendar icon with it's text seems off @Jaibles

**Pull request merged**
