### PR TITLE
fix: Exclude current rescheduled booking from limit

### LINKED ISSUE #13867: [CAL-3217] [CAL-3208] Booking limits should not count reschedules
When I want to reschedule a meeting on the same day (eg. move it from 15:00 to 16:00), and I have set a limit of 1 for this type of event per day, it shouldn't block me from moving the event I have already scheduled on that day. Currently it says "you already reached the limit for this type of event" and I have to manually change the limit to 2 every time i have to reschedule.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3208](https://linear.app/calcom/issue/CAL-3208/booking-limits-should-not-count-reschedules)</sub>

<sub>[CAL-3217](https://linear.app/calcom/issue/CAL-3217/[cal-3208]-booking-limits-should-not-count-reschedules)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

Fixes #13867

Screenshot 2024-02-26 at 7 33 51 PM

https://github.com/calcom/cal.com/assets/74371312/b8eac058-2b92-4e29-b739-d5c75d24bab2

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by keithwillcode — DISMISSED** [review]
This type of logic change needs tests to be added/modified to verify the logic.

**Review by joeauyeung — CHANGES_REQUESTED** [review]
Thanks for your contribution @Amit91848.

 Your changes look good but I agree with @keithwillcode that we should add some tests before merging. Feel free to retag me for review once that's done

**Comment by Amit91848** [comment]
Sorry for the delay got busy with college. 

Was looking at the present tests and booking limits test is being skipped. PR #13510 
Should I add more tests here?

https://github.com/calcom/cal.com/blob/3cefa94a94ad5ac96d72d91e72775e519bf5b145/apps/web/playwright/booking-limits.e2e.ts#L61

Or I also found this file but ig this is legacy?

https://github.com/calcom/cal.com/blob/3cefa94a94ad5ac96d72d91e72775e519bf5b145/apps/web/test/lib/checkBookingLimits.test.ts#L1

@joeauyeung @keithwillcode

**Comment by Amit91848** [comment]
@joeauyeung Added a test. Not sure if this is the correct way tho.
That particular test has been failing( #13510 ) for years limit. It works for the remaining.

**Review by joeauyeung — APPROVED** [review]
Test looks good. Thanks @Amit91848 for your contribution!

**Pull request merged**
