### PR TITLE
chore: removed old booker and make new booker as a default

### LINKED ISSUE #9608: [CAL-1980] chore: clean up old booking page
remove all components of the old booking page to prevent confusion for contributors

<sub>[CAL-1980](https://linear.app/calcom/issue/CAL-1980/chore-clean-up-old-booking-page)</sub>

### PR DESCRIPTION
**Pull request by servusrene**
## What does this PR do?

Fixes #9608

/claim #9608

### CODE REVIEW

**Comment by rene-mueller** [comment]
@PeerRich fixed :)

**Comment by PeerRich** [comment]
still failing some actions 🤔

**Comment by rene-mueller** [comment]
> still failing some actions 🤔

Oh, there was a missing piece which was committed 3 days ago... I'll fix it right now.

**Comment by rene-mueller** [comment]
@PeerRich throughout the project are still many references to the old types. The new booking page does not contain them anymore... it is a miracle that everything works so smoothly.

**Comment by rene-mueller** [comment]
@PeerRich i found the error. i forgot to remove components. These have now thrown the error. Type checks are now fixed. i now only test e2e and then push the result

**Review by emrysal — APPROVED** [review]
Looks good to me, well done 🙏

**Pull request merged**
