### PR TITLE
perf: Add database indexes

### PR DESCRIPTION
**Pull request by roae**
## What does this PR do?

Add missing database indexes

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

### CODE REVIEW

**Comment by keithwillcode** [comment]
@roae Was this list derived from tooling or did you manually go through pick out columns apt for indexes?

**Comment by roae** [comment]
> @roae Was this list derived from tooling or did you manually go through pick out columns apt for indexes?

All foreign keys were pick out manually.

cc @Mythie

**Comment by Mythie** [comment]
> > @roae Was this list derived from tooling or did you manually go through pick out columns apt for indexes?
> 
> All foreign keys were pick out manually.
> 
> cc @Mythie

Yep G'day, so this list was decided upon after reviewing every `where` statement within Cal.com and optimising on things that we actually use.

Additionally all common foreign keys are included since they'll likely be used under the hood by Prisma with its fake joins.

**Review by zomars — APPROVED** [review]
LGTM

**Pull request merged**
