### PR TITLE
React feather refactor

### PR DESCRIPTION
**Pull request by mehranShG**
## What does this PR do?

This will remove imports from react-feather and uses calcom icon instead, And also
changes Icon type used from react-feather and uses SVGComponent from calcom/types

Fixes # 6064

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
great refactor. code looks good, testing now

**Comment by PeerRich** [comment]
tested all pages, icons are fine

**Comment by PeerRich** [comment]
thank you @mehranShG!

**Comment by siddtheone** [comment]
Can we mark the Issue fixed?

**Comment by PeerRich** [comment]
@siddtheone  will do

**Pull request merged**
