### PR TITLE
fix: add typeform logo and fix alt text in /apps/typeform/how-to-use

### LINKED ISSUE #18390: Typeform logo not found in /apps/typeform/how-to-use
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Typeform logo 404  in /apps/typeform/how-to-use
Alt text also wrong

### Steps to Reproduce

1. Go to https://app.cal.com/apps/typeform/how-to-use

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
Image should be there, It is not.

### Actual Results

- Image not there

### Expected Results

- Image should be there also alt text should be there

### Technical details

- Prod
image

### Evidence

- Visible on hosted platform

### PR DESCRIPTION
**Pull request by ShashankGupta10**
## What does this PR do?

- Fixes #18390  

image

## Mandatory Tasks (DO NOT REMOVE)

- [X] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [X] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [X] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Typeform Image appears and also alt text is correct just in case. Can be verified in UI

### CODE REVIEW

**Review by Praashh — APPROVED** [review]
LGTM!!

**Review by Praashh — DISMISSED** [review]
Hey @ShashankGupta10 , E2E tests are failing, can you please fix this ?

**Comment by ShashankGupta10** [comment]
I dont know why it's failing. Looked in the logs, found this.
`[WebServer] error connecting to engine: sql, type: postgres db: error: password authentication failed for user "postgres"`

But I am not sure if it is because of my PR. Because it is actually just changing a text and an image.

**Comment by Praashh** [comment]
> I dont know why it's failing. Looked in the logs, found this. `[WebServer] error connecting to engine: sql, type: postgres db: error: password authentication failed for user "postgres"`
> 
> But I am not sure if it is because of my PR. Because it is actually just changing a text and an image.

please try running tests locally 🙏

**Review by Praashh — APPROVED** [review]

**Pull request merged**
