### PR TITLE
feat: 30 day email digest

### LINKED ISSUE #10026: [CAL-2127] feature: 30 day email digest
https://twitter.com/steventey/status/1678107446857072640?s=46&t=XsU6yrqPhYPfQwlOR-9I-w

<sub>[CAL-2127](https://linear.app/calcom/issue/CAL-2127/feature-30-day-email-digest)</sub>

### PR DESCRIPTION
**Pull request by rkreddy99**
## What does this PR do?

This pr creates a new feature for showing 30day summary of an user.
draft pr displaying the info that will be shown, styling is also left. PFA image below

check this for more info on calcs https://github.com/calcom/cal.com/pull/10627#issuecomment-1667426887

Fixes #10026 

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Login
- navigate to insights
- click on `GET 30 day email digest` button on top left.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by rkreddy99** [comment]
will replace the `attended x events` with `booked x events`

**Comment by rkreddy99** [comment]
Checks for hosted, attended, payments, unique attendees (by email), unique (timeZones) can display flags here like grouped avatars, would be cool, top events by bokings

a booking is considered to be hosted if the 
- user is the user for the booking 
- user is present in attendees and eventType has user in owners or users field, this check is done by checking the user emails in attendees table.

remaining are considered to be attended events (/booked events)

payments are considered to be successfull if booking.paid is true and payment is success and not refunded.

number of bokings is straightforward, check bookings for hosted events.

these calcs are present in https://github.com/calcom/cal.com/pull/10627/files#diff-6d0267b35107118d2b6a7edc76233a9f13ce89b7aaf2e99b82a9bfa55bbc44b7

**Comment by rkreddy99** [comment]
todo if this solves the issue

styles in email
cron scheduler 
graphs (maybe) - disaplying the 2 lines (one for bookings and one for booked duration per day for the last 30 days),  something like this - https://apexcharts.com/javascript-chart-demos/area-charts/spline/

**Comment by rkreddy99** [comment]
cc @PeerRich

**Comment by rkreddy99** [comment]
@PeerRich @baileypumfleet @CarinaWolli 

Can you guys confirm whether this is the data that has to be shown in the digest email?

**Comment by CarinaWolli** [comment]
I am not sure what we would want to show here, maybe @ciaranha could give some input, also some design suggestions for the email would be good

**Comment by PeerRich** [comment]
we merged https://github.com/calcom/cal.com/pull/10621 instead. thank you for contributing tho!

**Pull request closed without merging**
