### PR TITLE
Add automation category and move zapier and n8n to it

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes # (issue)
- Adds automation category
- Moves Zapier and n8n to automation category

[Loom Demo](https://www.loom.com/share/e7cb8556c6034ee3af406de7e33d381c)

**Environment**: Production

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Go and check that there there are 2 Apps shown under automation on Apps home page.
- [ ] Go to automation category and see that the 2 apps are n8n and Zapier

### CODE REVIEW

**Review by joeauyeung — COMMENTED** [review]
Code looks good but two things
1. Tried going to the automation category and got this error
https://app.birdeatsbug.com/sessions/V01CJrkJKU7Yznylk256OMy0cfuZuuyxboyMLSbforVA
2. I think "Automation" should be a category here 
image

**Comment by hariombalhara** [comment]
@joeauyeung It works for me. There is an automation category where you mentioned as shown in the Demo loom

I think it might be because you haven't run migrations?

**Review by pumfleet — APPROVED** [review]
Code changes look good to me

**Comment by zomars** [comment]
@hariombalhara do we need to update something on the current Zapier on prod to prevent breaking?

**Comment by hariombalhara** [comment]
There are migrations for that.

**Pull request merged**
