### PR TITLE
feat: Twipla app analytics added

### LINKED ISSUE #14758: [CAL-3557] add twipla
null

<sub>[CAL-3557](https://linear.app/calcom/issue/CAL-3557/add-twipla)</sub>

### PR DESCRIPTION
**Pull request by vikaspatil0021**
This PR is to add Twipla analytics in the app store

fixes: #14758 

loom video:
https://www.loom.com/share/2e97fea489044271b7f6f3fe03ccc52a

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

- Add Twipla analytics application to an event type.
- Open up the event page and it should automatically track it.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by PeerRich** [comment]
looks great! can you uncommit your yarn.lock? [main/CONTRIBUTING.md#guidelines-for-committing-yarn-lockfile](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md?rgh-link-date=2024-04-28T18%3A26%3A42Z#guidelines-for-committing-yarn-lockfile)

**Comment by vikaspatil0021** [comment]
@PeerRich Any updates on this?

**Review by PeerRich — DISMISSED** [review]
nice! thank you

**Review by hariombalhara — APPROVED** [review]
Thanks @vikaspatil0021 🙏

**Pull request merged**
