### PR TITLE
fix: #11555

### LINKED ISSUE #11555: Block/Restrict e,-,+ for number input fields for Event Type page
Found a bug? Please fill out the sections below. 👍

At Event Type page while creating a new event or editing an event, we are able to enter e,-,+ for "duration" field. Duration field accepts only number so we should block/restrict user from entering these characters.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. go to the "Event Types" page
2. Create a new event or edit an existing event
3. enter e,-,+ for duration field and try saving those changes.

### Actual Results

https://github.com/calcom/cal.com/assets/86093112/82363877-8ed8-49bb-96eb-1fd93a183493

### Expected Results
We should be able to block/restrict user from entering those characters instead of showing them error message.

### PR DESCRIPTION
**Pull request by Zopsss**
## What does this PR do?

Fixes #11555

https://github.com/calcom/cal.com/assets/86093112/990faf35-3d21-4af4-8656-908910a9bc3d

Here in this video, I'm trying to enter e,-,+ but it is restricting me to do that.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by PeerRich — CHANGES_REQUESTED** [review]
we should probably solve this differently, more generic, maybe with zod

**Review by Udit-takkar — COMMENTED** [review]
@MauryanKansara do not push yarn.lock file if there is no change in package.json file. 

Undo the changes
git checkout origin/main -- yarn.lock
and push yarn.lock again

**Comment by MauryanKansara** [comment]
> @MauryanKansara do not push yarn.lock file if there is no change in package.json file.
> 
> Undo the changes git checkout origin/main -- yarn.lock and push yarn.lock again

I have undo the changes of yarn.lock file and pushed it. can you check it??

**Comment by MauryanKansara** [comment]
> > @MauryanKansara do not push yarn.lock file if there is no change in package.json file.
> > 
> > Undo the changes git checkout origin/main -- yarn.lock and push yarn.lock again
> 
> I have undo the changes of yarn.lock file and pushed it. can you check it?? 

@Udit-takkar can you review my changes again?? I've make changes as you said.

**Comment by MauryanKansara** [comment]
> > > @MauryanKansara do not push yarn.lock file if there is no change in package.json file.
> > > Undo the changes git checkout origin/main -- yarn.lock and push yarn.lock again
> > 
> > 
> > I have undo the changes of yarn.lock file and pushed it. can you check it??
> 
> @Udit-takkar can you review my changes again?? I've make changes as you said.

@Udit-takkar hey can you review my PR?

**Comment by Udit-takkar** [comment]
@MauryanKansara can you sign CLA https://github.com/calcom/cal.com/pull/11556#issuecomment-1737307105 and fix the conflicts?

**Comment by MauryanKansara** [comment]
> @MauryanKansara can you sign CLA [#11556 (comment)](https://github.com/calcom/cal.com/pull/11556#issuecomment-1737307105) and fix the conflicts?

I'm facing some issues to resolve conflicts... can you help me to resolve them in discord??

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
@MauryanKansara I fixed the conflicts but I don't think we need these changes. Even if i enter "-", "+"  i get this 

https://github.com/calcom/cal.com/assets/53316345/c517735c-ce46-4533-b668-d84bd5b9c535

**Pull request closed without merging**
