### PR TITLE
feat: Added e2e test for validating phone number input

### LINKED ISSUE #9261: [CAL-1845] Update Manage Booking Questions tests to add an e2e for PhoneInput
Why this test?. See [https://github.com/calcom/cal.com/pull/9258](https://github.com/calcom/cal.com/pull/9258)

Test can be added to this file [https://github.com/calcom/cal.com/blob/main/apps/web/playwright/manage-booking-questions.e2e.ts#L11](https://github.com/calcom/cal.com/blob/main/apps/web/playwright/manage-booking-questions.e2e.ts#L11)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1845](https://linear.app/calcom/issue/CAL-1845/update-manage-booking-questions-tests-to-add-an-e2e-for-phoneinput)</sub>

### PR DESCRIPTION
**Pull request by piyushgarg-dev**
## What does this PR do?
Added a test case to validate the phone number input while booking a meeting.

Fixes #9261

**Environment**: Staging(main branch) / Production

## Type of change
- Test Case Added

### CODE REVIEW

**Review by hariombalhara — CHANGES_REQUESTED** [review]
@piyushgarg-dev thanks for the PR🙏 The tests are failing though

**Review by zomars — COMMENTED** [review]
Delegating final review to @hariombalhara and also retriggered checks.

**Review by hariombalhara — APPROVED** [review]

**Comment by hariombalhara** [comment]
@piyushgarg-dev The test is still failing/timing out. Can you take a look please

**Review by keithwillcode — CHANGES_REQUESTED** [review]
Type checks are failing

**Comment by keithwillcode** [comment]
This PR is being closed due to inactivity. Please reopen if work is intended to be continued.

**Pull request closed without merging**
