### PR TITLE
Fixes dialog content

### PR DESCRIPTION
**Pull request by sean-brydon**
Fixes dialog components being broken and showing our default buttons.

These changes still use the `v1` style of dialogs so we pass `useOwnActionButtons` which disables our dialogs from displaying the default ones. 

Fixed :) 
CleanShot 2022-11-25 at 22 02 24@2x

### CODE REVIEW

**Review by zomars — APPROVED** [review]
Thank you Sean

**Comment by PeerRich** [comment]
is useOwnButtons a good prop?

**Comment by zomars** [comment]
> is useOwnActionButtons a good prop?

That's not the scope of this PR. We could discuss Dialog API in another issue/PR.

**Comment by PeerRich** [comment]
ok lets merge and follow up with a proper fix as discussed in threads @sean-brydon

**Review by pumfleet — APPROVED** [review]
lovely stuff

**Comment by sean-brydon** [comment]
Closing in favour of PR that has been merged already

**Pull request closed without merging**
