### PR TITLE
feat: Use Stripe paymentElement with multiple payment methods

### LINKED ISSUE #18049: [CAL-4858] Paid Bookings: Use "Payment Element" instead of custom UI
lets use: https://docs.stripe.com/payments/payment-element

for:

image

so we can enable all possible stripe connect payment methods:

CleanShot 2024-12-06 at 21 53 08@2x

<sub>[CAL-4858](https://linear.app/calcom/issue/CAL-4858/paid-bookings-use-payment-element-instead-of-custom-ui)</sub>

### PR DESCRIPTION
**Pull request by itsalam**
## What does this PR do?

- Changes payment layout to accordion
- Adds all permitted options for immediate transactions (scheduled/delayed transactions are still card only).

- Fixes #18049 (GitHub issue number)
- Fixes CAL-4858 (Linear issue number - should be visible at the bottom of the GitHub issue description)
(https://www.loom.com/share/024bbb7cd17947edb33f773ee61fa4d8?sid=8d794599-0c88-4b79-b24e-9cdaa6778d89)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. On the main Stripe account that Cal.com uses, be sure to enable [payment methods for connected accounts](https://docs.stripe.com/connect/payment-methods)
2. Add the stripe account and connect whatever test account is desired.
3. Modify the connected test account for whatever payment methods you wish to view. 
4. Book a paid meeting to view the payment methods.

- Are there environment variables that should be set?
- NEXT_PUBLIC_STRIPE_PUBLIC_KEY, STRIPE_PRIVATE_KEY, and STRIPE_CLIENT_ID must be set to the account calcom intends to be using.
- What are the minimal test data to have?
- n/a
- What is expected (happy path) to have (input and output)?
- on paid bookings, multiple options may appear.
- Any other important info that could help to test that PR

/claim #18049

### CODE REVIEW

**Review by Praashh — CHANGES_REQUESTED** [review]
Overall, it looks good to me, but it would be great if we had a test case for this feature.

**Review by PeerRich — DISMISSED** [review]

**Comment by itsalam** [comment]
@Praashh, tried to give it a go, though I'm not entirely sure how feasible it is, so I'ld to hear your thoughts.

Since what this change is doing is changing the API calls that will later populate the Stripe Payment UI, which is an external component made by Stripe, the only real test we can do is: "given this api response field X, make sure the stripe element gets X". Which doesn't seem feasible to mock/test.

**Review by PeerRich — APPROVED** [review]
lets do a test as a follow up

**Comment by Praashh** [comment]
> @Praashh, tried to give it a go, though I'm not entirely sure how feasible it is, so I'ld to hear your thoughts.
> 
> Since what this change is doing is changing the API calls that will later populate the Stripe Payment UI, which is an external component made by Stripe, the only real test we can do is: "given this api response field X, make sure the stripe element gets X as a prop". Which doesn't seem feasible to mock/test.
> 
> EDIT: actually, still giving this a go, I might backtrack on this.

Yes, for a giving field, it should work correctly with Stripe API. If we add this, that would be very helpful.

**Comment by itsalam** [comment]
So then, how do we test this? What Stripe API keys do we use in the tests to see if it returns the expected extra fields?

**Review by Praashh — APPROVED** [review]
Ok then, lets do a test as a follow up

**Pull request merged**
