### PR TITLE
fix: update `cancel` dictionary key to `cancel_event`

### PR DESCRIPTION
**Pull request by albertborsos**
## What does this PR do?

Fixes a cancel dictionary key (which is more relevant to use if you want to cancel a form submission) usage in an event related context. This is important for languages where there are different words exists for "cancel" and "to cancel something".

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

I searched for `t("cancel")` and where the context looked like it is related to an event, then I replaced it with `t("cancel_event")`.

- What is expected (happy path) to have (input and output)?
    - [ ] in confirmation emails it should show "cancel event" instead of just "cancel"

## Checklist

- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by Amit91848** [comment]
Thanks for the PR  @albertborsos ! But your changes have broken unit tests, please fix those 🙏

**Comment by albertborsos** [comment]
You're welcome.

I have no clue how can I fix that 😄 I just replaced some strings with another strings, but there are no mentions in the failing unit tests for those string 😄

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Hey @albertborsos, in all the places where we are using the 'cancel' button to cancel an event, it's understandable for users. Alongside 'cancel', we consistently use 'reschedule', it might be more straightforward to use 'Reschedule | Cancel' instead of 'Reschedule | Cancel Event'. What do you think?

**Comment by Amit91848** [comment]
I agree with @anikdhabal . We don't really want this change. Also would have to needlessly change tests. Thanks for your time @albertborsos

**Comment by albertborsos** [comment]
This was my previous pull request which was similar to this: https://github.com/calcom/cal.com/pull/14047

@anikdhabal as I mentioned in the second sentence of the PR, there are languages where different words exists for "cancel" and "to cancel something".

Since I changed the translation keys, it does not mean that it could not be the translation text "Cancel" for the `cancel_event` translation key in some languages. But in my language (hungarian) "Reschedule or Cancel" is pointless without context because it looks like "Reschedule or I do not want to reschedule". In my language "Reschedule or Resign" would be a right use of words, that is why it is necessary to have different translation key.

**Comment by albertborsos** [comment]
Also you could give some time to let me answer or try to investigate the unit tests because not everyone have to time to do open source full time.

**Comment by Amit91848** [comment]
Wasn't aware about the context, I was only considering it from the perspective of the English language. Will reopen it.

Also tests are failing in `apps/web/test/utils/bookingScenario/expects.ts` where it is expecting "cancel" but received "cancel_event"

**Comment by albertborsos** [comment]
Thanks for the tip for the failing tests.

**Comment by anikdhabal** [comment]
Hey @albertborsos Thanks for the PR, but we currently don't find any errors with the understanding of the cancel button. It's not just here; in many places, 'Cancel' is generally used to cancel a specific action

**Comment by albertborsos** [comment]
@anikdhabal why is that so hard to understand this is a real issue? Maybe it is not an issue for you, but it is a real issue for hungarian customers.

I described this issue twice, I am not gonna write it again. A similar PR previously merged by @PeerRich #14047 

Maybe you can not imagine this issue in your language. But this sentece for my hungarian customers is incomprehensible.
IMG_6047

**Comment by albertborsos** [comment]
If this PR is not the correct solution for this issue, then consider an another solution.

Since the `cancel_event` translation key in english is "Cancel event"
https://cal.crowdin.com/editor/1/all/en-hu/7?view=comfortable&filter=basic&value=0#q=cancel_event

Which would be also a totally acceptable translation in the emails. 

But if it is not OK, then there is an option to create a new translation key like `cancel_event_short` which could be "Cancel" without the event suffix.

This way it would be possible to use the already used translation for languages where it does not matter you cancels a verb or a noun. And I can use a correct translation for my language and my customers will know I am not a complete idiot, who cannot formulate a sentence correctly in his native language.

**Comment by anikdhabal** [comment]
@albertborsos This was my point of understanding, but let me verify this with a team member. If they agree, then I will reopen it and approve it. I know this is an issue for the Hungarian customer, but if you consider the broader language context, it is understandable. That's why I am closing it. I hope you understand

**Pull request closed without merging**
