### PR TITLE
feat: allow marking no-shows on ongoing-meeting

### LINKED ISSUE #17599: [CAL-4703] Allow marking no-show after booking started
Currently, we only allow marking bookings as no-shows if they are already in the 'past' tab. We also want to allow marking bookings as no-shows if it already started but the end time isn't in the past yet. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4703](https://linear.app/calcom/issue/CAL-4703/allow-marking-no-show-after-booking-started)</sub>

### PR DESCRIPTION
**Pull request by VK-RED**
## What does this PR do?

Added support for marking no-show feature in Ongoing meetings

- Fixes #17599 
- Fixes CAL-4703

[Screencast from 2024-11-13 10-16-11.webm](https://github.com/user-attachments/assets/13fb2fe8-7ecb-4dce-9b21-1f3663ccaf1f)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by Praashh — CHANGES_REQUESTED** [review]
we also need error handling if the user is marking  no-show before the meeting starts. can you please add ?

**Comment by VK-RED** [comment]
@Praashh Ig we are adding a check, if it's an ongoing meeting (i.e the meeting has started started but not ended yet). If the meeting is not started or ended, the user can't use the mark as no show. Kindly LMK if any changes are required..

**Comment by Praashh** [comment]
> @Praashh Ig we are adding a check, if it's an ongoing meeting (i.e the meeting has started started but not ended yet). If the meeting is not started or ended, the user can't use the mark as no show. Kindly LMK if any changes are required..

hey @VK-RED , we need to check the timing/status of a booking to prevent marking a no-show before a meeting's scheduled, similar to what we are doing for accessing the booking.

reference: https://github.com/calcom/cal.com/blob/main/packages/features/handleMarkNoShow.ts

**Comment by VK-RED** [comment]
Closing the PR as the issue is resolved by #17625

**Pull request closed without merging**
