### PR TITLE
chore: Remove env file cache

### PR DESCRIPTION
**Pull request by keithwillcode**
## What does this PR do?

Removes the cache layer for GitHub env 

## Type of change

- [X] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

Verify all GitHub workflows pass

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

### CODE REVIEW

**Comment by keithwillcode** [comment]
@zomars @emrysal These checks are failing since the file that "main" workflows are looking for is now gone.

**Comment by keithwillcode** [comment]
Can see here that the workflow was successful. https://github.com/calcom/cal.com/actions/runs/5623428205

**Comment by hariombalhara** [comment]
What's the reasoning behind removing it ? I see one immediate disadvantage that all env variables are duplicated at many places now.

**Comment by zomars** [comment]
> What's the reasoning behind removing it ? I see one immediate disadvantage that all env variables are duplicated at many places now.

Dealing with stale cache, new variables not being picked up, less steps overall. I think is a nice tradeoff for some code repetition.

**Review by zomars — APPROVED** [review]
Ship it

**Pull request merged**
