### PR TITLE
fix: scheduleId not unset properly bug

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

* Deprecates useHostSchedulesForTeamEvent from metadata
* Fixes issue with scheduleId remaining after useHostSchedulesForTeamEvent toggled.

How to test:
* Use current main and attempt to get scheduleId set and desynced (simply enable the schedule, then set it, then untoggle).
* Checkout the fix, check behaviour (It should now show the schedule was in fact still enabled)

Fixup old affected event types:
https://github.com/calcom/cal.com/pull/15993/commits/81ce59deb1f2206fc5e88e6b02a2bd9bd5e9fee2

This is not done as a migration as migrations should be able to be ran at any time, however when running this migration after this fix this may unset schedules of event types that are working correctly.

### CODE REVIEW

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
I am getting this error in the availability tab of a child managed event type: 
Screenshot 2024-08-06 at 2 57 33 PM

**Review by zomars — DISMISSED** [review]

**Comment by zomars** [comment]
> I am getting this error in the availability tab of a child managed event type: Screenshot 2024-08-06 at 2 57 33 PM

Do we have a test on these?

**Comment by zomars** [comment]
I was able to replicate locally. Will add a failing test.

image

**Comment by CarinaWolli** [comment]
@emrysal  How can I reproduce the bug on main? I tried: 

1. toggle 'Choose a common schedule'
2. select a schedule 
3. save event type 
4.  untoggle 'Choose a common schedule'
5. save event type 

When doing these steps the `scheduleId` is not set and is null in the end

**Review by CarinaWolli — APPROVED** [review]

**Pull request merged**
