### PR TITLE
Icon button instead of text

### LINKED ISSUE #4630: Booking Page: Button Overflow
Button overflows on the booking page 

Bildschirm­foto 2022-09-20 um 16 07 22

Chrome Browser

### LINKED ISSUE #4632: /booking-page - Change "Add guests" button to a button-icon
Currently we're having issues with the "Add guests" button not fitting in German.

Image

We need to change this to an icon button so that it fits better.

### PR DESCRIPTION
**Pull request by emrysal**
Fixes #4632
Fixes #4630

image

image
image

### CODE REVIEW

**Review by agustif — APPROVED** [review]
LGTM! 
image
One question though @emrysal, didn't we allow before to add more than one guest? Now you click and the button disappears, not sure what's the correct/expected behaviour here, if we want to keep the button to add more guests visible once the first is added?

image

**Comment by sean-brydon** [comment]
@agustif I think you're miss understanding the use case here - once the input box is display it allows the user to enter multiple emails 
CleanShot 2022-09-20 at 17 09 59@2x

**Review by sean-brydon — APPROVED** [review]
LGTM

**Comment by agustif** [comment]
> Agusti Fernandez Pardo I think you're miss understanding the use case here - once the input box is display it allows the user to enter multiple emails CleanShot 2022-09-20 at 17 09 59@2x

You're right sean! I did miss that the new input accepts multiple emails
image
Maybe a label below Guests or a tooltip telling you to add as many emails as you want could help, maybe not needed!

**Comment by Jaibles** [comment]
I was just in the process of designing this, and had done it like this..
https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17845%3A169787

**Comment by emrysal** [comment]
@Jaibles The MultiEmailInput was already implemented, I just made the button into the icon with tooltip and looking at your design we are pretty well aligned so far 💯

**Comment by PeerRich** [comment]
CleanShot 2022-09-20 at 20 51 52@2x

tests failing but LGTM

**Pull request merged**
