### PR TITLE
Add user-dropdown test

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Adds playwright test for user-dropdown which could have avoided the bug #2133

## Type of change

- [ ] Playwright Test

### CODE REVIEW

**Comment by PeerRich** [comment]
great test, not sure if its a core piece to be tested. thoughts @zomars? We want to be mindful of not having too many test that are not that critical.

**Review by zomars — APPROVED** [review]
I'll approve this test, but let's try to focus on product-breaking paths first 🙏🏽

**Comment by zomars** [comment]
The linter is failing because we have read-only access to your fork @hariombalhara

**Comment by hariombalhara** [comment]
> I'll approve this test, but let's try to focus on product-breaking paths first 🙏🏽 

I would love to contribute a few tests. Is there list I can follow?

**Comment by hariombalhara** [comment]
> It is a very nicely done test @PeerRich @hariombalhara although we may want to focus our resources in testing more critical paths (apps, rescheduling, cancelling, adding team members, in-app upgrading). Also, the forgot password test has been acting up recently, @hariombalhara if you could take a look on possible improvements there that would be nice.

Yeah I noticed that. Spent some time debugging it. Would look into it.

**Comment by zomars** [comment]
> > I'll approve this test, but let's try to focus on product-breaking paths first 🙏🏽
> 
> I would love to contribute a few tests. Is there list I can follow?

You can look at all test that are marked as `todo(`.

**Comment by hariombalhara** [comment]
> > It is a very nicely done test @PeerRich @hariombalhara although we may want to focus our resources in testing more critical paths (apps, rescheduling, cancelling, adding team members, in-app upgrading). Also, the forgot password test has been acting up recently, @hariombalhara if you could take a look on possible improvements there that would be nice.
> 
> Yeah I noticed that. Spent some time debugging it. Would look into it.

Waiting on this PR https://calendso.slack.com/archives/C02QSEPN1FT/p1647391271487089 before starting work.

**Comment by zomars** [comment]
> > > It is a very nicely done test @PeerRich @hariombalhara although we may want to focus our resources in testing more critical paths (apps, rescheduling, cancelling, adding team members, in-app upgrading). Also, the forgot password test has been acting up recently, @hariombalhara if you could take a look on possible improvements there that would be nice.
> > 
> > 
> > Yeah I noticed that. Spent some time debugging it. Would look into it.
> 
> Waiting on this PR https://calendso.slack.com/archives/C02QSEPN1FT/p1647391271487089 before starting work.

There's no need to wait. Tests aren't going to change much, just the setup.

**Comment by zomars** [comment]
> > > It is a very nicely done test @PeerRich @hariombalhara although we may want to focus our resources in testing more critical paths (apps, rescheduling, cancelling, adding team members, in-app upgrading). Also, the forgot password test has been acting up recently, @hariombalhara if you could take a look on possible improvements there that would be nice.
> > 
> > 
> > Yeah I noticed that. Spent some time debugging it. Would look into it.
> 
> Waiting on this PR https://calendso.slack.com/archives/C02QSEPN1FT/p1647391271487089 before starting work.

There's no need to wait. Tests aren't going to change much, just the setup.

**Comment by zomars** [comment]
> > > It is a very nicely done test @PeerRich @hariombalhara although we may want to focus our resources in testing more critical paths (apps, rescheduling, cancelling, adding team members, in-app upgrading). Also, the forgot password test has been acting up recently, @hariombalhara if you could take a look on possible improvements there that would be nice.
> > 
> > 
> > Yeah I noticed that. Spent some time debugging it. Would look into it.
> 
> Waiting on this PR https://calendso.slack.com/archives/C02QSEPN1FT/p1647391271487089 before starting work.

There's no need to wait. Tests aren't going to change much, just the setup.

**Comment by hariombalhara** [comment]
Sure. I have already raised a PR for some tests. 

Forgot password test might be fixed with that PR mentioned on slack. So still waiting on that and instead will focus on adding more tests.

**Comment by zomars** [comment]
@hariombalhara can you enable the "Allow edit from maintainers" setting as disclosed in [our CONTRIBUTING guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md#making-a-pull-request)?

**Comment by hariombalhara** [comment]
> @hariombalhara can you enable the "Allow edit from maintainers" setting as disclosed in [our CONTRIBUTING guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md?rgh-link-date=2022-03-16T19%3A50%3A46Z#making-a-pull-request)?
> 
> This will allow the linting action to generate reports.

That option is already enabled
Screenshot 2022-03-17 at 6 07 58 PM

**Comment by hariombalhara** [comment]
Closing this PR as we should focus on core tests.

**Pull request closed without merging**
