### PR TITLE
Add logo to location options

### LINKED ISSUE #1763: event-types: add app logos to location dropdown
this dropdown should show the .svg of each app

image

like this:

image

### PR DESCRIPTION
**Pull request by miguelnietoa**
## What does this PR do?

Fixes #1763 
Note: I realized that the Jitsi logo is actually the Zoom logo, so the Cal.com team should provide the svg to use for Jitsi. However, this is not a problem because it would only be changing the svg

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

1. Enter an event type
2. Click on the Location dropdown
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
hmm i didn't think of the black hover. the logos on black look bad. maybe we should use a light gray when hovering @Jaibles

**Comment by miguelnietoa** [comment]
> hmm i didn't think of the black hover. the logos on black look bad. maybe we should use a light gray when hovering @Jaibles

Hey @PeerRich , sounds good. Do you need this `hover` to change only for this specific `Select`?
Because there is a class `react-select` that forces the background to be black and the letters to be white. (`apps/web/styles/globals.css`)

**Comment by PeerRich** [comment]
we'll find a better way with less hard coded app meta data

**Comment by miguelnietoa** [comment]
> we'll find a better way with less hard coded app meta data

Ok @PeerRich!

**Pull request closed without merging**
