### PR TITLE
feat: add name and email url params when rescheduling past bookings

### LINKED ISSUE #18310: [CAL-4944] URL params when rescheduling past bookings
When rescheduling past bookings, we redirect to the normal booking link. We should include the email and name as URL parameters.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4944](https://linear.app/calcom/issue/CAL-4944/url-params-when-rescheduling-past-bookings)</sub>

### PR DESCRIPTION
**Pull request by kart1ka**
## What does this PR do?

- Fixes #18310 (GitHub issue number)
- Fixes CAL-4944 (Linear issue number - should be visible at the bottom of the GitHub issue description)

https://github.com/user-attachments/assets/e2b062ff-9a6d-4156-bd6a-52fdb1a76069

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by retrogtx** [comment]
adding `responses: true,`  will help in getting rid of the type error in `getServerSideProps.ts`
I was trying to solve the same issue, hope this helps 🫡

image

**Comment by kart1ka** [comment]
> adding `responses: true,` will help in getting rid of the type error in `getServerSideProps.ts` I was trying to solve the same issue, hope this helps 🫡
> 
> image

I am not getting any type error.

**Comment by retrogtx** [comment]
> > adding `responses: true,` will help in getting rid of the type error in `getServerSideProps.ts` I was trying to solve the same issue, hope this helps 🫡
> > image
> 
> I am not getting any type error.

nothing while using .reponses() ?

image

**Comment by Praashh** [comment]
@kart1ka is correct 👌 , I am also not getting any type error and FYI: we also have a ci pipeline for type check as well
Screenshot 2024-12-23 at 10 21 44 AM
Screenshot 2024-12-23 at 10 21 58 AM

@retrogtx This is probably in your local machine,  @retrogtx can you check again.

**Comment by retrogtx** [comment]
> responses: true

I get it but this is with `responses: true`, right?
Look at the order of commits, my comment was right after the first commit when it wasn't the case :D

**Review by Praashh — APPROVED** [review]
LGTM!!

**Pull request merged**
