### PR TITLE
Trailing unlocking node <17

### PR DESCRIPTION
**Pull request by emrysal**
Allow the node v16 engine to run Cal.com

### CODE REVIEW

**Comment by zomars** [comment]
It seems the we got a cache hit `@calcom/web:build: cache hit, replaying output d04f7697c8ca95bb`

**Comment by zomars** [comment]
We will jump to `v16` eventually but as for now Vercel builds are fixed in 6a18b40c977774fcffa5ea9be8d31a0a1310fa33

**Review by PeerRich — APPROVED** [review]

**Review by zomars — CHANGES_REQUESTED** [review]
Holding for now

**Comment by zomars** [comment]
Closing for now

**Comment by emrysal** [comment]
Re-opened to make this happen 👍

**Review by zomars — APPROVED** [review]

**Comment by zomars** [comment]
Should we update the `.nvmrc` version as well? @emrysal

**Comment by emrysal** [comment]
@zomars I had to look up what this did, does anyone even use that?

**Comment by zomars** [comment]
@emrysal everyone but you it seems 😅

**Comment by emrysal** [comment]
I would consider it bad practise to have this in the repo, because we'd need to keep updating the .nvmrc every time a new lts comes out; rather than users picking the latest Gallium lts (which they should).

**Comment by zomars** [comment]
I don't consider it a bad practice. Also it is a very common one to ensure collaborators are on the same page. This is the "recommended" version to use, not necessarily enforced.

**Pull request merged**
