### PR TITLE
Web3 Experiment: connect to MetaMask & WalletConnect

### PR DESCRIPTION
**Pull request by PeerRich**
- [x] added MetaMask integration
- [x] added WalletConnect integration
- [ ]  a setting to offer bookings only to holders of the same coin (DAO-support)
- [ ] ability to stake coins (and get slashed) for a no show

https://user-images.githubusercontent.com/8019099/140900017-0bd37d62-bf79-44fc-8950-359edcc040d3.mov

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
Would love to help out if this still needs help 👀

**Comment by PeerRich** [comment]
> Would love to help out if this still needs help 👀

yes we need! can you book me? cal.com/peer

**Comment by Dhaiwat10** [comment]
Done

**Comment by Dhaiwat10** [comment]
@PeerRich I guess you couldn't make it to the call? I'm fine with continuing the convo here

**Comment by pedropregueiro** [comment]
@Dhaiwat10 have you started on this yet? thinking of helping out here as well

**Comment by Dhaiwat10** [comment]
> @Dhaiwat10 have you started on this yet? thinking of helping out here as well

Not yet. Just joined the Slack and we're supposed to talk further there

**Comment by kamikazebr** [comment]
Interessant! I'll suggest use the package of Aragon to make that integration easy.

https://github.com/aragon/use-wallet

Look that

**Pull request closed without merging**
