### PR TITLE
fix(@cal.com/web): update debounce logic to work correctly and not show non-premium usernames as premium

### LINKED ISSUE #15628: Non premium usernames being shown as premium during sign up due to an issue in debounce logic
Found a bug? Please fill out the sections below. 👍

### Issue Summary

As per [this logic](https://github.com/calcom/cal.com/blob/main/packages/lib/server/username.ts#L50-L55) from  `packages/lib/server/username.ts` the premium usernames are either `<=4` characters or are present in the username blacklist present the URL from `process.env.USERNAME_BLACKLIST_URL`. However, as you can see from the video below, the usernames that are longer than >=4 characters and not in the blacklist are still shown as `premium` and `unavailable` prompting users to upgrade.

https://github.com/calcom/cal.com/assets/19223383/e3ed651e-e100-4ce4-8a06-1da61aac1007

### Steps to Reproduce

1. Go to https://app.cal.com/getting-started
2. Enter a username that is longer than 4 characters, fast - for example: `liukang`
3. You'll see a premium username error even though `liukang` is >4 characters and isn't in the blacklist
Screenshot 2024-06-30 at 7 50 21 PM
4. Add a `-` at the end of `luikang` -> `liukang-`. As you can see from the image below, once you add `-` the premium name error goes away.
Screenshot 2024-06-30 at 7 51 31 PM
5. Now remove the `-` from the end and the name `liukang` will no longer show the premium validation error
Screenshot 2024-06-30 at 7 53 07 PM
6. You can click on update and save the name too
Screenshot 2024-06-30 at 8 08 41 PM

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

This is a bug because it's marking usernames that are not premium as being premium, additionally provides a janky user experience when trying to sign up to cal.com, which could negatively impact user perception.

### Actual Results

- usernames that aren't premium are marked as premium even though the `POST /api/username` responds with the following:
```json
{
    "available": true,
    "premium": false,
    "suggestedUsername": ""
}
```

### Expected Results

- Only the usernames that are satisfy the criteria should be marked as premium
- The UI should respect the API response from `POST /api/username`

### Technical details

- The reason for this is a bug in the debounce logic on the UI in [PremiumTextField.tsx](https://github.com/calcom/cal.com/blob/main/apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx)
- The debounce doesn't apply and if you see the network tab on the video attached or in your browser, you'll be able to see that there are API calls to `POST /api/username` on every `OnChange`.
- The main reason for this is because the `inputUsernameValue` prop changes on every `onChange` event on the `username` TextField (since it updates the external state via `setInputUsernameValue`)
- The way to resolve this is by cleaning up the `debouncedAPICall` in the `useEffect` cleanup function when the component unmounts.
- This bug is also present on the [UsernameTextField.tsx](https://github.com/calcom/cal.com/blob/main/apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx)

#### Additional feedback on these files:
- The [PremiumTextField.tsx](https://github.com/calcom/cal.com/blob/main/apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx) and [UsernameTextField.tsx](https://github.com/calcom/cal.com/blob/main/apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx) practically do the same thing, except one also checks whether a username is Premium for cal.com cloud instances. These two components can be merged into a single component.
- The `useMemo` hook is an unnecessary over optimization in this case and can be removed

### Evidence

- Please refer to the video & screenshots I've added above
- I've tested it on cal.com production website

### PR DESCRIPTION
**Pull request by theonly1me**
fix(@cal.com/web): update debounce logic to work correctly and not show non-premium usernames as premium

- removes redundant useMemo hook from UsernameTextfield.tsx & PremiumTextField.tsx
- cancles the debounceAPICall on every unmount of UsernameTextfield.tsx & PremiumTextfield.tsx via useEffect cleanup function

Fixes #15628

## What does this PR do?

- Fixes #15628 
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

### Video
In the video below you can see the debounce logic now works as expected and API requests to `POST /api/username` only happen when user is done typing. Towards the end of the video, I also show a comparison with cal.com/getting-started production site.

https://github.com/calcom/cal.com/assets/19223383/41e10ad4-3caa-4aff-9da9-4aeca96cb506

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? Just the basic seed data
- What is expected (happy path) to have (input and output)? When you enter `liukang` or some non-premium username in localhost:3000/getting-started it shouldn't show an incorrect Premium state
- Any other important info that could help to test that PR - I've added the details in the Issue description of #15628

### CODE REVIEW

**Review by Amit91848 — COMMENTED** [review]
Hey @theonly1me , thanks for the PR!! But I can still reproduce it on my end. Am I missing something?




https://github.com/calcom/cal.com/assets/74371312/96ae0185-f998-4155-bf42-5d4334d2797a

**Review by Amit91848 — CHANGES_REQUESTED** [review]
We also already have a useDebounce hook, can you please use that instead @theonly1me 🙏

**Comment by theonly1me** [comment]
@Amit91848 I've updated the code to use the pre-existing `useDebounce` hook. The debounce logic will also work as expected on both the UsernameTextfield and PremiumTextfield components, video references below.

Can you take another look at the PR?

**UsernameTextfield**
https://github.com/calcom/cal.com/assets/19223383/373ce17d-6d79-4936-810a-2e2a50bc6b6e

**PremiumTextfield**
https://github.com/calcom/cal.com/assets/19223383/a33e1c46-3012-473d-8e73-1ebe56f7d86a

**Review by Amit91848 — APPROVED** [review]
LGTM!

Great work @theonly1me , thanks for the fast response 🙏. Tested and works fine!

Also added a small fix for signup page


https://github.com/calcom/cal.com/assets/74371312/6eed117a-ce0f-4bd6-ad6a-813455d29f2d

**Pull request merged**
