### PR TITLE
RFC: added brandcolor for switch

### LINKED ISSUE #8212: make switch brand color
CleanShot 2023-04-11 at 23 09 18@2x

### PR DESCRIPTION
**Pull request by PeerRich**
- [x] needs brand contrast for thumb @sean-brydon 

CleanShot%202023-04-11%20at%2023 04 07@2x

-- Edit by @sean-brydon 
Brand color contrast check for thumb color

Screenshot 2023-04-12 at 12 46 36

Screenshot 2023-04-12 at 12 47 34

### CODE REVIEW

**Review by Udit-takkar — APPROVED** [review]
LGTM 
Screenshot 2023-04-13 at 3 51 09 PM

**Review by leog — APPROVED** [review]
LGTM

Was wondering if we could allow appearance change for the entire app, not just booking page now that we support it.

**Comment by sean-brydon** [comment]
> LGTM
> 
> Was wondering if we could allow appearance change for the entire app, not just booking page now that we support it.

Soon :) WIll be done after the PR @hariombalhara made fixing next theme cache

**Review by sean-brydon — APPROVED** [review]
LGTM :')

**Pull request merged**
