### PR TITLE
Feature/send opt in booking email

### LINKED ISSUE #1988: send email when booking an opt-in booking
as of today we only send emails when a booking was confirmed

for opt-in bookings we should also send an email with this content: 

image

### PR DESCRIPTION
**Pull request by Mayowa-Ojo**
## What does this PR do?

Adds a feature to also send emails to the attendee for opt-in bookings. Currently only the organizer gets an email to confirm/decline the opt-in booking.
> Note: The email template shown uses a clock icon, which isn't currently available, so I'm temporarily using a calendar icon till the clock icon is added.

#### TODO:
- [ ] Add clock icon

Fixes #1988 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [x] Login with two separate accounts. Create an `opt-in` event-type on **Account A**. From **Account B**, go to the link to that event and create a booking. Account B should receive an email that the booking has been submitted. 

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by alannnc — APPROVED** [review]
Thanks! It's working great

**Comment by Mayowa-Ojo** [comment]
Nice! How can I get the icon in this [image](https://user-images.githubusercontent.com/8019099/155882207-e585f25c-ab58-4766-a5ad-8b09dc0df894.png)? It seems they're hosted somewhere

**Comment by agustif** [comment]
> Nice! How can I get the icon in this [image](https://user-images.githubusercontent.com/8019099/155882207-e585f25c-ab58-4766-a5ad-8b09dc0df894.png)? It seems they're hosted somewhere

It's heroicons
`import { ClockIcon } from "@heroicons/react/solid";`
in `apps/web/pages/success.tsx:115 you can see how it's used:
```tsx
{needsConfirmation && <ClockIcon className="h-8 w-8 text-green-600" />}
```

**Review by agustif — APPROVED** [review]
Great work  @Mayowa-Ojo really useful feature for bookers. Looks good to me! giving it the OK

image
image

**Comment by Mayowa-Ojo** [comment]
Ah, yes that's true. But the imports from `heroicons` are `svgs` and I think the `png` icons are being used in email templates. Like this sample:
```tsx
import { IS_PRODUCTION, BASE_URL } from "@lib/config/constants";

export type BodyHeadType = "checkCircle" | "xCircle" | "calendarCircle";

export const getHeadImage = (headerType: BodyHeadType): string => {
  switch (headerType) {
    case "checkCircle":
      return IS_PRODUCTION
        ? BASE_URL + "/emails/checkCircle@2x.png"
        : "https://app.cal.com/emails/checkCircle@2x.png";
    case "xCircle":
      return IS_PRODUCTION
        ? BASE_URL + "/emails/xCircle@2x.png"
        : "https://app.cal.com/emails/xCircle@2x.png";
    case "calendarCircle":
      return IS_PRODUCTION
        ? BASE_URL + "/emails/calendarCircle@2x.png"
        : "https://app.cal.com/emails/calendarCircle@2x.png";
  }
};
```
I just want to be sure if it's okay to use the `svg` icons in email templates

**Comment by agustif** [comment]
> @agustif Ah, yes that's true. But the imports from `heroicons` are `svgs` and I think the `png` icons are being used in email templates. Like this sample:
> 
> ```tsx
> import { IS_PRODUCTION, BASE_URL } from "@lib/config/constants";
> 
> export type BodyHeadType = "checkCircle" | "xCircle" | "calendarCircle";
> 
> export const getHeadImage = (headerType: BodyHeadType): string => {
>   switch (headerType) {
>     case "checkCircle":
>       return IS_PRODUCTION
>         ? BASE_URL + "/emails/checkCircle@2x.png"
>         : "https://app.cal.com/emails/checkCircle@2x.png";
>     case "xCircle":
>       return IS_PRODUCTION
>         ? BASE_URL + "/emails/xCircle@2x.png"
>         : "https://app.cal.com/emails/xCircle@2x.png";
>     case "calendarCircle":
>       return IS_PRODUCTION
>         ? BASE_URL + "/emails/calendarCircle@2x.png"
>         : "https://app.cal.com/emails/calendarCircle@2x.png";
>   }
> };
> ```
> 
> I just want to be sure if it's okay to use the `svg` icons in email templates
oh good catch there, I'd say safest to do it like we do on templates and not use svg's, Outlook or other non web clients might not display them properly I guess

**Comment by Mayowa-Ojo** [comment]
@agustif Yes that's what I was thinking too. Although the clock icon png will need to be added. Only those three icons are currently available. Except I'm missing the `url`

**Review by zomars — APPROVED** [review]
Approved! Thank you for your contribution 🙏

**Pull request merged**
