### PR TITLE
fix: include eventTypeId in BOOKING_CANCELLED event

### PR DESCRIPTION
**Pull request by nicolls1**
## What does this PR do?

This addresses one missing field in webhook events as mentioned here: #12286. My integration is breaking because this field is missing.

## Requirement/Documentation

This updates the actual payload to be in line with the current documentation

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

I could not find any unit tests to update for this, happy to do so if I missed them.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by jkdowdle** [comment]
@Udit-takkar @CarinaWolli If this were to merge, when could we expect it to be deployed and available for use on the cal.com services?

**Comment by swain** [comment]
@CarinaWolli Worth noting: the failed status check here is only present because of a fluke Docker failure on one of the E2E test runs. It just needs to be re-triggered.

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
LGTM

**Comment by aecorredor** [comment]
@PeerRich thanks for getting this merged so quickly!

One more question: how does the deployment cycle work for `main`? At what point does it end up in your production environment for customers who use the cloud solution?

**Pull request merged**
