### PR TITLE
feat: Add syntax highlighting and autocomplete menu for workflow variables

### LINKED ISSUE #15285: [CAL-3847] Autocomplete and highlight variable names in workflows.
### Is your proposal related to a problem?

I'm always frustrated when I'm in a rich text editor and have to leave my keyboard to do an action.

### Describe the solution you'd like

I'd like to not leave my keyboard when trying to insert a variable, much like notion where when you press `/` you get an autocomplete list, I'd like to press `{` and get a list of all available variables. I'd also like to have highlighting on variables so it's more clear at first sight.

### Additional context

I can implement a autocompletion menu in lexical if this issue get's approved, I have a high degree experience with the editor so I'd just like to see if there is interest in this feature before start coding. 

### Requirement/Document

(Share it here.)

---
##### House rules
- If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  - For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  - Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>[CAL-3847](https://linear.app/calcom/issue/CAL-3847/autocomplete-and-highlight-variable-names-in-workflows)</sub>

### PR DESCRIPTION
**Pull request by martinsione**
## What does this PR do?

This adds syntax highlighting as well as notion-like autocomplete menu for workflow variables.
Screenshot 2024-06-02 at 15 57 12

- Fixes https://github.com/calcom/cal.com/issues/15285
- Fixes [CAL-3847]

 Loom Video: https://www.loom.com/share/c4f920e667ea490f9bca9bc64d1868a4?sid=82d7f2bb-d47c-49e8-9617-6d88ce43a0fa

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] (N/A) - I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] (N/A) - I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Create a new workflow with an email action go to the text editor and press `{`, you should get a notion-like autocomplete menu with all the available variables.
- Try adding custom variables, by default anything wrapped within `{` `}` will get highlighted as a variable

### CODE REVIEW

**Comment by sean-brydon** [comment]
Tested seems to work for me @CarinaWolli can you take a look at this since you worked on this initially

**Comment by PeerRich** [comment]
this is really cool!

**Review by CarinaWolli — COMMENTED** [review]
Love that 🙏  @martinsione any idea why it only works for email body but not for email subject and SMS text message?

**Comment by martinsione** [comment]
@CarinaWolli The reason it doesn't work for email subject or sms is that both of them are using a regular `<textarea />`. Would you like me to update those to use the editor?

**Review by CarinaWolli — APPROVED** [review]
> @CarinaWolli The reason it doesn't work for email subject or sms is that both of them are using a regular <textarea />. Would you like me to update those to use the editor?

Ah yes makes sense, I think this is good for now. Thank you @martinsione really nice new feature 🙏

**Pull request merged**
