### PR TITLE
fix: Tooltip must be used within TooltipProvider

### LINKED ISSUE #16833: Tooltip must be used within TooltipProvider
I have this problem when I deployed cal using docker 
image

### PR DESCRIPTION
**Pull request by notmuhammad**
## Fix #16833

After installing Cal.com for the first time, users are not able to run go through the setup process on the client due to `PageWrapper` not being applied to `/auth/setup`.

- Fixes #16833

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A - I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. Do a fresh install of Cal.com; clone the repo into a new workspace and run `yarn dev` after installing dependencies
2. Create a new Postgres DB so that Cal.com recognizes that a setup is required
3. Head over to localhost:3000. 
4. After getting redirected to localhost:3000/auth/setup, an error will occur: "Tooltip must be used within TooltipProvider"

- Are there environment variables that should be set?
Nope
- What are the minimal test data to have? 
An new DB with no users
- What is expected (happy path) to have (input and output)? 
No errors when going to localhost:3000/auth/setup
- Any other important info that could help to test that PR

### CODE REVIEW

**Review by anikdhabal — APPROVED** [review]
Great find @muhammadspace

**Comment by FrancoAlbarra** [comment]
i still get this error deploying on render 
image

**Comment by FrancoAlbarra** [comment]
> i still get this error deploying on render image

Also getting this error on console and the hole page goes blank first i get a error waring 505 but after a few seconds dissapears 
image

Thanks you for reading i hope we can fix this soon,
regards

**Comment by anikdhabal** [comment]
> i still get this error deploying on render 
Thanks for reporting; I will check that. Also, these changes have not been shipped to production yet

**Comment by FrancoAlbarra** [comment]
> > i still get this error deploying on render
> 
> Thanks for reporting; will check that. Also, these changes have not been shipped to production yet

ok, i'll wait for the solution to be publish

**Comment by FrancoAlbarra** [comment]
any news on this?

**Comment by anikdhabal** [comment]
> any news on this?

Yeah, it's shipped. Could you pls check

**Pull request merged**
