### PR TITLE
fix: remove away view

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

With the new OOO feature we got rid of the away feature. Remove the following view form the profile page: 

Screenshot 2024-04-19 at 11 45 53 AM

Also, always show green dot here: 
Screenshot 2024-04-19 at 11 49 59 AM

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@CarinaWolli do we also want to remove Away  from packages/features/bookings/Booker/Booker.tsx?

Screenshot 2024-04-19 at 9 42 18 PM

**Comment by CarinaWolli** [comment]
> @CarinaWolli do we also want to remove Away from packages/features/bookings/Booker/Booker.tsx?
> 
> Screenshot 2024-04-19 at 9 42 18 PM

Removed, we can remove all the logic around it in a follow-up if we decide to fully get rid of the away feature

**Review by sean-brydon — APPROVED** [review]
LGTM

**Review by zomars — APPROVED** [review]
LGTM. Can we remove the away column from the users table in a followup? Also we could at least mark it as deprecated in the prisma schema

**Comment by CarinaWolli** [comment]
> LGTM. Can we remove the away column from the users table in a followup? Also we could at least mark it as deprecated in the prisma schema

I will do that in a follow up, I am not sure if we made that decision to get rid of away or if it just happened with the introduction of OOO. Will clarify that first with @ciaranha

**Pull request merged**
