### PR TITLE
fix: mark people invited to an org as email-verified

### LINKED ISSUE #11209: [CAL-2420] Assure there is no verify email banner for verified org members
### Issue Summary

When people get in an org through invitation, there are times they are asked to verify their email, which doesn't make sense as they accepted the invitation using the provided email.

### Steps to Reproduce

1. Create an org
2. Invite members to the org
3. Create subteams
4. Invite members to the subteam

### Actual Results

Member will sometimes unexpectedly get a banner to verify their email

### Expected Results

Mark invited people to an org as email verified

### Evidence

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2420](https://linear.app/calcom/issue/CAL-2420/assure-there-is-no-verify-email-banner-for-verified-org-members)</sub>

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
## What does this PR do?

This PR marks users invited to an org as email verified.

Fixes #11209 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Invite a member to an org. 
- Try to login as the invited member. 
- You should not see email verified banner at top.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
So this introduces a new bug 
1) First invited user to organization team

2) This is the url i get in the mail http://app.cal.local:3000/signup?token=4d6bebc5af435b3834e61d6473d9d08aa4cc401457b564b2a6a71b6c5025ea13&callbackUrl=/getting-started which is correct.

3) When i enter this url i get redirected to /login page instead because of this

Screenshot 2023-09-09 at 2 11 24 AM

maybe we should try marking the email verified after sign up step.

**Comment by ujwalkumar1995** [comment]
Hey @Udit-takkar 
Have made the change as per your suggestion, please review.

**Comment by leog** [comment]
@ujwalkumar1995 @Udit-takkar I was thinking that marking an invited user as email-verified is something that should be already happening here: https://github.com/calcom/cal.com/blob/main/apps/web/pages/api/auth/signup.ts#L97

Is there any other use case which that code doesn't cover in order to pursue this PR?

**Review by leog — CHANGES_REQUESTED** [review]
@ujwalkumar1995 @Udit-takkar I was thinking that marking an invited user as email-verified is something that should be already happening here: https://github.com/calcom/cal.com/blob/main/apps/web/pages/api/auth/signup.ts#L97

Is there any other use case which that code doesn't cover in order to pursue this PR?

**Comment by ujwalkumar1995** [comment]
> @ujwalkumar1995 @Udit-takkar I was thinking that marking an invited user as email-verified is something that should be already happening here: https://github.com/calcom/cal.com/blob/main/apps/web/pages/api/auth/signup.ts#L97
Is there any other use case which that code doesn't cover in order to pursue this PR?


Hey @leog 
You are correct. This change is not needed as it is already handled at the place where you mentioned. I verified in local and could not replicate the original issue #11209. I will close the PR for now.

**Pull request closed without merging**
