### PR TITLE
fix: Fixed Issue #10291 removed brand color for tooltip

### LINKED ISSUE #10291: [CAL-2214] UI: Tooltips should not be branded
Currently, tooltips are taking on the brand color.
CleanShot 2023-07-21 at 08 41 50@2x

They should keep the standard tokens with `bg-inverted` `content-inverted`
CleanShot 2023-07-21 at 08 52 28@2x

**View in Figma**

<sub>[CAL-2214](https://linear.app/calcom/issue/CAL-2214/ui-tooltips-should-not-be-branded)</sub>

### PR DESCRIPTION
**Pull request by bhargavtenali**
## What does this PR do?
fixes #10291 

The issue simply happened because we have given bg-brand-default as background color of tooltip, which gets bg color from brand.
I had removed the class and gave bg-inverted static class which gives background color irrespective of brand color

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
See below screenshots taken after fix
https://drive.google.com/file/d/17sF5XTvlXA9rGiUXjAVx3Zog3sZfb8nW/view?usp=sharing
https://drive.google.com/file/d/1rPYfeSwav58OtLifYEpijcy69ZKXJGTD/view?usp=sharing

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
Screenshot 2023-07-24 at 3 49 43 PM

the circular box next to time is not visible

**Comment by bhargavtenali** [comment]
@Udit-takkar 
Hi, Can you tell me how your scenario has come.
Even after several try's i cant mimick your screenshot behaviour . lol

**Comment by bhargavtenali** [comment]
@Udit-takkar 
To show the +1 or -1 `(time.isNextDay || time.isPreviousDay)` condition should be true
I had now changed the hardcoded background and no color given text (it was inheriting from parent) to suitable colors

**Review by Udit-takkar — APPROVED** [review]
Great work

**Comment by bhargavtenali** [comment]
Hi @Udit-takkar ,
Can you please merge this branch to main ? 
Since this is very minor code change, we can safely deploy it to main
Also I had tested the same in local -> Everything is fine & as expected

**Pull request merged**
