### PR TITLE
fix: multiple getSchedule requests on email change in booker

### LINKED ISSUE #15574: [CAL-3974] Multiple Slots.getSchedule requests being sent when typing email on booker page
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When booking an event-type, entering email makes multiple requests for getSchedule. Tried with other question formats too but ig this is only broken for required email.

### Steps to Reproduce

1. Create event-type
2. Try making a booking for that event 
3. Open up chrome dev tools and check network tab

https://github.com/calcom/cal.com/assets/74371312/855b4d69-2781-4e88-af26-8154b1c11bde

### Actual Results

- Multiple unrelated requests are being sent 

### Expected Results

- No requests should be sent

<sub>[CAL-3974](https://linear.app/calcom/issue/CAL-3974/multiple-slotsgetschedule-requests-being-sent-when-typing-email-on)</sub>

### PR DESCRIPTION
**Pull request by dilpreetsio**
## What does this PR do?

- Fixes #15574 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A-I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] N/A-I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
- Create an event-type
- Create a booking
- Open network tab in dev tools & update the email field.

There are no more requests for slots when the email is changed.

https://github.com/calcom/cal.com/assets/12807846/91963249-e88c-4cef-93ff-bc3b499723be

### CODE REVIEW

**Review by anikdhabal — DISMISSED** [review]
Hey, one more request is being sent -` checkIfUserEmailVerificationRequired`. This is from the useVerifyEmail hook. Do you think it would be optimal to not pass bookerEmail? This bookerEmail retrieves the email address of the owner of a contact in the CRM system.

**Comment by dilpreetsio** [comment]
@anikdhabal The `checkIfUserEmailVerificationRequired` is basically checking if the email is blacklisted or not, so we need to keep it.

**Comment by nishchal27** [comment]
making a server request on every keystroke can be costly

**Comment by dilpreetsio** [comment]
The input is debounced to reduce the number of request. If we want to further reduce the number of requests one way to go ahead would be check if the email is valid before sending a request.

**Comment by dilpreetsio** [comment]
> Do you think it would be optimal to not pass bookerEmail? This bookerEmail retrieves the email address of the owner of a contact in the CRM system.

Do you mean not passing the bookerEmail to the `useScheduleForEvent` hook ?

**Review by Udit-takkar — DISMISSED** [review]
@dilpreetsio how does this fix the issue? 
bookerEmail was required in packages/trpc/server/routers/viewer/slots/util.ts

```
  const crmContactOwner = await getCRMContactOwnerForRRLeadSkip(
      input.bookerEmail,
      eventType?.metadata?.apps
    );
    
 ```

**Comment by anikdhabal** [comment]
> Do you mean not passing the bookerEmail to the `useScheduleForEvent` hook ?

Yes, @Udit-takkar shared the code above.

**Review by Amit91848 — CHANGES_REQUESTED** [review]
> The input is debounced to reduce the number of request. If we want to further reduce the number of requests one way to go ahead would be check if the email is valid before sending a request.

If you are saying the input is debounced but requests are still being sent on every keystroke, it suggests that the debounce may not have been configured correctly. Please look into it. @dilpreetsio

**Comment by dilpreetsio** [comment]
Totally missed that @Udit-takkar . Thanks for pointing that out.

One way of taking care of it would be to decouple the CRM logic from the getSchedule. Another way would be to debounce the email inside the `useScheduleForEvent` hook.

For the concerns regarding the debounce not optimized, we can increase the duratiion.

**Review by Amit91848 — APPROVED** [review]
LGTM!

Thanks @dilpreetsio

**Pull request merged**
