### PR TITLE
fix: Set mobile availability

### LINKED ISSUE #7351: [CAL-1151] mobile: set your availability
figma: [https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&mode=design](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Live?type=design&mode=design)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1151](https://linear.app/calcom/issue/CAL-1151/mobile-set-your-availability)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #7351 
/claim #7351

Before:-
Screenshot 2023-08-30 165330

Now:- 

Screenshot 2023-08-30 164611
Screenshot 2023-08-31 030044

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@anikdhabal i think the sidebar or drawer should have 100% height

**Comment by anikdhabal** [comment]
> @anikdhabal i think the sidebar or drawer should have 100% height

Okay Let me fix that.

**Comment by anikdhabal** [comment]
> @anikdhabal i think the sidebar or drawer should have 100% height

Done

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
looks fine

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Comment by anikdhabal** [comment]
> LGTM

Thank you🙏

**Pull request merged**
