### PR TITLE
Upgrades tRPC to 10.10.0

### PR DESCRIPTION
**Pull request by zomars**
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by zomars** [comment]
@SocketSecurity ignore @prisma/client@4.10.1 @prisma/engines@4.8.1

**Review by leog — APPROVED** [review]
LGTM

**Comment by PeerRich** [comment]
should we wait for @katt or merge @zomars ?

**Comment by zomars** [comment]
> should we wait for @KATT or merge @zomars ?

I would love to hear his input but all checks are passing and it gives enough confidence to merge IMO

**Pull request merged**
