### PR TITLE
feat: New Location - "System Default (<Name>)"

### LINKED ISSUE #14015: [CAL-4157] New Location: "System Default (<Name>)"
we already have the concept of "Default" Conferencing tool:

CleanShot 2024-03-07 at 15 28 07@2x

however, we dont use it for existing and new event-types and only use it for team links and group links.

we should add a new setting for event-types above all installed locations:

- System Default (`<Name>`)

CleanShot 2024-03-07 at 15 26 25@2x

when this is selected, whatever System default is selected will be used.

this way, you can mass-update all event-types with your new default

this also solves the issue if people dont ever want to use Cal Video, they can change their System Default and automatically past and future events will have their system default as a location

<sub>[CAL-4157](https://linear.app/calcom/issue/CAL-4157/new-location-system-default-name)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

fixes #14015

System default
Screenshot 2024-07-31 232633

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by SomayChauhan** [comment]
@anikdhabal can't seem to replicate the issue, could you confirm?

**Comment by anikdhabal** [comment]
https://github.com/calcom/cal.com/assets/81948346/3064ff77-368a-4f5c-87c9-a19146805ae1

@SomayChauhan

**Comment by SomayChauhan** [comment]
I think there's a larger issue at play here
we shouldn't be creating a team event with the user's default location 
pushed a fix https://github.com/calcom/cal.com/pull/15208/commits/ab7c88f8b1deec96c199fd01356844b8fd6a1d6f for it 
do let me know what you think

**Comment by anikdhabal** [comment]
Hey @SomayChauhan thanks for the commit. But I observe some bugs are still there:-

1. Currently, the default conferencing app label for the organizer is not visible (after your commit).
2. If the default app is calVideo, then the location field has not been set as the default location at the time of both team and personal event type creation. It was there before your commit.

**Comment by SomayChauhan** [comment]
Hey @anikdhabal, 
could you record a loom of the bugs you mentioned, and I can take a look if you want
couldn't replicate what you said, everything worked fine for me
thanks

**Comment by anikdhabal** [comment]
The previously mentioned bug has been fixed, so I am linking another feature related to location in this PR

**Comment by anikdhabal** [comment]
Need to update more thing, as per I noticed in the issue

**Pull request closed without merging**
