### PR TITLE
fix: email validation in user post method API

### PR DESCRIPTION
**Pull request by TaduJR**
## What does this PR do?

ref #12688

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Shpadoinkle** [comment]
Noticed this isnt isolated to the API,  as Creating a user through the front end also doesnt lower case the email address in the DB.   so i dont think this is a useful change as Calcom has never insisted on lowercase emails.  

not sure of the best solution to this.  It's weird that it expects a lower case email on the impersonation despite it never enforcing lower case anywhere else. 


maybe its best to change the impersonation logic.  Change how it handles the email checking as who knows how many users exist with capital letters in their email addresses.

**Comment by Shpadoinkle** [comment]
Noticed this isnt isolated to the API @hariombalhara ,   as Creating a user through the front end also doesnt lower case the email address in the DB either.   so i dont think this is a useful change as Calcom has never insisted on lowercase emails.  

not sure of the best solution to this.  It's weird that it expects a lower case email on the impersonation logic despite it never enforcing lower case anywhere else. 


maybe its best to change the impersonation logic.  Change how it handles the email checking as who knows how many users exist with capital letters in their email addresses.

**Comment by Shpadoinkle** [comment]
This PR also wont solve the issue for existing users with Capital email addresses that try to login.    You'll need to compare a lowercased input to a lowercased version of the db entry.

**Comment by TaduJR** [comment]
> This PR also wont solve the issue for existing users with Capital email addresses that try to login. You'll need to change the logic that is comparing a lowercased input to a **_non_**-lowercased version of the db entry.

@Shpadoinkle Note that this issue exists on API version only. So If you created a user via API and tried to login via dashboard it doesn't work because API creation of user is not converting email address to lowercase but not in tRPC backend server.

**Comment by Shpadoinkle** [comment]
> > This PR also wont solve the issue for existing users with Capital email addresses that try to login. You'll need to change the logic that is comparing a lowercased input to a **_non_**-lowercased version of the db entry.
> 
> @Shpadoinkle Note that this issue exists on API version only. So If you created a user via API and tried to login via dashboard it doesn't work because API creation of user is not converting email address to lowercase but not in tRPC backend server.

Has this changed since version 3.5.5?    I just created a user in the front end  and it also saves the user with capital letters to the database.

**Comment by Shpadoinkle** [comment]
> > This PR also wont solve the issue for existing users with Capital email addresses that try to login. You'll need to change the logic that is comparing a lowercased input to a **_non_**-lowercased version of the db entry.
> 
> @Shpadoinkle Note that this issue exists on API version only. So If you created a user via API and tried to login via dashboard it doesn't work because API creation of user is not converting email address to lowercase but not in tRPC backend server.

@TaduJR  Has this changed since version 3.5.5?    I just created a user in the front end  and it also saves the user with capital letters to the database.

**Comment by TaduJR** [comment]
Hmmm. Ok @Shpadoinkle. I will look it to that. Thanks.

**Comment by Shpadoinkle** [comment]
this PR should also handle existing users somehow.  

As lowercasing emails for new users only doesn't solve the login or impersonation issue for existing users.

**Comment by TaduJR** [comment]
@Shpadoinkle I created a user on the frontend using case-sensitive email but it is stored in lower-case email. I think it is fixed on later versions. Also I made my test email case-sensitive and it returned error.

Yes you are right.  The best solution is making lowercase their input behind the scenes to avoid throwing breaking API errors then also change the login/impersonation logic to read a lowercased version of the db entry.

But I tried to checkout Prisma Docs case-sensitive querying. It has some errors and lack of usage documentation in some prisma users report. https://www.prisma.io/docs/orm/prisma-client/queries/case-sensitivity

So the best would be converting all tables who has email attribute to lowercase in the production database.

Then This fix handles the API side by user creation email to lowercase.
And on the Backend I think it is already implemented. Because I created case-sensitive email and the backend stored it as lowercase.

**Comment by zomars** [comment]
Agreed with @Shpadoinkle that this PR helps but if doesn't close #12688  as we need to make sure all user creates/updates are lowercasing emails properly. Merging without closing the issue for now.

**Review by zomars — APPROVED** [review]

**Pull request merged**
