### PR TITLE
Resolve conflicted deps issue for v1.1

### PR DESCRIPTION
**Pull request by JakeCooper**
This PR resolves issue #1184 for Railway builds

Appears node17 doesn't seem to play well with a few deps

### CODE REVIEW

**Comment by emrysal** [comment]
Hi @JakeCooper - I've been working on fixing the dependency in question and had good success, I'm also doing other booking changes whilst I'm at it but the dependency issue should be solved by Friday.

**Comment by sreekaransrinath** [comment]
It hasn't been fixed yet, looks like.

**Comment by PeerRich** [comment]
@baileypumfleet @zomars is this safe to merge?

**Comment by zomars** [comment]
I think @emrysal would know best in this case

**Comment by zomars** [comment]
Closing since #1184 is already resolved. Feel free to reopen if necessary.

**Pull request closed without merging**
