### PR TITLE
fix: Hidden event type switch behaviour is out of sync between event types page & single view

### LINKED ISSUE #8766: [CAL-1634] Hidden event type switch behaviour is out of sync between event types page & single view
[33565863-920b-4e38-8d9c-1b6af944f158](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/0a565217-2e12-4db5-af7b-20584bc95f56/33565863-920b-4e38-8d9c-1b6af944f158)

When I toggle an event type as hidden on the event types page, the opposite behaviour appears when I click in to view the single event type. When I then toggle it in the single view and come back out, it seems to toggle the complete opposite behaviour by itself on the event types page.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1634](https://linear.app/calcom/issue/CAL-1634/hidden-event-type-switch-behaviour-is-out-of-sync-between-event-types)</sub>

### PR DESCRIPTION
**Pull request by gitstart-calcom**
Fixes #8766 

## Task Description
https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/2.-Cal---Live?type=design&node-id=4654%3A167842&t=eOPD3fNaNM4CMyZS-1

CleanShot 2023-05-17 at 11 14 36@2x CleanShot 2023-05-17 at 11 16 14@2x

## Loom video
https://www.loom.com/share/cc342bb949cf452aad7419f1d91858f7

### CODE REVIEW

**Comment by gitstart-calcom** [comment]
Hi @Jaibles, please review the PR

**Comment by Jaibles** [comment]
> Hi @Jaibles, please review the PR

@gitstart can you please update the loom link. It's a demo of something from an app called Spellbound.

**Comment by gitstart-calcom** [comment]
> @gitstart can you please update the loom link. It's a demo of something from an app called [Spellbound](https://share.cleanshot.com/zM5B53nx).

Sorry about that 😅 
Updated the link now

**Review by leog — APPROVED** [review]
LGTM @gitstart-calcom, let's wait for @Jaibles blessing.

Just a NIT that would be nice to tackle: adding the "Hide from profile" switch in the menu in the Event Types page just like it happens on the Event Type config page:

<kbd></kbd>

<kbd>image</kbd>

**Comment by gitstart-calcom** [comment]
Hi @leog, now that you mentioned it, we missed updating the switch behavior in the menu in Single Event Types. We are going to fix that and add the switch in the menu in the Event Types as well.

**Comment by PeerRich** [comment]
> Hi @leog, now that you mentioned it, we missed updating the switch behavior in the menu in Single Event Types. We are going to fix that and add the switch in the menu in the Event Types as well.

cool. will wait for the change before merging

**Comment by gitstart-calcom** [comment]
HI @leog, we have updated the PR, please re-review. cc: @Jaibles @PeerRich

**Pull request merged**
