### PR TITLE
fix #1330 add NEXT_PUBLIC_SITE_NAME alias SITE_NAME .env.example

### LINKED ISSUE #1330: There is no quick and conflict-free way to change the name of the site.
I propose to use an environment variable in .env for example: SITE_NAME=Cal.com

### PR DESCRIPTION
**Pull request by alejandroaguilarhiguera**

### CODE REVIEW

**Comment by zomars** [comment]
Is this related to #1330 ?

**Comment by PeerRich** [comment]
will look into this tomorrow and test each page. we could also think about having this as a setting in the profile 💭

**Comment by zomars** [comment]
I don't think it would make sense to have this on DB for self-hosted. A env var seems like the right approach. 👍🏽

**Comment by PeerRich** [comment]
we may introduce this in the enterprise license

**Comment by zomars** [comment]
> we may introduce this in the enterprise license

How so? I don't think we can do that.

**Pull request closed without merging**
