### PR TITLE
fix: Hide SAML/OIDC login button if no sso connection exists (Self hosted instance)

### LINKED ISSUE #10886: [CAL-2374] OIDC configuration deletion has poor cleanup
If we add an OIDC configuration, and later on we go and remove it, it shows removed from the `/settings/security/sso` page, however, the login page still shows the option to `Login with SAML/OIDC`. In that situation, if someone clicks on this login button, they are lead to an error page that doesn't look the best, but I imagine the option shouldn't exist in the first place.

Steps to recreate the issue:

1. Add a new OIDC configuration \[guide to set it up\](https://cal.com/docs/how-to-guides/how-to-setup-oidc-with-okta)
2. Now remove it
3. Go to the login page, and notice the Login with `SAML/OIDC` button still exists
4. Click on the Login with `SAML/SSO` button to see the error page

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2374](https://linear.app/calcom/issue/CAL-2374/oidc-configuration-deletion-has-poor-cleanup)</sub>

### PR DESCRIPTION
**Pull request by devkiran**
## What does this PR do?

Fixes #10886 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

See the description on the issue https://github.com/calcom/cal.com/issues/10886

### CODE REVIEW

**Review by zomars — DISMISSED** [review]
Fixed conflicts and updated the router syntax. 

LGTM

**Comment by PeerRich** [comment]
tests are failing. tests are expecting the SAML button to be there @devkiran

**Comment by PeerRich** [comment]
CleanShot 2023-09-07 at 19 27 04@2x

**Review by PeerRich — DISMISSED** [review]

**Comment by devkiran** [comment]
Self-hosted version: The SAML login button is visible only if a SAML connection exists.

Hosted version: The SAML login button is visible permanently. We validate the connection after the user enters their email address and clicks the SAML login button.

**Review by PeerRich — APPROVED** [review]
reapproved on behalf of @zomars

**Comment by zomars** [comment]
### Merge Activity

* **Oct 9, 5:02 AM**: [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/10903) failed to merge this pull request due to **internal failures**. Try your merge again, or report a bug if you see this consistently.

**Review by alishaz-polymath — APPROVED** [review]
Tested locally, works as expected 🚀

**Pull request merged**
