### PR TITLE
feat: display long durations in hours on booking

### LINKED ISSUE #12107: Display long durations in hours on the booking page
### Is your proposal related to a problem?

When using Cal.com to schedule longer events (such as workshops, trainings, etc. which take a half or full working day), displaying durations on the booking page in minutes (such as 240 minutes or 480 minutes) is confusing.

### Describe the solution you'd like

On the booking page, durations longer than a certain threshold should be rendered as `X hours` or `X hours Y mins` instead of in minutes.

My suggestion would be to do this for durations of 60 minutes and more, meaning that 60 minutes would be displayed as `1 hour` and 90 minutes would be displayed as `1 hour 30 mins`, but that is open for discussion.

This applies to event types with a fixed duration as well as event types where the booker can choose from multiple duration options.

Current | Proposed solution
---|---
afbeelding | afbeelding

### Describe alternatives you've considered

The scope of this issue is intentionally limited to the booking page. I initially also considered the event type management page, but that would introduce a lot of complexity in order to handle different input modes, standard durations vs events where the booker can choose from different durations, etc.
A solution for the event type management page could be proposed in a separate issue, but for me personally that would have less priority than this one. As the owner of the event I just have to convert hours to minutes once when I setup the event, as compared to every booker having to convert the number of minutes to hours.

Instead of the proposed threshold of 60 minutes a higher threshold could be considered. For example by setting it to 120 minutes, 120 minutes would be displayed as `2 hours` but 90 minutes would still be `90 mins`, which would avoid the complexity of singular/plural translations (needing different translations for `1 hour` and `2 hours`).

Alternatively, the singular/plural issue could simply be ignored, always showing plural (such as `1 hours` or `1 hours 30 mins`), but that doesn't feel like a good solution. For minutes I think it is less of an issue, because I don't think having a duration of X hours and 1 minute will be a very common use case.

I have also considered limiting this to very specific durations (for example a hard-coded mapping from 240 and 480 minutes to `4 hours` and `8 hours`), but I think a more generic solution would be preferable and will support more use cases.

### Additional context

#10663 introduced 240 and 480 minutes as options for multiple duration event types, resolving #10181.
In https://github.com/calcom/cal.com/issues/10181#issuecomment-1671588333 I suggested displaying longer durations in hours instead of minutes.

### PR DESCRIPTION
**Pull request by mikezzb**
## What does this PR do?

Fixes #12107

On the booking page, durations longer than a certain threshold should be rendered as X hours or X hours Y mins instead of in minutes.

120 minutes would be displayed as 2 hours ~but 90 minutes (< 120 minutes) would still be 90 mins, which would avoid the complexity of singular/plural translations (needing different translations for 1 hour and 2 hours).~

90 minutes would be displayed as 1 hour 30 mins

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Long duration (Bofore vs After)

Screenshot 2023-12-02 at 10 59 41

Screenshot 2023-12-02 at 11 14 00

### Internationalization (Left: Japan, Right: Chinese)

Screenshot 2023-12-02 at 11 20 36

Screenshot 2023-12-02 at 11 20 51

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@mikezzb I think it would be great if threshold is 60 minutes instead of 120.

Example:-
95 minutes -> 1 hour 35 minutes

**Comment by mikezzb** [comment]
> @mikezzb I think it would be great if threshold is 60 minutes instead of 120.
> 
> Example:- 95 minutes -> 1 hour 35 minutes

Sure, I will modify that.

**Comment by Udit-takkar** [comment]
please make sure to sign CLA https://github.com/calcom/cal.com/pull/12631#issuecomment-1837196530 so that we can accept your contributions

**Comment by mikezzb** [comment]
> @mikezzb I think it would be great if threshold is 60 minutes instead of 120.
> 
> Example:- 95 minutes -> 1 hour 35 minutes

Updated with demo:

Single hour & single minute:

Screenshot 2023-12-02 at 12 37 12


Single hour & plural minutes:
Screenshot 2023-12-02 at 12 37 22

Plural hours & plural minutes:
Screenshot 2023-12-02 at 12 37 34

Hour only:
Screenshot 2023-12-02 at 12 37 57

Minute only:
Screenshot 2023-12-02 at 12 37 51

**Review by Udit-takkar — COMMENTED** [review]
@mikezzb Awesome work. 

multi duration event types still display "75 minutes" and "90 minutes"

Screenshot 2023-12-02 at 11 20 21 PM

How to reproduce?

1) Go to event type settings

Screenshot 2023-12-02 at 11 21 17 PM

2) Turn on "Allow booker to select duration"

**Comment by mikezzb** [comment]
> @mikezzb Awesome work.
> 
> multi duration event types still display "75 minutes" and "90 minutes"
> 
> Screenshot 2023-12-02 at 11 20 21 PM
> How to reproduce?
> 
> 1. Go to event type settings
> 
> Screenshot 2023-12-02 at 11 21 17 PM
> 2. Turn on "Allow booker to select duration"

Thank you for your review! The original issue says "The scope of this issue is intentionally limited to the booking page. I initially also considered the event type management page, but that would introduce a lot of complexity in order to handle different input modes, standard durations vs events where the booker can choose from different durations, etc.", should we also integrate this on the event-types page?

**Comment by Udit-takkar** [comment]
@mikezzb this is the booking page. you can just update it here and leave the event type setting for now

Screenshot 2023-12-02 at 11 25 24 PM

**Comment by mikezzb** [comment]
> @mikezzb this is the booking page. you can just update it here and leave the event type setting for now
> 
> Screenshot 2023-12-02 at 11 25 24 PM

Thank you for your clarification! Updated with preview:

Screenshot 2023-12-02 at 12 59 15

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Pull request merged**
