### PR TITLE
fixed team URL in settings

### LINKED ISSUE #5029: [CAL-161] wrong link in teams
instead of cal.com/team-name it needs to be cal.com/team/team-name in settings

> From [Linear-GitHub Sync](https://synclinear.com)

### PR DESCRIPTION
**Pull request by PeerRich**
before
CleanShot 2022-10-15 at 21 29 22@2x

after
CleanShot 2022-10-15 at 21 29 55@2x

### CODE REVIEW

**Review by leog — COMMENTED** [review]
Would it make sense to apply the fallback I introduced somewhere where we show the web app URL differently when it surpasses certain character limit? Otherwise if the instance has a long URL, it might break or become unusable.

**Comment by PeerRich** [comment]
> Would it make sense to apply the fallback I introduced somewhere where we show the web app URL differently when it surpasses certain character limit? Otherwise if the instance has a long URL, it might break or become unusable.

do you know where we use it?

**Comment by leog** [comment]
> do you know where we use it?

[This](https://github.com/calcom/cal.com/pull/4738)  is the last variation I worked on, there is another version[here](https://github.com/calcom/cal.com/pull/3171)  that goes for having the url in the label. We should probably settle on one strategy only 😅

**Comment by PeerRich** [comment]
> > do you know where we use it?
> 
> [This](https://github.com/calcom/cal.com/pull/4738) is the last variation I worked on, there is another one [here](https://github.com/calcom/cal.com/pull/3171) that goes for having the url in the label. We should probably settle on one strategy only 😅

lets merge this and open a ticket to consolidate all of this into /lib/

**Review by hariombalhara — APPROVED** [review]

**Pull request merged**
