### PR TITLE
Fix prettier importOrderSeparation not working

### PR DESCRIPTION
**Pull request by denik1981**
## What does this PR do?

Prettier's configuration file is wrongly composed adding the [Tailwind Plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) in a declarative way within the **plugin** key. Prettier mentions that third-party plugins are automatically loaded if they have been installed in the same **node_modules** folder and follow the name of `@prettier/<plugin>` or `prettier-plugin-<plugin>` ([prettier-on-how-to-add-third-party-plugins](https://prettier.io/docs/en/plugins.html#using-plugins))

Placing a `plugin` key within `prettierrc.js` causes a not expected behavior because despite prettier actually runs, it fails on applying certain rules, being `importOrderSeparation` one of them.  A clear side effect for this is within issue #1791 where a missing space between the first import in all the `prisma/zod/*` files is causing all of them to differ from **HEAD** when they are regenerated by **prisma** (and later formatted by prettier)  
 
Fixes # (1791)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Test A: Fix for issue #1791 

- yarn generate-schemas
- git diff --name-only | grep "prisma/zod" || echo "PASSED"

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by zomars** [comment]
The problem is that If we remove the plugin declaration, the tailwind classes aren't sorted. You can try yourself locally.

**Comment by denik1981** [comment]
btw, regarding #1791, why it is necessary to vc prisma/zod files if they are fully generated in the post installation step by prisma. Can we gitignore them?

**Comment by PeerRich** [comment]
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1024722576 this seems to at least hotfix it

**Comment by zomars** [comment]
> btw, regarding #1791, why it is necessary to vc prisma/zod files if they are fully generated in the post installation step by prisma. Can we gitignore them?

Fair point @denik1981 we would probably just prettier ignore those files

**Review by zomars — APPROVED** [review]

**Comment by zomars** [comment]
The linter is working "too well" now 🤣 will merge as it is for now and we can fix those error on a followup.
image

**Comment by denik1981** [comment]
@zomars Thanks! 
I can confirm that the hotfix works well for autosave, linting and formatting.

This (below) is an emulation in an isolated nextjs app with all the Cal settings for prettier and eslint and tests added to it.
https://stackblitz.com/github/denik1981/prettier-tailwind-trivago-hotfix

`npm run test:should-fail` unformats a random file and then runs the linter
`npm run test:should-pass`  formats a random file and then runs the linter.

The reason I delayed this PR is because the hotfix throw me an error that I was not able to reproduce anymore.
Not sure the reason cause it is trying to parse an MD file but I will post it here just in case appears again.  

```
> yarn  format
yarn run v1.22.17
$ prettier --write "**/*.{ts,tsx,md}"
[error] Invalid configuration file `.github/ISSUE_TEMPLATE/bug_report.md`: Obejct is not defined
```

**Comment by PeerRich** [comment]
great work folks!

**Comment by PeerRich** [comment]
> @zomars Thanks! I can confirm that the hotfix works well for autosave, linting and formatting.
> 
> This (below) is an emulation in an isolated nextjs app with all the Cal settings for prettier and eslint and tests added to it. https://stackblitz.com/github/denik1981/prettier-tailwind-trivago-hotfix
> 
> `npm run test:should-fail` unformats a random file and then runs the linter `npm run test:should-pass` formats a random file and then runs the linter.
> 
> The reason I delayed this PR is because the hotfix throw me an error that I was not able to reproduce anymore. Not sure the reason cause it is trying to parse an MD file but I will post it here just in case appears again.
> 
> ```
> > yarn  format
> yarn run v1.22.17
> $ prettier --write "**/*.{ts,tsx,md}"
> [error] Invalid configuration file `.github/ISSUE_TEMPLATE/bug_report.md`: Obejct is not defined
> ```

oh whats the best way moving forward? @zomars

**Comment by zomars** [comment]
That's odd. I can't seem to replicate locally. Will investigate further.

**Pull request merged**
