### PR TITLE
Bugfix/revert e5ba8616

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

Reverts e5ba8616
Reverts the Sentry revert

### CODE REVIEW

**Review by zomars — CHANGES_REQUESTED** [review]
Thank you Alex. I got some observations:

- Let's add a self review
- Need context on why we're removing sendgrid
- Need context on what was causing the 500 error on user/type

**Comment by emrysal** [comment]
Let's add a self review - purely reverts / adds; no code authored.

* Need context on why we're removing sendgrid
* Need context on what was causing the 500 error on user/type

At this moment we don't know yet, @leog and I will tear that commit apart piece by piece until we've found the reason for a crash that seems unrelated. This commit will allow us to deploy again however something we've been unable to since v2.1.3.

**Comment by zomars** [comment]
Let's fix tests as well

**Review by zomars — APPROVED** [review]

**Comment by hariombalhara** [comment]
Wow, crash is gone🤯
 Seems like some unintended import happening in [user]/[type]

**Comment by rene-mueller** [comment]
is this related to https://github.com/calcom/cal.com/issues/5435?

**Comment by emrysal** [comment]
@rene-mueller - could potentially fix your issue too - yes.

**Pull request merged**
