### PR TITLE
feat: redirect after booking: option to forward parameters

### LINKED ISSUE #14223: [CAL-3315] redirect after booking: option to forward parameters
right now by default we always forward parameters. lets give people the option to make it optional (opt-out).

by default this should be on:

image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3315](https://linear.app/calcom/issue/CAL-3315/redirect-after-booking-option-to-forward-parameters)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

Fixes #14223 
/claim #14223

https://github.com/calcom/cal.com/assets/74371312/8939cca9-8570-4577-b081-5399e1ec549c

## Type of change

- New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by joeauyeung — CHANGES_REQUESTED** [review]
Heads up @Amit91848 when testing with a booking that requires payment, the payment specific params are still being added.

Ex. `http://localhost:3001/?payment_intent=pi_*****&payment_intent_client_secret=pi_***8&redirect_status=succeeded`

**Comment by Amit91848** [comment]
> Heads up @Amit91848 when testing with a booking that requires payment, the payment specific params are still being added.
> 
> Ex. `http://localhost:3001/?payment_intent=pi_*****&payment_intent_client_secret=pi_***8&redirect_status=succeeded`

Hmm, will look into it.

**Comment by Amit91848** [comment]
> Ex. `http://localhost:3001/?payment_intent=pi_*****&payment_intent_client_secret=pi_***8&redirect_status=succeeded`

Hey @joeauyeung, those params are being automatically added by Stripe on the return_url. Tried searching but unfortunately stripe does not give any option to not include those.

https://github.com/calcom/cal.com/blob/d59e68de6d2a6476c7f2e0ccbe63c545223e0ff3/packages/features/ee/payments/components/Payment.tsx#L111-L116

Relevant docs:
https://docs.stripe.com/js/payment_intents/confirm_payment#confirm_payment_intent-options-confirmParams-return_url

**Comment by Amit91848** [comment]
This should fix stripe passing params.


https://github.com/calcom/cal.com/assets/74371312/b7f4d1a4-a9f7-4c4c-8096-1a5bb5d5f0f0

**Comment by Amit91848** [comment]
Didn't realize we were using those stripe params, all tests are passing now.

**Review by joeauyeung — APPROVED** [review]
Now working as expected. Great work @Amit91848

**Pull request merged**
