### PR TITLE
Add Huddle01 integration

### PR DESCRIPTION
**Pull request by rohg007**
## What does this PR do?

This PR includes integration for Huddle01 Web3 Video Conferencing.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

Performed booking an event with Huddle01 Video as the location and worked fine.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pumfleet — COMMENTED** [review]
Code looks good to me, will test

**Review by pumfleet — APPROVED** [review]
Testing went great, thank you for your contribution!

**Review by alishaz-polymath — APPROVED** [review]
Looks good. Thanks for the contribution  @rohg007 :)
Much appreciated!

**Comment by rohg007** [comment]
Thanks for the review guys @baileypumfleet @alishaz-polymath :) Cheers!

**Pull request merged**
