### PR TITLE
adds devcontainer/codespaces support

### PR DESCRIPTION
**Pull request by phishy**
## What does this PR do?

Adds setup-free development environments in VSCode/docker and also VSCode/GitHub Codespaces

**Environment**: Staging(main branch)

image

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] Navigate to this PR
- [ ] Click "Code", "+", tooltip should say "create a codespace on devcontainer"
- [ ] Open Codespaces in the browser, however, you can also connect to these Codespaces from desktop VSCode 
- [ ] Should setup .env and yarn

Also, you should be able to run this locally without Codespaces

- [ ] Clone cal.com
- [ ] Change branch to `devcontainer`
- [ ] Open VSCode, it should ask to open the project in a devcontainer
- [ ] Should setup .env and yarn

## Checklist

### CODE REVIEW

**Comment by PeerRich** [comment]
this is really cool!

**Comment by PeerRich** [comment]
looks save to merge but cc'ed @zomars to give the opinion. cloudspaces look really cool imo

**Comment by zomars** [comment]
I suppose this is because this PR isn't merged yet right? 
image

**Review by zomars — APPROVED** [review]
Noice

**Pull request merged**
