### PR TITLE
Set a default for "create events on"

### LINKED ISSUE #2149: set a default for "create events on"
the lack of defaults here may cause side effects:

image

### PR DESCRIPTION
**Pull request by miguelnietoa**
## What does this PR do?

Set the first calendar connected as default to create events on.

Fixes #2149
Fixes #1744

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Go to Integrations
- [ ] Connect any Integration
- [ ] Notice now there is a default for "create events on"

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
thank you! looks good to me. passing it over to @zomars

**Review by zomars — CHANGES_REQUESTED** [review]
Thank you for your contribution. This a good start, but it doesn't solve the actual problem.

With your fix it now displays the first available calendar as a selected value. But this value isn't actually being saved in the DB. So until the user interacts with the Selector and the mutation runs, it will only "appear as selected". This can be misleading for users since they can assume that no interaction is necessary to save (which is).

I'll have to block this PR until this is addressed properly.

Possible solutions:

- Add logic to trigger the onChange callback so actually save the data
- Add visual indication that the user MUST select a calendar in order to actually work
-

**Comment by miguelnietoa** [comment]
> Thank you for your contribution. This a good start, but it doesn't solve the actual problem.
> 
> With your fix it now displays the first available calendar as a selected value. But this value isn't actually being saved in the DB. So until the user interacts with the Selector and the mutation runs, it will only "appear as selected". This can be misleading for users since they can assume that no interaction is necessary to save (which is).
> 
> I'll have to block this PR until this is addressed properly.
> 
> Possible solutions:
> 
> * Add logic to trigger the onChange callback so actually save the data
> * Add visual indication that the user MUST select a calendar in order to actually work

Agree, I will try out with the first possible solution suggested. 👌🏻

**Comment by miguelnietoa** [comment]
Hi @zomars, the default value is already saved in the database. But I have detected certain things:
1. When some integration is **disconnected**, the destination calendar is not updated.
I think this should be the expected behavior:
  a. **If any integrations remain**, **update** the destination calendar to the first remaining connected calendar.
  b. If there are **no integrations left**, **delete** the row from the destination calendar.

2. When some integration is connected from the onboarding, the default destination calendar is not created.
So I think that assigning the default value of the destination calendar should be within the mutation that creates the integration, instead of inside the component `DestinationCalendarSelector`.

What do you think?

**Comment by zomars** [comment]
> Hi @zomars, the default value is already saved in the database. But I have detected certain things:
> 
> 1. When some calendar is **disconnected**, the destination calendar is not updated.
>    I think this should be the expected behavior:
>    a. **If any calendars remain**, **update** the destination calendar to the first remaining connected calendar.

Agreed!

>    b. If there are **no calendars left**, **delete** the row from the destination calendar.

Agreed as well

> 2. When some calendar is connected from the onboarding, the default destination calendar is not created.
>    So I think that assigning the default value of the destination calendar should be within the mutation that creates the calendar, instead of inside the component `DestinationCalendarSelector`.

Yes, let the server handle this instead of doing it from the frontend. That way we will always have a selected calendar until all calendars are removed.

**Comment by miguelnietoa** [comment]
Nice! Working on that 💯

**Comment by miguelnietoa** [comment]
Hi @zomars, I already applied the changes I mentioned, and everything seems to be working fine, check it out!

**Comment by miguelnietoa** [comment]
Hey @zomars, have you had time to check it out? what news about this PR? let me know :)

**Review by zomars — APPROVED** [review]
Can confirm that this is working as expected. Thank you for your contribution 🙏

**Comment by miguelnietoa** [comment]
🎉 🎉 🎉

**Pull request merged**
