### PR TITLE
Update README.md: Google API instructions

### PR DESCRIPTION
**Pull request by PabloCastellano**
I got a bit confused when reading the Google API instructions. With these changes I think it's easier now.

---

<a href="https://app.devin.ai/review/calcom/cal.com/pull/146" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by baileypumfleet** [comment]
Are you able to approve my suggestion? Once that's done, I'll get this PR merged in :)

**Comment by PabloCastellano** [comment]
@baileypumfleet Where can I see your suggestion!?

**Review by pumfleet — APPROVED** [review]
Remove duplicate word

**Comment by baileypumfleet** [comment]
It's all merged in now, thanks for this contribution :)

**Pull request merged**
