### PR TITLE
disable standard confirmation emails if workflow exists

### LINKED ISSUE #3680: [CAL-1424] Disable standard confirmation email in even type settings
### Is your proposal related to a problem?

No

### Describe the solution you'd like

Possibility to disable the standard confirmation email in event type settings.

### Additional context

Requested by a user. He wants to set up his own confirmation email with workflows. 

<sub>[CAL-1424](https://linear.app/calcom/issue/CAL-1424/disable-standard-confirmation-email-in-even-type-settings)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Allow disabling standard confirmation emails for host and attendees if event type is active on a workflow that will send these emails instead. 

The trigger EMAIL_ATTENDEE now sends emails to all attendees not just the first one. 

Switches to disable emails can be found in advanced event type settings:
Screenshot 2023-05-08 at 13 13 14

Fixes #3680

Loom: https://www.loom.com/share/f569f130746748ffaa6481a9536ba2e3

### CODE REVIEW

**Review by ciaranha — COMMENTED** [review]
Looks great 👏

Should the copy read the other way around in terms of what gets applied to what? ie workflow applied to event type rather than event type applied to workflow? I know technically in the workflow we do select the event type, but feels to me like a workflow to event type relationship.

CleanShot 2023-05-08 at 16 45 23@2x

**Comment by CarinaWolli** [comment]
Updated text:
Screenshot 2023-05-09 at 08 55 51

**Review by Udit-takkar — APPROVED** [review]
LGTM. tested locally

**Comment by PeerRich** [comment]
@CarinaWolli i mentioned this before, should the checkbox not be visible inside the workflows area?

**Comment by PeerRich** [comment]
ok merging when ready

**Pull request merged**
