### PR TITLE
Feature: Add a "Return" button after cancellation of a booking

### PR DESCRIPTION
**Pull request by olui1**
After cancellation of a booking, a return button will redirect the user back to "/bookings" for convenience instead of typing the route manually in the address bar.

returnblue

### CODE REVIEW

**Comment by baileypumfleet** [comment]
Great work, but the problem is that the reschedule/cancel links are also given to the guest in the confirmation email, and they don't have access to /bookings because /bookings is part of the admin panel.

**Comment by emrysal** [comment]
@baileypumfleet Maybe a check for a logged in user? If logged in -> back to bookings

**Comment by olui1** [comment]
Ah! I should not have said "user". What I meant was for the admin to have an easier way to return back to "/bookings" after the cancellation of a booking through "/booking". Prior to the code, the admin only had one option which was to click the "Pick another" button which redirects the admin to the "Your Public Page".

pickanother

I should've been more specific!!

**Comment by baileypumfleet** [comment]
Looks like we would need to check for a logged in user before displaying the button. However, as this is low priority and we won't be working on this for a while, I'll close this off and reopen once we get back to it :)

**Pull request closed without merging**
