### PR TITLE
fix: Stripe integration

### LINKED ISSUE #9365: [CAL-1879] Make E2E test: Pending payment booking should not be confirmed by default
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1879](https://linear.app/calcom/issue/CAL-1879/make-e2e-test-pending-payment-booking-should-not-be-confirmed-by)</sub>

### PR DESCRIPTION
**Pull request by zodman**
## What does this PR do?

Fixes #9365

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

automated test

/claim #9365

### CODE REVIEW

**Comment by keithwillcode** [comment]
@zodman Thanks for your contribution. For future PRs, can you please fill in the PR description? 🙏

**Comment by zodman** [comment]
@keithwillcode this PR is complement of  https://github.com/calcom/cal.com/issues/9365 I need to know if this needs to be finish for finish https://github.com/calcom/cal.com/issues/9365

**Review by alannnc — APPROVED** [review]
Code looks good and it's working.
@roae Is this exactly what we wanted?

**Pull request merged**
