### PR TITLE
Replace React in client production build with Preact

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

take 2 of #1292

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How should this be tested?

- [ ] `yarn build` and `yarn start`
- [ ] `yarn test-e2e`

## Checklist

- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Udit-takkar** [comment]
@zomars are there any more benefits of preact other than reduced bundle size ?

**Comment by zomars** [comment]
> @zomars are there any more benefits of preact other than reduced bundle size ?

Other than reducing client side bundle size I'm not pretty sure. But every KB we can save without sacrificing functionality and performance is a win if you ask me.

**Comment by zlwaterfield** [comment]
@zomars do you still want to implement this change? Preact is a pretty strong alternative (https://preactjs.com/guide/v8/differences-to-react/) but my main concern is versioning. As Cal keeps the Next.js version up to date, they may bump the React version under the hood and I'm thinking this will be a cause of concern around keeping the Preact version inline. Do you think the space saving is worth it? IMO it is not.

**Comment by zomars** [comment]
I would worry too much about versioning as this change is easily reversible. Even [Next.js maintainers use this technique all the time](https://github.com/leerob/leerob.io/commit/74a3ebb14b81f785ea96f9c73fbe4f6c2463679c).

**Comment by alannnc** [comment]
@zomars PR has been updated in case anyone wanna try it out. It worked for me

**Review by alannnc — APPROVED** [review]

**Comment by PeerRich** [comment]
how much do we save? anyone has benchmarks?

**Comment by zomars** [comment]
Closing since the gain/effort to debug tests is not worth right now.

**Pull request closed without merging**
