### PR TITLE
fix: Added a time padding to hash my url

### LINKED ISSUE #6325: [CAL-703] Fix E2E Flaky test: hash my url
[This test](https://github.com/calcom/cal.com/blob/6f48869021055e12e2cfef4cdfbfbfd734aa95d5/apps/web/playwright/hash-my-url.e2e.ts#L8-L9) has been failing randomly.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-703](https://linear.app/calcom/issue/CAL-703/fix-e2e-flaky-test-hash-my-url)</sub>

### PR DESCRIPTION
**Pull request by tachyonicbytes**
## What does this PR do?

Adds a sleep of 1 second to the hash my url test.

Fixes #6325 

It seems that the "networkidle" heuristics were insufficient some of the times. A strange thing that happened on my machine, at least, is that the test seemed to fail much more often when I would run in headed mode and I would change the focus from the Chromium window to some other window.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Run the "hash my url" test multiple times, in order to test that it is not flaky anymore. You should also run with PLAYWRIGHT_HEADLESS set and unset, because it seemed to matter, when I tested.
I ran 10 times with both.

/claim #6325

### CODE REVIEW

**Comment by usmaann1** [comment]
/claim #6325 

Test Plan: Testing Time Padding in URL Hashing

Objective:
The objective of this test plan is to verify the addition of time padding to the URL hashing process. The test plan includes both manual tests and automated tests to ensure thorough verification. The focus of the tests will be on addressing flakiness and validating the impact of the PLAYWRIGHT_HEADLESS environment variable.

Test Scope:
The test scope includes multiple runs of the "hash my URL" test with variations in the PLAYWRIGHT_HEADLESS environment variable. The tests aim to confirm that the time padding implementation is consistent and not affected by the headless mode.

Test Environment:
The test environment should consist of:

- The system or application where the URL hashing process is implemented.
- Test data or content that triggers URL hashing.
- Test scripts or utilities for automated testing.

Test Plan:
4.1 Manual Tests:

4.1.1 Visual Inspection:
Objective: To visually inspect the hashed URLs and verify the presence of time padding.

Steps:
- Run the "hash my URL" test multiple times, specifying different inputs for URL hashing.
- Note down the generated hashed URLs for each run.
- Inspect the hashed URLs and validate the presence of a timestamp component.
- Verify that the timestamp is properly formatted and contains the necessary time padding.

4.1.2 Flakiness Testing:
Objective: To test the stability and consistency of the URL hashing process.

Steps:
- Run the "hash my URL" test multiple times, specifying different inputs for URL hashing.
- Note down the generated hashed URLs for each run.
- Compare the generated hashed URLs across multiple runs to identify any variations or inconsistencies.
- Verify that the time padding remains consistent across all runs.

4.1.3 Headless Mode Testing:
Objective: To validate the impact of the PLAYWRIGHT_HEADLESS environment variable on the URL hashing process.

Steps:
- Set the PLAYWRIGHT_HEADLESS environment variable and run the "hash my URL" test multiple times.
- Note down the generated hashed URLs for each run.
- Unset the PLAYWRIGHT_HEADLESS environment variable and run the "hash my URL" test multiple times.
- Compare the generated hashed URLs between the runs with PLAYWRIGHT_HEADLESS set and unset.
- Verify that the time padding and the overall URL hashing process are not affected by the headless mode.

4.2 Automated Tests:

4.2.1 Automated Flakiness Testing:
Objective: To automate the "hash my URL" test with different inputs to validate stability.

Steps:
- Develop a test script or utility that triggers the "hash my URL" test with various inputs.
- Run the test script multiple times, specifying different inputs for URL hashing.
- Compare the generated hashed URLs across multiple runs to identify any variations or inconsistencies.
- Validate that the time padding remains consistent across all runs.

4.2.2 Automated Headless Mode Testing:
Objective: To automate the "hash my URL" test with the PLAYWRIGHT_HEADLESS environment variable variations.

Steps:
- Develop a test script or utility that triggers the "hash my URL" test with different values of PLAYWRIGHT_HEADLESS.
- Set the PLAYWRIGHT_HEADLESS environment variable and run the test script multiple times.
- Note down the generated hashed URLs for each run.
- Unset the PLAYWRIGHT_HEADLESS environment variable and run the test script multiple times.
- Compare the generated hashed URLs between the runs with PLAYWRIGHT_HEADLESS set and unset.
- Verify the time padding and the overall URL hashing process.

**Comment by tachyonicbytes** [comment]
@usmaann1 What? Can you please not claim my PR? Yeah, I made a mistake and forgot to add `#`, thank you for attracting my attention to that. But this is unbelivable.

/claim #6325

**Comment by PeerRich** [comment]
no worry @tachyonicbytes it is claimed by whoever submits a PR first,  which is you

**Comment by IoannisFlo** [comment]
no worries @tachyonicbytes only your claim is linked to the PR. apologies for the inconvenience here - algora team

**Pull request closed without merging**
