### PR TITLE
Stripe automatic payment method

### LINKED ISSUE #5263: [CAL-3032] Allow other payment method types
### Is your proposal related to a problem?

We're trying to use `cal.com` in Poland, where payment cards are very unpopular. Most of the payment is being done via `Przelewy24` or `BLIK`, both of which Stripe has support for (even inside their `Checkout` page

(Write your answer here.)

### Describe the solution you'd like

I'd love cal.com to just see what payment methods are used in the connected Stripe account, and allow them on the checkout page.

### Describe alternatives you've considered

The only solution for us is doing a custom integration.

<sub>[CAL-3032](https://linear.app/calcom/issue/CAL-3032/allow-other-payment-method-types)</sub>

### PR DESCRIPTION
**Pull request by jepek**
## What does this PR do?

1. Deleting `payment_method_types` in Stripe Payments lets clients to manage payments methods by them - they know  best.
2. Introducing `automatic_payment_methods` (see [the docs](https://www.youtube.com/watch?v=5lS6WdT2GUI)) improves the payment methods - Stripe will automatically propose payment methods based on currency/locale.

Fixes #5263 

This video from the [Stripe Developers](https://www.youtube.com/watch?v=5lS6WdT2GUI&ab_channel=StripeDevelopers)  visually shows the difference

## Type of change
- [x] Chore (refactoring code, technical debt, workflow improvements)

## Required actions ❗ 
Let connected accounts manage their payments methods:

> Stripe recommends that you allow the owners of your platform’s connected accounts to customize their own payment methods from the Dashboard. If you enable this option, then each Standard connected account can log in to their Dashboard and view their [Payment methods](https://dashboard.stripe.com/settings/payment_methods) page.

Pleas see and follow the instructions here: https://stripe.com/docs/connect/automatic-payment-methods?connect-payment-integration-type=checkout&connect-charge-type=direct&connect-account-type=standard#allow-connected-accounts-manage

## How should this be tested?
This changes the flow on the payment page from Stripe.

- Check if other payment methods are available on payments page of connected account
- Check if specific payments methods are available on payments page of connected account after customazing them under connected account payment methods

## Additional
I wasn't able to publish self hosted version to test the custom payment methods from Stripe (they block it from local) thus preview instance and the change from **Required actions** would help a lot.

### CODE REVIEW

**Comment by PeerRich** [comment]
hey @jepek, we'll look into this! thank you for the PR

**Comment by PeerRich** [comment]
gave permission for a vercel deploymetn

**Comment by PeerRich** [comment]
weird. deployment failed

**Comment by jepek** [comment]
@PeerRich any reason from logs?

**Comment by PeerRich** [comment]
> @PeerRich any reason from logs?

somehow not

**Comment by jepek** [comment]
@PeerRich I rebased the branch on top of current `main` branch. Could you please approve the deployment to preview again?

**Comment by jepek** [comment]
Hey @zomars 

I see some conflicts now :eyes: Do you have any idea why this fails?

**Review by zomars — COMMENTED** [review]
Sorry for the delay @jepek I was just testing this change an realized that this doesn't affect in any way with our current payment flow. Even I this is set to auto we still only display the Stripe Elements Credit Card field. We don't use Stripe Checkout anywhere which I assume this is what this parameters control.

Will close this for now but a more complete approach would be always welcome.

Thank you for your contribution 🙏

**Comment by jepek** [comment]
Hey @zomars 

I am back to the topic as I have another opportunity to integrate cal.com for one of my clients but I need the payment method via Stripe that they provide.

I am not sure if this touches Stripe Checkout feature - I just want to activate one of the payment methods they are providing. 

I have tested a few calendar-booking solutions and some of them enable users to control by their own (via their Stripe account) the payment methods, some of them block this and pretend to do it in their behalf (what imo limits the usage). I am sure this is only a matter of configuration because once some payment method is activated Stripe checkout handles that perfectly.

@zomars Can we get back to this? Would be happy to work more on that. The thing that blocked us here was a failing preview branch.

**Comment by rushilsrivastava** [comment]
@PeerRich / @zomars

Same as @jepek mentioned above, we use Cal.com but are now considering switching over to other competitors because this feature is blocking us. Is this on the roadmap to fix?

**Comment by davidparys** [comment]
Hey, do we have any update on that? I'd like to integrate Polish payments (BLIK etc) but we're getting blocked by this.

**Comment by PeerRich** [comment]
we are looking into this again!

**Pull request closed without merging**
