### PR TITLE
fix: Org context added inside URL

### LINKED ISSUE #10690: [CAL-2334] Orgs: url in event type settings for individual doesn't reflect the org context
Currently

Should be

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2334](https://linear.app/calcom/issue/CAL-2334/orgs-url-in-event-type-settings-for-individual-doesnt-reflect-the-org)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #10690

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
This doesn't solve the issue.

with your change i see acme.localhost:3000 instead of acme.cal.local:3000 in /profile

Screenshot 2023-08-14 at 11 37 25 PM

Screenshot 2023-08-14 at 11 38 29 PM

**Comment by anikdhabal** [comment]
> This doesn't solve the issue.
> 
> with your change i see acme.localhost:3000 instead of acme.cal.local:3000 in /profile
> 
> Screenshot 2023-08-14 at 11 37 25 PM Screenshot 2023-08-14 at 11 38 29 PM

Ok understood where to change. Thank you

**Comment by anikdhabal** [comment]
> This doesn't solve the issue.
> 
> with your change i see acme.localhost:3000 instead of acme.cal.local:3000 in /profile
> 
> Screenshot 2023-08-14 at 11 37 25 PM Screenshot 2023-08-14 at 11 38 29 PM

Fixed.

**Comment by anikdhabal** [comment]
@Udit-takkar this issue is assigns to a team member. So what can I do? Should I attach another issue here instead of closing this?

**Comment by Udit-takkar** [comment]
thanks for he contribution but https://github.com/calcom/cal.com/pull/10790 already fixes this issue

**Pull request closed without merging**
