### PR TITLE
fix: Redirect URL with query params

### LINKED ISSUE #13899: [CAL-3429] Redirect URL issue
The redirect URL that can be customized for event booking is an excellent feature.

However, if the specified redirect URL has query parameters in it, then the relevant code adds more query parameters with an additional `?`. This leads to malformation of the last query parameter in the already specified URL

Relevant code:

https://github.com/calcom/cal.com/blob/86c379817e43791278a9e14f5ea1d9f2ca2bd259/packages/lib/bookingSuccessRedirect.ts#L66C1-L66C87

Should be an easy PR to fix if this is agreed as a fix.

<sub>[CAL-3429](https://linear.app/calcom/issue/CAL-3429/redirect-url-issue)</sub>

### PR DESCRIPTION
**Pull request by vikas-verma**
Fixes #13899 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
@vikas-verma I tried adding a url with query param and i got redirected to invalid url with two query params and params should be encoded

**Comment by vikas-verma** [comment]
> @vikas-verma I tried adding a url with query param and i got redirected to invalid url with two query params and params should be encoded

@Udit-takkar  can you share the exact URL you tried, that will help.

**Comment by Udit-takkar** [comment]
@vikas-verma take any test url https://www.google.com/search?q=tst 
I was redirected to this

Screenshot 2024-03-05 at 1 49 26 AM

**Comment by vikas-verma** [comment]
@Udit-takkar  pls verify

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
It's still not generating a valid url 
Screenshot 2024-03-12 at 5 58 29 PM

**Review by Udit-takkar — DISMISSED** [review]
LGTM. I have fixed it now

**Review by keithwillcode — DISMISSED** [review]
Type checks and E2E test are failing

**Review by anikdhabal — APPROVED** [review]
LGTM, I've updated the code

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Comment by PeerRich** [comment]
E2E failing

**Pull request merged**
