### PR TITLE
feat: add confirmed booking webhook event

### PR DESCRIPTION
**Pull request by ikadix**
## What does this PR do?

This adds a webhook trigger for an opt-in booking getting confirmed.
I'm not 100% sure if this is the correct way to add it, I kind of just figured it out by reading the others. Any changes, please let me know :pray: 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

1. Set up a webhook test endpoint
2. set a webhook integration with it's URL
3. select the booking confirmed option
4. save it.
5. create an event that is opt-in and book it
6. then confirm it 
7. you should get a payload sent to the test endpoint.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
@alishaz-polymath you implemented webhooks, can you give this a review and test manually?

**Review by alishaz-polymath — APPROVED** [review]
Works well. LGTM

**Review by zomars — CHANGES_REQUESTED** [review]
I'm currently testing this PR and found some details that IMO need to be addressed before merging. I was trying to expand web hook testing so we can have a test for each event and found out some quirks.

- Normal bookings trigger the `BOOKING_CREATED` event.
- Opt in bookings trigger the `BOOKING_CREATED` and after confirming the `BOOKING_CONFIRMED` event.

Should normal bookings trigger the `BOOKING_CONFIRMED` event as well? Since they're "auto-confirmed"

**Comment by zomars** [comment]
@ikadix I've added a [PR to your PR](https://github.com/ikadix/calendso/pull/1) (IKR) that adds tests for this new feature. Please take a look and once it's merged there we will merge here. 👍🏽

**Comment by alishaz-polymath** [comment]
> I'm currently testing this PR and found some details that IMO need to be addressed before merging. I was trying to expand web hook testing so we can have a test for each event and found out some quirks.
> 
>     * Normal bookings trigger the `BOOKING_CREATED` event.
> 
>     * Opt in bookings trigger the `BOOKING_CREATED` and after confirming the `BOOKING_CONFIRMED` event.
> 
> 
> Should normal bookings trigger the `BOOKING_CONFIRMED` event as well? Since they're "auto-confirmed"

We could do that, but it would be an exact duplicate of `BOOKING_CREATED` and at the same time.

**Comment by ikadix** [comment]
@zomars 
I have merged your PR, all looks good to me, apologies this wasn't tested initially, I just started reading up and learning playwright in the last few days :pray: 

 @alishaz-polymath 
Agreed that a `BOOKING_CONFIRMED` webhook should only be triggered if the event was an opt-in booking and confirmed later, not at booking time. 

I think this would mean some call to prisma to get check if the event type is opt-in ?
I have no real experience with prisma, but if that is the route to go down to do this check then I can read up on it and give it a go

**Comment by zomars** [comment]
I think this will cause confusion, let's define this:

- `BOOKING_CREATED` A new booking is created (but it is unknown if it's confirmed)
- `BOOKING_CONFIRMED` A booking was confirmed (this will be true for opt-ins but for normal bookings we won't know)

**Comment by zomars** [comment]
IMO we should rename `BOOKING_CREATED` to `BOOKING_CONFIRMED` and use this new structure.
- Normal bookings trigger `BOOKING_CONFIRMED` (skipping the created event)
- Opt-in bookings trigger `BOOKING_CREATED` and then `BOOKING_CONFIRMED` once confirmed.

Thoughts @PeerRich ?

**Review by zomars — APPROVED** [review]
I'll take it from here @ikadix Thank you for your contribution 🙏🏽

**Pull request merged**
