### PR TITLE
i18n - Translate booking status when empty screen

### PR DESCRIPTION
**Pull request by arb0z**
Translate booking status parameter for EmptyScreen's messages to be fully i18n

### CODE REVIEW

**Comment by PeerRich** [comment]
does translations for "status" exist already?

**Comment by PeerRich** [comment]
this PR misses a "status" key in /en/common.json

this would break if merged

**Comment by arb0z** [comment]
All "status" values are translated (past, cancelled, upcoming).
I've added "status" key for EN & FR

**Review by PeerRich — APPROVED** [review]
thank you for adding this translation!

**Comment by PeerRich** [comment]
thank you @arb0z – merged 🙏

**Pull request merged**
