### PR TITLE
fix: phone-number-input

### LINKED ISSUE #12162: [CAL-2664] Phone Number Input
The Phone number type input only supports international phone numbers so local numbers like 415-999-9999 would become "+415 999 9999". 

- Add information icon next to label with text "Please enter number in international format"

- Cache country code for some time

https://github.com/calcom/cal.com/assets/53316345/6caff0f5-1f6b-4980-adb3-f01e1de653d0

<sub>[CAL-2664](https://linear.app/calcom/issue/CAL-2664/phone-number-input)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

a) of #12162 

Screenshot (1)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
I don't see info badge here

Screenshot 2023-11-08 at 8 42 18 PM

Steps to reproduce 

1) Go to event type advanced settings
2) Add a Booking questions of type phone


Also when there is only one location ( Attendee Phone Numeber)

Screenshot 2023-11-08 at 8 44 56 PM

**Comment by Amit91848** [comment]
Made recommended changes @Udit-takkar

Single Location 
Screenshot (2)

Booking Questions
Screenshot (3)

Multiple Locations
Screenshot (4)

**Comment by Udit-takkar** [comment]
@Amit91848 e2e tests are failing

**Comment by Amit91848** [comment]
I have no idea how to fix it. Can you guide me @Udit-takkar ?

**Review by Udit-takkar — DISMISSED** [review]
LGTM. @Amit91848 I have all tests now

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Pull request merged**
