### PR TITLE
chore: Remove deprecated logo/avatar/away fields

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

* Drops away, avatar fields from `users`
* Drops logo field from `Team`

### CODE REVIEW

**Review by CarinaWolli — DISMISSED** [review]

**Review by zomars — DISMISSED** [review]
Ship it

**Comment by CarinaWolli** [comment]
Why do all e2e tests fail here? I already tried re-running them 🤔

**Comment by keithwillcode** [comment]
@emrysal Looks like e2e 6/7 are failing consistently. Might need to look into it a bit more

**Review by keithwillcode — CHANGES_REQUESTED** [review]
Requesting changes for this reason: https://github.com/calcom/cal.com/pull/14705#issuecomment-2096994345

**Review by keithwillcode — DISMISSED** [review]
@emrysal Do we need to make 2 separate PRs here?
1) Remove the fields from the schema
2) Drop the columns

Will dropping the columns before the deployment hits production start throwing errors if queries are still using the schema will these 3 fields?

**Comment by PeerRich** [comment]
what do we do here @emrysal @keithwillcode

**Comment by emrysal** [comment]
> @emrysal Do we need to make 2 separate PRs here?
> 
> 1. Remove the fields from the schema
> 2. Drop the columns
> 
> Will dropping the columns before the deployment hits production start throwing errors if queries are still using the schema will these 3 fields?

So I don't think this is needed if there are no usages, but if there are there must be two PRs - unfortunately since the PR removing all logo/avatar uses this has sneaked back in. I've reverted this in this PR however this does mean two PRs are required after all. 

No problem, I'll remove the migration files, then do another PR.

**Review by zomars — APPROVED** [review]

**Comment by Udit-takkar** [comment]
@emrysal there is a missing migration in the main branch after this was merged

**Pull request merged**
