### PR TITLE
use new v2 Dropdown in booking page

### LINKED ISSUE #4508: use new v2 Dropdown in booking page
CleanShot 2022-09-15 at 22 14 33@2x

### PR DESCRIPTION
**Pull request by gitstart**
## What does this PR do?

Fixes #4508

## Demo
https://www.loom.com/share/3883a9c491d74e4b8ea6d4a049409a26

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
this doesnt solve the issue. we want to use the `<Dialog>` component from v2

**Comment by gitstart** [comment]
> this doesnt solve the issue. we want to use the `<Dialog>` component from v2

Thank you for the review @PeerRich, will get back to you with the required changes asap

**Comment by gitstart** [comment]
> this doesnt solve the issue. we want to use the `<Dialog>` component from v2

Hey @PeerRich can you please give more clarification on this? Do we want to replace `Collapsible` with `Dialog`?

**Comment by PeerRich** [comment]
> > this doesnt solve the issue. we want to use the `<Dialog>` component from v2
> 
> 
> 
> Hey @PeerRich can you please give more clarification on this? Do we want to replace `Collapsible` with `Dialog`?

correct

**Pull request closed without merging**
