### PR TITLE
Dark theme support required for button component

### LINKED ISSUE #4544: [CAL-116] Dark theme support required for button component
https://www.loom.com/share/a7545b343c8043268dfe270040fb0628

### PR DESCRIPTION
**Pull request by gitstart**
## What does this PR do?

Fixes #4544

## Demo
https://www.loom.com/share/5ed040dede4343dba5a1e9935334794e

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by sean-brydon** [comment]
This only seems to be adding the dark mode support for this button component

We can use dark: within the component to change the theme. 

Public pages are now using the `class` mode in tailwind so we can freely add support for dark mode components. As they only get dark mode activated when the next-theme class is present

**Review by sean-brydon — CHANGES_REQUESTED** [review]
See comment above

**Comment by gitstart** [comment]
Thank you @sean-brydon for the review, will make the required changes and get back to you.

**Comment by PeerRich** [comment]
> This only seems to be adding the dark mode support for this button component
> 
> We can use dark: within the component to change the theme.
> 
> Public pages are now using the `class` mode in tailwind so we can freely add support for dark mode components. As they only get dark mode activated when the next-theme class is present

does that mean we can close this PR @sean-brydon ?

**Comment by sean-brydon** [comment]
> > This only seems to be adding the dark mode support for this button component
> > We can use dark: within the component to change the theme.
> > Public pages are now using the `class` mode in tailwind so we can freely add support for dark mode components. As they only get dark mode activated when the next-theme class is present
> 
> does that mean we can close this PR @sean-brydon ?

We still need dark mode support in the button component - but I will be picking this up in the dark mode work I am doing. If the OP wants to create a dark mode component I'm more than happy for that to go ahead

**Comment by sean-brydon** [comment]
Closing due to inactivity.

**Pull request closed without merging**
