### PR TITLE
fix: Adjust height of sidebar to fit on screen when top banner is visible

### LINKED ISSUE #8783: [CAL-1641] Top banner creates an issue where all of the sidebar is not visible
The sidebar should take up the remaining space, not have a scroll.

Currently:

[2b0af20d-6ff2-46d2-b04c-6e5a5bdcc13f](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f7bad905-fc3a-4e98-b816-c32713c85bc2/2b0af20d-6ff2-46d2-b04c-6e5a5bdcc13f)

Should be:

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1641](https://linear.app/calcom/issue/CAL-1641/top-banner-creates-an-issue-where-all-of-the-sidebar-is-not-visible)</sub>

### PR DESCRIPTION
**Pull request by paridhi7**
Adjusts the height of the sidebar to fit on screen and not be scrollable when top banner is visible. 

Fixes #8783 

https://www.loom.com/share/dcaee4eae95f42ae941e2ef2bfefd4e3

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Go to the event-types page and observe the sidebar when a banner is visible on the top.

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
@paridhi7 there is empty space in the bottom of sidebar after i scroll 

https://github.com/calcom/cal.com/assets/53316345/c7531e09-f41c-42c8-b941-05e09aac58e9

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
There is gap at the bottom left

Screenshot 2023-05-12 at 2 31 13 PM

**Comment by Udit-takkar** [comment]
@paridhi7 you might wanna have a look here  https://github.com/calcom/cal.com/pull/6098/files#r1052035715 (maybe adding a div with position fixed in sidebar component outside of userdropdown )  and https://github.com/calcom/cal.com/pull/6228/files#diff-682568b9bcea96dd5dfd183b5b3303e27c13ac922731e9d2a26d65b8e59d342d.  

Make sure to test it properly. also with Tips Component active like you can see in my image

**Review by zomars — COMMENTED** [review]
Thank you for your contribution 🙏 I'm delegating my approval to @Udit-takkar

**Comment by paridhi7** [comment]
Hi @Udit-takkar, can you please take a look now? I have made the top banner fixed as @Jaibles mentioned on the Loom that I attached with the PR. 
Screenshot 2023-05-23 at 10 02 49 PM

The events page looks like this now:
https://www.loom.com/share/9eb5d61801ec44afba1040bc8829c5f7

**Review by Udit-takkar — APPROVED** [review]
https://github.com/calcom/cal.com/assets/53316345/40a9a37f-c192-4dce-9b85-bbb29ec4643a

LGTM. Pushed some changes

**Pull request merged**
