### PR TITLE
feat: lever.co app

### LINKED ISSUE #3717: App: Lever.co
similar to Greenhouse

### PR DESCRIPTION
**Pull request by RajatYadav01**
## What does this PR do?

- Fixes #3717
- Fixes CAL-3414
- /claim #3717

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Need help from the Cal team to become a [Lever partner](https://hire.lever.co/developer/partner) for getting access to Lever OAuth sandbox account credentials to test this app and complete the integration after incorporating the required changes in the code.

### CODE REVIEW

**Review by Praashh — CHANGES_REQUESTED** [review]
type checks are failing, can you please fix it ?

**Comment by RajatYadav01** [comment]
Hey there @Praashh, sure I'll fix it asap.

**Comment by RajatYadav01** [comment]
Hey @Praashh, can you review the changes that I have pushed?

**Comment by RajatYadav01** [comment]
@Praashh, can you provide me with Lever OAuth sandbox account credentials by registering Cal as a [Lever partner](https://hire.lever.co/developer/partner)? 
Because without access to those credentials, the app can't be tested and hence app integration can't be completed.

**Comment by anikdhabal** [comment]
@RajatYadav01 Thanks for your work on this PR. But unfortunately, if a PR is not tested and not completed by the author, we can't accept it.

**Pull request closed without merging**
