### PR TITLE
fix: css for location

### LINKED ISSUE #3741: Locations has the wrong display on AvailabilityPage
### Issue Summary

The css for eventType.locations on the AvailabilityPage page is different from the others.

### Steps to Reproduce

Try to book a meeting that has a location and see that it is different from the others

Captura de tela de 2022-08-08 09-18-36

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes #3741 

Screenshot 2022-08-08 at 9 10 06 PM

- made css consistent for location text
- aligned center icon and  locations(if multiple locations are present)

### CODE REVIEW

**Comment by leog** [comment]
Thanks a lot for your contribution @Udit-takkar.

Please take a look at the icon position when there are more than one line of text. 

For recurring it looks like this: 
image

**Review by leog — DISMISSED** [review]
Thanks a lot for your contribution @Udit-takkar.

Please take a look at the icon position when there are more than one line of text.

For recurring it looks like this:
<kbd></kbd>

**Comment by Udit-takkar** [comment]
Screenshot 2022-08-09 at 3 03 17 AM

**Review by zomars — APPROVED** [review]
LGTM. Thank you for your contribution 🙏

**Comment by Udit-takkar** [comment]
resolved merge conflict

**Comment by Udit-takkar** [comment]
@zomars i though you would have to add auto-merge tag

**Pull request merged**
