### PR TITLE
fix: spelling errors

### PR DESCRIPTION
**Pull request by sydwardrae**
fixed spelling errors, added consistency for canceled -> cancelled

### CODE REVIEW

**Comment by CarinaWolli** [comment]
@sydwardrae  I thought we use American English and therefore going with canceled (one l)? 🤔

**Comment by sydwardrae** [comment]
> @sydwardrae I thought we use American English and therefore going with canceled (one l)? 🤔

yes yes I'm so sorry - haha fixing @CarinaWolli

**Review by Udit-takkar — DISMISSED** [review]

**Comment by Udit-takkar** [comment]
> yes yes I'm so sorry - haha fixing @CarinaWolli

@sydwardrae are we going ahead with "cancelled" or should i close this PR?

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
As already mentioned should be 'canceled' not 'cancelled'

**Review by CarinaWolli — APPROVED** [review]

**Pull request merged**
