### PR TITLE
Fix form inputs height to 36px

### LINKED ISSUE #8511: [CAL-1593] Component: Segments are rendering at the wrong height
All segments are rendering at 46px high. They should be 36px high, the same as inputs.

Designs: left ; Live: right

[Double check all tokens from Figma while updating also.](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=15212%3A117411&t=p5OTxjr1wkCAybAQ-1)

* radius
* borders
* text color
* bg for active, hover 
* etc.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1593](https://linear.app/calcom/issue/CAL-1593/component-segments-are-rendering-at-the-wrong-height)</sub>

### PR DESCRIPTION
**Pull request by ExplorerAadi**
## What does this PR do?

It makes the height consistent i.e. 36px for form inputs and I have also attached a loom video to show to verify.
It also fixes a small bug where the select bg when disabled is creating issue in dark mode. Check the input type field of the booking question form in the screenshot I attached and then check that field in the loom video. I simply added the same class for disabled select input that was being used for text input.

Fixes #8511 and #8512 

Loom Video: https://www.loom.com/share/7b5de63965dd4568919c4bf3eb467962

Screenshot of the other issue:

cal-input-bg-issue

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Go to any event and then the advanced menu and open the form to edit a booking question then inspect the fields.
- Go to event setup menu and then try to inspect the location field before selecting a value and then after.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Udit-takkar — APPROVED** [review]
Thanks for your contribution. 

1) h-9 is already available so you don't have to add this in tailwind-preset
2) input addon is also 36px ( https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?type=design&node-id=346-26218&t=cOOwyx9vm6oHjV7f-0) 

i have fixed these issue in this PR

**Comment by ExplorerAadi** [comment]
@Udit-takkar Hey buddy, Did you test after removing those values?
`h-9` is still being used in multiple files in my PR and `min-h-8.5` was to adjust heights of input addOns because after adding their 1px border width, their overall container height would be 36px and match the inputs.

I have also added a loom with all the changes working properly.

**Comment by ExplorerAadi** [comment]
@Udit-takkar I have updated the PR with my earlier fix for input addOns.
Thanks a lot for the review and catching a redundant custom tailwind class.

**Comment by Udit-takkar** [comment]
@ExplorerAadi you are right maybe we should use h-9 instead of min-h-8.5 in the AddOn component. 

Screenshot 2023-04-27 at 4 45 18 PM

**Comment by ExplorerAadi** [comment]
@Udit-takkar Yes, that works too and we won't need a custom class. I have updated with the changes, thanks a lot for you input.

**Review by sean-brydon — APPROVED** [review]
Looks good from UI side :) Thank you 

CC: @Jaibles finally fixed :P

**Pull request merged**
