### PR TITLE
[CAL-115] /onboarding /connected-calendar - Toggle the first calendar on

### LINKED ISSUE #4384: [CAL-115] /onboarding /connected-calendar - Toggle the first calendar on
- [ ] toggle the first calendar on by default

CleanShot 2022-09-12 at 11 12 25@2x

### PR DESCRIPTION
**Pull request by gitstart**
## What does this PR do?

Fixes

## Demo
https://www.loom.com/share/3b3d2638a5dc4e29ae3ae53fca0096a3

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by alannnc — CHANGES_REQUESTED** [review]
I believe this solution only fixes the problem on the UI, when what it should be done it's :

1. when first installing any calendar app
2. see if calendars exist in that credential
3. add first element returned to destinationCalendar

**Comment by gitstart** [comment]
Thank you for the review @alannnc, will make the required changes and get back to you

**Comment by gitstart** [comment]
Sorry this is taking too long, will push a fix later today

**Comment by gitstart** [comment]
closing this for now, will reopen the PR when we find a better solution

**Pull request closed without merging**
