### PR TITLE
fix: Impersonate on users page

### LINKED ISSUE #13240: [CAL-2975] Allow impersonation from the /settings/admin/users page.
### Is your proposal related to a problem?

We have a clear list of users, and then a seperate impersonation page, where we type in the user?

CleanShot 2024-01-17 at 13 09 23@2x

Why are these not just tied together? and/or better yet, inside the dropdown for the edit/lock/etc.

### Describe the solution you'd like

Add impersonation to the dropdown on the users row of /settings/admin/users
(Describe your proposed solution here.)

### Describe alternatives you've considered

Could just put the impersonation on this page?

---

##### House rules

* If this issue has a `🚨 needs approval` label, don't start coding yet. Wait until a core member approves feature request by removing this label, then you can start coding.
  * For clarity: Non-core member issues automatically get the `🚨 needs approval` label.
  * Your feature ideas are invaluable to us! However, they undergo review to ensure alignment with the product's direction.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2975](https://linear.app/calcom/issue/CAL-2975/allow-impersonation-from-the-settingsadminusers-page)</sub>

### PR DESCRIPTION
**Pull request by Utkarshn10**
## What does this PR do?

Added an option as `Impersonate User` to admin/settings/user. 

Fixes https://github.com/calcom/cal.com/issues/13240
/claim #13240 

image

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

- What is expected (happy path) to have (input and output)?

An option as `Impersonate User` is added to admin/settings/user. You can go to the url and click on the three dots on the right of the user information to view options. Click on "Impersonate User" to use the option.

## Mandatory Tasks

- [X ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by joeauyeung — APPROVED** [review]
Thanks for your contribution @Utkarshn10! 

Tested and working as expected. I'm a little on the fence of immediately redirecting to the event types page but that's a small nit.

**Comment by anikdhabal** [comment]
Hey @joeauyeung I already made this PR https://github.com/calcom/cal.com/pull/13281

**Comment by Utkarshn10** [comment]
> Thanks for your contribution @Utkarshn10! 
> 
> Tested and working as expected. I'm a little on the fence of immediately redirecting to the event types page but that's a small nit.

Hey Thanks. I added the redirect because after login the users are directed to event types page.

**Comment by Utkarshn10** [comment]
> Hey @joeauyeung I already made this PR https://github.com/calcom/cal.com/pull/13281

Hey @anikdhabal I made this PR since the issue was assigned. Since #13281 is merged hence closing this one.

**Pull request closed without merging**
