### PR TITLE
refactor: remove @calcom/features dependency to @calcom/web

### PR DESCRIPTION
**Pull request by ThyMinimalDev**
## What does this PR do?

Refactor @calcom/features, in order for it to not depend on @calcom/web anymore

## Type of change

- Chore (refactoring code, technical debt, workflow improvements)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by keithwillcode — DISMISSED** [review]
Very nice.

**Comment by keithwillcode** [comment]
@ThyMinimalDev Type checks are failing

**Comment by keithwillcode** [comment]
Screenshot 2024-01-23 at 10 29 05 AM
@ThyMinimalDev AI build is failing

**Review by zomars — DISMISSED** [review]
You beat me to it. Nice job 🙏🏽

**Comment by ThyMinimalDev** [comment]
checking how to fix the build of ai and then we can merge

**Comment by zomars** [comment]
Just noticed the error. It seems like inside apps/web there's an extension of global window. We would need to move that as well.

**Comment by ThyMinimalDev** [comment]
> Just noticed the error. It seems like inside apps/web there's an extension of global window. We would need to move that as well.

tsconfig.json of lib was not include the window.d.ts from types packages, its done now

**Comment by ThyMinimalDev** [comment]
all good ready for merge

**Review by keithwillcode — APPROVED** [review]

**Pull request merged**
