### PR TITLE
overflow scroll to mobile settings

### PR DESCRIPTION
**Pull request by PeerRich**
not the best UX but a good hotfix for now

maybe moving "teams" into main menu gives us more space

before:  

https://user-images.githubusercontent.com/8019099/172573227-c0814d79-fae5-4e8b-9635-87d9c289c962.MOV

### CODE REVIEW

**Review by joeauyeung — APPROVED** [review]
Good fix for now

**Comment by zomars** [comment]
this is adding a nasty horizontal scrollbar for mouse users @PeerRich 

image

**Comment by PeerRich** [comment]
> this is adding a nasty horizontal scrollbar for mouse users @PeerRich 
> 
> 
> 
> image
> 
> 

oh right... will come up with an alternative

**Comment by joeauyeung** [comment]
Could we use tailwind breakpoints? `overflow-x-auto md:overflow-x-hidden`

**Comment by zomars** [comment]
Could work yeah @joeauyeung

**Pull request merged**
