### PR TITLE
feat: add each app from the app store to KBar

### LINKED ISSUE #5712: [CAL-460] add each app from the app store to KBar
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-460](https://linear.app/calcom/issue/CAL-460/add-each-app-from-the-app-store-to-kbar)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #5712

https://www.loom.com/share/fcfcf09b878e4414b5538ae0ebb2670f

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by PeerRich** [comment]
great work! will test asap!

**Comment by PeerRich** [comment]
@alishaz-polymath can review this tomorrow when he is back from OOO

**Review by alishaz-polymath — APPROVED** [review]
Looks and works great @G3root 
Much appreciated. Thanks for your contribution 🙂

**Review by pumfleet — APPROVED** [review]
Thank you!

**Pull request merged**
