### PR TITLE
feat(app-store): Add Giphy app

### LINKED ISSUE #2473: Giphy App
select a gif in event types that'll be shown on the success page

### PR DESCRIPTION
**Pull request by with-shrey**
## What does this PR do?

Add a Giphy app that allows users to search and select gif for each event type

Fixes #2473 

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## How should this be tested?

- Install the Giphy app from App Store 
- Create a new event or use any existing event type 
- Click on "Show advanced settings" & scroll to the bottom 
- Press search on the Giphy button which should open a popup 
- On the popup type something in the search box and press search 
- You can use the next & prev icons to see more gifs
- After selecting one press `Save`
- the selected Gif should be visible on the event edit page 
- Press the update button on the page 
- Preview this event and schedule a time, the gif should be visible on the success page 

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

## Screenshots
Screenshot 2022-04-23 at 8 41 17 PM
Screenshot 2022-04-23 at 8 47 41 PM
Screenshot 2022-04-23 at 8 41 38 PM
Screenshot 2022-04-23 at 9 32 44 PM

### CODE REVIEW

**Comment by sean-brydon** [comment]
Hey @with-shrey  code is looking pretty solid - however, the build is failing on our end 
CleanShot 2022-04-23 at 22 53 14@2x

There is also a slight issue on the layout of the button and search bar 
CleanShot 2022-04-23 at 22 51 39@2x


Thanks again - We all love GIFs :D

**Comment by with-shrey** [comment]
@sean-brydon I swear that was working on my machine 🤣 
could be because i renamed that file and git wasn't happy about that 

Have made the requested changes

**Comment by PeerRich** [comment]
added giphy credentials to vercel preview

**Comment by sean-brydon** [comment]
All works well on my end :) A few nit picks about the Layout 

This isn't centred like the rest of the options on the event types page
CleanShot 2022-04-24 at 12 37 45@2x

I also can't seem to see the next button however, it is there and I can click it 🤔 
CleanShot 2022-04-24 at 12 38 24@2x

**Comment by with-shrey** [comment]
@sean-brydon Is it possible that the styles didn't load up properly ?

The search button was black , in the screenshot it looks green
The icons are from the lib that is being used in the app at several places

Will take a look at the styling fix

**Comment by sean-brydon** [comment]
@with-shrey  The button colour is driven off the users theme that is logged in - in my case it was green.

I was having a talk with @PeerRich before and we discussed using the official [giphy react components](https://www.npmjs.com/package/@giphy/react-components) Is this something you'd be up for trying to implement here?

**Comment by PeerRich** [comment]
yeah we could use the SearchComponent:

image
https://giphy.github.io/giphy-js/?path=/story/react-components-search-experience--search-experience

**Comment by PeerRich** [comment]
but dont worry if it's too much, we can use our own UI too

**Comment by with-shrey** [comment]
Yeah @PeerRich @sean-brydon 
I will check that out .

Should not be a huge change

**Comment by with-shrey** [comment]
The search popup component would be replaced with the giphy component and the rest remains same. Is that correct ?

**Comment by with-shrey** [comment]
@PeerRich @sean-brydon 

I tried out the Search Component and
The Grid Component in Giphy SDK isn't responsive, they have a required width prop which is always in pixels 😞 

Not sure how should we proceed here ?

I can change the search component that we have implemented to display a grid of images instead of a single image

**Comment by PeerRich** [comment]
> @PeerRich @sean-brydon
> 
> I tried out the Search Component and The Grid Component in Giphy SDK isn't responsive, they have a required width prop which is always in pixels 😞
> 
> Not sure how should we proceed here ?
> 
> I can change the search component that we have implemented to display a grid of images instead of a single image

ok in that case dont proceed with the giphy components

**Comment by with-shrey** [comment]
Let me know if something needs to be changed in this 😃.

Thanks for all the help guys

**Comment by agustif** [comment]
Hey what about using window.width - (X)px to pass as props?

Looking good either way! Great job ;)

**Comment by with-shrey** [comment]
@agustif 

I am currently showing the search component within the Dialog component from the App's @calcom/ui
which has variable widths for mobile and desktop ranging between full-width to 35rem for desktops.

If you wanna take a look, i can push the changes to a different branch?

**Comment by agustif** [comment]
> @agustif
> 
> I am currently showing the search component within the Dialog component from the App's @calcom/ui which has variable widths for mobile and desktop ranging between 360px to full-width for mobile devices.
> 
> If you wanna take a look, i can push the changes to a different branch?

Hey @with-shrey I don't think it's needed. We can merge it as is as it's already looking good and leave future polishing/improvments for separate PR's

Thank you very much for you contribution.

**Review by emrysal — APPROVED** [review]
Happy with this; as soon as our preview branches are fixed we can merge :)

**Review by agustif — APPROVED** [review]
Code wise everything looks good to me.

I do have some UI/UX nitpicks that are not that important but would make a great improvement maybe in a second PR for polish after landing the app first MVP!

- When clicking search, both it and the save modal button go into a loading state, which is weird.
- When searching for an empty string/query, it returns always obviously no results, we could maybe disable search button if it's empty, just to avoid it.
- When changing between gif's in the carousel, the difference between the height of the gif and the loading state, makes the modal change in height which it's a little wonky, we could fix it by giving the modal a min-height or by using a wrapper around the loading state or moving the loading to skeleton or whatever you think it's best!

Great work on landing your first app! Thanks for the contribution @with-shrey

**Comment by with-shrey** [comment]
@agustif Sure Thing !
Will open a new PR for thoose fixes

**Comment by Jaibles** [comment]
@with-shrey I've reviewed this for some UI/UX issues and proposed some changes. Would you be able to work on these?
https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6293%3A99883

**Comment by with-shrey** [comment]
Thanks , will work on this over the weekend

Thanks
Shrey

**Comment by Jaibles** [comment]
Great! Any questions let me know. Thanks @with-shrey 🙏

**Comment by with-shrey** [comment]
@Jaibles 
How would this work if i want to change the search term ?
image

**Comment by NexusEFR** [comment]
Hello everyone, it's great giphy but in the version with API for docker or self-hosted, it always gives an error even if you create the API KEY on the Giphy developers website, does anyone know why it doesn't validate the Key? Any necessary variable? Thanks for the help!
image

**Pull request merged**
