### PR TITLE
adds event types to kbar #6210

### LINKED ISSUE #6196: [CAL-654] KBar: add all event-types to search
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-654](https://linear.app/calcom/issue/CAL-654/kbar-add-all-event-types-to-search)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
reopening https://github.com/calcom/cal.com/pull/6210 due to branch protection 

original PR by @phishy

### CODE REVIEW

**Comment by phishy** [comment]
What do you mean due to branch protection? I'm sure whatever it is, I can fix it. I prefer you didn't commit my changes under your name.

**Comment by zomars** [comment]
Closed in favor of the original PR

**Comment by PeerRich** [comment]
> What do you mean due to branch protection? I'm sure whatever it is, I can fix it. I prefer you didn't commit my changes under your name.

whops made a mistake, I thought the branch was protected. 

thank you @zomars for closing and reopening the OG commit

**Comment by zomars** [comment]
@phishy I think Peer refers to [check the "Allow edits from maintainers" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) while creating you PR. As described in [our CONTRIBUTING guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md#making-a-pull-request).

That way we can keep the PR updated without bothering for you.

**Pull request closed without merging**
