### PR TITLE
chore: [app-router-migration] - adds the missing routes of /settings/admin to future

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

added /settings/admin/lockedSMS to future routes
added /settings/admin/orgMigration to future routes

- Fixes #XXXX (GitHub issue number)
- Fixes CAL-4022 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] --(n/a)-- I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- set APP_ROUTER_SETTINGS_ADMIN_ENABLED=1
- go to /settings/admin/lockedSMS
- go to /settings/admin/orgMigration/moveTeamToOrg
- go to /settings/admin/orgMigration/moveUserToOrg
- go to /settings/admin/orgMigration/removeTeamFromOrg
- go to /settings/admin/orgMigration/removeUserFromOrg

### CODE REVIEW

**Review by zomars — CHANGES_REQUESTED** [review]
We're getting some production builds issues @SomayChauhan

**Review by joeauyeung — COMMENTED** [review]
@zomars can you take another look at this? I've made the following changes.

- Removed instances of orgMigration routes from app router (based off of @hariombalhara's comment on campsite)
- In the edit user route, I've fetched data server side 050f4a96441f00d75c88d4147b83fee3f767bf25
- In the edit organization route, I've fetched data server side b4488d6a1f81d1b3e03cf498bc90ab977a266d9c

I want to follow this up by removing instances of `MetaContext` and generating the data server side.

**Comment by hbjORbj** [comment]
@SomayChauhan Hey Sonmay, I resolved conflicts and pushed a few improvement commits. It seems that you haven't added  pages under `/orgMigrations` to App router. Can you?

**Review by hbjORbj — CHANGES_REQUESTED** [review]
@SomayChauhan Hey Sonmay, I resolved conflicts and pushed a few improvement commits. It seems that you haven't added the pages for `/orgMigrations` group to App router. Can you?

UPDATE: according to this [thread](https://app.campsite.co/cal/posts/d2s9xnbwgw96#comment-77reyx2seojr) it seems that orgMigrations pages are not needed

**Comment by SomayChauhan** [comment]
> @SomayChauhan Hey Sonmay, I resolved conflicts and pushed a few improvement commits. It seems that you haven't added the pages for `/orgMigrations` group to App router. Can you?

will take a look 👍

**Comment by joeauyeung** [comment]
> @zomars can you take another look at this? I've made the following changes.
> 
> * Removed instances of orgMigration routes from app router (based off of @hariombalhara's comment on campsite)
> * In the edit user route, I've fetched data server side [050f4a9](https://github.com/calcom/cal.com/commit/050f4a96441f00d75c88d4147b83fee3f767bf25)
> * In the edit organization route, I've fetched data server side [b4488d6](https://github.com/calcom/cal.com/commit/b4488d6a1f81d1b3e03cf498bc90ab977a266d9c)
> 
> I want to follow this up by removing instances of `MetaContext` and generating the data server side.

Heads up @hbjORbj we don't need to include the org migration routes in the app router

**Comment by hbjORbj** [comment]
I see, I found the thread. https://app.campsite.co/cal/posts/d2s9xnbwgw96#comment-77reyx2seojr  

Thanks Joe

**Pull request closed without merging**
