### PR TITLE
availability: end time should not be lower than start time

### LINKED ISSUE #1606: availability: end time should not be lower than start time
image

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

- Adds a check to make sure the end time is not lower than start time

Fixes #1606 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [x] The availability should now only allow end time to be higher than start time

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Jenietoc — COMMENTED** [review]
Hello @alishaz-polymath , I think that the initialization of the `useState` with the `selected` variable should not be `dayjs(defaultDayRange.start).toDate().valueOf()` because it could be the case where the initial Select is greater than `09:00` and we would return to the error where the final Select is less than the initial Select. you should initialize it with the current value of the starting Select.

**Comment by alishaz-polymath** [comment]
> Hello @alishaz-polymath , I think that the initialization of the `useState` with the `selected` variable should not be `dayjs(defaultDayRange.start).toDate().valueOf()` because it could be the case where the initial Select is greater than `09:00` and we would return to the error where the final Select is less than the initial Select. you should initialize it with the current value of the starting Select.

Ah, good point. Will update this.

**Review by Jenietoc — COMMENTED** [review]
Hello @alishaz-polymath , what a good solution to the problem that I had told you yesterday. I did some testing to your implementation and I had this problem:
image

The idea for the solutions could be that when the value of the final Select is less than the value of the start Select, the value of the final Select changes to the same value of the start Select.

let me see your solution for this. good work.

**Comment by alishaz-polymath** [comment]
> Hello @alishaz-polymath , what a good solution to the problem that I had told you yesterday. I did some testing to your implementation and I had this problem: image
> 
> The idea for the solutions could be that when the value of the final Select is less than the value of the start Select, the value of the final Select changes to the same value of the start Select.
> 
> let me see your solution for this. good work.

Hi, I was unable to re-create your issue. Please take a look at the loom video attached:
https://www.loom.com/share/e01d3863b4d942888bb86f7fe341efc3

**Comment by Jenietoc** [comment]
> > Hello @alishaz-polymath , what a good solution to the problem that I had told you yesterday. I did some testing to your implementation and I had this problem: image
> > The idea for the solutions could be that when the value of the final Select is less than the value of the start Select, the value of the final Select changes to the same value of the start Select.
> > let me see your solution for this. good work.
> 
> Hi @Jenietoc , I was unable to re-create your issue. Please take a look at the loom video attached: https://www.loom.com/share/e01d3863b4d942888bb86f7fe341efc3
> 
> Can you provide me with steps to re-create the issue, or a video of it? Thanks



> > Hello @alishaz-polymath , what a good solution to the problem that I had told you yesterday. I did some testing to your implementation and I had this problem: image
> > The idea for the solutions could be that when the value of the final Select is less than the value of the start Select, the value of the final Select changes to the same value of the start Select.
> > let me see your solution for this. good work.
> 
> Hi @Jenietoc , I was unable to re-create your issue. Please take a look at the loom video attached: https://www.loom.com/share/e01d3863b4d942888bb86f7fe341efc3
> 
> Can you provide me with steps to re-create the issue, or a video of it? Thanks

Try this to simulate the issue
Grabación_área-de-selección_20220202111100

**Comment by alishaz-polymath** [comment]
> 

Good catch. Yeah, I'll get this sorted

**Comment by alishaz-polymath** [comment]
> > > Hello @alishaz-polymath , what a good solution to the problem that I had told you yesterday. I did some testing to your implementation and I had this problem: image
> > > The idea for the solutions could be that when the value of the final Select is less than the value of the start Select, the value of the final Select changes to the same value of the start Select.
> > > let me see your solution for this. good work.
> > 
> > 
> > Hi @Jenietoc , I was unable to re-create your issue. Please take a look at the loom video attached: https://www.loom.com/share/e01d3863b4d942888bb86f7fe341efc3
> > Can you provide me with steps to re-create the issue, or a video of it? Thanks
> 
> > > Hello @alishaz-polymath , what a good solution to the problem that I had told you yesterday. I did some testing to your implementation and I had this problem: image
> > > The idea for the solutions could be that when the value of the final Select is less than the value of the start Select, the value of the final Select changes to the same value of the start Select.
> > > let me see your solution for this. good work.
> > 
> > 
> > Hi @Jenietoc , I was unable to re-create your issue. Please take a look at the loom video attached: https://www.loom.com/share/e01d3863b4d942888bb86f7fe341efc3
> > Can you provide me with steps to re-create the issue, or a video of it? Thanks
> 
> Try this to simulate the issue Grabación_área-de-selección_20220202111100

Since I can't get access to the value of end-time using the react-hook-form's getValues on this page, it made more sense to just add zod validation instead to make sure that invalid data isn't passed on to update Availability API. This should now only allow valid times at submission time. Do let me know if you think there's a better alternative to this :)

**Review by PeerRich — APPROVED** [review]
great bugfix! thank you! also shoutout to @Jenietoc for the feedback

**Comment by LecrisUT** [comment]
I believe this has created an issue that the end time for the day is no longer `24:00` if the user and browser or not on UTC timezone.

**Comment by alishaz-polymath** [comment]
> I believe this has created an issue that the end time for the day is no longer `24:00` if the user and browser or not on UTC timezone.
> 
> image

Hi @LecrisUT . Thank you for mentioning this. We'll take a look and if this is unexpected/unintentional, we'll create an issue and pursue this :)

**Pull request merged**
