### PR TITLE
fix: 150min duration time for scheduling not possibe

### LINKED ISSUE #10711: 2 1/2 Hours / 150min duration time for scheduling not possibe
I'm trying to set up an scheduling option for 150 min, but I seem not to be able to do so. Only 120 and 180 min are possible or at least clickable when I let my clients choose from different duration times.

2023-08-11 10 00 35 app cal com 5bbf75861d45

Any idea / workaround / fix how to offer 2 1/2 hours appointments?

Thanks in advance and anyways I'm really happy for this amazing tool!

### PR DESCRIPTION
**Pull request by MehulZR**
## What does this PR do?

Fixes #10711  (issue)

https://github.com/calcom/cal.com/assets/86384652/d4fcc8c3-1f33-41f8-9fe5-79e31a8812d6

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Comment by Obiast** [comment]
Thanks for your fast response and action!

It works for creating an event where the clients can't choose between the duration lenght. When I check the box for them to do so unfortunately I still do not have the option for 150 min. 

Could you fix that too?

**Comment by MehulZR** [comment]
Hey Obiast, The changes are currently being tested and will be deployed to production soon.

**Comment by Obiast** [comment]
Perfect!

**Pull request merged**
