### PR TITLE
feat: Add a setting/toggle to show user profile first when a user only has 1 event type

### LINKED ISSUE #12789: [CAL-2808] Public booking page: Add a setting/toggle to show user profile first when a user only has 1 event type
**Currently**

When a user only has one event type, the link to their public project automatically redirects right into the calendar view to book that event type.

**Proposal**

Add a setting somewhere so the the user can decide whether their profile comes up first or it redirects automatically to the event type.

**Considerations**

* I think we should have this toggle on by default
* Would likely live under Settings/Appearance

Copy could do with work but could look something like

CleanShot 2023-12-14 at 08 43 20@2x

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2808](https://linear.app/calcom/issue/CAL-2808/public-booking-page-add-a-settingtoggle-to-show-user-profile-first)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

Fixes #12789

[Screencast from 14-12-23 04:11:43 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/0f1e40ec-9a2a-462d-98fa-0ed9d7461f6a)

### CODE REVIEW

**Comment by ciaranha** [comment]
@SomayChauhan thanks for taking this on! Could you upload the video again please? It doesn't seem to play for me.

**Comment by SomayChauhan** [comment]
[Screencast from 14-12-23 04:11:43 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/0a7c4b06-d690-4646-b154-41d044d448c0)
let me know if its still not working, will re-record and upload

**Review by PeerRich — CHANGES_REQUESTED** [review]
i am not sure if we should really make this optional. feels kinda polluting the db for a pretty low priority setting. talking to @ciaranha to figure out if we want to merge this or not.

sorry @SomayChauhan for the back and forth 🙏

**Comment by ciaranha** [comment]
Sorry for the confusion @SomayChauhan we're going to solve this another way.

**Pull request closed without merging**
