### PR TITLE
feat:  Organizations no middleware rewrite

### PR DESCRIPTION
**Pull request by roae**
## What does this PR do?

Use the rewrite beforeFiles config on next.config.js to rewrite the requests to an organization subdomain to the correct page. 

https://www.loom.com/share/d4502f3b93754bb694b8655bda1eea0d

## Type of change

- New feature (non-breaking change which adds functionality)

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## How should this be tested?

In order to test this org routing approach, you must run the app using a local domain e.g. http://app.cal.local:3000

- [x] Login with the Pro user, then visit `/settings/organizations/new` to create the organization, owner user, teams and send invites to org members.
- [x] Complete the owner user onboarding. 
- [x] Add the local subdomain for the organizations e.g. `acme.cal.local`.
- [x] Make sure the organization has teams.
- [x] Visit `http://[your-org-slug].cal.local/` the org profile page should be displayed.
- [x] Visit a org team page `http://[your-org-slug].cal.local/[your-team-slug]` the team profile page should be displayed
- [x] Visit a org user profile page `http://[your-org-slug].cal.local/[org-user-slug]` the user profile page should be displayed.
- [x] Try visit a non-user profile page `http://[your-org-slug].cal.local/pro` you should get 404 error.
- [x] Try visit an org user profile page using the default app domain`http://app.cal.local/[org-user-slug]` you should get 404 error.

### CODE REVIEW

**Comment by hariombalhara** [comment]
Mention here for awareness, /:path* matcher is also being used now to enable new booker. It's a temp change. 

So, when it works, let's not remove that /:path* right now.

**Review by zomars — DISMISSED** [review]
Code LGTM. Let's test in preview and staging if possible.

**Comment by zomars** [comment]
There's something breaking  e2e-embed tests. We need to investigate

**Comment by hariombalhara** [comment]
They are passing now @zomars. But I am debugging this behaviour now which sometimes happen.

**Review by ericrommel — COMMENTED** [review]
@roae, thanks for guiding me to put my local to work. I have done some more test as I said and everything looks fine.

**Review by ericrommel — DISMISSED** [review]

**Review by zomars — APPROVED** [review]
Fixed conflicts. LGTM!

**Pull request merged**
