### PR TITLE
feat: verificationTokenComponent

### LINKED ISSUE #9468: [CAL-1932] Create DIGIT input a component
Lets create a component to handle verification tokens.

Create component
Create a story in storybook or add to the existing input story

_Originally posted by @sean-brydon in https://github.com/calcom/cal.com/pull/8993#discussion_r1226617972_
            

<sub>[CAL-1932](https://linear.app/calcom/issue/CAL-1932/create-digit-input-a-component)</sub>

### PR DESCRIPTION
**Pull request by saurabbot**
## What does this PR do?
Fixes #9468

### CODE REVIEW

**Comment by PeerRich** [comment]
cc @sean-brydon

**Comment by sean-brydon** [comment]
Sorry missed this in my notifications!  Code looks create just testing it!

**Review by sean-brydon — DISMISSED** [review]
I can't push to your branch but we can improve the types here to work getter with the library we use for pin inputs.





Nice work!

**Comment by PeerRich** [comment]
> I can't push to your branch but we can improve the types here to work getter with the library we use for pin inputs.
> 
> 
> 
> Nice work!

lets address this in a follow up PR

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
