### PR TITLE
fix(readme): update setup steps

### PR DESCRIPTION
**Pull request by YassinEldeeb**
## What does this PR do?

Updates the setup step 1 to copy the `.env.example` file from the root instead.

## Type of change

Modified setup step 1 to copy the `.env.example` from the updated path.

## How should this be tested?

just a readme update.

### CODE REVIEW

**Comment by YassinEldeeb** [comment]
@zomars, Could you please give me some feedback on this feature request #2511, I'm willing to contribute to implementing it but just want a confirmation that It's a feature you wanna merge to production.

**Comment by zomars** [comment]
Thanks for taking the time for doing this. Actually this step isn't needed anymore since the yarn dev command auto updates it if missing.

**Comment by YassinEldeeb** [comment]
@zomars  Then It's better to remove this step altogether from the setup guide right?

**Comment by zomars** [comment]
Makes sense yeah

El 15 abr 2022, a la(s) 17:00, Yassin Eldeeb ***@***.***> escribió:

﻿
@zomars Then It's better to remove this step altogether from the setup guide right?

**Pull request closed without merging**
