### PR TITLE
fix: CAL-3959 Disable Duplicate button in Readonly event type

### LINKED ISSUE #15509: [CAL-3959] Remove/Disable Duplicate button in Read Only mode of an event-type
Add a user to a team with MEMBER role. He can't create any event for that team. But for an existing event he sees duplicate button which errors in the end.

image

<sub>[CAL-3959](https://linear.app/calcom/issue/CAL-3959/removedisable-duplicate-button-in-read-only-mode-of-an-event-type)</sub>

### PR DESCRIPTION
**Pull request by DiveshHariani**
## What does this PR do?

Summary of Changes: Added condition to disable the duplicate button based on the readOnly value

- Fixes #15509 
- Fixes CAL-3959

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A-I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Hey @DiveshHariani, instead of disabling the button, could you remove it?

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Nice job!

You need to add this condition at the bottom component as well for small screens. You missed it.
And pls update the e2e test.

**Comment by DiveshHariani** [comment]
Hi, I updated the code to remove the duplicate button. Can you please provide some guidelines for E2E tests? I cannot see any, for now, on Contributing.md. Do I need to create a new test or change the existing test?

**Comment by anikdhabal** [comment]
Hey Divesh thanks for the work. But this pr https://github.com/calcom/cal.com/pull/15511 is much earlier. Closing this

**Pull request closed without merging**
