### PR TITLE
Fix/force username after signup

### LINKED ISSUE #2018: Force user to choose username after signup
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I have added new user to the team and he signed up and tried to create a booking for one of the default event but it gave 404 error because of incorrect url it caused because user didn't setup the username.

image
image

### Steps to Reproduce

1. Add new user to team
2. Sign up
3. Open booking and select any event

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
Occurred on self-hosted version

Solution would be to add the username field while on-boarding or force user to add the username before doing certain actions.

### PR DESCRIPTION
**Pull request by andreaestefania12**
## What does this PR do?

Fixes #2018
When you create a new account on Cal.com and you do not have username, it going to give you one with your name and some random letters. I only can tested create accounts from Prisma Data Platform. 
image

Once the registration is complete you can change the username in settings.
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1. Add a new user to the team.
2. Sign up with the new user. (This user has to be created in DB). 
3. Once the registration is complete you can see a random username.
4. Go back to the owner team account and open view public page, booking and select any event
image

### CODE REVIEW

**Review by leog — APPROVED** [review]
LGTM, thanks for tackling this!

**Review by zomars — CHANGES_REQUESTED** [review]
_"Is this such a great idea @Jaibles?"_

**Comment by Jaibles** [comment]
@zomars what do you think might be some better ways to handle this? The potential options I can think of (though not sure they're better are
- Force the person adding the team member to choose a URL (don't like)
- Don't create a public profile for the person until they claim the account. When they do create their account make them pick a username. (Preferred if possible)

**Comment by zomars** [comment]
> @zomars what do you think might be some better ways to handle this? The potential options I can think of (though not sure they're better are
> 
> 1. Force the person adding the team member to choose a URL (don't like)
> 2. Don't create a public profile for the person until they claim the account. When they do create their account make them pick a username. (Preferred if possible)

The latter seems like the most sensible approach. Also tagging @alannnc since he's working on in-app premium username purchase, we may add-on a "regular choose a username" to that.

**Comment by PeerRich** [comment]
> @zomars what do you think might be some better ways to handle this? The potential options I can think of (though not sure they're better are
> 
> 1. Force the person adding the team member to choose a URL (don't like)
> 2. Don't create a public profile for the person until they claim the account. When they do create their account make them pick a username. (Preferred if possible)

option #2 @alannnc

**Comment by PeerRich** [comment]
thank you for your contribution but we will go with option #2 from @Jaibles in a new PR 🙏

**Pull request closed without merging**
