### PR TITLE
fix: lock on user view

### LINKED ISSUE #16021: [CAL-4508] Visual issue on Users view, settings/admin/users
### Issue Summary

On locked accounts, upon locking, the lock does not show up, and after refresh when it does show up, it looks wrong: 
image

### Steps to Reproduce

1. On settings/admin/users page as an admin, lock a users account.
2. Lock does not appear until refresh
3. Lock Icon is visually incorrect

### Expected behavior

Lock should appear once locked, and should look correct inline with the username/url

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: MacOS 
- Node: LTS
- npm: ?
```

<sub>[CAL-4508](https://linear.app/calcom/issue/CAL-4508/visual-issue-on-users-view-settingsadminusers)</sub>

### PR DESCRIPTION
**Pull request by ezhil56x**
## What does this PR do?

- Fixes #16021 (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

/claim #16021

Screenshot from 2024-10-12 17-16-50

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

### CODE REVIEW

**Review by anikdhabal — CHANGES_REQUESTED** [review]
@ezhil56x thanks for your work. As you can see, on locked accounts, upon locking, the lock does not show up and needs a refresh. Fix it

**Comment by ezhil56x** [comment]
@anikdhabal Fixed

**Comment by ezhil56x** [comment]
https://github.com/user-attachments/assets/acb7b517-989d-4668-92ad-c5c1009f1f91

**Review by anikdhabal — APPROVED** [review]
LGTM

**Pull request merged**
