### PR TITLE
Kanakpandit17/add team

### LINKED ISSUE #8731: Asterisk sign needed for the mandatory fields while creating new team
### Issue Summary

Asterisk sign needed for the mandatory fields while creating new team
### Steps to Reproduce

1. Go to cal.com
2. Go to Settings
3. Click on **ADD A TEAM** button
4. In the team creating page, the mandatory fields do not have any asterisk sign 

### Technical details
OS: MacOS Ventura 13.3.1 (a)
Browser: Chrome 113.0.5672.63 

### Attachment
Screenshot 2023-05-07 at 2 46 28 PM

### PR DESCRIPTION
**Pull request by kanakpandit17**
Added "*" after Team Name and Team URL to inform the onboarding users that the fields are required.

Fixes #8731

### CODE REVIEW

**Comment by sean-brydon** [comment]
@Jaibles we discussed about not needing these here from a design perspective right? Could we add the discussed info to the attached issue?

**Comment by Jaibles** [comment]
> @Jaibles we discussed about not needing these here from a design perspective right? Could we add the discussed info to the attached issue?

Correct @sean-brydon. We're not going to add these here. 

While in some cases it can be helpful to use an asterix, within our app the majority of our fields are in fact required. It would be better for us to take the approach of indicating which fields are optional. Not all users know what the asterix means. 

Also, in this context it's not reasonable for a user to think they can create a team without a name or URL and it's not the case where some are required and some are not and the user won't know. If they do try, the feedback will tell them.

**Comment by sean-brydon** [comment]
Closing - not planned to implement

Thanks for your contribution @kanakpandit17 take a look at our open issues to work on something we have planned :)

**Comment by kanakpandit17** [comment]
> Closing - not planned to implement
> 
> Thanks for your contribution @kanakpandit17 take a look at our open issues to work on something we have planned :)

No problem, will contribute on different issues :)

**Pull request closed without merging**
