### PR TITLE
feat: Add Hungarian support

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

- Enables Hungarian support in language selector
- Sorts locales alphabetically

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

- In account settings, select Hungarian and test for anomalies.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by keithwillcode — APPROVED** [review]

**Review by PeerRich — DISMISSED** [review]

**Review by keithwillcode — DISMISSED** [review]
@zomars there is a test for locale that's failing consistently. Don't think it's an e2e flake but rather an actual thing we need to investigate in the test

**Comment by zomars** [comment]
> @zomars there is a test for locale that's failing consistently. Don't think it's an e2e flake but rather an actual thing we need to investigate in the test

This is very odd indeed since this is an one file change. Will investigate

**Comment by kissgyula** [comment]
What preventing this single line code change to be merged? Is there anything I can help? Is it related to an another problem?

**Comment by PeerRich** [comment]
> What preventing this single line code change to be merged? Is there anything I can help? Is it related to an another problem?

we dont know why this is breaking our E2E to be fair

**Comment by hariombalhara** [comment]
Fixed the test. Should be mergeable now.

**Review by hariombalhara — APPROVED** [review]

**Pull request merged**
