### PR TITLE
feat(web): case insensitive slug search

### PR DESCRIPTION
**Pull request by heuels**
Not sure if this is something you want, but after upgrading we have lots of differently-cased event types that we still need to support 😞

### CODE REVIEW

**Comment by agustif** [comment]
I'd go as far to say it might be good to normalize always slugs to be lowercase and use only dash as separator?
I know we recently had to cleanup some chars in event-slugs too...
Thoughts @zomars ?

**Comment by heuels** [comment]
@zomars yes, that's right!

**Comment by zomars** [comment]
@heuels @agustif I see this like something desirable yes. But we should make sure it is being used consistently in the codebase. Or find a way to enable this globally:

image

**Comment by agustif** [comment]
@zomars we could add maybe a prisma middleware for this, that extends event-type calls adding the `      slug: { equals: slug, mode: "insensitive" },` where prop?

**Comment by hariombalhara** [comment]
@heuels Were you done with your changes?

**Comment by heuels** [comment]
@hariombalhara I have not sadly. We deprioritized using Cal.com for now and this has fallen off my radar.

**Comment by emrysal** [comment]
This needs to be fixed in the middleware to catch the many, many different places we query things by slug. - further improvement but this will definitely stay on our radar for implementation. Thanks @heuels for the PR and ensuing discussions too.

**Pull request closed without merging**
