### PR TITLE
Zoom link missing when rescheduled from In-person meeting to zoom video 

### LINKED ISSUE #2431: Zoom link missing when rescheduled from In-person meeting to zoom video
### Issue Summary

When rescheduling an event and changing from In-person meeting to zoom video, the zoom link is missing in the notification email:

Bildschirmfoto 2022-04-08 um 09 48 36

### Steps to Reproduce

1. Set an event type with location options In-person meeting and zoom video
2. Schedule an event with location In-person meeting
3. Reschedule event to any time slot and change location from In-person meeting to zoom video
4. Have a look at the notification email

### Technical details

- Browser version: Firefox 99.0
- Node.js version: v14.19.1
- cal.com selfhosted

### PR DESCRIPTION
**Pull request by andreaestefania12**
## What does this PR do?
Fixes #2431

This PR fixes the issue when rescheduling an event and changing from In-person meeting to zoom video, the zoom link is missing in the notification email.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Set an event type with location options In-person meeting and zoom video
- Schedule an event with location In-person meeting
- Reschedule event to any time slot and change location from In-person meeting to zoom video
- Have a look at the notification email

### CODE REVIEW

**Review by zomars — CHANGES_REQUESTED** [review]
Blocking so @sean-brydon can come in and see if this is an already solved issue.

**Comment by baileypumfleet** [comment]
@sean-brydon

**Comment by baileypumfleet** [comment]
@sean-brydon

**Comment by sean-brydon** [comment]
This appears to already be fixed in prod. A lot of changes have been implemented to improve the zoom link creation and I believe it was tackled in that.

**Pull request closed without merging**
