### PR TITLE
fix: don't send notes to booker if  "Hide notes in calendar" is on

### LINKED ISSUE #12259: [CAL-2680] Hide notes in email aswell as calendar
We currently have the ability to "Hide notes in calendar". These notes still show up in the email for the booker.

We should edit this so that when you hide notes, it hides notes for the booker in the calendar invite and in the email.

The organiser should still receive the Notes in their email.

Open question:

* Do we also hide the notes in the booking confirmation page?

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2680](https://linear.app/calcom/issue/CAL-2680/hide-notes-in-email-aswell-as-calendar)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
Fixes #12259

[Screencast from 13-11-23 01:59:57 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/2f415cdd-cc91-4c9b-8993-f3d48837d4d1)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by supalarry — COMMENTED** [review]
@SomayChauhan On line 134 of the file you edited `packages/emails/email-manager.ts` we have function `sendScheduledSeatsEmails` which on line 155 also sends attendee e-mails. I think that we need to update it too.

I wanted to test seats e-mail but have problems with e-mail provider, so would be nice if you can confirm it with Mailhog. Cheers.

**Comment by SomayChauhan** [comment]
Hey @supalarry,

I've addressed the issue, and it looks like things should be fixed now. If you want to give it a spin, I've got an EC2 instance with mailhog setup at http://13.233.201.155:8025/. Just update your .env file with 
`EMAIL_SERVER_HOST='13.233.201.155'`
`EMAIL_SERVER_PORT=1025`
 
  and you should be good to roll. Cheers!

**Comment by supalarry** [comment]
> Hey @supalarry,
> 
> You are right, updated sendScheduledSeatsEmails too, and it looks like things should be fixed now. If you want to give it a spin, I've got an EC2 instance with mailhog setup at http://13.233.201.155:8025/. Just update your .env file with `EMAIL_SERVER_HOST='13.233.201.155'` `EMAIL_SERVER_PORT=1025`
> 
> and you should be good to roll. Cheers!

That's very nice of you, appreciate! : )

However, I still have the same problem - I set environment variables to above, restarted app but still no e-mails are getting sent, and neither could I get mailhog to sent e-mails locally, so I can't test this : (

**Comment by SomayChauhan** [comment]
## meeting without seats
[Screencast from 17-11-23 03:58:15 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/f6b9bd20-1a9d-40d7-b390-36b7a5e0b982)


## meeting with seats
[Screencast from 17-11-23 03:51:10 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/8289c849-b234-4791-8d45-1dfddb54838a)


PS: sorry about the lengthy videos, my system's acting a bit sluggish

**Comment by supalarry** [comment]
> ## meeting without seats
>  Screencast.from.17-11-23.03.58.15.PM.IST.webm 
> ## meeting with seats
>  Screencast.from.17-11-23.03.51.10.PM.IST.webm 
> PS: sorry about the lengthy videos, my system's acting a bit sluggish

Amazing, thank you for the recordings!

**Review by supalarry — APPROVED** [review]
Great work and thank you for contributing! 🚀 Have a nice weekend!

**Comment by SomayChauhan** [comment]
😁😁 you too!!

**Pull request merged**
