### PR TITLE
[CAL-812] Button group focus/hover state

### LINKED ISSUE #6527: [CAL-812] Button group focus/hover state
Fix button group component that breaks combined focus/hover states

* We can move away from the current approach as long as the api stays the same 
* Breaks as we don't technically have left and right borders 

  

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-812](https://linear.app/calcom/issue/CAL-812/button-group-focushover-state)</sub>

### PR DESCRIPTION
**Pull request by gitstart-calcom**
## What does this PR do?

Fixes #6527

## Demo
https://www.loom.com/share/adb39a6c26614415946247a66ae7b880

**Environment**: Staging(main branch) / Production

### CODE REVIEW

**Review by PeerRich — CHANGES_REQUESTED** [review]
looks great, only thing that needs change is that the menuItem hover should not have a border right

CleanShot 2023-02-02 at 18 40 43@2x

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, border issue has been fixed now. Please take a look.
https://www.loom.com/share/adb39a6c26614415946247a66ae7b880

**Review by PeerRich — APPROVED** [review]

**Review by PeerRich — CHANGES_REQUESTED** [review]
found another issue on mobile

- [ ] flickering border
- [ ] double border for delete button

https://user-images.githubusercontent.com/8019099/217485440-22d1d56d-4c65-4475-ac3a-a8008bb5073a.mp4

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
> found another issue on mobile
> 
> * [ ]  flickering border
> * [ ]  double border for delete button
> 
>  CleanShot.2023-02-08.at.10.10.32.mp4

we will fix this @G3root @Udit-takkar 

merging this PR now, thank you @gitstart-calcom

**Pull request merged**
