### PR TITLE
fix: Attendee address and phone number field not shown in booking questions

### LINKED ISSUE #13670: [CAL-3128] Attendee address and phone number field not shown in booking questions
### Issue Summary

When choosing 'In Person (Attendee Address)' or 'Attendee phone number' as an event location this field should show as a booking question (advanced tab). Right now, it's not shown and can't be edited.

### Steps to Reproduce

1. Create event type
2. Change location to In Person (Attendee Address)
3. Go to Advanced and see that the booking question for the Attendee Adress is not shown

<sub>[CAL-3128](https://linear.app/calcom/issue/CAL-3128/attendee-address-and-phone-number-field-not-shown-in-booking-questions)</sub>

### PR DESCRIPTION
**Pull request by asadath1395**
## What does this PR do?

Fixes #13670 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by asadath1395** [comment]
@CarinaWolli Anything stopping us from getting this merged?

**Comment by Udit-takkar** [comment]
> @CarinaWolli Anything stopping us from getting this reviewed and merged?

The milestone for this issue is 4.0. This will be reviewed and merged after v3.9 release

**Review by joeauyeung — CHANGES_REQUESTED** [review]
Thanks for your contribution @asadath1395. I have a few comments that need to be addressed first.


## Blocking
- The input type should match the location either a phone number or address
image
- When editing the field. The required selector should be marked as "Yes".
image

**Comment by asadath1395** [comment]
@joeauyeung 
> * When editing the field. The required selector should be marked as "Yes".

There are cases when multiple locations are selected, couple is marked as required and one is marked as not required, how should we show in that case?

**Review by joeauyeung — APPROVED** [review]
Feedback address and code LGTM. Thanks again for your contribution @asadath1395

**Pull request merged**
