### PR TITLE
Make the caldav queries run in parallel when querying availability

### PR DESCRIPTION
**Pull request by kuba-orlik**
Ref  #479

### CODE REVIEW

**Comment by femyeda** [comment]
Nice!

I had plans to modify this code. 
Could you add the case where when provided no selectedCalendars, then query all calendars.

An example could be found here.
https://github.com/calendso/calendso/blob/main/lib/calendarClient.ts#L218

**Comment by kuba-orlik** [comment]
@femyeda this should do the trick :)

**Comment by baileypumfleet** [comment]
@femyeda can you review, now that this has been added?

**Comment by femyeda** [comment]
The check should be done on `selectedCalendarIds` as all the user's selected calendars are passed to this function.

**Comment by femyeda** [comment]
Gonna cherry pick your first commit, then add the fix just to get this merged in quicker. Great work.

**Pull request closed without merging**
