### PR TITLE
Added 'Add Guest' button at the confirm booking step

### PR DESCRIPTION
**Pull request by alishaz-polymath**
Hi @PeerRich , please take a look at this.

### CODE REVIEW

**Comment by PeerRich** [comment]
i like the multi-email input but i am not sure if we want to pull in another dependency just for it. i would be surprised if it was hard to remake this component with basic tailwind + some js.

additionally, the input has a different styling for both light mode and dark mode:

image
image
image

it's also unstyled for dark mode:
image

I'll ask what @baileypumfleet thinks about pulling in a new package and then we'll merge this in and I'll make a layout clean up and restyle the input.

i am working on the booking page layout anyway right now :)

**Review by PeerRich — CHANGES_REQUESTED** [review]
- styling
- dark mode

**Comment by alishaz-polymath** [comment]
> i like the multi-email input but i am not sure if we want to pull in another dependency just for it. i would be surprised if it was hard to remake this component with basic tailwind + some js.
> 
> additionally, the input has a different styling for both light mode and dark mode:
> 
> image
> image
> image
> 
> it's also unstyled for dark mode:
> image
> 
> I'll ask what @baileypumfleet thinks about pulling in a new package and then we'll merge this in and I'll make a layout clean up and restyle the input.
> 
> i am working on the booking page layout anyway right now :)

Oh, okay. Well, I had a chat with Bailey about the plugin earlier and he was okay with it. But yeah, we can definitely create a similar function ourselves, if that's preferred. I'm fine either way.

**Comment by baileypumfleet** [comment]
It's all good to go ahead with using the npm package, I have no problem with it because it's very small in size. As long as the dark mode fixes and such are resolved, this should be good to go :)

**Comment by PeerRich** [comment]
i will merge and fix dark mode in a new PR :)

**Pull request merged**
