### PR TITLE
Fix missing phone data from location after booking

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Fixes missing phone data from the location after booking (phone data wasn't passed through the booking earlier, ever since the `react-hook-form` update of the component, I'd imagine)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [x] Test for phone location meeting booking in staging and see if it is passed on as expected
- [x] Test for all other location meetings to ensure that this doesn't create an issue with them

## Checklist

[Currently showing a TS error because of the passed on `control` value of react-hook-form for phone input]

### CODE REVIEW

**Comment by PeerRich** [comment]
assigned to @agustif

**Comment by agustif** [comment]
Hey, I've been having a first check, my first intuition was trying to fix the Control Type issues, but after a bit further digging it seems we've been ignoring it for a while (at least since 2 weeks ago when git timeline get's lost for me after moving the file from it's original place)

Anyways, I suggest to keep doing that (ignoring the typescript) error for now, and focus on fixing the bug itself.

image

So basically before, PhoneInput took one line, and the ignore was correctly ignoring it on top of it, since we moved to multiline due to line passing ESlint limit, the easier way to 'fix' it for now is to just move the ignore.

We can get unto fixing the underlying type issue later maybe.

You can keep ignoring the typescript compile issue by moving it before control props in BookingPage.tsx component:
```diff
- {/* @ts-ignore */}
<PhoneInput
 name="phone"
+ // @ts-ignore
 control={bookingForm.control}
 placeholder={t("enter_phone_number")}
 id="phone"
 required
/>
```

Will test it further and add anything else I might find or give it the OK to the review

**Comment by agustif** [comment]
Aaand it works!

I might suggest removing the unneeded added Control<> props in InputPhone since we're ignoring those now, we might fix'em later.

Good work with the fix!

image

**Comment by alishaz-polymath** [comment]
> Aaand it works!
> 
> I might suggest removing the unneeded added Control<> props in InputPhone since we're ignoring those now, we might fix'em later.
> 
> Good work with the fix! ✅ Screenshot 2022-02-25 at 02 02 01

I don't think it would work if we remove the control prop. The control prop actually passes in the react-hook-form registration to the phone input.

**Review by agustif — APPROVED** [review]

**Review by pumfleet — APPROVED** [review]

**Pull request merged**
