### PR TITLE
fix: username + replaced with -

### PR DESCRIPTION
**Pull request by AyushGovil**
## What does this PR do?

replaces all '+' with '-' in the username string.

Fixes # [(issue)](https://github.com/calcom/cal.com/issues/10078)

## Type of change

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] Chore (refactoring code, technical debt, workflow improvements)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How should this be tested?

image

Did console.log to check the new string in the browser console. Got the desired log in the browser. Could not test the functionality e2e in local because sign up functionality doesn't work in local therefore used console.log to check the final object.

image

Inputs used as username to test => ayush+gov, ayush-gov+,  +ayush-gov+, ++a 

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by emrysal** [comment]
Hi @AyushGovil Have a look at our slugify (packages/lib/slugify.ts) - this is not the only place the username is slugified. Needs a global solution.

**Review by emrysal — CHANGES_REQUESTED** [review]
Hi @AyushGovil Have a look at our slugify (packages/lib/slugify.ts) - this is not the only place the username is slugified. Needs a global solution.

**Comment by AyushGovil** [comment]
Hey @emrysal, I see that cal has a sign up page in this format but in local project setup, the sign up page is different.

image

image

I asked this because I have to handle all possible ways in which the username can be created.

**Comment by hariombalhara** [comment]
> Hey @emrysal, I see that cal has a sign up page in this format but in local project setup, the sign up page is different.
> 
> image
> 
> image
> 
> What is the reason for this? I asked this because I have to handle all possible ways in which the username can be created.

cal.com/signup is coming from the website repo which is private. If you would go to app.cal.com/signup, you would see the same.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
As @emrysal mentioned there would be more occurences.
Also let's make the change in `slugify` as well so if any existing + in username, that's also taken care of.

Other places we might need to handle are
- Username change from within the app(/settings/my-account)
- username change during onboarding

Also, I think we should call `slugify` function itself before saving the username

**Comment by AyushGovil** [comment]
Hey @hariombalhara , @emrysal  I have made the changes => https://github.com/calcom/cal.com/pull/10142. Also regarding the slugify function there was no modification required because it was already converting the + to -. I have created a separate branch with new pr because my branch for this pr got deleted because of some issue in my local.

**Pull request closed without merging**
