### PR TITLE
feat: Add app store entry for "Autocheckin" (Challenge/Bounty)

### PR DESCRIPTION
**Pull request by pgvr**
## What does this PR do?

This PR adds an entry for [Autocheckin](https://autocheckin.up.railway.app) to the Cal.com app store. I hope I generated the files correctly.

This app is part of a bounty/challenge, so it's **TBD** whether this should be merged.

Loom Video: https://www.loom.com/share/0e3817ac913240ddb1289517a4074383?sid=0d14a271-46a7-44c0-97ab-9f57c035735a

/claim #14676

### CODE REVIEW

**Comment by PeerRich** [comment]
now that i am thinking about it, we could even use our OAuth here instead of manually copy & pasting the API key

**Review by PeerRich — DISMISSED** [review]
so far the best contender i have seen for this challenge 🔥🔥

**Comment by pgvr** [comment]
Thank you @PeerRich!
I'd love to use OAuth, but I didn't find anything in the docs. If there's a way to do it, that would be way smoother.

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
> Thank you @PeerRich!
> 
> I'd love to use OAuth, but I didn't find anything in the docs. If there's a way to do it, that would be way smoother.

connected you with @CarinaWolli via email about OAuth

**Comment by CarinaWolli** [comment]
I think it's best to stay with API keys here. The endpoints that are being called only allow apiKey for now, we would have to change that first 

By the way nice work, I just checked out your app 👏🏻

**Comment by pgvr** [comment]
Thanks you :)
Ok got it. If that ever changes, I'm happy to add OAuth instead.

**Pull request merged**
