### PR TITLE
[CAL-1545] replace heroicons with lucide.dev

### LINKED ISSUE #8423: [CAL-1545] replace heroicons with lucide.dev
we are now using lucide.dev in calcom/icons and we should get rid of heroicons altogether: 

CleanShot 2023-04-21 at 00 53 27@2x
 
@gitstart-calcom one thing to keep in mind is that the default sizes of lucide.dev icons may be different than the default sizes of heroicons, which means you may need to add className="w-4 h-4" or similar to the lucide.dev icons when removing hero icons.

for this PR, can you take screenshots of before and after for every icon?

<sub>[CAL-1545](https://linear.app/calcom/issue/CAL-1545/replace-heroicons-with-lucidedev)</sub>

### PR DESCRIPTION
**Pull request by gitstart-calcom**
Fixes #8423 

## Before
Screenshot 2023-05-12 at 2 29 41 PM

Screenshot 2023-05-12 at 2 52 08 PM
Screenshot 2023-05-12 at 2 52 55 PM
Screenshot 2023-05-12 at 2 54 52 PM
Screenshot 2023-05-12 at 2 55 04 PM 
Screenshot 2023-05-12 at 2 55 39 PM
Screenshot 2023-05-12 at 2 59 14 PM
Screenshot 2023-05-12 at 2 59 38 PM
Screenshot 2023-05-12 at 3 00 02 PM
Screenshot 2023-05-12 at 3 00 20 PM
image
image 
image

## After
Screenshot 2023-05-12 at 1 10 16 PM 
Screenshot 2023-05-12 at 1 11 49 PM 
Screenshot 2023-05-12 at 1 13 01 PM 
Screenshot 2023-05-12 at 1 19 22 PM 
Screenshot 2023-05-12 at 1 19 44 PM 
Screenshot 2023-05-12 at 1 20 15 PM 
Screenshot 2023-05-12 at 1 20 33 PM 
Screenshot 2023-05-16 at 12 12 17 PM 
image 
image 
image 
image

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]

**Comment by PeerRich** [comment]
CleanShot 2023-05-05 at 22 07 01@2x
@gitstart-calcom

**Comment by gitstart-calcom** [comment]
Hi @PeerRich, the failing tests have been fixed now

**Comment by PeerRich** [comment]
still failing @gitstart-calcom

**Comment by gitstart-calcom** [comment]
> still failing @gitstart-calcom

It's failing because the new changes from the main branch have heroicons. We have fixed this on our end and will push the changes along with the before and after screenshots.

**Pull request merged**
