### PR TITLE
Hotfix:All non recurring bookings were clubbed into one distinct booking

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Bug: https://www.loom.com/share/1d8d8bd2982d4f1bbfba93715eb829fd
You won't see newly created booking.

Avoid clubbing all non recurring bookings into a single distinct booking(due to recurringEventId being undefined for all non-recurring events)

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Simply create 2 bookings(non-recurring) and you would only see 1. After the fix it should work fine.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by zomars — APPROVED** [review]
Seems like a better behavior than the current one. Will tag @leog so he can give his two cents.

**Comment by zomars** [comment]
My bad. Automerged :/

**Comment by leog** [comment]
Thanks @hariombalhara. Makes sense to approach it the way you did for now to then revisit it later.

**Review by leog — COMMENTED** [review]
Ok to merge

**Pull request merged**
