### PR TITLE
chore: Add transition effects in UI components

### PR DESCRIPTION
**Pull request by clicktodev**
## What does this PR do?

Add transitions to components that miss them

https://github.com/user-attachments/assets/50fa2d71-b161-4cf3-8941-daec1b4e0922

https://github.com/user-attachments/assets/1d254383-b3c9-4143-815a-cc2472a46d57

https://github.com/user-attachments/assets/03dfc6de-1eea-40aa-baf2-201e99bb3f8d

https://github.com/user-attachments/assets/a63be255-ae0e-4c6b-a513-227e364924de

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
@hichemfantar, thanks for your work. I haven't seen any significant changes. I think they are already fine.

**Comment by hichemfantar** [comment]
> @hichemfantar, thanks for your work. However, I've tested it and haven't seen any significant changes. Also, I think we don't need transitions in those components; they are already fine.

This pr makes those components consistent with the existing components.
Check out my commit history because i added many transitions before:
https://github.com/calcom/cal.com/pulls?q=is%3Apr+is%3Aclosed+author%3Ahichemfantar

**Comment by anikdhabal** [comment]
> > @hichemfantar, thanks for your work. However, I've tested it and haven't seen any significant changes. Also, I think we don't need transitions in those components; they are already fine.
> 
> This pr makes those components consistent with the existing components. Check out my commit history because i added many transitions before: https://github.com/calcom/cal.com/pulls?q=is%3Apr+is%3Aclosed+author%3Ahichemfantar

Got it, thanks for your work. Let me reopen it.

**Comment by anikdhabal** [comment]
@hichemfantar got it. And besides these, are there any components left?

**Review by anikdhabal — APPROVED** [review]
Thanks for your work
LGTM!

**Comment by keithwillcode** [comment]
Waiting for @ciaranha @itsberkaya sign-off before merging.

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
