### PR TITLE
No confirmation shall be needed when rescheduling events that need confirmation

### PR DESCRIPTION
**Pull request by Nico-J**
When rescheduling an event that needs confirmation after initial booking, another confirmation was required by the system, leading to strange double bookings in the integrations.

This PR resolves this by properly checking whether another confirmation is required or not. Also, the success page has been adapted in a way that it now recognizes when rescheduling instead of scheduling with confirmation has occured.

### CODE REVIEW

**Comment by Nico-J** [comment]
Conflicts have been resolved and several linting errors were fixed. Tested again and ready to merge from my side, @baileypumfleet . :)

**Comment by Nico-J** [comment]
Re-resolved all conflicts and tested it again. It'll work as soon as @emrysal 's PR https://github.com/calendso/calendso/pull/601 is merged as well.

**Review by pumfleet — APPROVED** [review]
Looks good to me :)

**Review by PeerRich — APPROVED** [review]

**Review by emrysal — APPROVED** [review]
Looks good! tested on local and functions as expected

**Pull request merged**
