### PR TITLE
feat: Add support for multiple google calendars

### PR DESCRIPTION
**Pull request by jfernandogt**
Hello Team, 

I'm adding support to verify if you are busy in more than one calendar in this PR. 

**Purpose**
I'm using two google accounts (work and personal). I shared my work calendar to my personal account, but calendso only supports verifying if you are busy in the primary calendar.

**Changes**
Readme: Updating the documentation about the scopes
calendarClient: adding the support verifying more than one calendar
googlecalendar/add.ts: Update the scopes

**Images**

Screenshot_1

Screenshot_2

https://github.com/calendso/calendso/issues/15

### CODE REVIEW

**Comment by jtylerhartley** [comment]
One small issue I found. If I have a calendar shared with the default calendar (ending in @group.calendar.google.com) it still does not populate as busy.

**Comment by jfernandogt** [comment]
> One small issue I found. If I have a calendar shared with the default calendar (ending in @group.calendar.google.com) it still does not populate as busy.

Oh, I deactivated the option to that kind of calendars, let me update it :).

**Comment by jtylerhartley** [comment]
> > One small issue I found. If I have a calendar shared with the default calendar (ending in @group.calendar.google.com) it still does not populate as busy.
> 
> Oh, I deactivated the option to that kind of calendars, let me update it :).
> 
> Edit: I Updated

Thank you for making the update!

**Comment by jtylerhartley** [comment]
> > > One small issue I found. If I have a calendar shared with the default calendar (ending in @group.calendar.google.com) it still does not populate as busy.
> > 
> > 
> > Oh, I deactivated the option to that kind of calendars, let me update it :).
> > Edit: I Updated
> 
> Thank you for making the update!

**Comment by baileypumfleet** [comment]
I don't see why the auth/calendar scope is needed, it seems to work on mine without it?

**Comment by baileypumfleet** [comment]
This PR is properly awesome though, thanks so much for your contribution 🎉

**Comment by clementgalopin** [comment]
Hi there, I am not sure to understand how does the feature work. It looks like it takes all busy slots from all the calendar that are shared with the main one.

But I do think you would rather need to select which ones of those calendars you want to consider (or not).

Indeed, it is very common to share several secondary calendars with your main one, but it is also very common that other people share their calendar with you so that you can see when they are available or not.

From what I understand, this feature would prevent people from booking your calendar whenever one of your coworker already has an event. This sounds like a big issue for me.

As a reference, you can have a look at how mixmax deals with this issue. They ask you which ones of the shared calendars do you want to take into account.

**Comment by Gitfrogger** [comment]
This PR is blocking the whole agenda upon full-day events in Google calendar.

**Comment by jtylerhartley** [comment]
> Hi there, I am not sure to understand how does the feature work. It looks like it takes all busy slots from all the calendar that are shared with the main one.
> 
> But I do think you would rather need to select which ones of those calendars you want to consider (or not).
> 
> Indeed, it is very common to share several secondary calendars with your main one, but it is also very common that other people share their calendar with you so that you can see when they are available or not.
> 
> From what I understand, this feature would prevent people from booking your calendar whenever one of your coworker already has an event. This sounds like a big issue for me.
> 
> As a reference, you can have a look at how mixmax deals with this issue. They ask you which ones of the shared calendars do you want to take into account.

Yes, I agree that this would be a logical next step, but it has yet to be implemented. Hopefully soon!

**Pull request merged**
