### PR TITLE
Fix TimezoneDropdown Overflow < 768W

### LINKED ISSUE #4724: Mobile /Public Booking page - Timezone dropdown goes offscreen
image

The dropdown should be aligned left of the screen and below the icon & text with a max width ensuring it doesn't go off screen.

Requires confirmation and duration text size are also a size bigger than the other items and should be aligned.

### PR DESCRIPTION
**Pull request by davidtaing**
## What does this PR do?
- Fixes TimezoneDropdown component overflowing due to it being a flex child.
- Convert the Radix Collapsible component to the @calcom Dropdown.

Fixes #4724 

Note: The primitive Radix DropdownMenu.Content was used because the classes were clashing in @calcom DropdownMenuContent. The DropdownMenuContent does not provide a way to opt out of the default classes.

https://github.com/calcom/cal.com/blob/9304ca141568f5f098ada6e350910cc1c4ea639e/packages/ui/Dropdown.tsx#L28-L43

## Before
Screenshots
[320W - Overflow](https://user-images.githubusercontent.com/8443215/193062798-606f36c7-7b91-4f52-9c1b-7bde639b05e7.png)

[768W - OK](https://user-images.githubusercontent.com/8443215/193062641-440cb016-1946-4c0c-9e53-49bd3b937703.png)

## After

[Loom Video](https://www.loom.com/share/dc485c38bf1844ebb56229c25b74b394)

[320W](https://user-images.githubusercontent.com/8443215/193063304-97e1916a-afc5-42f4-bfc8-99ca014c04e3.png)

[768W](https://user-images.githubusercontent.com/8443215/193063270-5e5c94a5-ad19-45b2-b1cf-219a0504a892.png)

**Environment**: Staging(main branch)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Navigate to the Booking Availability Page. Example: `http://localhost:3000/free/30min`
- Test the dropdown list.

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by davidtaing** [comment]
If you review my Loom video, you can see that when I resize the window from 768W to lower sizes (or vise versa) the TimezoneDropdown does not correctly position itself.

I'm not too sure what would be causing the issue, I'm more of a beginner programmer. But I'll note down a few things below. 

- If you close it and reopen after resizing the window, it renders with the correct position.
- TimezoneDropdown is memo-ized.
- The primitive Radix Dropdown renders the DropdownMenuContent in a Portal. There's an div with absolute position, and the MenuContent has a translate3d(x, y, z) applied to it. _I'm not sure how exactly it calculates the position._

**Comment by davidtaing** [comment]
Just to touch base again on why I used the Primitive Radix DropdownMenu.Content instead of calcom's DropdownMenuContent.

The default classes were clashing with the classes and I had no way of opting out of using the default classes. I was able to get my classes to work by removing the default classes on my local machine. I have not included this change as I'm sure it will break the other dependent components.

https://github.com/calcom/cal.com/blob/9304ca141568f5f098ada6e350910cc1c4ea639e/packages/ui/Dropdown.tsx#L28-L43

For the calcom DropdownMenuTrigger, I was able to opt out of the classes via the "asChild" prop.

https://github.com/calcom/cal.com/blob/9304ca141568f5f098ada6e350910cc1c4ea639e/packages/ui/Dropdown.tsx#L10-L22

**Comment by PeerRich** [comment]
i think we'll end up rebuilding most of this UI @Jaibles what do you think?

**Comment by davidtaing** [comment]
Hi @PeerRich,
Can I create another PR with only the changes to the Tailwind classes? And leave the UI rebuild for you and @Jaibles  to revisit at a later stage?

This is what it would look like. [Loom Video](https://www.loom.com/share/ecd9ff30e6e0438089bebb952bd90c38)

**Comment by PeerRich** [comment]
> Hi @PeerRich,
> 
> Can I create another PR with only the changes to the Tailwind classes? And leave the UI rebuild for you and @Jaibles  to revisit at a later stage?
> 
> 
> 
> This is what it would look like. [Loom Video](https://www.loom.com/share/ecd9ff30e6e0438089bebb952bd90c38)
> 
> 

yes please, much better

**Pull request closed without merging**
