### PR TITLE
adds event types to kbar

### LINKED ISSUE #6196: [CAL-654] KBar: add all event-types to search
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-654](https://linear.app/calcom/issue/CAL-654/kbar-add-all-event-types-to-search)</sub>

### PR DESCRIPTION
**Pull request by phishy**
## What does this PR do?

Adds Event Types to KBar.

Fixes #6196 

**Environment**: Production

image

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

* Create event types
* Open kbar
* Check for event type entries

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by PeerRich** [comment]
really cool! I wonder if we wanna abstract the code more so we can combine calling "app store" and "event-types" without re-writing everything again.

adding "booking" information would be valuable too in the future

**Comment by PeerRich** [comment]
tested on vercel, doesnt work for me: https://cal-git-fork-phishy-6196-kbar-event-types-cal.vercel.app/event-types

username: pro@example.com
password: pro

CleanShot 2022-12-29 at 12 02 54

**Comment by phishy** [comment]
Yeah, having some service files would be useful. As far as it not working, I think the data already needs to be loaded elsewhere via navigation. Gotta figure that out. Not used to trpc.

**Comment by PeerRich** [comment]
> Yeah, having some service files would be useful. As far as it not working, I think the data already needs to be loaded elsewhere via navigation. Gotta figure that out. Not used to trpc.

yes can confirm, after clicking an event-type you can then search for it.

there is an endpoint to get all event-types tho. not sure what the endpoint is called but it should be quite trivial

**Review by PeerRich — DISMISSED** [review]
right now it only shows event-types that you have visited

**Comment by PeerRich** [comment]
@phishy let us know if someone of our team should help out 🙏

**Comment by phishy** [comment]
I might. Its a doozy.

**Comment by phishy** [comment]
Oh wait. I was confusing this with another PR. This should be good.

**Review by PeerRich — APPROVED** [review]
awesome. worked!

only NIT would be to group the request for future data into an adaptor but we can do that in the next PR

**Comment by phishy** [comment]
Need to consider service classes to abstract data calls, yeah?

**Comment by PeerRich** [comment]
> Need to consider service classes to abstract data calls, yeah?

yeah sort of. but we can do that in a different PR once we add more data to KBar

**Comment by PeerRich** [comment]
E2E seems to be failing but i dont know why

**Comment by PeerRich** [comment]
reopened here: https://github.com/calcom/cal.com/pull/6319

**Review by zomars — APPROVED** [review]
Thank you for your contribution 🙏 

LGTM

**Comment by zomars** [comment]
> E2E seems to be failing but i dont know why

We got a flaky test `hash-my-url.e2e.ts` will mark it as `fixme` on another PR

**Comment by PeerRich** [comment]
ok, lets let @phishy know when this is mergeable so he can update the branch

**Comment by zomars** [comment]
Will merge as test are flaky and confirm that it is working. Thanks again @phishy 🙏🏽

**Comment by PeerRich** [comment]
awesome!!

**Pull request merged**
