### PR TITLE
chore: update formbricks-js to newest version

### PR DESCRIPTION
**Pull request by mattinannt**
## What does this PR do?

[Co-Founder of Formbricks here]
This PR updates `@formbricks/js` to the newest version to support the newest feature and newest API.

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] N/A-I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] N/A-I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Set the env vars `NEXT_PUBLIC_FORMBRICKS_HOST_URL` & `NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID` according to the values of your Formbricks account
- Create the code action with the key `team_disbanded` and the in-app survey triggered on this action
- Now try Deleting a Team and you should see the survey in the cal app!

### CODE REVIEW

**Review by emrysal — DISMISSED** [review]
Regenerated the yarn.lock file to contain some private repo's - contains some minor version bumps but as long as the tests pass I'm happy to merge.

**Comment by emrysal** [comment]
@mattinannt This requires a foundational change to our compilerOptions, playing around with moduleResolution(="Bundler")/target(="es2015") settings for @calcom/lib packages to resolve. Do you have any thoughts on this?

**Review by keithwillcode — DISMISSED** [review]
Type checks and builds are failing.

**Comment by mattinannt** [comment]
> @mattinannt This requires a foundational change to our compilerOptions, playing around with moduleResolution(="Bundler")/target(="es2015") settings for @calcom/lib packages to resolve. Do you have any thoughts on this?

Right, we have also seen the same issue. We are reverting back to our previous package- and ts-config to solve these issues and update the PR :-)

**Comment by PeerRich** [comment]
> > @mattinannt This requires a foundational change to our compilerOptions, playing around with moduleResolution(="Bundler")/target(="es2015") settings for @calcom/lib packages to resolve. Do you have any thoughts on this?
> 
> Right, we have also seen the same issue. We are reverting back to our previous package- and ts-config to solve these issues and update the PR :-)

converting back to draft until resolved 🙏

**Comment by keithwillcode** [comment]
@anikdhabal @Amit91848 can one of you review and test this please?

**Comment by anikdhabal** [comment]
> @anikdhabal @Amit91848 can one of you review and test this please?

sure keith

**Review by anikdhabal — COMMENTED** [review]
Tested it, LGTM

Let me fix the conflict and update the lock file

**Review by anikdhabal — APPROVED** [review]

**Pull request merged**
