### PR TITLE
fix: clear params on event type creation cancellation

### LINKED ISSUE #1363: Team ID parameter remains set after cancelling team event type creation
### Issue Summary

When creating a new team event type and cancelling in the 'Add a new event type' modal, `teamId` remains set. This causes the wrong form modal to appear when subsequently trying to create a regular/non-team event type.

### Steps to Reproduce

1. Be part of a team
2. Navigate to the Event Types page
3. Click on the 'New Event Type' dropdown button and select a team
4. Click 'Cancel' (or outside of the modal) in the subsequent 'Add a new team event type' modal
5. Click on the 'New Event Type' dropdown button and select your username (observe the unexpected query params)

Screenshot 2021-12-20 at 22 15 52

6. The 'Add a new team event type' formal modal appears (the 'Add a new event type' one is expected; also observe the URL pointing to the personal booking page rather than the team one)

Screenshot 2021-12-20 at 22 24 31

### Technical details

- Browser version: Chrome 96

### PR DESCRIPTION
**Pull request by nrademacher**
Fixes #1363 by using the router to navigate back if event type creation is cancelled (when user clicks the Cancel button or closes the modal by clicking outside of it).

### CODE REVIEW

**Review by zomars — APPROVED** [review]
Code looks good, let's test this on preview. Nice work!

**Comment by zomars** [comment]
It seems it's not working properly on preview. Opening a modal trigger from `/event-types` triggers to`/event-types?new=1&eventPage=rick` and after closing it goest back to `/event-types?eventPage=rick`.

Also on a side note we should add this behavior to the new team event modal as well.

**Review by zomars — CHANGES_REQUESTED** [review]
It seems it's not working properly on preview. Opening a modal trigger from `/event-types` triggers to`/event-types?new=1&eventPage=rick` and after closing it goest back to `/event-types?eventPage=rick`.

Also on a side note we should add this behavior to the new team event modal as well.

**Comment by nrademacher** [comment]
Hi, the bug seems to have been fixed now in a subsequent PR, so I'm closing this 👍

**Pull request closed without merging**
