### PR TITLE
Timeslot selectable times fix for not UTC timezones in Availability

### LINKED ISSUE #1437: Availability is being ignored (or timezones are off)
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I've set up my global availability after 10am  (GMT+1). The event availability itself starts at 9am (GMT+1). When I go to my scheduling, users can book times starting at 8am (GMT+1).

Screenshot 2022-01-10 at 08 56 52

Screenshot 2022-01-10 at 08 57 00

Screenshot 2022-01-10 at 08 57 09

### Steps to Reproduce

Using GMT+1 everywhere

1. Set up global availability to 10am
2. Set up event availability to 9am
3. Check when event is actually available

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version: https://www.whatsmybrowser.org/b/KRHWO
- Node.js version: Hosted cal.com
- Anything else that you think could be an issue: My account cal.com/dom/ also suffered from #1236 which is not un-related

### LINKED ISSUE #1718: End Time not 24:00 for other TZ users after the end time check fix in #1673 issue
Reported by Cristian Le (@LecrisUT) on PR#1673
```
I believe this has created an issue that the end time for the day is no longer `24:00` if the user and browser or not on UTC timezone. 
```
image

_Originally posted by @LecrisUT in https://github.com/calcom/cal.com/issues/1673#issuecomment-1031018770_

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

- Updates the selectable timeslots to allow `start time `and `end time` dropdowns to be from `00:00 to 24:00`  for non UTC timezones as well.
- Fixes the availability set within eventType to now provide accurate availability override for non UTC users

Fixes #1718
Fixes #1437 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] For non UTC user, the availability set inside `/availability` should allow time 00:00 to 23:45 in the start and end time selectables
- [x] For non UTC user, the availability set inside `/event-types/[type]` should now respect the override accurately instead of adding an extra timezone difference

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by LecrisUT** [comment]
I can confirm that this fixes the view in the `/availability` url, however there are still dangling issues. E.g. if you manually edit the availability of an event, it will still use the old logic, and not convert the time properly to and from UTC. Also, did you confirm that this does not affect the integrations time?

**Comment by alishaz-polymath** [comment]
> I can confirm that this fixes the view in the `/availability` url, however there are still dangling issues. E.g. if you manually edit the availability of an event, it will still use the old logic, and not convert the time properly to and from UTC. Also, did you confirm that this does not affect the integrations time?

Hi @LecrisUT . This is still a WIP, thanks for your testing and input. I'll make sure to take a look at the aforementioned points and that it's ready as best as I can get it, before I take it out of the draft.

**Comment by LecrisUT** [comment]
Great,  #1437 and the PR #1691 seem to already be fixing this issue. Could you review that one? I cannot check the Vercel build as it's not being approved.

**Comment by alishaz-polymath** [comment]
> Great, #1437 and the PR #1691 ([fa10391](https://github.com/calcom/cal.com/commit/fa1039198f7a47fa2e3ace6ddb55d519004eba31) to be precise) seem to already be fixing this issue. Could you review that one? I cannot check the Vercel build as it's not being approved.

Thank you for metioning it. I'll take a look at it later today :)

**Comment by alishaz-polymath** [comment]
Hi @LecrisUT , can you check the latest commit and see if the eventtype time set issue is now fixed for you as well?
Thanks

**Comment by alishaz-polymath** [comment]
@emrysal Can you please provide an extra pair of eyes here, because you're most aware of how all of it works and I'd rather not create more mess than I solve lol 😅

**Comment by LecrisUT** [comment]
Quick test, that problem is solved.

Other issues:
- [ ] When inputting the availability time in the event's advanced menu, there is no check if `end time < start time`.
- [ ] Curiously it also allows for `>24h` format, however it does not have proper logic to deal with it. Intended logic is for it to spill over the next day (similarly for `-24h` format), e.g. selecting `Tue, Wed` with availability `20:00 - 26:00` should translate to `Tue 20:00-24:00`, `Wed 00:00-02:00`, `Wed 20:00-24:00`, `Thu 00:00-02:00`. This should probably be a separate PR though.

Otherwise I am not sure where to test, I will leave the rest to the others to do a more thorough test around.

**Comment by alishaz-polymath** [comment]
> Quick test, that problem is solved.
> 
> Other issues:
> 
>     * [ ]  When inputting the availability time in the event's advanced menu, there is no check if `end time < start time`.
> 
>     * [ ]  Curiously it also allows for `>24h` format, however it does not have proper logic to deal with it. Intended logic is for it to spill over the next day (similarly for `-24h` format), e.g. selecting `Tue, Wed` with availability `20:00 - 26:00` should translate to `Tue 20:00-24:00`, `Wed 00:00-02:00`, `Wed 20:00-24:00`, `Thu 00:00-02:00`. This should probably be a separate PR though.
> 
> 
> Otherwise I am not sure where to test, I will leave the rest to the others to do a more thorough test around.

Thank you @LecrisUT for your valuable feedback, testing and input 😄. I'll try to accommodate validation within this PR if that fits, else I'll create a follow up for it. I'm waiting for a few more users/developers to test this out before I proceed in any other direction. Once again, thank you for your contribution

**Review by zomars — APPROVED** [review]
Nice and elegant solution @alishaz-polymath Thank you! 🙏🏽

**Comment by LecrisUT** [comment]
> - [ ]  When inputting the availability time in the event's advanced menu, there is no check if end time < start time.

@zomars this issue is still relevant though

**Comment by alishaz-polymath** [comment]
https://github.com/calcom/cal.com/issues/1739
We already have the issue reported here for a follow up PR, where I intend to solve for issue #1754 as well @LecrisUT @zomars

**Pull request merged**
