### PR TITLE
feat: Add app store entry for Clic (CheckIn application)

### PR DESCRIPTION
**Pull request by chrisdadev13**
Hey everyone! I know I'm kinda late to claim the bounty 😄 cheers to Patrick. I still wanted to share my attempt to the [check-in app challenge](https://github.com/calcom/cal.com/issues/14676) Now you can seamlessly manage your contacts and set up personalized check-ins with friends, family, and coworkers taking into account your availability and their availability... It may still have some bugs and weird behaviors 👀

This is part of a bounty/challenge, and I don't think it should be merged, I just added those files to open up the pull request and showcase my project... I don't wanna break Cal.com

[App](https://clicis.vercel.app)
[Repo](https://github.com/chrisdadev13)

/claim #14676

### CODE REVIEW

**Comment by Ash-2k3** [comment]
Hey @PeerRich, just wanted to check, if the bounty's still open for this issue ?

**Comment by syedbarimanjan** [comment]
@chrisdadev13 best implementation I have seen so far.

**Comment by chrisdadev13** [comment]
> @chrisdadev13 great work on this best implementation I have seen so far.

Thanks @syedbarimanjan 🙏 appreciate it. I still have more work to do on it but I'm glad you liked the progress I've made so far. 

I've seen that you've been quite active on this challenge, I'm looking forward to seeing what you're building 🙂 .

**Comment by PeerRich** [comment]
image

got this when signing in

**Comment by chrisdadev13** [comment]
> image
> 
> got this when signing in

Oh no @PeerRich... Sorry, my skill issues. I think I solved the problem for now. Let me know what you think 🙏

**Review by PeerRich — APPROVED** [review]

**Pull request merged**
