### PR TITLE
feat: Make Team Private

### LINKED ISSUE #8974: [CAL-1722] Private team so your team members won't see other team members
I think it would be nice if we can have a checkbox called

﻿title: "Private team"

description: "Your team members won't see other team members"

﻿and it would hide all of it.

This is useful for all the marketplaces that people use "teams" for, such as ollie, sholder, etc.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1722](https://linear.app/calcom/issue/CAL-1722/private-team-so-your-team-members-wont-see-other-team-members)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/8974

1) When user is admin

Screenshot 2023-07-03 at 6 45 50 PM

2) When user is not admin and team is private

Screenshot 2023-07-03 at 6 47 15 PM

3) 
Screenshot 2023-07-03 at 6 51 56 PM

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?

1) go to Team members page and turn on switch Make Team Private.

Now after making the team private only admin would be able to see all the members list in the settings. There will not be a button to Book a team member instead on the team page like before.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@Jaibles can you create a design for this page ?  (  When a team is marked private but user still try to go the url of "Book a team member instead" Button on the team's page)

Screenshot 2023-07-03 at 6 55 06 PM

**Review by pumfleet — APPROVED** [review]
Code looks good to me

**Comment by baileypumfleet** [comment]
@baileypumfleet merged this pull request with [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/9870).

**Comment by PeerRich** [comment]
> @Jaibles can you create a design for this page ? ( When a team is marked private but user still try to go the url of "Book a team member instead" Button on the team's page)
> 
> Screenshot 2023-07-03 at 6 55 06 PM

this is good enough for sure. rarely people will visit this

**Pull request merged**
