### PR TITLE
fix(calendar): recurring event fix

### PR DESCRIPTION
**Pull request by wzrdtales**
the loop was running way too often on every recurring object mostly due to the fact that the iterator was not checked for finalization, and in fact the iterator is not implemented correctly so it does not have the `done` property. instead it checks for undefined or not

also further note, this part is a very slow implementation, which will cause everything to become very slow and practically unusable, there are probably better ways to handle this.
Why? well simple, this iterates through every possible day, instead of just applying the current window to it. That means on the one hand this functionality is broken from the first place (b/c it wont work if it is a very long running event) and on the other it was implemented at a very high expense.

--

edit, added at least a start date to the iterator, that should increase the speed of this already.

Signed-off-by: Tobias Gurtzick <magic@wizardtales.com>

### CODE REVIEW

**Comment by PeerRich** [comment]
hey @wzrdtales thank you for the PR 

this touches core logic and requires a lot of eyeballs from our team. tagging @leog @emrysal and @zomars

**Comment by wzrdtales** [comment]
> this touches core logic and requires a lot of eyeballs from our team.

agreed, this logic is broken in the first place though, so even more eyeballs to maybe suggest an even better fix. I validated the fix for now and it is indeed operational. I didn't include my hotfix for zoho calendars, see my comment in this issue regarding that.

https://github.com/calcom/cal.com/issues/3457

This is what you will get from me so far, I wont try to fix any code style issues, I don't have time for that really, you may want to introduce husky into your project and automatically adjust the CS to your standards, this would do contributors a big favor, b/c no one wants to adjust to someones random standards every 5 minutes when you switch working on a project. Auto Code style formatted with husky git hook do a long way here. Over and out

**Comment by wzrdtales** [comment]
bump

**Comment by PeerRich** [comment]
> bump

thank you for bumping, our lead dev @zomars  who would review this was on vacation for a week and will look at this monday

**Comment by PeerRich** [comment]
there are a few other PRs working o recurring events too, so lets hope there wont be any merge conflicts cc @leog

**Comment by zomars** [comment]
Hey @wzrdtales thanks for the contribution. I'm trying to get this branch up to date but I cannot push to it.

image

Can you enable "Allow edit by maintainers" as described in our [CONTRIBUTING guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md#making-a-pull-request)? Thank you

**Comment by zomars** [comment]
We'll take it from here @wzrdtales Thank you for your contribution 🙏

**Comment by wzrdtales** [comment]
so its off the radar again?

**Pull request merged**
