### PR TITLE
chore: Delete unused module

### LINKED ISSUE #15630: Use Correct Object Keys
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Application using the keys which are wrong/not_available

### Steps to Reproduce

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Using wrong keys

### Expected Results

- Use correct object keys

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### PR DESCRIPTION
**Pull request by RushikeshGandhmal**
## What does this PR do?

- Fixes  #15630 
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by hariombalhara** [comment]
Thanks for the PR @RushikeshGandhmal 🙏 But I just discovered while testing that this component isn't being used, could you confirm and just delete this file.

We actually have an `AppDependencyComponent` that replaces this and is reusable across all apps that need it.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Left a comment.

**Comment by RushikeshGandhmal** [comment]
Welcome, @hariombalhara. Yes, I confirmed that ExistingGoogleCal component is not being used so I removed.

rushikesh

**Review by hariombalhara — APPROVED** [review]
🚀

**Comment by hariombalhara** [comment]
@RushikeshGandhmal I think you have not signed CLA. That's required to merge the PR.

**Comment by RushikeshGandhmal** [comment]
@hariombalhara previously my PR's got merged. you can check: https://github.com/calcom/cal.com/pull/15463

**Pull request merged**
