### PR TITLE
fix: Add signup disabled flag check on signup route

### LINKED ISSUE #15758: [CAL-4038] feature flag for Signup can't be disabled
### Discussed in https://github.com/calcom/cal.com/discussions/15708

<div type='discussions-op-text'>

<sup>Originally posted by **AhmedAburady** July  9, 2024</sup>
I found the setting in settings > admin features > disable-signup
even when enabling that and i see "flags updated" still users can signup
any solution for that?
i'm using Cloudflare tunnel so i don't use reverse proxy to disable the link</div>

<sub>[CAL-4038](https://linear.app/calcom/issue/CAL-4038/feature-flag-for-signup-cant-be-disabled)</sub>

### PR DESCRIPTION
**Pull request by Souptik2001**
## What does this PR do?

(Just to note that in the below video I am refreshing the server again and again is just to refresh the cache, so that I don't have to wait for 5 mins.)

https://www.loom.com/share/5246b4b7e13b4b759086f74d57fa19d5?sid=9eadf523-4c58-440b-bdc6-31a96cee0152

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create a POST request to signup API as demonstrated in the video. This should be successful.
- Then disable the signup from the admin settings.
- Wait for 5 mins. (cache expiration time)
- Then again make the above request. This should now say that signup is disabled.

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Hey @Souptik2001, as we check the admin feature flag, shouldn't we also update the other routes that have related flags present in the admin feature? For example: email verification, team, etc.

**Comment by Souptik2001** [comment]
@anikdhabal Yes you are correct!

Seems like the feature falgs are not respected at many places.

- For `email-verification`, it is properly implemented. ✅ 
- For `emails`, it is properly implemented. ✅ 
- For `organizations` it is partially implemented. ⚠️ 
- For `teams`, seems like it is not at all implemented? 🤔  As per I saw the `teams` feature was used nowhere (I may have missed also 🙏 )

For `organizations` - 
I was not able to fully understand the purpose of this feature flag. I thought that it should disable the `organizations` feature completely. Is it meant for that only?
Because at some places (front-ends) (like creating a new organization), it redirects the page to 404 if this flag is disabled.
But majority front-ends are not handled, even the Organizations are visible in the left sidebar.
And the APIs are completely unprotected just like the signup one.
I have pushed a commit, which basically implements a middleware to check for the feature flag. Can you please check that.
I have implemented it in such a way that we can now protect any APIs (example - teams) using a feature flag.

If you can confirm the function of the `organization` feature flag, then I can go ahead and modify the front-end also to respect the flag.

And also if you can confirm that `teams` will need to be also respected.

**Comment by zomars** [comment]
> Hey @Souptik2001, as we check the admin feature flag, shouldn't we also update the other routes that have related flags present in the admin feature? For example: email verification, team, etc.

This is out of scope for this PR. We should open up different issues for each one.

**Review by zomars — APPROVED** [review]

**Comment by zomars** [comment]
I think this is good enough for now. As extra points we could add some tests to verify the signup page/endpoint are disabled tho.

**Comment by Souptik2001** [comment]
> As extra points we could add some tests to verify the signup page/endpoint are disabled tho.

Sure @zomars will do that in sometime.

**Comment by Souptik2001** [comment]
hey @zomars sorry, was working on another issue (https://github.com/calcom/cal.com/issues/15828), therefore couldn't get this one done.

Will do this one sometime tomorrow. 👍

**Pull request merged**
