### PR TITLE
Fix jackson build error

### PR DESCRIPTION
**Pull request by keithwillcode**
## What does this PR do?

Fixes build error when prettier runs against the jackson.js file. There was a conflict of variable names between local and global scope.

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [x] Ensure SSO functionality has not been affected

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
It looks good to me - IMO we don't even need to alias `g` to `global` (and pollute the global NS with it) - so that's one further tweak I'd suggest.

**Comment by keithwillcode** [comment]
> It looks good to me - IMO we don't even need to alias `g` to `global` (and pollute the global NS with it) - so that's one further tweak I'd suggest.

Yeah I was thinking something similar. You mean by using `globalThis` or were you thinking of something else?

**Comment by emrysal** [comment]
@keithwillcode Global this will add an additional layer of safety - good thought

**Review by leog — APPROVED** [review]
Thank you for this, it was annoying!

**Pull request merged**
