### PR TITLE
Remove Moment dependency by changing implementation of DateRangePicker to something leaner

### PR DESCRIPTION
**Pull request by emrysal**
* chore: extracted all DateRangePicker logic from event-types/[type].tsx
* Added https://github.com/wojtekmaj/react-daterange-picker (See screenshots below on how this looks)
* Removed react-dates & @types/react-dates - this removes moment.js as this is the only dependency depending on moment.js

### CODE REVIEW

**Comment by emrysal** [comment]
I'm going to try going with https://github.com/wojtekmaj/react-daterange-picker as the philosophy of this library aligns with what we're trying to achieve here; last release is 9 hours ago so active too. -  

https://projects.wojtekmaj.pl/react-datetime-picker/

**Comment by emrysal** [comment]
Before:
image


After:

* Mobile:
  image

* Desktop:
  image

**Comment by PeerRich** [comment]
I actually don't think we need a datepicker, do we? just put in the date as 09/27/2021 (or 27.09.2021 whatever time zone you're in)

**Review by pumfleet — APPROVED** [review]
Looks good to me, really happy to get these big dependencies removed

**Comment by emrysal** [comment]
@PeerRich There is a niceness to this kind of UI but the primary reason I put it in is because we put it in before, we can always re-valuate later (but this fixes most of our peer dependency issues and removes some large dependencies)

**Review by PeerRich — APPROVED** [review]
good stuff on getting rid of it. i still think it's worth rethinking if we actually need a datepicker here. what does the figma say? @Jaibles

**Pull request merged**
