### PR TITLE
chore(availabilty-page): Bulk update modal

### LINKED ISSUE #16266: [CAL-4161] Bulk update schedule for existing event types missing
When changing the default schedule in the list of availabilities (https://app.cal.com/availability) a modal opens to bulk update schedule for existing event types: 

But when you set the default schedule in the availability settings (https://app.cal.com/availability/<id>) this modal doesn't appear: 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4161](https://linear.app/calcom/issue/CAL-4161/bulk-update-schedule-for-existing-event-types-missing)</sub>

### PR DESCRIPTION
**Pull request by SySagar**
## What does this PR do?

- Fixes #16266
- Fixes CAL-4161

https://www.loom.com/share/7e353854d14142b88313b713317609c8?sid=a4bdd0c9-a82c-4a97-b0ee-103dd146e103

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by anikdhabal — CHANGES_REQUESTED** [review]
fix the type check error. I think you are forgot to import the `showtoast` component

**Comment by SySagar** [comment]
@anikdhabal looks like you fixed the type check. np :)

**Review by anikdhabal — APPROVED** [review]
LGTM !!

**Review by Amit91848 — APPROVED** [review]
LGTM!

**Comment by ThyMinimalDev** [comment]
description text in the modal seems incorrect ? why are we displaying "Update the locations for the selected event types" and not "Update the schedules for the selected event types"

**Comment by SySagar** [comment]
yup will look into this.

**Comment by SySagar** [comment]
@anikdhabal I have raisd a draft pr for this. I have changed the localiztion file for englsih. However is there technique  how to update in all the corresponding languages.

pr: https://github.com/calcom/cal.com/pull/16343

**Pull request merged**
