### PR TITLE
fix: Tickets are being shown in user preferred time format

### LINKED ISSUE #11348: Ticket generated does not show time in user preferred format
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I have noticed that when the bookings are clicked and user is taken to booking status page. The time is not shown there in the user preferred time format in the settings.

### Steps to Reproduce

1. Set Time format to 12 hours or 24 hours in settings>general.
2. Go to bookings page and click on any booking.
3. The time is always being shown in same format no matter what user sets.

### Actual Results

- The time is always being shown in one format, either 12 hours or 24 hours.

### Expected Results

- The time should be shown in user preferred format.

### Evidence

[screen-capture (2).webm](https://github.com/calcom/cal.com/assets/93988200/30e317e4-7319-4069-acd3-b4460afea26c)

### PR DESCRIPTION
**Pull request by harsh11101**
## What does this PR do?

I have noticed that when the bookings are clicked and user is taken to booking status page. The time is not shown there in the user preferred time format in the settings. Now the time is being shown in user preferred format. This was done by geting user preferred time format using useMeQuery and the settting format in relation to it.

Fixes #11348 

[screen-capture (3).webm](https://github.com/calcom/cal.com/assets/93988200/d0788443-a593-4672-a286-04d5c9fd65af)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1. Set Time format to 12 hours or 24 hours in settings>general.
2. Go to bookings page and click on any booking.
3. The time is always being shown in user preferred format no matter what user sets.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by anikdhabal — CHANGES_REQUESTED** [review]
No need to push the yarn.lock file

**Comment by harsh11101** [comment]
> No need to push the yarn.lock file

Done. Can you check it now. Thanks for the feedback.

**Review by sean-brydon — DISMISSED** [review]
Please run 

git checkout origin/main -- yarn.lock  

to reset your yarn.lock file. 

Please also remove yarn.lock from .gitignore

**Comment by harsh11101** [comment]
> Please run
> 
> git checkout origin/main -- yarn.lock
> 
> to reset your yarn.lock file.
> 
> Please also remove yarn.lock from .gitignore

Is this ok now. I am new to open source contributions, sorry if this is causing any problems.

**Comment by Udit-takkar** [comment]
@harsh11101 i fixed it now.

**Comment by harsh11101** [comment]
> @harsh11101 i fixed it now.



> @harsh11101 i fixed it now.

Thank you😊

**Review by Udit-takkar — DISMISSED** [review]
LGTM. I pushed some change. we don't need to fetch user again on the client side

**Review by Udit-takkar — APPROVED** [review]
Approving again

**Comment by PeerRich** [comment]
hey @harsh11101 would you mind signing the [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=11349)?

**Comment by harsh11101** [comment]
> hey @harsh11101 would you mind signing the [Contributor License Agreement](https://cla-assistant.io/calcom/cal.com?pullRequest=11349)?

Done

**Pull request merged**
