### PR TITLE
Add ability to edit the appearance for teams

### LINKED ISSUE #6106: [CAL-623] /settings/teams/appearance missing the ability to edit the appearance
Teams appearance settings don't have the option to add your own brand colours or to change to dark / light mode.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-623](https://linear.app/calcom/issue/CAL-623/settingsteamsappearance-missing-the-ability-to-edit-the-appearance)</sub>

Acceptance criteria 
- Team admins can see those settings, 
- Team members cannot see the settings
- The settings take effect on the relevant teams public booking pages

### PR DESCRIPTION
**Pull request by leventdeniz**
## What does this PR do?

This PR adds the settings "theme", "brandColor" and "darkBrandColor" to the teams appearance page. The settings also take effect on the relevant teams public booking pages.

Fixes #6106 

https://user-images.githubusercontent.com/32421538/212119908-12a3ac02-58a7-4519-90dc-953f153b3c9b.mov

**Environment**: Staging(main branch) / Production

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [x] Log in as Team-Admin, change settings and check public booking page for effects
- [x] Make sure only team's public booking page is affected and not the users own public booking page
- [x] Log in as Team-Member and try to change the settings, this was not possible, as intended

### CODE REVIEW

**Comment by leventdeniz** [comment]
Not sure if I should have added the translations or not, did them with ChatGPT

**Comment by leventdeniz** [comment]
> Please let the Crowdin team to handle missing translations. 🙏🏽 

Sure, should I leave these in or remove them? If I remove them, should I leave the English strings in or how else would the Crowding team know what to translate?

**Comment by zomars** [comment]
> > Please let the Crowdin team to handle missing translations. 🙏🏽
> 
> Sure, should I leave these in or remove them? If I remove them, should I leave the English strings in or how else would the Crowding team know what to translate?

Just leave the new English strings. Otherwise the crowding team won't be notified that there are new strings to be translated.

**Comment by leventdeniz** [comment]
Got it, thanks!
Maybe add this info to the contribution guide, as this was something I was looking for in there.

**Comment by leventdeniz** [comment]
@zomars you added "Needs Documentation Update". Is that something I have to do in this PR?
And if so, where should the changes be made? Before opening this PR I checked the documentation but did not see anything that I changed.

**Comment by leventdeniz** [comment]
image
The e2e tests don't fail due to the changes I made, is there a way to manually rerun the github action?

**Comment by hariombalhara** [comment]
This is now already merged through https://github.com/calcom/cal.com/pull/6807. So closing it.

**Comment by leventdeniz** [comment]
Can I ask why?

**Comment by hariombalhara** [comment]
I think it happened because there were duplicate issues that weren't linked and work got started on them independently.

But I do agree this shouldn't have happened. There is a huge gap in the PR opening dates.

**Comment by PeerRich** [comment]
> Can I ask why? @zomars @hariombalhara 
> I submitted my PR before the one that got merged. I am a bit confused.

Hey @leventdeniz i am so sorry this was overlooked and another PR has been merged

its not always easy to be ahead of everything thats happening here

can you send me an email peer@cal.com so we can send you a gift box as a thank you?

Moin Moin nach Hamburg 👋

**Comment by leventdeniz** [comment]
@PeerRich Thanks for clarification! Was wondering if there was anything wrong with the PR but I understand managing a Open Source project can be a lot.
Just sent you an email!

**Pull request closed without merging**
