### PR TITLE
Add next i18next module

### PR DESCRIPTION
**Pull request by amirajorloo**
Hi,

I would like to add the Persian language to your great project, and I saw there is already a branch named `react-intl` to add i18n to the project. But it was a draft branch and it was way behind the `main` branch.
I created a branch from `react-intl`, add the `next-i18next` module, and merge it with the `main` branch. I also added the Persian language with RTL support.
There is a lot of work to do yet (translating and fixing the remaining pages), but I would like to create a draft MR to share my work with you and check if the process is okay or not.

Screen Shot 2021-05-27 at 18 09 18
Screen Shot 2021-05-27 at 18 09 30

### CODE REVIEW

**Comment by theSinner** [comment]
Hi
May I ask you to take a look at this PR to see if the implementation is correct and I may continue adding the i18n feature?
@baileypumfleet

**Comment by Freundschaft** [comment]
am I seeing right that this only changes the language for the admin panel not for frontend?

**Comment by theSinner** [comment]
> am I seeing right that this only changes the language for the admin panel not for frontend?

@Freundschaft 
No, I added the choose language button to the frontend too. But there is a lot of work to do.
Screen Shot 2021-06-13 at 18 11 01

**Comment by Freundschaft** [comment]
yes I saw that but its not functioning right now, right?

**Comment by theSinner** [comment]
> yes I saw that but its not functioning right now, right?

@Freundschaft 
Yes. Actually, because It's a huge change, I prefer to confirm the implementation with the contributors first and then complete it.
@emrysal

**Comment by baileypumfleet** [comment]
We've spoke about this internally, and we've decided that we're not going to merge in any localisation until we hit version 1.0, because the product is rapidly changing and it would be a huge amount of effort to keep translating while we're building

**Comment by baileypumfleet** [comment]
I'll temporarily close this off as we've put localisation on hold until we hit version 1.0. I'll reopen this and merge these changes once we've resumed localisation efforts. Many thanks!

**Pull request closed without merging**
