### PR TITLE
fix: missing timezones in dropdown list

### LINKED ISSUE #9054: repeated prompts to update timezone + doesn't actually save it
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Bug 1

1. travel to cyprus
2. open cal.com
3. on the "Update Timezone?" popup, hit the 'Update Timezone' button to update to Asia/Nicosia.
4. go to another page, such as bookings or availability
5. GOTO 3

the cycle from 3 to 5 keeps repeating indefinitely. any page you open, will retrigger it.
Unless you do the below:

### Bug 2

6. Then go to settings > General.
7. Notice that timezone is set to Europe/Bucharest
8. type 'nicosia' in the search field, Asia/Nicosia appears. click on it. It's again set to Europe/Bucharest and the 'Update' button is unavailable

### Technical details

- Bug 2 reproduces in firefox developer edition and qutebrowser. bug 1 only in qutebrowser

### LINKED ISSUE #9506: Problem with timezones in Cal.com
Hello Guys,
as you can see below we have a lot of countries in GMT+2 timezone. Unfortunately they're not available on timezones list in Cal.com. It may be weird for customers..

image

List of countries in Cal.com:
image

### PR DESCRIPTION
**Pull request by oksdav**
## What does this PR do?

Fixes #9054
Fixes #9506 

It seems like the project uses several different npm packages for working with time zones.
I have found at least 4:
1. *react-timezone-select* for the dropdown list
2. *city-timezones* for a list of time zones
3. *tzdata* for validation
4. *dayjs* for applying time zones to dates

The problem is that each package has its own list of time zones, which are not identical to each other.
In this case, the list for the dropdown is provided by [react-timezone-select](https://github.com/ndom91/react-timezone-select/blob/main/src/timezone-list.ts), which is **very** short (you can see it when you scroll the dropdown list without using search).
But, when you use the search option, it uses a different list, provided by [city-timezones](https://github.com/kevinroberts/city-timezones/blob/master/data/cityMap.json), which is longer.
It looks like even if you select a time zone after using the search option, like Asia/Nicosia in #9054, it still does not work properly.

This PR solves it by using the list from *city-timezones* from the start.
It is a quick fix, which is not perfect, as there are other problems, such as the component's [rejection](https://github.com/calcom/cal.com/blob/main/packages/lib/isProblematicTimezone.ts) of some time zones.

I would suggest replacing the dropdown component from *react-timezone-select* with just a regular dropdown component, because it does not need all this complex logic, just a list of time zones (no need for cities and other data).
After that, stay with only one package, such as the *dayjs* one (or *luxon* is another popular one), which is popular and maintained, unlike the other ones.

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set?
  - No
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't checked if new and existing unit tests pass locally with my changes
  - I haven't run the e2e tests, as my computer is too slow for them. My apologies!

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
I don't think this solves the issue because i don't see some timezones like "Hawaii" which were earlier available

**Comment by oksdav** [comment]
> I don't think this solves the issue because i don't see some timezones like "Hawaii" which were earlier available

According to https://www.iana.org/time-zones, US/Hawaii is not used since 1993, the correct one is Pacific/Honolulu.
Even with the current incorrect list, when you select Hawaii, it saves it as Pacific/Honolulu.
There is a built-in function in browsers and Node which returns a list of time zones: `Intl.supportedValuesOf("timeZone")`
I have tested it with Chrome, Firefox and Node and there is no Hawaii, but there is Pacific/Honolulu, in accordance with the tz database.
As I said, this is a quick fix and I would suggest replacing the dropdown component with a regular one and using a proper list like the one in `Intl.supportedValuesOf("timeZone")` or a better maintained package.

**Review by Udit-takkar — APPROVED** [review]
LGTM.

city-timezones covers almost every timezone in allTimezones ( react-timezone-select)

**Comment by PeerRich** [comment]
just to make sure: this wont break the ability to enter any city right? I think we did this "manual timezone list" because we added the most common cities to the search:

https://github.com/calcom/cal.com/assets/8019099/332a0318-8f89-4659-bd8a-0bf2fc67c4cc

**Comment by PeerRich** [comment]
i think @zomars knows a little bit more about the current timezone components

**Comment by oksdav** [comment]
> just to make sure: this wont break the ability to enter any city right? I think we did this "manual timezone list" because we added the most common cities to the search:
> CleanShot.2023-08-22.at.13.04.40.mp4

No, it uses the same list used for search.
I've tested the cities in your recording, everything works, and Hamburg will be the correct Europe/Berlin time zone.
The only time zone this list does not include, which is included in the current list (and is correct), is Pacific/Midway, but after the patch it is converted to Pacific/Pago Pago, which is the best next option, because Midway Islands use the Samoa Time Zone anyway (and there are only about 40-60 people living in Midway Islands).

**Review by zomars — APPROVED** [review]
This seems like a step in the right direction. Thank you for your contribution 🙏

**Comment by buzzard10** [comment]
Thank you Sir for your work!

**Pull request merged**
