### PR TITLE
fix: [CAL-3940] randomize Tip Sidebar

### LINKED ISSUE #15458: [CAL-3940] randomize "Tip Sidebar"
super easy, lets randomise this list, just in case people havent clicked through them:

image

<sub>[CAL-3940](https://linear.app/calcom/issue/CAL-3940/randomize-tip-sidebar)</sub>

### PR DESCRIPTION
**Pull request by jscafe-dev**
## What does this PR do?
Fixes #15458 

Used lodash shuffle to randomize "Tips Sidebar"

Loom Video: https://www.loom.com/share/6f839cc1435e4b5d8afb535b2ce34ad5?sid=26474013-c39e-4722-8511-9a20dc7e4148

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
NO
- What are the minimal test data to have?
NA
- What is expected (happy path) to have (input and output)?
To see randomized Tips sidebar on each reload
- Any other important info that could help to test that PR
- No

### CODE REVIEW

**Comment by jscafe-dev** [comment]
@PeerRich All checks are green!

**Comment by jscafe-dev** [comment]
@PeerRich quick reminder, if we can merge this PR?

**Review by PeerRich — APPROVED** [review]

**Comment by jscafe-dev** [comment]
@PeerRich i don't have the permission to merge

**Comment by jscafe-dev** [comment]
@PeerRich @joeauyeung @sean-brydon I do not have permission to merge.

**Comment by jscafe-dev** [comment]
@hariombalhara this PR got removed from the Merge queue due to some mysterious reasons.

**Pull request merged**
